### ISSUE TITLE
Parts of layout appear broken randomly and are fixed after a refresh

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1460] opened 2016-07-21 10:11 UTC
Throughout the testing of the upcoming template using Gantry 5.3.2, certain sections in the layout manager appear broken randomly. After a refresh, the issue fixes itself.

Please see pic for the latest example.

![gantry_glitch1](https://cloud.githubusercontent.com/assets/5719486/17019343/268f3ea2-4f3c-11e6-8a5f-bd27d5ba4182.png)

![gantry_glitch2](https://cloud.githubusercontent.com/assets/5719486/17019344/26904306-4f3c-11e6-98f2-42d473f957a5.png)

**Comment by mahagr** [comment] 2016-07-21 11:17
I've run into this issue a few times, too. Reloading page always fixes the layout.

**Comment by kat05** [comment] 2016-07-21 16:26
Another example which I've just come across in the upcoming template...

![gantry_glitch3](https://cloud.githubusercontent.com/assets/5719486/17030624/9ddde45c-4f70-11e6-81fd-c44f1176899d.png)

![gantry_glitch4](https://cloud.githubusercontent.com/assets/5719486/17030623/9ddc787e-4f70-11e6-809a-f83a4403566d.png)

**Comment by w00fz** [comment] 2016-07-21 16:34
Looks like the rendered JSON is corrupted.

**Comment by kat05** [comment] 2016-07-21 18:46
Please also note ticket #79 for the upcoming template in our internal bugtracker.

**Comment by w00fz** [comment] 2016-07-22 05:42
Could also be just a browser glitch, happens very rarely and only when there's a lot of data in the Layout.

**Comment by kat05** [comment] 2016-08-25 10:08
Also seen this happening during Remnant pre-release testing, a refresh fixed it.
The Simple menu particle in the screenshot is supposed to sit in the Copyright section.

![remnant_-_administration](https://cloud.githubusercontent.com/assets/5719486/17965378/9e9aafa8-6abc-11e6-9c96-d36797150576.jpg)

**Comment by w00fz** [comment] 2016-09-12 00:22
I could never reproduce this. I think somehow these layouts were just corrupted somehow.

**Comment by kat05** [comment] 2016-12-07 09:00
Just a note, a browser refresh sorted the issue, but I believe if I had saved, it would have been broken for good. At least this is what I experienced the first time I saw this issue months ago.

**Comment by kat05** [comment] 2017-10-06 06:28
This is still happening, please see
http://www.rockettheme.com/forum/gantry5-for-joomla/272504-gantry-container-problems-and-ghost-particles

**Comment by blizam** [comment] 2017-10-06 14:09
I usually see it on Containers... so Sections with Sidebars... and I usually see this on Particles that are inherited from other Outlines, though it can happen on "normal" in-Outline Particles as well... usually an extra line of YAML that shouldn't be there

**Comment by blizam** [comment] 2017-10-10 00:07
I would also add that I do not see the issue clear after refresh... it stays until the Layout Preset is reloaded (sometimes that doesn't even fix it though) or the extra line of YAML is manually deleted from the layout config

**Comment by mahagr** [comment] 2017-10-11 06:23
@blizam Do you have any reliable way to reproduce this issue?

**Comment by blizam** [comment] 2017-10-13 16:00
Unfortunately no, and I have tried. I see it related to Inheriting a Section with a Sidebar or other Container wrappers pretty much exclusively... so I've seen it in Topaz a lot where every Section has a left/right Sidebar and my intuition is that it's something that occurs after a Gantry update as it doesn't seem to surface is just normal day to day activities... next time I run into it I'll try to clear it and reproduce it

**Comment by blizam** [comment] 2017-10-14 16:31
Ok, I just installed the Supra Grav Rocketlauncher.

I created a new Outline based off the Front Page Outline ~ everything cloned. I then set my new Outline to Inherit the Top, Navigation, Footer, Copyright, and Offcanvas Sections of my Base Outline.

Base Outline looks like this:
![image](https://user-images.githubusercontent.com/8940155/31577313-6c40194a-b0c9-11e7-8004-b882f64a4724.png)

But my new Outline looks like this.... it shows the Mobile Menu in my Top Section and it's like it's not totally grayed out... I can still grab and move the Grids even though they should be inaccessible as their inheriting from the Base Outline

![image](https://user-images.githubusercontent.com/8940155/31577353-fa6be514-b0c9-11e7-90c2-b7ebc3671384.png)

There IS a mobile menu particle in the Offcanvas section but it should not be showing in the Top section obviously... only the Top section seems screwy currently where I can actually interact with the Grids and Particles... in all the other Sections that are inheriting from the Base Outline I can interact with the Grids or Particles

I've attached the full YAML for this new Outline and my Base Outline

[layouts.zip](https://github.com/gantry/gantry5/files/1384795/layouts.zip)

**Comment by mahagr** [comment] 2017-10-17 15:15
@w00fz Can you take a look when you have a chance?

**Comment by mahagr** [comment] 2017-11-30 13:15
The issue with inherited layouts should have been fixed with my commit. Please use latest CI build to test this issue.

To better test this issue in Joomla, please find following lines in `libraries/gantry5/classes/Gantry/Component/Layout/Layout.php` (852-858):

```php
                    if (isset($this->references[$item->id])) {
                        if ($type === 'block') {
                            $item->id = $this->id($type, $subtype);
                        } else {
                            throw new \RuntimeException('Layout reference conflict on #' . $item->id);
                        }
                    }
```

and replace it with:

```php
                    if (isset($this->references[$item->id])) {
                        if ($type === 'block') {
                            \JFactory::getApplication()->enqueueMessage('Layout reference conflict fixed for ' . $item->id);
                            $item->id = $this->id($type, $subtype);
                        } else {
                            throw new \RuntimeException('Layout reference conflict on #' . $item->id);
                        }
                    }
```

This will allow you to see when the error happens, so it's easier to check the layout.

**Closed** 2017-11-30 13:33 UTC
Labels: bug

**Comment by blizam** [comment] 2017-11-30 15:06
w00t!
