### ISSUE TITLE
The Gantry 5 framework: Changes not saving/updating fast enough. Loading icon shown forever.. Maybe Ajax not loading fast enough?

### ISSUE THREAD

**Issue by bloominari** [gantry/gantry5#1277] opened 2016-05-09 20:09 UTC
Hello,

The following emails was sent to the InspireTheme Tech support team, who asked me to get in touch with you to solve this problem. They state that their template is not the problem, but most likely something else out of their control:

Please read below and you'll understand.

VIDEO of what I'm talking about also included below
--------------

I just purchased and installed your Oxygen Theme on Joomla 3.5.1 running PHP 5.6, using your Quickstart package.

I've also read the entire Gantry 5 documentation here: http://docs.gantry.org/gantry5/, so I'm very familiar with how Gantry works.

My issue is the following:

- Every button that I press for "save" or any button/switches that I move/change do not seem to quickly save and reload the page.
- The saving styles button and other items (such as the "developer on/off switch under extras" show the "loading" icon which loads forever, and never goes away. Thus, I never know if the page ever saves or not, but I end up having to press "reload" on my browser for it to refresh the page and do something...
- The Gantry 5 framework, or something on your theme isn't working completely.

After viewing various videos of how Gantry 5 works, I see that after pressing save, I'm supposed to see a pop-up notification (most of the times) saying "changes saved" or something similar. Yet, my site just stays on the "loading" icon and things don't change.

Yet, when I do press refresh after few seconds, I DO SEE that the changes were in fact saved... Which makes me think that changes do get saved, yet for some reason the Javascript or AJax on my page is not loading right or fast.

Video that shows what I'm talking about: http://screencast-o-matic.com/watch/cdh1ra1np8

I'm using the latest version of Chrome on OSX. Using Joomla 3.5.1, on latest Gantry 5

any questions, please contact me at jaime@bloominari.com 

Jaime Nacach
Bloominari.com 

@w00fz would you please take a look? # @

**Comment by w00fz** [comment] 2016-05-09 20:14
Your screencast has been deleted and I am not entirely sure what could be the cause.
An idea could be to also inspect the Ajax response through the Chrome inspector, in the Network panel, to see what response you get back.

Sharing the URL would also help better understand the issue.

**Comment by bloominari** [comment] 2016-05-09 20:20
Hi @w00fz Thanks for your quick reply. The video can still be seen here: http://screencast-o-matic.com/watch/cDh1rA1Np8 (I just tested it).

the domain is www.bloominari.com/bloominate/ (test site)

Happy to hop on a Teamviewer to share my screen with you and show you the error in 2 minutes, if you'd like :-)

thanks!

**Comment by w00fz** [comment] 2016-05-09 21:20
Could see the video now, thanks. It is definitely not behaving right. It takes way too long and I suspect something on the server side is truncatinng the response. if you could hop on gitter and PM me and admin account I can take a closer look at the Ajax response.

I also noticed when you went to the G5 themes that you had a ionCube error at the bottom, are you able to disable ionCube to see if that could be the cause?

This is very weird behavior and not something we have seen before, it must have to do with some server setting, the challenge is going to figure out which.

**Comment by JoomFX** [comment] 2016-05-09 21:20
@bloominari Hey Jaime,

Ivo here - the developer of the Oxygen template and the guys who asked you to open this issue. Thanks for doing that :wink: 

I just want to make a little comment about what you said above:

> InspireTheme Tech support team, who asked me to get in touch with you to solve this problem.

I actually said the following:

> Anyway, this is not a template related issue (the template is responsible for the front-end only). I also doubt it that it is a Gantry 5 issue, but this is where we should start from.
> ...
> ...
> In my opinion the issue comes from your environment somehow

Anyway, let's track the issue down...

@w00fz Djamil, I asked Jaime to open this issue because the issue he experiences is pretty much the same as [the one you were looking at on the Gitter chat](https://gitter.im/gantry/gantry5?at=571a7cfef5b6334a5e701265).

Jaime and the other user are both on OSX.

**Comment by JoomFX** [comment] 2016-05-09 21:23
@w00fz And thanks for looking into it :wink:

**Comment by bloominari** [comment] 2016-05-09 21:24
Hi @JoomFX Sorry about the specifics of what you said. In general, you did just think it was a good idea to reach out to them. So I did, but agree. you didn't say they'll for sure solve it, but they can help :-)

**Comment by bloominari** [comment] 2016-05-09 21:25
@w00fz I'm not sure how to private message you via GitHub here.. Do you mind PM me first and I'll reply. I'm sure I'll get a notification I can press to reply :-) Thanks! ready to hop on a quick chat

**Comment by JoomFX** [comment] 2016-05-09 21:32
@bloominari No problem at all Jaime.
I just want to be very clear about everything as I greatly respect and appreciate the work that @w00fz , @mahagr , @newkind and all the other RT guys do!

And from another point of view, I don't want you to think that I'm just "passing the ball" to the G5 developers.

Anyway, I do believe that the issue comes from your environment, but there might very way be something in G5 that can be changed so this issue does not happen anymore.

Djamil is the expert here so he should say the final word :wink: 

By the way Jaime, can you join the [Gitter Chat](https://gitter.im/gantry/gantry5). This is what Djamil meant and this is the place where you can send PMs.

**Comment by bloominari** [comment] 2016-05-09 21:34
hi @JoomFX Just sent him a PM via Gitter Chat. I also though that is what he meant. Thanks again for your help. VERY appreciated. 👍

**Comment by w00fz** [comment] 2016-05-09 22:00
Hi Ivo,
no problem at all here, glad to help getting to the bottom of the issue and fix what needs to be fixed if it's a Gantry problem.

The issue you mentioned about the raspberry pi turned out to be a proxy server misconfiguration, the follow up of that issue was:

> Good morning. I hope you are well. I wanted to get back in touch about the issue I was having with particles Friday. It's not dyndns causing it. It's the proxy server causing the issue. Just wanted you to know. Thx again for your help.
Further, this 'proxy' server also causes some web pages to stall in my web browser as well as some pdf's to stall while downloading. All our internet is routed through our home office in another state. It's ridiculous, but I'd expect nothing less from the people in charge of it.

This could be the same issue but only it looked like a very isolated issue. We've also seen some issues with `mod_security` which could well be the cause, however we only have ever seen it related to the `Save` and never the `Load` (like loading the fonts in the screencast). The root cause of this was  the HTML we were  passing in the JSON encoded value upon Save. We did fix this latest problem last week, we now encode the whole value so that `mod_security` doesn't complain and it's available as CI Build, I doubt this is the same issue though.


Thank you for the access details @bloominari, I've looked at it and as I suspected there is something wrong with the `ionCube` module on your server. As I said above, I noticed in your screencast that when you go to the G5 Themes, at the bottom you get an exception. 

![crikey there was an error 2016-05-09 14-56-38](https://cloud.githubusercontent.com/assets/11734/15129413/46cf95ce-15f6-11e6-8a5e-41817bf7e4d9.png)

That same exception appears in the response of the Ajax calls, making the expected JSON response to be impossible to decode.


I have now fixed this for you by changing the Joomla Server Settings to `Simple` which excludes these warnings, however this does not really explain why it tries to load it twice and quite likely you will get this error also somewhere else outside of the whole Gantry scope. If you have control over it, I would try to disable it and see if that helps, it will probably also speed up the whole site.

Cheers.

**Comment by bloominari** [comment] 2016-05-09 22:24
Hi @w00fz 

Thanks so much for the update. I'm not that technical, so some things are beyond my understanding. I do know how to code basic PHP and understand the basic idea of how things load on a page, etc. But not in super detail.

I do have full access to my website, which now you have as well. I also have access to my cPanel on Bluehost.com (my hosting). I went into my PHPConfig on cPanel and "unchekced the "ioncube" (see screenshot attached).
![screen shot 2016-05-09 at 3 19 50 pm](https://cloud.githubusercontent.com/assets/14933286/15129884/89af9206-15f9-11e6-85bc-3f31bc40f2e4.png)

I'm HAPPY to report that this has now solved the problem :-)

I would have NEVER guessed this would have been the issue. Things are now working as expected.

thanks for your help!!! :-) 👍 👍 👍

**Comment by w00fz** [comment] 2016-05-09 22:25
Glad to hear that everything is resolved now!

**Closed by w00fz** 2016-05-09 22:25 UTC
Labels: question

**Comment by szoupi** [comment] 2016-09-13 17:26
hello, 
after upgrading to Joomla 3.6.2, gantry 5.3.5 and php 5.6  i am having the same issue described above. Disabling ionCube didn't (my server is on Bluehost too). The cog is keep spinning when i press the Layout tab (if i press previously the other tabs there is no problem). Pressing F5 to resume layout tab is loaded but changes in particles are not saved at all. This is the error i get: 

SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 66243 of the JSON data
http://szoupi.com/administrator/components/com_gantry5/js/main.js?57d69954
Line 10

**Comment by mahagr** [comment] 2016-09-14 06:50
@szoupi Check ajax response, there's likely something extra in it -- likely error message from PHP.

**Comment by szoupi** [comment] 2016-09-14 10:02
Thanks for the response. 
What file exactly should i check?

Until now, I reinstalled gantry5, checked multiple times php settings, and searched for every possible error. There is only one error which occurs only in the layout tab (the one i mentioned before:  SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data ) and directs me to gantry core files (.../administrator/components/com_gantry5/js/main.js) which is extremely huge to check it. 
I would be helpful to have more detailed instructions (i have good  knowledge of web design and linux systems but  as far as php programming is concerned  i only scratch the surface).
if access to ftp is required i can provide credentials.
Thanks

**Comment by mahagr** [comment] 2016-09-15 06:02
The issue is not in the code but in the JSON response coming from the server. You have likely PHP error in outputting into JSON, which makes it invalid.

To look into the network traffic you need to inspect the document and take a look into network traffic. In there take a look of the contents of the json response.

**Comment by szoupi** [comment] 2016-09-15 13:59
you are right, at the end of the server's JSON response it get 
`{"JSON code here...    <\/div>"}<!DOCTYPE html>`
and `<` creates the error. 
How can i fix it?

**Comment by mahagr** [comment] 2016-09-15 14:07
Yeah, you shoudn't have `<!DOCTYPE html>` or anything that follows it. Is there anything else in the response? I'm mostly interested what comes after doctype declaration.

**Comment by szoupi** [comment] 2016-09-15 14:15
on the same line (line 1), no there isn't anything else. On line 2 an on, starts the `<html>  <head>` etc code

**Comment by szoupi** [comment] 2016-09-15 14:33
i attach the full JSON response 
[json_error_szoupi.txt](https://github.com/gantry/gantry5/files/474883/json_error_szoupi.txt)

**Comment by mahagr** [comment] 2016-09-15 17:49
Exception thrown with message "Module 'uploadprogress' already loaded"

So its issue with your PHP configuration.

**Comment by szoupi** [comment] 2016-09-15 23:37
@mahagr thanks, with your help i managed to fix the problem. Inside php.ini there were duplicate lines loading the same modules. I deleted them and everything worked like a charm. The problem was caused after switching to php 5.6. Bluehost's cp seems to not working properly...

Worth mentioning that enabling PHP 5.6 (FastCGI) there are again duplicate lines but no errors occur... :)
