### ISSUE TITLE
Atom inheritance from Base Outline

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1235] opened 2016-04-13 01:57 UTC
The Custom CSS/JS Atom is meant to be a default for every outlines. If I understand it right, in an outline's "Page Settings", when the checkbox in Atom section is unchecked, the outline will use Base Outline's Atom setting. The problem is, when you edit the Custom CSS/JS atom in the Base Outline, other outlines won't automatically get it. I test it many times, everytime you edit the Base Outline atom, you have to log out and log in for other outlines to inherit the new atom. This is very counter-intuitive.

**Comment by w00fz** [comment] 2016-04-13 01:59
Are you sure this is not just cache? Have you tried editing the Atoms in Base Outline, saving, and clearing Gantry and Joomla cache (if you are in Joomla)?

**Comment by newjie** [comment] 2016-04-13 02:37
Yes it is cache. But don't you think having to clear cache everytime after editting an Atom is weird and inconvenient too?

**Comment by w00fz** [comment] 2016-04-13 03:43
It is, but that's not the behavior I'm getting. Cache gets automatically cleared at every save. I'm suspecting it might be something on your server setup related to file caching or perhaps a cache plugin you are using?

Maybe @mahagr has some ideas about it. 

// Djamil Legato // From iPhone //

**Comment by mahagr** [comment] 2016-04-13 05:40
This issue has likely nothing to do with caching, but how atoms in Page Settings work. If you modify any atoms for the outline, all atoms get saved locally in that outline.

We may need some inheritance implementation here, too, @w00fz..?

**Comment by w00fz** [comment] 2016-04-13 15:17
No I think you are missing the usage explained by @newjie.
He is saying that he has a bunch of atoms in Base Outline, all Outlines are inheriting from Base and no Outline is overriding Base (all Outlines have unchecked / overlayed Atoms).

What happens is that, for @newjie, whenever he goes changing some settings of atoms in Base, the Outlines are not reflecting the change until cache gets cleared.

This seems to be working fine for me though, it might be file cache related (server) or I am not quite sure.

**Comment by mahagr** [comment] 2016-04-13 16:02
Atoms are handled by the same code as particle defaults, so if this is true, also changing particle defaults (Settings tab) would have no effect until cache gets cleared. That's why I thought that the issue would be elsewhere.

We do have opcache issue which would cause similar symptoms, but I am not sure if clearing cache helps for it (didn't test it like that when I was fixing it).

**Comment by w00fz** [comment] 2016-04-21 03:03
Hey @newjie , I've been trying to reproduce this issue but for me the cache clears itself as expected every time i Save.

Are you sure you don't have any plugin interfering? This doesn't sound like a Gantry issue, the behavior is working as expected.

**Comment by newjie** [comment] 2016-04-24 16:30
Sorry what I said in the main question was not accurate. The truth is, for those outlines that only uses the base outline's atom, it works fine - every change in base's atom will immediately affect those outlines. 
But there is a little confusion when an outline not only uses base outline's atom but also has its own. My scenario is, I have some CSS/JS that I want them active for all pages, I put them in the base's atom. But I also have some CSS/JS that I only want them available for a particular outline. So in addition to inheriting  base's atom I need to create another atom for this outline. To do this, I need to check the checkbox in this outline's atom section and drag an atom into it. Once this checkbox is checked, the outline won't get any changes that are made to the base atom afterwards. 
This is where I thought I had to relog to get the changed base atom. But I didn't have to. All I need to do is delete the 3 atoms(2 from the base and 1 created for this outline) currently in the outline, make sure the box is unchecked and save the outline. This way the outline will get the changed atom from base, and then I can create an atom for this outline again. Although this is still a little weird and takes me some time to figure out, but it works without having to log out or clear cache. I am thinking maybe this is not the way you had in mind when you designed the whole thing though, if there is a better way to do this, please enlighten me.

**Comment by mahagr** [comment] 2016-04-25 07:51
Yes, this is how it works right now. We really need to implement some kind of inheritance on atoms to fix this issue.

**Comment by w00fz** [comment] 2016-06-04 05:11
I'm closing this as we have a better tracker in #1312, it will make it for 5.3, we are actively working on this implementation at the moment.

**Closed by w00fz** 2016-06-04 05:11 UTC
Labels: feature
