### ISSUE TITLE
PageSpeed Insights 

### ISSUE THREAD

**Issue by a0677703787** [gantry/gantry5#3175] opened 2023-08-27 10:19 UTC
When a lighthouse from Google (https://pagespeed.web.dev) checks a site on joomla 4 with installed Gantry5, a warning is issued about an outdated API

Deprecated APIs will eventually be removed from the browser.

DOM  Mutation Events, including `DOMSubtreeModified`, `DOMNodeInserted`,  `DOMNodeRemoved`, `DOMNodeRemovedFromDocument`,  `DOMNodeInsertedIntoDocument`, and `DOMCharacterDataModified` are  deprecated (https://w3c.github.io/uievents/#legacy-event-types) and will  be removed. Please use `MutationObserver` instead.

This API is located in /media/gantry5/assets/js/main.js

Is it possible for the developers of gantry 5 to fix this warning?

![image](https://github.com/gantry/gantry5/assets/64018955/f83db50c-75f5-46cd-8760-342be3b8b236)

**Comment by N8Solutions** [comment] 2023-08-28 13:00
You didn't mention the CMS you are using, but in reviewing this, it appears to be a duplicate of https://github.com/gantry/gantry5/issues/3174 which involves the Grav CMS.

**Comment by N8Solutions** [comment] 2023-08-28 20:19
> Why didn't I mention CMS? "a site on joomla 4 with installed Gantry5" - quote from my first post

My apologies, you're correct. I didn't get much sleep last night so I obviously just ended up glazing over that.

It still stands though, the issue you are facing seems to be the same as in the other ticket. It must have something to do with the Libraries that Gantry 5 is using which is cross platform compatible and independent of the CMS and Themes.

@hexplor Can you take a look at this?

**Comment by a0677703787** [comment] 2023-08-29 06:58
if the developers are aware of this problem, then I will close my ticket.
I will look forward to when the problems are fixed and I can update all my sites with the new version of gentry.
 Thank you!

**Closed** 2023-08-29 07:39 UTC
