### ISSUE TITLE
Grav Production / Development Toggle Issue

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#1846] opened 2017-02-02 17:50 UTC
Please see GIF. This is an issue with Gantry 5.4.6 on Grav (not an issue in Joomla / WordPress).

![feb-02-2017 11-21-50](https://cloud.githubusercontent.com/assets/5002814/22561411/bb755e48-e93d-11e6-9e01-a09284edb355.gif)

**Comment by simmonsr** [comment] 2017-02-03 15:52
still an issue in latest CI. start in Development mode to see.

![feb-03-2017 09-52-06](https://cloud.githubusercontent.com/assets/5002814/22597749/849e0c1c-e9f6-11e6-90f6-ab4aec6535e6.gif)

**Comment by mahagr** [comment] 2017-02-09 10:01
Make sure you clear cache as Grav doesn't always clear cached template files.

Cannot reproduce, latest CI works just fine for me.

**Comment by simmonsr** [comment] 2017-02-09 16:22
It's still an issue with latest CI. start in Development mode to see.

caching is off for grav (i cleared browser cache / gantry cache).

**Comment by mahagr** [comment] 2017-02-10 07:26
It is weird because of previously it did work wrong (by toggling to the opposite state), but now it does what the request asks it to do and there's no way it goes wrong unless server responses ajax requests in wrong order. If so, there is a bug in Grav, not in Gantry.

Also I am not able to reproduce the issue, no matter what I try. Also you need to clear Grav cache, not Gantry cache in order to update twig cache in admin.

**Comment by mahagr** [comment] 2017-02-10 07:40
Ok, so it is the first request going wrong.

**Comment by mahagr** [comment] 2017-02-10 07:46
HTML is identical, the issue must be in JS.

Can you create a new issue for the new bug, I'll close this one as the first bug has been fixed and the second one seems not to be related to it.

**Closed by mahagr** 2017-02-10 07:46 UTC
Labels: bug, grav

**Comment by mahagr** [comment] 2017-02-10 08:32
Ok, boolean false = ''. Issue fixed.

**Comment by simmonsr** [comment] 2017-02-10 15:25
fixed confirmed awesome thank you!
