### ISSUE TITLE
HikaShop geolocation and gantry

### ISSUE THREAD

**Issue by hikashop-nicolas** [gantry/gantry5#1972] opened 2017-04-27 08:05 UTC
I'm reporting the issue here as gantry support asked. However, I'm not able to reproduce myself on my local server as I don't have a gantry template and I'm forwarding the issue reported by one of our customers.

Apparently, when the geolocation system of HikaShop is run (the first time someone reach the website), the template is not able to display the modules on the main area of the page.
It might actually not be related to the gantry framework but the template being used, or even a third party extension.
I'm not able to reproduce myself as I don't have the template but I confirm I saw the issue on the user's website which reported the issue. You can read more about it here:
https://www.hikashop.com/forum/payment-methods/889985-multi-currency-allow-payment-in-multi-currency.html

In the last message, gantry support answered:
"I agree it doesn't make sense that disabling/enabling a plugin that purports to only geo-locate and set price accordingly would cause the entire contents of the Hikashop module to not output."
Note however that it doesn't only happen with the HikaShop module. It also happens with other custom modules on the main area of the homepage of that website, which is why I'm thinking that it must be something related to the display of the modules by the template.

**Comment by mahagr** [comment] 2017-05-02 07:12
Sorry for a delay, I was on a long weekend.

To me, the issue looks like it might be something to do with template assignments to the menu items. Issues in the assignments are usually caused by calling certain Joomla API functions (like JHtml etc) too early, or before Joomla has determined the route to the page. This causes Joomla to display a wrong template style.

The easiest way to test this out is to assign a different template to the landing page (beez vs protostar), which allows you to observe the issue without installing any template to the site. During the first visit, you will likely see a wrong template, which should pinpoint if the issue is in the plugin or not. If you are able to reproduce the issue, just look through the geolocation code and look for any Joomla API calls which could be run too early.

I don't think that this issue has anything to do with Gantry 5 as Gantry doesn't alter the behavior of Joomla in any way.

**Comment by edzz83** [comment] 2017-05-03 13:37
Hi,

I have tried as you recommended. 
You are correct, this issue is now resolved to have nothing to do with gantry as far as i can tell.

If I do the following template assignment:

Beez = Default Template Style
Create HOME menu item and set this item to PROTOSTAR TEMPLATE.
Then, refresh page cache and reload, the page first loads teh BEEZ template (should be loading PROTOSTAR, then on refresh the page loads the correct PROTOSTAR template.

There is obviously something wrong with the geolocation plugin per your advice.

**Comment by mahagr** [comment] 2017-05-04 06:47
Thanks for your update.

@hikashop-nicolas Just look into event calls happening before onAfterRoute() event call. First, make sure you're not including any php files that do stuff outside of method calls as those are the most likely cause of the issue. After that take a look if there are any calls to Joomla API inside the events (or functions called in those events), especially calls to JHtml class.

**Comment by mahagr** [comment] 2017-05-04 06:49
I'm closing the issue as it has nothing to do with Gantry. Be free to continue the discussion, though, I will be monitoring this topic.

**Closed by mahagr** 2017-05-04 06:49 UTC
Labels: invalid, joomla, question
