### ISSUE TITLE
Impossible to login with the BTlogin plugin from Bowthems

### ISSUE THREAD

**Issue by gyvermac** [gantry/gantry5#407] opened 2015-06-03 07:47 UTC
I come back with a problem I already talked about...
I use the free BTLogin (Bowthemes) plugin version 2.6.0 : [DL here](https://www.dropbox.com/s/9xfsmsy01ej1a3q/mod_bt_login_j2.5%26j3.x_j2.5_v2.6.0.zip?dl=0)
It work perfectly under G4 but not under G5 !

Under G5 I get this error :
*Another plugin has redirected the page on login, Please check your plugins system*

But the plugins are the same as I have G4 and G5 on the same Joomla install !

You can see this on http://interface34.fr/gantry5
The home page is under G5 + hydrogen and the others pages under G4 + JGT1.
You can login as test/test to check (no way from Home but OK from other pages).

This issue could be related to #392

**Comment by mahagr** [comment] 2015-06-09 10:08
Issue was not related to #392.

I just installed the latest version of the module and it works just fine for me. Tried a few different pages in Hydrogen.

**Comment by gyvermac** [comment] 2015-06-09 12:44
Ok May be something else "wrong" with my website but I still can't explain why it works on pages under G4 and not on page under G5... (as all except Gantry + hydrogen is the same)

**Comment by mahagr** [comment] 2015-06-09 13:03
There's no redirect, but for some reason login module doesn't get run. Make sure you do not have caching on for it.

**Comment by gyvermac** [comment] 2015-06-09 13:34
No caching... I tried to update from 2.6.0 to 2.6.2 : it's worth it doesn't no even respond to any clic on the button now (G5 and G4 !)

**Comment by mahagr** [comment] 2015-06-10 07:34
Oh wow. And for me it just works. I have no idea what's going on with it!

**Comment by gyvermac** [comment] 2015-06-10 07:47
I'll try on a fresh install of Joomla + Gantry 5 + Hydrogen + BTLogin...

**Comment by gyvermac** [comment] 2015-06-11 12:52
BT login 2.6.2 has a language string issue that breaks the JS so rest of it doesn't get run.
Correct by adding the parameter `$jsSafe = true`to `JText` in `default.php` in mod_ bt_login.

But still have the first issue...

**Comment by mahagr** [comment] 2015-07-16 20:08
I'm still not able to reproduce the issue on login. I don't think it has anything to do with Gantry, there must have been something else causing it.

Closing the issue, please be free to reopen it if there's new information.

**Closed by mahagr** 2015-07-16 20:08 UTC
Labels: bug

**Comment by pupsikus** [comment] 2015-11-05 15:08
I had the same error with BT login. I disabled cache in Joomla! and everything now works properly. Now I am using cache not in Joomla! but on CDN. Before it were double caching services and probably they conflicted somehow.
