### ISSUE TITLE
Can't delete social items from social particle in all templates.

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#767] opened 2015-08-30 12:26 UTC
You cannot delete the items in the social particle in any of the G5 templates

1. delete items from social particle on "settings" tab of base outline and save 
2. go to another outline
3. return to base outline and look at social items - they have all been reinstated again!

**Comment by marktaylor46** [comment] 2015-08-30 12:47
http://www.rockettheme.com/forum/joomla-template-salient/247055-can-t-change-social-items-since-gantry-update?start=0#1230916

http://www.rockettheme.com/forum/joomla-template-callisto/247054-tearing-hair-out

**Comment by marktaylor46** [comment] 2015-08-30 15:23
http://www.rockettheme.com/forum/gantry5-for-joomla/247062-gantry-5-11-problem?start=0#1230951

**Comment by adi8i** [comment] 2015-08-31 09:52
The issue should be fixed in the latest CI Build, please read: #773

**Comment by kat05** [comment] 2015-08-31 12:24
no, this is still not fixed in latest ci a45f4d370

**Comment by mahagr** [comment] 2015-08-31 13:06
I'm not sure anymore that this is caused by the same issue.

**Comment by mahagr** [comment] 2015-08-31 19:21
Should be fixed now.

**Comment by kat05** [comment] 2015-08-31 19:28
commit: d32d5e61d seems to have fixed this, works now as expected!

**Closed** 2015-08-31 19:29 UTC
Labels: bug, regression

**Comment by marktaylor46** [comment] 2015-08-31 19:52
yah is good for me too - great :)
