### ISSUE TITLE
Future Request: HTML Editor as Particle Field

### ISSUE THREAD

**Issue by reramjiawan** [gantry/gantry5#2058] opened 2017-07-23 22:31 UTC
Hello,

I would like to make a future request to have the HTML Editor just like on the Pages Section available in Particle Fields f.e. input.textarea.

Thanks!

**Comment by paulzz3000** [comment] 2017-08-10 08:00
+1

**Comment by mahagr** [comment] 2017-08-14 16:38
Duplicate of #236

**Closed by mahagr** 2017-08-14 16:38 UTC
Labels: duplicate
