### ISSUE TITLE
Installing CI does not always update all changed files on Mac Yosemite

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#492] opened 2015-06-24 09:38 UTC
This is the third time I have encountered the problem.

Today, I was verifying the file `/media/gantry5/engines/common/nucleus/templates/layout/section.html.twig` due to conflicts between my overridden version and the more recent changes that have been implemented since RC3. I then verified the code in the github repo and it was significantly different.

I have installed multiple updates of the CI since RC3, and yet this file never seems to have updated. At this point, I have no idea what files are at what version, and since this is at least the third time I have encountered this issue, I am certain that many files are not updated.

As there is no simple way to `git pull` the CI packages, it will be very difficult for me to do a manual update to ensure all core files are properly updated.

I know that there is now an MD5 checksum and that this is available but as yet not implemented. I feel that this is a high priority because man users develop on Mac and need to be able to feel certain that when they install a new CI build, all changed files are updated accordingly.

**Comment by w00fz** [comment] 2015-06-24 16:54
I think something might be off with your installation. I would suggest making a backup (just in case) and uninstall Gantry (just gantry, not the theme). Then verify that no Gantry folders or files are left in the various locations and once that's done, install the CI Build again.

From that point you should be getting everything synched again whenever you reinstall a CI Build. Files are getting replaced during Joomla installation but old orphan ones aren't getting removed. 
I think it just needs a cleanup to get synchronized with the latest restructure, I dont think this is CI Build fault.

Please try the above. I know for instance that layouts have been moved into a subfolder `layouts` not so long ago and I did see something similar to what you are describing in some of my oldest local instances where I had symbolic links. None of my overrides tests were working because of that, so I just had to cleanup all and relink and everything worked again.

**Comment by alisamii** [comment] 2015-06-25 12:16
@w00fz My overrides are working. The problem is that core files, located in the same directory hierarchy as found in the repo, don't get updated.

I tried on a fresh install. I started with RC3, then updated to the latest CI build. I then checked to see if all files that had been changed in the latest CI build were updated. Some were, others were not.

For example, this file should have been updated:

`engines/joomla/nucleus/twig/partials/base.html.twig`

On line 10, the string `Sorry, no content` should have been updated to `{{ 'GANTRY5_ENGINE_SORRY_NO_CONTENT'|trans }}` but it was not!

**Comment by w00fz** [comment] 2015-06-25 19:45
I did try also yours steps. Fresh Joomla 3.4.1 installation, installed RC3, checked the file in question and there was `Sorry, no content`. I then downloaded the latest CI, installed it, checked the file again and now it was saying `{{ 'GANTRY5_ENGINE_SORRY_NO_CONTENT'|trans }}`.

There might be other issues with your setup. For instance, there is no `engines/joomla/nucleus` with the installable packages, just `engines/nucleus`.

**Comment by alisamii** [comment] 2015-06-25 22:29
Hi Djamil,

The `engines/joomla/nucleus` path is the path to the file in the github Repo. There is no such path in the joomla install, as you correctly mentioned, it is `engines/nucleus`. Since I was typing on the iPad when I replied earlier, as I am doing now as well, I just put the Repo path in with a copy paste and forgot to remove the `joomla/` from the path.

This issue is not trivial as it can be very counterproductive to work on files that don't get properly updated. And as Matias has stayed, this issue is something that has been encountered before. He believes it is a Mac Yosemite relayed issue, which may very well be the case. But implementing checksums and ensuring that updated files pad a checksum could help reduce or at the very least provide guidance to users as to what files may need to be manually verified.

Since the md5 checksum is being generated, I would hope that you could implement a post install process that verifies the checksum and displays any files that do not match the hash.

Best regards,

Ali

**Comment by w00fz** [comment] 2015-06-25 22:41
I think what Matias was referring to was purely regarding the file modified time in OSX, that's the only issue we have seen and noticed. For whatever reason in OS X, sometimes, modified files are not being detected as so which let the Compiler to believe nothing has changed and so that it doesn't need recompilation.

That is a whole different thing, what you are describing is purely joomla installation, not replacing files as expected. There is no file modification time check on our end for that, it's purely replacing files and folders. I haven't heard of anyone else having this issue and I am on Yosemite as well, unable to reproduce this issue.

Whenever I install a CI Build, the files that are supposed to be different make their way into the filesystem. If you are having problem with the CI Build, you should be also having the same sort of  issue with everything else that you install via Joomla.

I also asked others to try reproduce it, I'm going to ask again: @gantry/developers Is any of you guys able to reproduce this issue at all?

**Comment by mahagr** [comment] 2015-06-26 06:45
I've never been able to reproduce this bug, but I know that there is a bug in Joomla that causes errors during unzipping or copying contents from a package to be ignored, which may also be the case in here. If the same files get ignored every time, I would suspect the issue being this. Usually uninstall/install fixes those issues (though uninstalling may have other side effects, like menu item wrong component id bug).

There has been also zlib bug in the past, which caused some files to be corrupted/missing during unzip if they were zipped in newer version of zlib. But that was years ago and I've not seen the issue for 2 years anymore.

I don't believe that there is any bug in our code and using MD5 checks wouldn't really fix the issue either. I do agree with adding MD5 checks as it would allow us to detect if user has changed wrong files, but we already have issue #209 for it.

**Comment by alisamii** [comment] 2015-06-27 20:47
I'm just suggesting that if the md5 check is performed, then an additional action could be added to display a list of files that did not pass the md5 check. Perhaps it could be added as a post install message that users can Consult rather than displayed in the installer page as an error so that users don't get confused

Best regards,

Ali

**Comment by mahagr** [comment] 2015-07-17 10:14
Update on this. After talking with @alisamii it looks like the issue is Joomla failing to unzip some files from the archive but not detecting the issue.

Issue can be avoided by unzipping the package to server and running install from the directory. I bet that the issue gets also fixed by locally unzipping and zipping the package before installation.

I've seen the issue numerous times in Kunena when packaging zip in Linux / Java. I think the issue comes from slight incompatibilities between zlib versions and happens when PHP has statically linked version of zlib in some unknown circumstances. In Kunena's case we used to have files cut into half and sometimes changing only one byte (adding space) fixed the issue.. Or caused it to happen in another file.

**Comment by w00fz** [comment] 2015-08-12 21:20
Alright, I'm going to close this since it's been determined to be a Platform and OS issue and not really Gantry related.

**Closed by w00fz** 2015-08-12 21:20 UTC
Labels: question
