### ISSUE TITLE
"Joomla Articles" pagination does not work when used in module

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2511] opened 2019-07-02 08:48 UTC
The "Joomla Articles" particle pagination does not work when used in a "Gantry 5 particle" module.

If you place the particle directly on the layout of the outline then it works fine, just not inside a module. There are no error messages shown at all.

To reproduce:

1. Add a module position somewhere on the layout of your chosen outline.
2. Create a "Gantry 5 particle" module of type "Joomla articles" particle type, turn pagination to "show" in the settings and select a suitable category to show, set module position as the position created in step 1. SAVE.
3. Look on front end and try the pagination buttons... they do not work at all.

Originally reported in Forum here: https://rockettheme.com/forum/joomla-template-callisto/281472-joomla-articles-contentarray-in-module-issue

 This ticket may also be the same issue https://github.com/gantry/gantry5/issues/2381

**Comment by simmonsr** [comment] 2020-02-28 23:12
If a module created the content-array-##-particle id then it would work, but since there is no id being loaded, it doesn't work.

**Comment by jikometrix** [comment] 2020-03-03 19:53
Hello, 
Do you think this will be fixed in the next release?

**Comment by jikometrix** [comment] 2020-03-16 21:35
Hello,
Do you think this will be fixed in the next release?

**Comment by jikometrix** [comment] 2020-03-26 15:14
Hello,
Do you think this will be fixed in the next release?

**Comment by jikometrix** [comment] 2020-04-22 21:26
Hello,
Do you think this will be fixed in the next release?

**Closed** 2020-04-27 11:06 UTC
Labels: bug, joomla

**Comment by simmonsr** [comment] 2020-04-27 17:54
confirmed fix
