### ISSUE TITLE
gantry5 joomla https font-awesome IE11

### ISSUE THREAD

**Issue by ghazal** [gantry/gantry5#1151] opened 2016-02-17 09:46 UTC
hi,
while using https:, there is a loading pb with font-awesome css library back and front on IE11.
No pb with Firefox or Chrome with a SSL certificate.

Anyone an idea ?

Gantry 5.2.10

**Comment by mahagr** [comment] 2016-02-17 15:00
I'm not sure what you mean my pb..?

**Comment by w00fz** [comment] 2016-02-19 22:42
He means `problem`. I am not sure how this could be a problem though, we load font-awesome css and fonts relative to the site, which means it's protocol-less and it doesn't matter if it's HTTP or HTTPS.

Could you paste a link to the site with the issue?

**Comment by ghazal** [comment] 2016-02-20 09:53
@w00fz Tks for "interpreting" my "pb".  :-)
>> we load font-awesome css and fonts relative to the site
this is as it should be. Thats why I dont understand why IE behaves like this.
Maybe a wrong setting somewhere. I'll keep digging and get back to you if needed.

**Comment by w00fz** [comment] 2016-02-23 19:56
I don't seem to be able to reproduce this issue @ghazal.
The file seems to be loading fine and doesn't cause any error. What exactly are you getting?

![ie11 - win10 fresh install running 2016-02-23 11-53-58](https://cloud.githubusercontent.com/assets/11734/13264720/62304092-da24-11e5-9a2f-fc7be6e65e19.png)

**Comment by chanteu94** [comment] 2016-02-25 10:33
Hi, i'm the owner of this problèm and i subscribe today on github.  I don't think that the problem is due to gantry or font awesome because the problem occurs orly when i use internet explorer (no problem with chrome and mozilla) and only when i refresh my website.  I'm sorry but i can't now reproduice the problem because i change the framework. I'm still interested by an issue because i'll come back on gantry framework soon. Thank you.

**Comment by chanteu94** [comment] 2016-02-25 10:37
Just one more thing: for your question 'what i'm getting?'...  On refresh, social icons and icons menu disappear..

**Comment by mahagr** [comment] 2016-02-25 11:23
Can you see the same issue in our demos or was it just in your website?

**Comment by chanteu94** [comment] 2016-02-25 18:41
I'v made something different. I've tried my web site with Protostar Template of Joomla. The icons of the login disapear too when I refresh the website.
How can I try your demo on my https website ?

**Comment by chanteu94** [comment] 2016-02-25 19:05
I have an idea to show you the problem. The problem occurs without opening the website.

Try with internet explorer  11 :

https://www.immofiliere.fr/immo/administrator

You can see that the display  icons for login are wrong.
If you try to connect without sign in, icons becomes ok.
And if you refresh the website, display icons becomes wrong.

With Chrome and Mozilla, no problem.

Any idea ?

**Comment by chanteu94** [comment] 2016-02-25 19:07
For more information, I use Joomla 3.4.8 and my host is OVH (php 5.6)

**Comment by w00fz** [comment] 2016-02-25 19:13
This is IE11 for me when going to that site, everything seems to work fine. I am now thinking this issue might be related to your own computer. Do you have any way to test with another windows with the same browser and see if the issue still occurs?

![ie11 - win10 fresh install running 2016-02-25 11-12-38](https://cloud.githubusercontent.com/assets/11734/13331078/b6c08d0a-dbb0-11e5-89e4-4b7bca2c5633.png)

**Comment by mahagr** [comment] 2016-02-26 07:36
By asking you to test our demos I meant if you get the same issue with some other Joomla site, or if the issue is only happening in your server. Or does it happen with another computer with IE11?

Something is causing your issues and it could be

1) your computer (IE11)
2) your server
3) something else

As it happens in both frontend and backend, I wonder if the font file gets properly loaded..?

I'm also guessing that this isn't Gantry issue as it happens in login screen of Joomla. But I don't think its Joomla that has the issue either.

**Comment by chanteu94** [comment] 2016-02-26 15:33
Hi everybody
I've  made the test on two others computers and I have the same problem.
My computer ; Windows 8.1, IE 11.0.28 (last version)
Other computer : Windows 8.1 IE 11.0.28 
Other computer : Windows 7  IE 11.0.13
So, for the moment we can say that it's not my computer.
I see that you use Windows 10 and it works. So, perhaps something wrong with older version than Windows 10 ?

**Comment by Exrace** [comment] 2016-02-26 21:38
I see this with win 8.1 and ie11
![ie11_win81](https://cloud.githubusercontent.com/assets/11910897/13366131/4ff910ae-dca7-11e5-877a-817ec4a72bf3.JPG)

**Comment by chanteu94** [comment] 2016-02-26 23:22
Hi Exrace,  mystery becomes more and more bigger... 
Can you tell me the version of ie 11 and Windows 8.1 (pro, family,...) ?
I use Windows 8.1 pro on 2 computers and Windows 7 on the third.. No icons for me first time...Very, Very strange.

**Comment by Exrace** [comment] 2016-02-27 14:25
Windows 8.1 Enterprise
![ie11_ver](https://cloud.githubusercontent.com/assets/11910897/13373351/edee0620-dd33-11e5-9375-b5ced5f11b27.JPG)

**Comment by Exrace** [comment] 2016-02-27 14:26
Possible you have some type of AV link scanner on your computer?

**Comment by chanteu94** [comment] 2016-02-27 14:45
No AV Link Scanner on the 3 computers - no antivirus - here is hard copy

![capture](https://cloud.githubusercontent.com/assets/17471856/13373452/d8649d3e-dd68-11e5-953f-58d75114192e.JPG)

**Comment by w00fz** [comment] 2016-02-27 19:13
By the way, the login page is not related to gantry in any way, that is joomla.
I don't think your issue is caused by Gantry or Joomla, something else is going on with the server where you are hosting the joomla instance and the way it serves fonts.

**Comment by chanteu94** [comment] 2016-02-28 11:16
Hi w00fz, i'm quite sure you're right.. I try yesterday with annoter computer Windows 10 with ie 11..always the same. So what can be the problem between ie11 and joomla or between ie11 and my host ?

**Comment by marktaylor46** [comment] 2016-02-28 13:32
I can get the same effect by disabling the "iconmoon" font manually using IE11 dev tools. So the issue is that the font is not loading.

![2016-02-28_11-49-58](https://cloud.githubusercontent.com/assets/11683218/13379513/571fc14c-de1f-11e5-94e9-ff9de645f91a.png)

So the next question is why not... well I found this articles and it appears that suggests the reason is because he response from your server has a Cache-Control header of 'no-store'. IE seems to have issues with caching and fonts.

You can find more information here (and the links therein).

http://stackoverflow.com/questions/26894319/icon-fonts-not-loading-in-ie11

I hope that helps.

**Comment by Exrace** [comment] 2016-02-28 15:48
I can dup the problem now with my IE 11 and win 8.1 by simply refreshing the page once the has loaded once. I can also repeat the issue by enabling dev tools and loading the page or by opening the page with an inprivate session. Your apache is reporting the following with a discovery web server tool: cache-control	no-store, no-cache, must-revalidate, post-check=0, pre-check=0,no-store, no-cache, must-revalidate, post-check=0, pre-check=0

**Comment by mahagr** [comment] 2016-02-29 08:32
If it is indeed caching issue with fonts, you should be able to change that in your .htaccess

I agree that this looks like server configuration vs a bug in IE.

**Comment by chanteu94** [comment] 2016-02-29 17:35
Hi everybody,
Thanks for all and particulary to marktaylor46 . With his answer, i found how to correct the bug 

**In my .ovhconfig , i delete line environment=development**

And now it works !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

We can close this issue.

**Comment by marktaylor46** [comment] 2016-02-29 17:37
woohoo :+1:  glad I could help :)

**Closed** 2016-02-29 17:47 UTC
Labels: question
