### ISSUE TITLE
Exportable Particles and Sections

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#339] opened 2015-05-22 18:47 UTC
As a developer, I would like to be able to have the ability to reverse the particle and section definition process so that particles and / or sections that I have defined and structured within a layout can be exported / saved into a global bucket and then be available to be imported / inserted in another layout.

The workflow would be:

In **Theme Outline > Hydrogen - Home > Layout ** I populate a section called "Regions".

In this section, I have 2 rows

The first row has a Custom HTML Particle which has been defined with *default content*, *CSS ID*, *CSS Classes*, *Variations* and *Tag Attributes*.

In the 2nd row, I have 4 Custom HTML Particles, again, defined and populated with various settings and content.

As I will be using those same particles (or almost the same particles) on other layouts, I would like to save the particles (and perhaps the section) such that I could later import that setup in another layout rather than reconfigure each one multiple times.

As such, I would click on an "export" button within the particle modal which would then prompt me for a name and save both the **.yaml* file and the **.html.twig* in the *custom* directory.

I can then switch to the *settings* tab and that custom saved particle would be available there, and also available in all other outlines.

**Comment by mahagr** [comment] 2015-05-23 07:12
Right now we are doing some of that in Callisto inside layout presets, but I agree that a better way to handle it is needed than to change presets by hand.

**Comment by alisamii** [comment] 2015-07-08 22:53
Bumping this issue up to see if this can get a bit of RT TLC,!!

**Comment by alisamii** [comment] 2015-09-01 04:09
Any chance this can be added to the 5.2 release?

**Comment by mahagr** [comment] 2015-09-10 09:56
We cannot implement this feature until some other stuff has been implemented. One of the requirements is the new yaml syntax to be used for the layouts and that one has been targeted to 5.2.

**Comment by alisamii** [comment] 2016-05-09 18:48
Now that we have inheritance almost out the door, I would hope that this issue could get some attention. It is the next logical extension to inheritance, especially with #680 as well (even though that issue is closed).

**Comment by w00fz** [comment] 2016-05-09 19:21
After Inheritance, our focus will revert back to Grav integration. We have flipped the priorities of Grav integration and Inheritance because we didn't want to wait any longer for Inheritance. We know this has been the Achille's heel of Gantry 5 and we felt with you guys the pain, that's why we switched gear to get Inheritance done now.

However, Grav is still high in priority for us, so I think export/import will have to still wait. All we would add is really just an UI from the admin, since you can already export / import manually.

Keep in mind we also have to address multi-language / translations support, this is also going to soon become a very high priority.

**Comment by w00fz** [comment] 2016-06-04 01:05
Marking this as duplicate of #218, even though it's probably going to be layout export/import more than individual particle settings.

**Closed by w00fz** 2016-06-04 01:05 UTC
Labels: duplicate, feature
