### ISSUE TITLE
Ability do display yaml settings as body class

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1120] opened 2016-01-22 12:07 UTC
Like in Gantry 4 where you could set `isBodyClass="true"` and the param would be displayed in `<body>` tag as class ie. `header-style-light`

**Comment by mahagr** [comment] 2016-03-16 19:06
One alternative would be to have extra twig file where you could have extra functionality and possibility to alter how Gantry works.

In that file you could do something like this:

    {% do gantry.page.addBodyClass('g-navigation-' ~ gantry.config.styles.navigation.style) %}

**Comment by w00fz** [comment] 2016-06-04 05:06
Duplicate of #948

**Closed by w00fz** 2016-06-04 05:06 UTC
Labels: duplicate, feature, grav, joomla, wordpress
