### ISSUE TITLE
adding icon to menu option breaks menu 

### ISSUE THREAD

**Issue by webmasterchris** [gantry/gantry5#245] opened 2015-05-13 17:15 UTC
![fontawesomemenuicon](https://cloud.githubusercontent.com/assets/11822535/7616298/5ae1f6c6-f971-11e4-93d6-046104014885.PNG) this error comes up when attempting to either access menu editor after saving icon addition or anytime I attempt to change arrangement of current menu children
![sitemenuissue](https://cloud.githubusercontent.com/assets/11822535/7616301/60b185da-f971-11e4-8977-6b396500ecd0.PNG) this error shows up on front end of the website after saving an icon in the menu

**Comment by webmasterchris** [comment] 2015-05-13 17:15
PATH 	/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
PWD 	/usr/local/cpanel/cgi-sys
SHLVL 	0
PHP_FCGI_MAX_REQUESTS 	5000
SCRIPT_NAME 	/dpls/administrator/index.php
REQUEST_URI 	/dpls/administrator/index.php?option=com_gantry5&view=menu/mainmenu/discover&style=17&c99698666be4ba919e24ef9ecb066e8c=1&format=json&inline=1
QUERY_STRING 	option=com_gantry5&view=menu/mainmenu/discover&style=17&c99698666be4ba919e24ef9ecb066e8c=1&format=json&inline=1
REQUEST_METHOD 	POST
SERVER_PROTOCOL 	HTTP/1.1
GATEWAY_INTERFACE 	CGI/1.1
REMOTE_PORT 	61305
SCRIPT_FILENAME 	/home/ckrumnow2/public_html/dpls/administrator/index.php
SERVER_ADMIN 	webmaster@webmasterchris.com
CONTEXT_DOCUMENT_ROOT 	/home/ckrumnow2/public_html
CONTEXT_PREFIX 	
REQUEST_SCHEME 	http
DOCUMENT_ROOT 	/home/ckrumnow2/public_html
REMOTE_ADDR 	66.213.96.100
SERVER_PORT 	80
SERVER_ADDR 	192.186.201.196
SERVER_NAME 	www.webmasterchris.com
SERVER_SOFTWARE 	Apache/2.4.12 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.10-dev
SERVER_SIGNATURE 	
LD_LIBRARY_PATH 	/usr/local/apache/lib
HTTP_CACHE_CONTROL 	no-cache
HTTP_PRAGMA 	no-cache
HTTP_CONNECTION 	close
HTTP_COOKIE 	d5cb2b06382e1baeaac76917ef41ad66=en-GB; roksprocket-showitems=1; __utma=90103069.2106527708.1429547806.1430412867.1430483944.17; __utmz=90103069.1429547806.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); 5554f28395b66a9ec5b25be46f152c7e=8d145a5be4d173a43d2b451b58f3d968; 76972f553f29e347d14831284982808b=e5ac63b4743c44b41c06cfde17af8f89
CONTENT_LENGTH 	11895
HTTP_REFERER 	http://www.webmasterchris.com/dpls/administrator/index.php?option=com_gantry5&view=menu/mainmenu/discover&style=17&c99698666be4ba919e24ef9ecb066e8c=1
CONTENT_TYPE 	application/x-www-form-urlencoded; charset=UTF-8
HTTP_ACCEPT_ENCODING 	gzip, deflate
HTTP_ACCEPT_LANGUAGE 	en-US,en;q=0.5
HTTP_ACCEPT 	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
HTTP_USER_AGENT 	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0
HTTP_HOST 	www.webmasterchris.com
HTTP_AUTHORIZATION 	
UNIQUE_ID 	VVOGtLioyGsAABG60WoAAAIN
FCGI_ROLE 	RESPONDER
PHP_SELF 	/dpls/administrator/index.php
REQUEST_TIME_FLOAT 	1431537332.18
REQUEST_TIME 	1431537332
argv 	Array ( [0] => option=com_gantry5&view=menu/mainmenu/discover&style=17&c99698666be4ba919e24ef9ecb066e8c=1&format=json&inline=1 )
argc 	1
GET Data
option 	com_gantry5
view 	menu/mainmenu/discover
style 	17
c99698666be4ba919e24ef9ecb066e8c 	1
format 	json
inline 	1
POST Data
menutype 	mainmenu
settings 	[]
ordering 	{"":[["home","discover","using-the-library","research-learning","events-classes","kids","teens","about","locations"]],"discover":[["discover/new-titles","discover/best-sellers","discover/book-groups","discover/novelist-plus","discover/novelist-k-8-plus"]],"using-the-library":[["using-the-library/get-a-library-card","using-the-library/wifi"]],"locations":[["locations/defiance-public-library","locations/johnson-memorial-library","locations/sherwood-branch-library"]]}
items 	{"home":{"id":"101","type":"component","alias":"home","path":"home","link":"index.php?option=com_content&view=article&id=1","title":"Home","subtitle":"","image":"","icon_only":false,"parent_id":"","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":1},"discover":{"id":"110","type":"component","alias":"discover","path":"discover","link":"index.php?option=com_content&view=article&id=2","title":"Discover","subtitle":"","image":"","icon_only":false,"parent_id":"","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":1},"discover/new-titles":{"id":"122","type":"component","alias":"new-titles","path":"discover/new-titles","link":"index.php?option=com_content&view=article&id=17","title":"New Titles","subtitle":"","image":"","icon_only":false,"parent_id":"discover","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":2},"discover/best-sellers":{"id":"126","type":"component","alias":"best-sellers","path":"discover/best-sellers","link":"index.php?option=com_content&view=article&id=18","title":"Best Sellers","subtitle":"","image":"","icon_only":false,"parent_id":"discover","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":2},"discover/book-groups":{"id":"127","type":"component","alias":"book-groups","path":"discover/book-groups","link":"index.php?option=com_content&view=article&id=19","title":"Book Groups","subtitle":"","image":"","icon_only":false,"parent_id":"discover","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":2},"discover/novelist-plus":{"id":"128","type":"component","alias":"novelist-plus","path":"discover/novelist-plus","link":"index.php?option=com_content&view=article&id=20","title":"Novelist Plus","subtitle":"","image":"","icon_only":false,"parent_id":"discover","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":2},"discover/novelist-k-8-plus":{"id":"129","type":"component","alias":"novelist-k-8-plus","path":"discover/novelist-k-8-plus","link":"index.php?option=com_content&view=article&id=21","title":"Novelist K-8 Plus","subtitle":"","image":"","icon_only":false,"parent_id":"discover","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":2},"using-the-library":{"id":"111","type":"component","alias":"using-the-library","path":"using-the-library","link":"index.php?option=com_content&view=article&id=3","title":"Using the Library","subtitle":"","image":"","icon_only":false,"parent_id":"","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":1},"using-the-library/get-a-library-card":{"id":"130","type":"component","alias":"get-a-library-card","path":"using-the-library/get-a-library-card","link":"index.php?option=com_content&view=article&id=22","title":"Get a Library Card","subtitle":"","image":"","icon_only":false,"parent_id":"using-the-library","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":2},"using-the-library/wifi":{"id":"131","type":"component","alias":"wifi","path":"using-the-library/wifi","link":"index.php?option=com_content&view=article&id=23","title":"WiFi","subtitle":"","image":"","icon_only":false,"parent_id":"using-the-library","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":2},"research-learning":{"id":"112","type":"component","alias":"research-learning","path":"research-learning","link":"index.php?option=com_content&view=article&id=4","title":"Research & Learning","subtitle":"","image":"","icon_only":false,"parent_id":"","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":1},"events-classes":{"id":"113","type":"component","alias":"events-classes","path":"events-classes","link":"index.php?option=com_content&view=article&id=5","title":"Events & Classes","subtitle":"","image":"","icon_only":false,"parent_id":"","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":1},"kids":{"id":"114","type":"component","alias":"kids","path":"kids","link":"index.php?option=com_content&view=article&id=6","title":"Kids","subtitle":"","image":"","icon_only":false,"parent_id":"","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":1},"teens":{"id":"115","type":"component","alias":"teens","path":"teens","link":"index.php?option=com_content&view=article&id=7","title":"Teens","subtitle":"","image":"","icon_only":false,"parent_id":"","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":1},"about":{"id":"120","type":"component","alias":"about","path":"about","link":"index.php?option=com_content&view=article&id=12","title":"About","subtitle":"","image":"","icon_only":false,"parent_id":"","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":1},"locations":{"id":"121","type":"component","alias":"locations","path":"locations","link":"index.php?option=com_content&view=article&id=13","title":"Locations","subtitle":"","image":"","icon_only":false,"parent_id":"","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":1},"locations/defiance-public-library":{"id":"123","type":"component","alias":"defiance-public-library","path":"locations/defiance-public-library","link":"index.php?option=com_content&view=article&id=15","title":"Defiance Public Library","subtitle":"","image":"","icon_only":false,"parent_id":"locations","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":2},"locations/johnson-memorial-library":{"id":"124","type":"component","alias":"johnson-memorial-library","path":"locations/johnson-memorial-library","link":"index.php?option=com_content&view=article&id=14","title":"Johnson Memorial Library","subtitle":"","image":"","icon_only":false,"parent_id":"locations","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":2},"locations/sherwood-branch-library":{"id":"125","type":"component","alias":"sherwood-branch-library","path":"locations/sherwood-branch-library","link":"index.php?option=com_content&view=article&id=16","title":"Sherwood Branch Library","subtitle":"","image":"","icon_only":false,"parent_id":"locations","layout":"list","target":"_self","dropdown":"standard","icon":"","visible":true,"group":0,"columns":[],"level":2}}
Files
empty
Cookies
d5cb2b06382e1baeaac76917ef41ad66 	en-GB
roksprocket-showitems 	1
__utma 	90103069.2106527708.1429547806.1430412867.1430483944.17
__utmz 	90103069.1429547806.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
5554f28395b66a9ec5b25be46f152c7e 	8d145a5be4d173a43d2b451b58f3d968
76972f553f29e347d14831284982808b 	e5ac63b4743c44b41c06cfde17af8f89
Session
__default 	Array ( [session.counter] => 203 [session.timer.start] => 1431531370 [session.timer.last] => 1431537275 [session.timer.now] => 1431537332 [session.client.browser] => Mozilla/5.0 (Windows NT 6.3; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0 [registry] => Joomla\Registry\Registry Object ( [data:protected] => stdClass Object ( [application] => stdClass Object ( [lang] => en-GB ) [com_modules] => stdClass Object ( [modules] => stdClass Object ( [filter] => stdClass Object ( [client_id_previous] => 0 ) ) ) [com_installer] => stdClass Object ( [message] => [extension_message] => [manage] => stdClass Object ( [filter] => stdClass Object ( [search] => cal [client_id] => [status] => [type] => [group] => ) [ordercol] => name [orderdirn] => asc [limitstart] => 0 ) [redirect_url] => ) [global] => stdClass Object ( [list] => stdClass Object ( [limit] => 20 ) ) [com_cache] => stdClass Object ( [cache] => stdClass Object ( [ordercol] => group [filter] => stdClass Object ( [client_id] => 0 ) [orderdirn] => asc [limitstart] => 0 ) ) [com_menus] => stdClass Object ( [items] => stdClass Object ( [menutype] => mainmenu [limitstart] => 0 [list] => Array ( [direction] => asc [limit] => 20 [ordering] => a.lft [start] => 0 ) ) ) ) [separator] => . ) [user] => JUser Object ( [isRoot:protected] => 1 [id] => 842 [name] => Chris Krumnow [username] => ckrumnow [email] => ckrumnow@hotmail.com [password] => $2y$10$Kzm7oa3A0KBpg5JGsqUq5.5KcI4Nsuxl/3mk23/hsPva5Cc47LU4. [password_clear] => [block] => 0 [sendEmail] => 1 [registerDate] => 2015-05-04 19:43:08 [lastvisitDate] => 2015-05-13 14:29:40 [activation] => [params] => {"admin_style":"","admin_language":"","language":"","editor":"","helpsite":"","timezone":""} [groups] => Array ( [8] => 8 ) [guest] => 0 [lastResetTime] => 2015-05-04 19:43:08 [resetCount] => 0 [requireReset] => 0 [_params:protected] => Joomla\Registry\Registry Object ( [data:protected] => stdClass Object ( [admin_style] => [admin_language] => [language] => [editor] => [helpsite] => [timezone] => ) [separator] => . ) [_authGroups:protected] => Array ( [0] => 1 [1] => 8 ) [_authLevels:protected] => Array ( [0] => 1 [1] => 1 [2] => 2 [3] => 3 [4] => 6 ) [_authActions:protected] => [_errorMsg:protected] => [userHelper:protected] => JUserWrapperHelper Object ( ) [_errors:protected] => Array ( ) [aid] => 0 [otpKey] => [otep] => ) [session.token] => 140a62c99e53d211a83569248e9c3fe6 )
Environment Variables
PATH 	/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
PWD 	/usr/local/cpanel/cgi-sys
SHLVL 	0
PHP_FCGI_MAX_REQUESTS 	5000
SCRIPT_NAME 	/dpls/administrator/index.php
REQUEST_URI 	/dpls/administrator/index.php?option=com_gantry5&view=menu/mainmenu/discover&style=17&c99698666be4ba919e24ef9ecb066e8c=1&format=json&inline=1
QUERY_STRING 	option=com_gantry5&view=menu/mainmenu/discover&style=17&c99698666be4ba919e24ef9ecb066e8c=1&format=json&inline=1
REQUEST_METHOD 	POST
SERVER_PROTOCOL 	HTTP/1.1
GATEWAY_INTERFACE 	CGI/1.1
REMOTE_PORT 	61305
SCRIPT_FILENAME 	/home/ckrumnow2/public_html/dpls/administrator/index.php
SERVER_ADMIN 	webmaster@webmasterchris.com
CONTEXT_DOCUMENT_ROOT 	/home/ckrumnow2/public_html
CONTEXT_PREFIX 	
REQUEST_SCHEME 	http
DOCUMENT_ROOT 	/home/ckrumnow2/public_html
REMOTE_ADDR 	66.213.96.100
SERVER_PORT 	80
SERVER_ADDR 	192.186.201.196
SERVER_NAME 	www.webmasterchris.com
SERVER_SOFTWARE 	Apache/2.4.12 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.10-dev
SERVER_SIGNATURE 	
LD_LIBRARY_PATH 	/usr/local/apache/lib
HTTP_CACHE_CONTROL 	no-cache
HTTP_PRAGMA 	no-cache
HTTP_CONNECTION 	close
HTTP_COOKIE 	d5cb2b06382e1baeaac76917ef41ad66=en-GB; roksprocket-showitems=1; __utma=90103069.2106527708.1429547806.1430412867.1430483944.17; __utmz=90103069.1429547806.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); 5554f28395b66a9ec5b25be46f152c7e=8d145a5be4d173a43d2b451b58f3d968; 76972f553f29e347d14831284982808b=e5ac63b4743c44b41c06cfde17af8f89
CONTENT_LENGTH 	11895
HTTP_REFERER 	http://www.webmasterchris.com/dpls/administrator/index.php?option=com_gantry5&view=menu/mainmenu/discover&style=17&c99698666be4ba919e24ef9ecb066e8c=1
CONTENT_TYPE 	application/x-www-form-urlencoded; charset=UTF-8
HTTP_ACCEPT_ENCODING 	gzip, deflate
HTTP_ACCEPT_LANGUAGE 	en-US,en;q=0.5
HTTP_ACCEPT 	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
HTTP_USER_AGENT 	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0
HTTP_HOST 	www.webmasterchris.com
HTTP_AUTHORIZATION 	
UNIQUE_ID 	VVOGtLioyGsAABG60WoAAAIN
FCGI_ROLE 	RESPONDER
PHP_SELF 	/dpls/administrator/index.php
REQUEST_TIME_FLOAT 	1431537332.18
REQUEST_TIME 	1431537332
argv 	Array ( [0] => option=com_gantry5&view=menu/mainmenu/discover&style=17&c99698666be4ba919e24ef9ecb066e8c=1&format=json&inline=1 )
argc 	1
Registered Handlers
0. Whoops\Handler\PrettyPageHandler
1. Whoops\Handler\PlainTextHandler
2. Whoops\Handler\JsonResponseHandler
Gantry Administration by RocketTheme.

**Comment by kat05** [comment] 2015-05-13 17:52
i tried to replicate this issue in both hydrogen and callisto, but i am not running into any issue so far. i keep trying though. :)

**Comment by webmasterchris** [comment] 2015-05-13 18:30
last week I did the update to RC1. I uninstalled and reinstalled Gantry RC1. I can not replicate the error. Issue appears to have been the upgrade from Beta 5 to RC1 via the Joomla updater.

**Comment by adi8i** [comment] 2015-05-13 18:31
Yes... will be some issues if you just update, you need to uninstall and reinstall, so actually this is not a bug @mahagr

**Comment by w00fz** [comment] 2015-05-13 18:31
That sounds plausible explanation for this. There have been quite some changes between B5 and RC1.
I'll close it for now, feel free to open again if it happens again

**Closed by w00fz** 2015-05-13 18:31 UTC
Labels: bug
