### ISSUE TITLE
Clearing outline causes disruption to atoms

### ISSUE THREAD

**Issue by coolman01** [gantry/gantry5#1009] opened 2015-11-15 09:43 UTC
I cleared the default outline and everything worked fine (gantry 5.2.2 with isotope). Then tried to use Gantry Particle and when I clicked the select particle button got the 500 error with "Oops, Cache path not defined for compiled file " --path/analytics.yaml. So clearing an outline affects the defined atoms and prevents use of the gantry particle

As an addendum - i turned off the analytics atom everywhere and deleted my analytics settings so that it's not being used, and I still get the same error. Can't move forward now....

**Comment by w00fz** [comment] 2015-11-15 20:30
Hi,
when you say you cleared the outline did you mean you click the Clear button in Layout Manager? Also when you say you tried to use the Gantry Particle, did you mean you tried to drag and drop a Particle in the Layout Manager after having cleared it out?

**Comment by coolman01** [comment] 2015-11-15 20:32
Yes, I used the clear button in the layout manager.
I tried to use the gantry particle in the module manager and that's where the error shows up. Not in the layout manager. Sorry I wasn't clear.

**Comment by w00fz** [comment] 2015-11-15 20:34
The two shouldn't be related, the Gantry 5 Particle Module is an independent Joomla Module that you can setup and assign to any Position.
I wonder if you have Joomla cache enabled and/or Gantry set to Production?

**Comment by coolman01** [comment] 2015-11-15 20:35
No cache - I'm building so I never use cache, but it is on a real server. I'm not sure I know what you mean by "Gantry set to Production"

**Comment by w00fz** [comment] 2015-11-15 20:36
In the Gantry System plugin, you can set Gantry to either Development or Production.

**Comment by coolman01** [comment] 2015-11-15 20:37
Oh - OK - I just checked. Production mode is off.

**Comment by w00fz** [comment] 2015-11-15 21:56
If you like you can hop into [Gitter Chat](http://gitter.im/explore/tags/php) and PM me with the details for the site so I can have a closer look. I cannot reproduce the issue you are reporting in my local.

**Comment by mahagr** [comment] 2015-11-16 13:05
You are missing default style in Joomla; you only have default style for each language, but you really need also one which is global fallback to all the other languages.

**Comment by mahagr** [comment] 2015-11-16 15:25
Issue was solved in gitter chat.

**Closed by mahagr** 2015-11-16 15:25 UTC
Labels: question
