### ISSUE TITLE
custom.scss @import "dependencies" is adding CSS 

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1152] opened 2016-02-17 15:46 UTC
If you create a custom.scss file and just put in that one line

@import "dependencies";

Then if you recompiled CSS from the base outline you will see that there are serveral CSS statements being added to the compiled CSS file.

The import of dependencies should only be giving access to the mixins and variables. The import itself should not be adding any CSS statements.

I checked from Hydrogen to Galatea and they all do the same thing.

![2016-02-17_15-45-06](https://cloud.githubusercontent.com/assets/11683218/13114916/89291b4c-d58d-11e5-97a4-511c4d73f30e.png)

**Comment by mahagr** [comment] 2016-02-17 16:08
@w00fz Can you take a look on this? Something in our recent CSS changes has broken the dependencies import a bit.

**Comment by w00fz** [comment] 2016-02-19 20:59
Just to move our private discussion to here. This has always been this way and it's not an issue introduced at any time.
The culprit for this to happen is in caused by [`@import "nucleus/theme/base";`](https://github.com/gantry/gantry5/blob/develop/themes/hydrogen/common/scss/_dependencies.scss#L16) which was added 25th of may 2015.

That said, ideally we should move that portion somewhere else theme specific, the only big worry here is making sure everything continues working as expected.

**Comment by w00fz** [comment] 2016-02-19 21:02
Additionally, another issue with that portion is that it is implemented in each and every template, so removing that bit will require touching any template, potentially causing a breaking change.

**Comment by w00fz** [comment] 2016-02-19 21:41
@marktaylor46 Please have a look at this commit https://github.com/gantry/gantry5/commit/b1f9523b492401c18186ebb8c1501e66df98fb2e , I applied a change and explained all that is involved.
If you could give this a good test, perhaps even try this approach on other RT themes that would be appreciated (note, no RT theme has this fix yet so you would have to manually try applying the fix as you see in my commit).

---

@JoomFX, @adi8i I know you guys develop G5 themes and I believe this affects you guys directly as well, could you take a look at this. Basically what I'm trying to do here is try to make sure after this change dependencies and compilation are still working as expected, without causing any issues I haven't considered.

---
Cheers!
/cc @gantry/team

**Comment by JoomFX** [comment] 2016-02-20 08:05
Thanks for letting us know @w00fz (and thanks @marktaylor46 for reporting this).

I gave it a quick test - I moved `@import "nucleus/theme/base";` from `_dependencies.scss` into `themename.scss` and everything works as expected. I then imported `dependencies` into `custom.scss`, tested a Bourbon mixin and everything seems to work just fine ;)

**Comment by marktaylor46** [comment] 2016-02-20 10:38
@w00fz thanks. I have tested this in Antares, Ambrosia and Callisto and it seems to work perfectly - no issues. I will raise a ticket to change all the templates on our internal tracker.

:)

**Comment by mahagr** [comment] 2016-02-22 07:48
What I am really worried about:

What happens if users update Gantry but not the template? I am sure that it will happen in way too many sites as users have no automated way to update anything else than Hydrogen.

From what I can see, this is backwards incompatible change that breaks all the sites which do not update the theme as well. As such, should we keep the BC and introduce new dependencies file?

**Comment by w00fz** [comment] 2016-02-22 08:02
It is backward incompatible but after further investigation and confirmations from the guys above, it is not such a big deal if someone has the template _un-patched_.
In fact, the only downside for not updating the templates (since this fix is purely template related and not Gantry core itself), is that you will keep getting the extra CSS in your compiled SCSS files, which is the behavior that has been going on for over a year and hasn't really caused any issue.

The fix itself is just to remove the extra overhead going forward but even though it's not backward compatible, it is not a breaking change.

I would probably categorize this as a cosmetic change and an optimization, more than anything else.

**Comment by mahagr** [comment] 2016-02-22 08:17
Oh, right. I missed the fact that dependencies was inside the theme and not nucleus. I am cool with the change. :)

**Comment by kat05** [comment] 2016-02-22 09:40
applied to all g5 club templates from callisto to galatea. will go out with next update releases.

**Comment by mahagr** [comment] 2016-02-22 10:54
I'm closing the issue.

**Closed by mahagr** 2016-02-22 10:54 UTC
Labels: bug
