### ISSUE TITLE
Strange behavior of the assignments tab H 5.5.13

### ISSUE THREAD

**Issue by kosh2323** [gantry/gantry5#3038] opened 2022-05-14 10:58 UTC
Hello everyone. I noticed that the assignment in the Gelium 5.5.13 template works strangely. For example, if you assign a default template for all pages, then for some reason the switches do not respond on the Assignment tab, even if you select them manually and then add a new page, the switch of this page will not be activated, although the template itself is still connected. Even if you assign the Home template to the main page, then in this template, by default, the switches also do not respond. If I'm not mistaken, this was not the case in earlier versions. What could be the reason?

![1](https://user-images.githubusercontent.com/82117170/168422876-cd1ad798-c21a-42d6-9c39-759d60472aa1.jpg)

![2](https://user-images.githubusercontent.com/82117170/168422879-f9db8c43-c414-4d6f-b6da-3a4c7fbe9d50.jpg)

![3](https://user-images.githubusercontent.com/82117170/168422882-364d28bb-62ef-4517-8182-4d0d66721d06.jpg)

![4](https://user-images.githubusercontent.com/82117170/168422952-81d5ac60-0982-4de6-ac94-9765de890f15.jpg)

![5](https://user-images.githubusercontent.com/82117170/168423056-3c771222-dc6a-4e40-a7e0-53a4269e176d.jpg)

**Comment by mahagr** [comment] 2022-05-14 11:25
This is expected behavior and the same as with layouts in the Joomla itself.

Default star in Joomla doesn't mean that the page is assigned, it just means it's the fallback for menu items that do not have any layout assigned to them. You can still assign default to some pages and if you later change the default, those pages would still keep on using the layout.

**Comment by mahagr** [comment] 2022-05-14 11:25
Well, that said.. We could have some kind of indication if the outline is the default one...

**Comment by kosh2323** [comment] 2022-05-14 11:34
> This is expected behavior and the same as with layouts in the Joomla itself.
> 
> Default star in Joomla doesn't mean that the page is assigned, it just means it's the fallback for menu items that do not have any layout assigned to them. You can still assign default to some pages and if you later change the default, those pages would still keep on using the layout.

Yes, thank you for the answer, of course there is logic in this, if I understood correctly. We forcibly move the switches on the assignment tab if we want to assign the display of these pages with this template. If we don't move it, then by default it will work for all pages (if selected), right?

**Comment by mahagr** [comment] 2022-05-14 11:41
Yes, default means that it is basically used as a fallback for everything which is not assigned. Thus, that's where the name default comes from. Assignments in Joomla are a bit confusing for newcomers, most people assume that it means the home page.

**Comment by kosh2323** [comment] 2022-05-14 11:52
Of course, when faced with the incomprehensible, you start looking for answers. It's good that there is a community and in particular such caring people like you. I sincerely thank you for your help, tips and hints. I'm learning Gantry a little bit, and I would like to write a few wishes to developers from the user's point of view, maybe they will pay attention, and if it is possible, they will someday implement it. But I don't know if such a branch is here? They mostly write about problems here.

**Comment by N8Solutions** [comment] 2022-05-16 13:50
> Of course, when faced with the incomprehensible, you start looking for answers. It's good that there is a community and in particular such caring people like you. I sincerely thank you for your help, tips and hints. I'm learning Gantry a little bit, and I would like to write a few wishes to developers from the user's point of view, maybe they will pay attention, and if it is possible, they will someday implement it. But I don't know if such a branch is here? They mostly write about problems here.

@kosh2323 You should know that Matias (@mahagr) is one of the developers for Gantry.

**Comment by kosh2323** [comment] 2022-05-16 14:02
> > Of course, when faced with the incomprehensible, you start looking for answers. It's good that there is a community and in particular such caring people like you. I sincerely thank you for your help, tips and hints. I'm learning Gantry a little bit, and I would like to write a few wishes to developers from the user's point of view, maybe they will pay attention, and if it is possible, they will someday implement it. But I don't know if such a branch is here? They mostly write about problems here.
> 
> @kosh2323 You should know that Matias (@mahagr) is one of the developers for Gantry.

Yes, I know that, but this thread is dedicated to another and it will most likely be incorrect to write about wishes here. That's why I ask, maybe there is a separate branch where it will be more correct to write about it.

**Comment by N8Solutions** [comment] 2022-05-16 14:06
You can just open a new ticket @kosh2323

**Comment by mahagr** [comment] 2022-05-16 15:48
Thank you. That said, I'm not that happy with myself as I often do not have the time required to support people, at least not fast enough. But thankfully there are others who are willing to help, too.

**Comment by kosh2323** [comment] 2022-05-16 16:00
Would it be right if I open a branch with suggestions for improvement from the point of view of user convenience? Or is it customary to write only about errors here?

**Comment by mahagr** [comment] 2022-05-16 16:28
You are welcome to open an issue. But try to keep the request simple as less work means far better chances to get it implemented.

Suggestions are always welcome, but most of the time I'm going to ignore them and only look into them when we're implementing a new version. Unless there is a really easy fix or the user provides the code to fix it (and we agree on the fix). Many of the feature and improvement requests may also be ignored because the issue isn't in the focus of the release (a smaller amount of changes means far more regular updates).

**Closed** 2022-05-16 16:55 UTC
Labels: enhancement, question, joomla
