### ISSUE TITLE
Custom template layout not saving

### ISSUE THREAD

**Issue by mdanijel** [gantry/gantry5#1464] opened 2016-07-22 10:44 UTC
I'am having trouble with saving custom layout in hydrogen template. All other option can be saved.

When saving, it shows following:

Error 403 index.php?option=com_gantry5&view=configurations/12/layout&theme=g5_hydrogen&e8494833e00e253f144f06c04e3d81f2=1

I'm using Gantry Framework and template (Hydrogen) version 5.3.2, Joomla v3.6, Google Chrome v51, running on php 5.4....

**Comment by mahagr** [comment] 2016-07-22 16:05
403 Forbidden; it could your session have timed out? Try reloading the page.

**Comment by mdanijel** [comment] 2016-07-22 16:48
Session not timed out. I tried to clear cache (from template & page) on my Joomla page. Nothing hapens, still same error.

**Comment by mdanijel** [comment] 2016-07-25 09:27
I installed fresh Joomla 3.6 and Gantry 5.3.2 with Hydrogen template. It also give me same 403 error, when saving custom layout. Saving in other tabs (presets, styles, settings, menu, ...)

At home PC on XAMMP 5.6, Joomla 3.5 and Gantry 5.2.28 works all fine.

**Comment by mahagr** [comment] 2016-08-01 08:36
Sorry for delay; I was on a vacation.

Is the server in public? If so, contact me in gitter chat https://gitter.im/gantry/gantry5 in order to send login details in private chat so I can test this out.

**Comment by mahagr** [comment] 2016-08-02 07:30
I logged into the site and I believe the issue could be caused by mod_security not liking html inside json response. 

https://github.com/gantry/gantry5/issues/1137#issuecomment-201782323

There have been other issues reported on this, too, but I couldn't find them right away.

**Comment by mdanijel** [comment] 2016-08-04 16:16
Could be something wrong in JS code??? See attached picture ...

![image](https://cloud.githubusercontent.com/assets/20595760/17409293/f5d0cc84-5a6e-11e6-8fa0-b7f13d82df62.png)

**Comment by mahagr** [comment] 2016-08-04 16:22
No. As I said, the response coming from server is `403 Forbidden`, which means that the server aborted the request. Usually it happens if there's "a firewall" blocking the request as being detected as an attack. And mod_security rules are known to cause issues with JSON requests having some HTML in it.

**Comment by mdanijel** [comment] 2016-08-05 16:11
In Cpanel I couldn't find any configuration about security, firewall (maybe host provider doesn't provide to me) .... Is possible to code in .htaccess file?

**Comment by mahagr** [comment] 2016-08-05 17:03
mod_security is extension for Apache; might help you to find out what's going on. My next question, though, is whether the error only happens on saving layout or also saving something else like styles or assignments?

**Comment by mdanijel** [comment] 2016-08-05 17:05
error only happens on saving layout

**Comment by mahagr** [comment] 2016-08-05 17:06
Yes, then its likely caused by mod_security.

**Comment by w00fz** [comment] 2016-08-29 23:21
@mdanijel were you able to resolve the issue?

I will be closing this as it seems related to your server setup rather than Gantry. Feel free to reopen if you have anything else to add.

**Closed by w00fz** 2016-08-29 23:21 UTC
Labels: question
