### ISSUE TITLE
Joomla module in menu - infinite spinner

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2384] opened 2018-10-08 14:47 UTC
Gantry 5 menu editor allows the possibility to add modules or particles anywhere in the menu structure.

This does not appear to be functioning though if you try to an a module in the dropdown level1 panel and there are no other pre-existing menu items at that level. As soon as you press "save" you get an infinite spinner on the save button.

Steps to reproduce:

1. Add a menu item to an existing menu of type "Menu Heading" or "Seperator".
2. Go to Gantry 5 menu editor and open that menu item so you can see the child dropdown "well" level 1
3. Drag and drop a "module" onto that "well" (level 1) and then choose any module ID you wish and press "Save".

Result: infinite spinner

If you add another menu item as a child of the first you create then you WILL be able to add the module ok.

**Comment by JoomFX** [comment] 2018-11-05 09:43
I can confirm the issue and it seems to have been introduced in Gantry 5.4.25.
If you downgrade to 5.4.24 the issue is no longer reproducible.

**Comment by mahagr** [comment] 2018-11-05 10:58
I'm assuming this happens in Joomla only?

**Comment by marktaylor46** [comment] 2018-11-05 14:22
Nope - it's broken in Wordpress and GRAV too. Exactly the same breakage - forever spinner.

**Comment by simmonsr** [comment] 2018-11-15 16:35
+1 should really fix this before next release.

**Comment by mahagr** [comment] 2021-05-13 14:18
Should be fixed in Gantry 5.5

**Closed by mahagr** 2021-05-13 14:18 UTC
Labels: bug, important
