### ISSUE TITLE
Ability to set menu dropdown direction by breakpoint required

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#825] opened 2015-09-12 12:50 UTC
In Gantry 4 (most recent) templates we had the ability to set the menu dropdown direction by breakpoint.
![2015-09-12_13-49-08](https://cloud.githubusercontent.com/assets/11683218/9831559/31c79c5c-5955-11e5-8944-f8e3a65bdf98.png)

It would be very helpful it Gantry 5 menu editor had the ability to set dropdown direction too (even if just left/right and not by breakpoint). Why? - because if you have a long menu in LTR language the right most menu items (and sublevels) can end  up going off the page (to the right) on smaller devices such as tablet so you can never get to the menu items to select them.

This has been requested by members in the RT forum.

**Comment by w00fz** [comment] 2015-09-18 22:35
This is duplicate of #417

**Closed** 2015-09-19 07:36 UTC
Labels: duplicate, question

**Comment by w00fz** [comment] 2015-12-14 16:48
This is now implemented with #1058
