### ISSUE TITLE
ampersand in Menu Editor / Particle title

### ISSUE THREAD

**Issue by blizam** [gantry/gantry5#1742] opened 2016-12-13 22:03 UTC
In Joomla...

a Menu Item title such as:

`Hours & Directions` as configured in the Menu Editor (or passed through from Joomla)

renders as:

`Hours &amp; Directions`

on the frontend

I have tried the inverse of actually specifying `&amp;` as well as `&#38;` but those render through as plain text, exactly as entered

**Comment by hacki65** [comment] 2016-12-14 19:26
Can not confirm. Which template & fonts is used?

**Comment by blizam** [comment] 2016-12-14 19:45
Protean... font-family: "Raleway" .... and I should note I only tested it in the OffCanvas position/mobile menu ... this is related to a rockettheme.com forum post

-Matt

**Comment by mahagr** [comment] 2017-01-24 09:45
I am not able to reproduce this either, not in Helium or Protean. It also works in OffCanvas.

**Comment by blizam** [comment] 2017-01-24 15:43
I'll move this to an RT internal ticket for Protean only

**Comment by mahagr** [comment] 2017-01-24 16:21
Are still you able to reproduce this, @blizam, as I could not with the latest version.

**Comment by mahagr** [comment] 2017-01-24 18:36
@blizam sent me a message that he's not able to reproduce this anymore. Closing.

**Closed by mahagr** 2017-01-24 18:36 UTC
Labels: cannot reproduce, joomla

**Comment by blizam** [comment] 2017-01-24 18:48
I am no longer able to reproduce this
