### ISSUE TITLE
Responsive support classes broken.

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1705] opened 2016-11-28 15:08 UTC
Further to #1487 that was fixed in G5.3.9 it would appear that the responsive support classes have been broken further.

Example: 
"hidden-desktop" should only hide content in desktop and large display viewports but in fact the content never shows with this responsive support class as it is always set to display: none !important.

The problem seems to eminate though the bootstrap responsive-utilities.less which is setting display : none !important and then the Gantry responsive utility code in /media/gantry5/engines/nucleus/scss/nucleus/theme/breakpoints/_utilities.scss never contradicts this or sets the correct value according to the breakpoints. 

Also note that the bootstrap CSS is using all the wrong breakpoints (hardcoded viewport sizes) which is not compatible with Gantry 5 (which can have variable viewport sizes).

I think all of the responsive support classes should be retested to ensure that they match what they are supposed to be.

**Comment by hexplor** [comment] 2016-11-28 18:06
Well i found this code in nucleus.css:

```
.visible-phone {
  display: none !important;
}

.visible-tablet {
  display: none !important;
}

.hidden-desktop {
  display: none !important;
}

.visible-desktop {
  display: inherit !important;
}
```

It completely makes no sense. It's not assigned into any breakpoints...

**Comment by hexplor** [comment] 2016-11-28 18:13
Ok. I think I nailed it down. Removed conflicting classes from nucleus and polished utilities. Please check now @marktaylor46

**Comment by marktaylor46** [comment] 2016-11-29 10:11
@hexplor - I don't think this is right. I think we need to fix _utilities,scss. I think each media query should specifically set the classes directly associated with it explicitly and no more, no less. There's are still loads of display: inherit !important in there which leads to unpredicatable results.

So taking "large display" as the example I think the code should be:

@include breakpoint(large-desktop-range) {
    .visible-large {
        display: block !important;
    }
    .g-block.visible-large {
        display: block !important;
    }
    .hidden-large {
        display: none !important;
    }
    .visible-desktop {
        display: block !important;
    }
    .g-block.visible-desktop {
        display: block !important;
    }
    .hidden-desktop {
        display: none !important;
    }
}

If you look at what's there now it's a mess, Why on earth it should be doing anything with "visible-phone" in the "large display" media query is a mystery to me?

Because of the code in Bootstrap we have to be explicit in everything otherwise you just get unpredictable results. The bootstrap code is using incompatible media queries and with us using "inherit" it's just really weird results that you get.

**Comment by hacki65** [comment] 2016-12-01 11:40
In my eyes ALL possible responsive classes must be include in each breakpoints. If not this can get unexpected results.

But another point for this issue is: why is it necessary to configure the breakpoints itself. I really more need another setting:
**The with of the sections FOR each breakpoint**. At large desktops i would set the with e.g. at 80rem, but for tablets or phones i need a with at 95%. This setting is not possible at the moment.

**Comment by marktaylor46** [comment] 2016-12-01 11:47
I disagree if the media query is for example "mobile" then the only thing that should be set  is "hidden-phone" and "visible-phone" but these should be set explcitly to display: none and display: block respectively (not inherit). They should touch any of the other responsive support classes at all since they are only settting these values for the specific viewport that they apply in.

Obviously the whole set of viewports must be covered. though for this to work.

You can set the breakpoint size in Gantry 5 on the "styles" tab of the base outline - you can change each breakpoint to whatever size you need (but I wouldn't deviate from the standard ones the your users will expect if I were you).

**Comment by hacki65** [comment] 2016-12-03 00:35
> You can set the breakpoint size in Gantry 5 on the "styles" tab of the base outline - you can change each breakpoint to whatever size you need (but I wouldn't deviate from the standard ones the your users will expect if I were you).

This is not correct, sorry. If i change the breakpoints this changed the media query itself to this size and the classes, e.g. "visible-phone", react completly wrong. But what i mean with the sections is that with the breakpoints i can not really change the witdh of a section.

**Comment by marktaylor46** [comment] 2016-12-03 09:13
What I said is correct. The breakpoints change the point at which the width of the template steps down to the next width. The breakpoint DO set the actual width of the template (assuming blocked layout). You can also tell the section to be "fullwidth (boxed)" or "fullwidth (flushed)" the former constraining the template width to the breakpoint size, the later not constraining the section at all. 

Within that you can also set spacer particle in the section, and also padding and margins.

All that said this has nothing to do with the original purpose of my ticket which is that the breakpoints were broken in G5.3.9 with the fix applied for #1487 and this needs to be corrected. This ticket is not about changing any behaviour from what was intended - it's about correcting the existing broken behaviour.

**Comment by adi8i** [comment] 2016-12-04 09:44
`!important` also breaks the layout if you use this classes togheter with `equal-height`, that's another story.

**Comment by hacki65** [comment] 2016-12-05 08:05
Sorry for my reply. I agree that this issue must be fixed. I make a feature request for a separat setting of the width for each breakpoints (because in my eyes it makes sense to differ with breakpoints itself and gives possibility to set this value in percent).

**Comment by marktaylor46** [comment] 2016-12-05 09:20
adi8i - !important has to be used because Twitter's Bootstrap CSS already uses it. So to override a !important you unfortunately again have to use !important. I dislike it too and would always avoid using !important but given that Twitter have already done this we have no choice. As for "equal height", yes that's another story and should be another ticket - it's not directly related to this issue.

**Comment by marktaylor46** [comment] 2016-12-05 09:26
hacki65 - I still don't see the need for your suggestion at all since you can use spacer and/or custom CSS with/without media queries to do everything that you need. But yes, by all means raise your own ticket.

**Comment by hacki65** [comment] 2016-12-05 09:46
I have checked the bs media-queries and made a possible cleanup _utilities.scss.
BS makes a clean way to use the media classes. It sets all classes at first at "display: none". Than for each class in the right media brealpoint the class will set to "display: block". I think this gives the right behaviour.
@marktaylor46 can you check it?

`// Visibility

.visible-large,
.visible-desktop,
.visible-tablet,
.visible-phone,
.g-block.visible-large,
.g-block.visible-desktop,
.g-block.visible-tablet,
.g-block.visible-phone {
  display: none !important;
}

@include breakpoint(large-desktop-range) {
	.visible-large {
		display: block !important;
	}
    .g-block.visible-large {
        display: block !important;
    }
	.hidden-large {
		display: none !important;
	}
}

@include breakpoint(desktop-range) {
	.visible-desktop {
		display: block !important;
	}
    .g-block.visible-desktop {
        display: block !important;
    }
	.hidden-desktop {
		display: none !important;
	}
}

@include breakpoint(tablet-range) {
	.visible-tablet {
		display: block !important;
	}
    .g-block.visible-tablet {
        display: block !important;
    }
	.hidden-tablet {
		display: none !important;
	}
}

@include breakpoint(mobile-only) {
	.visible-phone {
		display: block !important;
	}
    .g-block.visible-phone {
        display: block !important;
    }
	.hidden-phone {
		display: none !important;
	}
}

// Alignment
@include breakpoint(mobile-only) {
	.align-right {
		text-align: inherit !important;
	}
	.align-left {
		text-align: inherit !important;
	}
}
`

**Comment by marktaylor46** [comment] 2016-12-05 09:54
@hacki65  - No, that's not correct because you have to also take into account that "visible-desktop" also means the item it to be visible in "visible-large" too. check the matrix here http://docs.gantry.org/gantry5/tutorials/utility-classes.

Also you have to consider the order in which you wriote those statements to have a logical outcome when people add strange combinations of those classes on onw item(e.g. hidden-desktop with visible-large) as an example (but there are others too).

Not sure what those alignment ones are doing there either? but again I don't like using "inherit" because you can't predict what you are inheriting?

**Comment by mahagr** [comment] 2016-12-05 10:44
I think the best way to deal with this is to convert bootstrap file into scss and load it through the compiler with our breakpoints set with it...?

**Comment by marktaylor46** [comment] 2016-12-05 10:51
Good idea @mahagr  but that leaves us in the position of having to maintain our bootstrap.scss with whatever happens to bootstrap.css - probably  not a problem as it's ancient now anyway... but just pointing that out. That bootstrap.css contains some horrible stuff in this regard anyway that could be made much better removing the !important and the wholesale setting of things to display none when it shouldn't be too.

**Comment by mahagr** [comment] 2016-12-05 12:20
We are already maintaining our own version of it.

**Comment by marktaylor46** [comment] 2016-12-05 13:23
Ok in that case - great - let's fix the thing at the root cause - lovely :)

**Comment by hacki65** [comment] 2016-12-05 18:08
I think that the bootstrap logic is clear. .hidden-large mean hide on Large Desktop (and not Desktop). If i want to hide on large-desktop AND desktop i expect to use both classes (.hidden-large and .hidden-desktop). But now if i use .hdden-destop the element is hidden on large too. BS makes this part clearly.

**Comment by hacki65** [comment] 2016-12-05 18:10
I have make another change (the order reflect the order of BS 3.3.7):

`
// Visibility

.visible-large,
.visible-desktop,
.visible-tablet,
.visible-phone,
.g-block.visible-large,
.g-block.visible-desktop,
.g-block.visible-tablet,
.g-block.visible-phone {
  display: none !important;
}

@include breakpoint(mobile-only) {
	.visible-phone {
		display: block !important;
	}
  .g-block.visible-phone {
    display: block !important;
  }
}

@include breakpoint(tablet-range) {
	.visible-tablet {
		display: block !important;
	}
  .g-block.visible-tablet {
    display: block !important;
  }
}

@include breakpoint(desktop-range) {
	.visible-desktop {
		display: block !important;
	}
  .g-block.visible-desktop {
    display: block !important;
  }
}

@include breakpoint(large-desktop-range) {
	.visible-large {
		display: block !important;
	}
  .g-block.visible-large {
    display: block !important;
  }
}

// Invisibility

@include breakpoint(mobile-only) {
	.hidden-phone {
		display: none !important;
	}
}

@include breakpoint(tablet-range) {
	.hidden-tablet {
		display: none !important;
	}
}

@include breakpoint(desktop-range) {
	.hidden-desktop {
		display: none !important;
	}
}

@include breakpoint(large-desktop-range) {
	.hidden-large {
		display: none !important;
	}
}

// Alignment
@include breakpoint(mobile-only) {
	.align-right {
		text-align: inherit !important;
	}
	.align-left {
		text-align: inherit !important;
	}
}
`

**Comment by mahagr** [comment] 2016-12-05 18:24
Joomla is using Bootstrap 2.3, not 3.3

**Comment by hacki65** [comment] 2016-12-05 18:26
I know this but what is the problem?

**Comment by hacki65** [comment] 2016-12-05 18:52
The only thing i don't know is if the classes ".visible-*" must be "display: inherit" and only the ".block.visible-*" classes become "display: block" ? If all visibility classes becaome "block" this can cause unexpected behaviours because of the "!important" state.

**Comment by hacki65** [comment] 2016-12-05 19:17
And one another idea is no more display: block or inherit (except .block.* classes):

`
// Invisibility

@include breakpoint(mobile-only) {
  .visible-tablet, .visible-desktop, .visible-large {
    display: none !important;
  }
  .g-block.visible-phone {
    display: block !important;
  }
  .hidden-phone {
    display: hidden !important;
  }
}

@include breakpoint(tablet-range) {
  .visible-phone, .visible-desktop, .visible-large {
    display: none !important;
  }
  .g-block.visible-tablet {
    display: block !important;
  }
  .hidden-tablet {
    display: hidden !important;
  }
}

@include breakpoint(desktop-range) {
  .visible-phone, .visible-tablet, .visible-large {
    display: none !important;
  }
  .g-block.visible-desktop {
    display: block !important;
  }
  .hidden-desktop {
    display: hidden !important;
  }
}

@include breakpoint(large-desktop-range) {
  .visible-phone, .visible-tablet, .visible-desktop {
    display: none !important;
  }
  .g-block.visible-large {
    display: block !important;
  }
  .hidden-large {
    display: hidden !important;
  }
}

// Alignment
@include breakpoint(mobile-only) {
  .align-right {
    text-align: inherit !important;
  }
  .align-left {
    text-align: inherit !important;
  }
}
`
It's a quick shot. Can this be possible to give a correct behavoiur?

**Comment by marktaylor46** [comment] 2016-12-06 08:41
I don't see the need to do anything with responsive support classes that are not related to the media query at all. So in the "desktop-range" media query setting anything for "visible-phone", "visible-tablet" is not correct in my opinion. If the screen is sized at desktop, then the visible-phone setting is irrelevant as it is not applicable at that screensize.

Also setting "visible-large" to "none" in the "desktop-range" media query is incorrect since the viewport size is a desktop then again "visible-large" is not applicable at that viewport size at all.

So, the premise of the media query usage should be that the responsive support classes should only be explicitly set for the media query that they directly pertain to. i.e. mobile in mobile, tablet in tablet, etc, etc. The only remaining complication is that "visible-desktop" applies to both "desktop-range" and "large-display" range (as defined by Twitter for Bootstrap - and we need to be consistent with that).

To answer you earlier question, what's wrong with the bootstrap.css is that it is using "inherit" and explicitly setting value outside of media queries altogether and also the media queries that it is using are not compatible with Gantry 5 (they are hardcoded values as opposed to Gantry 5's ability to define the breakpoint range).

I hope that helps.

**Comment by hacki65** [comment] 2016-12-06 12:20
.visible-desktop  = on desktop: **visible** | on all other device-screens: **hidden**
.hidden-desktop = on desktop: **hidden** | on all other device-screens: **visible**

This is a mirror effect... and in this case i must set the hidden state on .visible-destop for the other device-screens too.

**Comment by marktaylor46** [comment] 2016-12-06 14:38
Well I disagree, but let's leave it for the DEVS to decide. I can only see the need to specifically set the class that applies to that specific viewport (but also there is the complication of "visible-desktop" also implying "visible-large" too.

**Comment by hacki65** [comment] 2016-12-06 15:21
Here is the explanation table from BS 2,3,2 (Responsive utility classes). All blue underlined cases must be set explicit to "display: none" for the related media-query to give the expected behaviour. That's my opinion.

![classes-visible](https://cloud.githubusercontent.com/assets/20481746/20930928/973f095c-bbcf-11e6-9829-ccd1b567c115.jpg)

![classes-hidden](https://cloud.githubusercontent.com/assets/20481746/20930932/9d44613a-bbcf-11e6-902f-9a2473937f81.jpg)

**Comment by marktaylor46** [comment] 2016-12-06 15:27
We're not going to agree.. I leave it to the DEVS...

Just remember that the reason I raised this ticket is the it's currently broken and needs fixing... I don't care what the solution is... I just want to see it fixed.

**Comment by mahagr** [comment] 2016-12-12 10:17
I made a test case from bootstrap 2.3 docs:

```html
          <h3>Responsive utilities test case</h3>
          <p>Resize your browser or load on different devices to test the above classes.</p>
          <h4>Visible on...</h4>
          <p>Green checkmarks indicate that class is visible in your current viewport.</p>
          <ul class="responsive-utilities-test">
            <li>Phone <span class="visible-phone">&#10004;</span></li>
            <li>Tablet <span class="visible-tablet">&#10004;</span></li>
            <li>Desktop <span class="visible-desktop">&#10004;</span></li>
            <li>Phone Tablet <span class="visible-phone visible-tablet">&#10004;</span></li>
            <li>Phone Desktop <span class="visible-phone visible-desktop">&#10004;</span></li>
            <li>Tablet Desktop <span class="visible-tablet visible-desktop">&#10004;</span></li>
            <li>Phone Tablet Desktop <span class="visible-phone visible-tablet visible-desktop">&#10004;</span></li>
			<li>...</li>
            <li>Large <span class="visible-large">&#10004;</span></li>            
            <li>Phone Large <span class="visible-phone visible-large">&#10004;</span></li>
            <li>Tablet Large <span class="visible-tablet visible-large">&#10004;</span></li>
            <li>Desktop Large <span class="visible-desktop visible-large">&#10004;</span></li>
            <li>Phone Desktop Large <span class="visible-phone visible-desktop visible-large">&#10004;</span></li>
            <li>Tablet Desktop Large <span class="visible-tablet visible-desktop visible-large">&#10004;</span></li>
            <li>Phone Tablet Desktop Large <span class="visible-phone visible-tablet visible-desktop visible-large">&#10004;</span></li>
          </ul>
          <h4>Hidden on...</h4>
          <p>Here, green checkmarks indicate that class is hidden in your current viewport.</p>
          <ul class="responsive-utilities-test hidden-on">
            <li>Phone <span class="hidden-phone">&#10004;</span></li>
            <li>Tablet <span class="hidden-tablet">&#10004;</span></li>
            <li>Desktop <span class="hidden-desktop">&#10004;</span></li>

            <li>Phone Tablet <span class="hidden-phone hidden-tablet">&#10004;</span></li>
            <li>Phone Desktop <span class="hidden-phone hidden-desktop">&#10004;</span></li>
            <li>Tablet Desktop <span class="hidden-tablet hidden-desktop">&#10004;</span></li>
            <li>Phone Tablet Desktop <span class="hidden-phone hidden-tablet hidden-desktop">&#10004;</span></li>
			<li>...</li>
            <li>Large <span class="hidden-large">&#10004;</span></li>
            <li>Phone Large <span class="hidden-phone hidden-large">&#10004;</span></li>
            <li>Tablet Large <span class="hidden-tablet hidden-large">&#10004;</span></li>
            <li>Desktop Large <span class="hidden-desktop hidden-large">&#10004;</span></li>
            <li>Phone Desktop Large <span class="hidden-phone hidden-desktop hidden-large">&#10004;</span></li>
            <li>Tablet Desktop Large <span class="hidden-tablet hidden-desktop hidden-large">&#10004;</span></li>
            <li>Phone Tablet Desktop Large <span class="hidden-phone hidden-tablet hidden-desktop hidden-large">&#10004;</span></li>
</ul>
```

If you copy this to an article and create 2 menu items from it (one for Gantry theme, another for Protostar), you should see both the current and wanted behaviour.

**NOTE**: Joomla doesn't support `visible-large` and `hidden-large` classes, so they should behave like they are right now in order not to break Joomla behaviour.

Also as you can see from the example, you should be able to combine multiple classes to hide/show content in all listed responsive sizes.

**Comment by hexplor** [comment] 2016-12-12 12:52
Good job @hacki65 
So If i take that visible-desktop also should be visible in large-desktop (visible desktop is like min width), then modified code should be like that:
```css
// Visibility
.visible-large,
.visible-desktop,
.visible-tablet,
.visible-phone,
.g-block.visible-large,
.g-block.visible-desktop,
.g-block.visible-tablet,
.g-block.visible-phone {
  display: none !important;
}

@include breakpoint(mobile-only) {
  .visible-phone {
    display: block !important;
  }
  .g-block.visible-phone {
    display: block !important;
  }
}

@include breakpoint(tablet-range) {
  .visible-tablet {
    display: block !important;
  }
  .g-block.visible-tablet {
    display: block !important;
  }
}

@include breakpoint(desktop-range) {
  .visible-desktop {
    display: block !important;
  }
  .g-block.visible-desktop {
    display: block !important;
  }
}

@include breakpoint(large-desktop-range) {
  .visible-large {
    display: block !important;
  }
  .g-block.visible-large {
    display: block !important;
  }
  .visible-desktop {
    display: block !important;
  }
  .g-block.visible-desktop {
    display: block !important;
  }
}

// Invisibility
@include breakpoint(mobile-only) {
  .hidden-phone {
    display: none !important;
  }
}

@include breakpoint(tablet-range) {
  .hidden-tablet {
    display: none !important;
  }
}

@include breakpoint(desktop-range) {
  .hidden-desktop {
    display: none !important;
  }
}

@include breakpoint(large-desktop-range) {
  .hidden-large {
    display: none !important;
  }
  .hidden-desktop {
    display: none !important;
  }
}

// Alignment
@include breakpoint(mobile-only) {
  .align-right {
    text-align: inherit !important;
  }
  .align-left {
    text-align: inherit !important;
  }
}
```

**Comment by marktaylor46** [comment] 2016-12-12 13:34
@hexplor That makes much more sense to me... I will test it for you and let you know :)

**Comment by hacki65** [comment] 2016-12-13 11:38
@hexplor thanks, but i think my solution is not the best. It's a clear solution, but i'm afraid that this can cause unexpected results.

For the classes .visible-* as example: what happens if i use .visible-desktop at a table element? Because of display: block !important this can destroy the table. Or not?

**Comment by mahagr** [comment] 2016-12-13 11:45
There's really no way to make it to work. For example `display: inherit` doesn't work either as it takes the property from the parent node, which in case of table is always wrong. Neither does work `display: initial` as it may have changed for example when using flex.

**Comment by marktaylor46** [comment] 2016-12-13 11:51
Don't use it on a table element - wrap your table in a DIV and put the class on that instead.

**Comment by hacki65** [comment] 2016-12-13 18:03
Agree with that. But the user must this keep in mind :)

**Comment by mahagr** [comment] 2016-12-13 21:03
Closing.. Open a new one if there are still issues.

**Closed by mahagr** 2016-12-13 21:03 UTC
Labels: bug, joomla
