### ISSUE TITLE
Can't delete outline from outlines screen

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#254] opened 2015-05-14 18:27 UTC
in the 'configurations' screen, hitting the 'delete' icon for any configuration will open the smart messages. if you then select 'save before leaving', nothing seems to happen. it appears that configurations can't be deleted from there at this point.

![g5_config_savebeforeleaving](https://cloud.githubusercontent.com/assets/5719486/7638793/e0f215e0-fa3c-11e4-9b2a-911b17c3b6dd.jpg)

**Comment by mahagr** [comment] 2015-05-14 18:49
@w00fz Same issue as I've run into.

**Comment by w00fz** [comment] 2015-05-16 00:44
hey @kat05 now that RC2 is out let me know if you can still reproduce this one, I was never able to.

**Comment by w00fz** [comment] 2015-05-16 01:04
Looks like @WebTread was able to reproduce this still in RC2. How come I cannot!

**Comment by w00fz** [comment] 2015-05-19 20:18
Any idea guys on how i can reproduce this one? As of today I still haven't managed to get the issue happening for me. 
If I can't reproduce, I can't fix. :)

**Comment by adi8i** [comment] 2015-05-19 20:28
First off all there is not `save before leaving ` button in rc 2

**Comment by JoomFX** [comment] 2015-05-19 20:29
@w00fz I'm not sure how to try to reproduce this. I mean, I do not get this popup when I click on the "Delete" button. I get:

"Are you sure you want to delete this Outline?"

And the buttons are "Confirm" and "Cancel".
If I confirm, the Outline is delete successfully.

**Comment by adi8i** [comment] 2015-05-19 20:31
But i have other thing for you @w00fz  :) . 

First, you need to have 2 themes installed. Then go to `Outlines`, hit `delete`, `confirm` then all the outlines will show. If you are in Hydrogen template you should see only hydrogen outlines.

**Comment by w00fz** [comment] 2015-05-19 20:31
Yah that's the proper behavior, I cannot get it to show the other pop-up at all. Either this is fixed already or I don't know :)

// Djamil Legato // From iPhone //

**Comment by adi8i** [comment] 2015-05-19 20:37
How to make a pie, in 3 steps: 
![1](https://cloud.githubusercontent.com/assets/9744973/7713380/0857a2de-fe80-11e4-8e88-57c08bb44ecc.png)
![2](https://cloud.githubusercontent.com/assets/9744973/7713382/0995225c-fe80-11e4-8f37-c92532a2e82f.png)
![3](https://cloud.githubusercontent.com/assets/9744973/7713384/0a966580-fe80-11e4-97ba-4353a2d64a15.png)

**Comment by w00fz** [comment] 2015-05-19 22:11
That's a nasty bug @adi8i, not related to this one though. Mind opening it in a new issue?

**Comment by w00fz** [comment] 2015-05-20 00:16
I'm going to close this as I am not able to reproduce, I think it was fixed already during the releases.
The other issue reported last and ticketed separately in #324 also has been fixed.

**Comment by kat05** [comment] 2015-06-08 22:24
like mentioned on hipchat, i ran into this one again today, it's very rare and random and i have no solid way to replicate it yet. i will keep trying though.

**Closed** 2015-06-08 22:26 UTC
Labels: question

**Comment by w00fz** [comment] 2015-06-18 23:02
FYI, I was FINALLY able to reproduce this, it happened randomly but I could consistently get it to appear. It should be now fixed once and for all.

**Comment by kat05** [comment] 2015-06-18 23:19
awesome! :)

**Comment by WebTread** [comment] 2015-06-19 03:30
Awesome
