### ISSUE TITLE
G-main's g-blocks spreading over anything to the right (Aside, Sidebar)

### ISSUE THREAD

**Issue by Crolug** [gantry/gantry5#404] opened 2015-06-02 11:58 UTC
How I got it:
1. Installed latest, clean Joomla
2. Installed G5rc2
3. Installed Hydrogen rc2
4. Deleted Home outline
5. Loaded to Default Outline "3 Columns" preset

Result:
G-blocks of g-main get size-100 class and they're spreading over (technically, under, z-index is lower I guess) Aside, up to 1200px wide. It works with "2 Columns - Right" as well.

**Comment by JoomFX** [comment] 2015-06-02 12:00
It seems to be the same as https://github.com/gantry/gantry5/issues/354

**Comment by Crolug** [comment] 2015-06-02 12:05
Indeed. Giving to blocks Main's current size class somewhat does the trick but it sticks with them, so kind of breaks RWD in the process.

**Comment by w00fz** [comment] 2015-06-02 20:27
Yes this is a duplicate of #354, we are looking into it. Looks to be related to Loading a preset while preserving the particles.
Sorry about that.

**Closed by w00fz** 2015-06-02 20:27 UTC
Labels: duplicate
