### ISSUE TITLE
Gantry's Relationship with YAML is leading to unpredictable results (Hydrogen)

### ISSUE THREAD

**Issue by greenlanegreb** [gantry/gantry5#2685] opened 2020-08-09 13:14 UTC
Hello, 

I have an issue whereby, if I load the same YAML file, I end up with different sections nested inside each other without any other changes - these change each time I reload. I am calling this unpredictable results. 

Whilst there could easily be something slightly off with my YAML, Gantry's error handling is nowhere near strict enough to point to a line of code it is not happy with. 

I have checked, and checked again the sections that are affected and compared them to working YAML templates and, for love nor money, I cannot see any issues with spacing or syntax. 

The YAML file itself is here - [https://pastebin.com/FMnMr8ay](url)

A screenshot of the latest weird nesting is here: [https://snipboard.io/zBjin2.jpg](url)

As you can see, it's still seeing container sections as numbers rather than letters. 

Many thanks.

**Comment by greenlanegreb** [comment] 2020-08-09 13:18
Update: I've just pulled it through again and unticked keep particles and it seems to have stopped the nesting this time but each main section is appearing as a number (for example main1, main2 etc) despite them being a, b, c per my YAML code above.

**Comment by thexmanxyz** [comment] 2020-08-09 15:09
Your file is incorrect, why including `system-messages` one trillion times in your file? Can you explain the purpose. This is what I found in 3 seconds investigating your file.

**Comment by greenlanegreb** [comment] 2020-08-09 15:44
themanxyz - that's just trolling and I refuse to get into a debate about it. There's clearly a bug, per my explanation above and, regardless of the system messages position being restated, this is no reason for the above issues. I would ask that you please do not comment rather than trolling - it doesn't do anything for you when other people read it, not to mention breaking Github rules. Many thanks.

**Comment by thexmanxyz** [comment] 2020-08-09 16:27
I'm pretty sure my comment is not against any code of conduct. But feel free to report it 🙂 I'm exited to see what happens. You did not waste one word on an obvious issue in your file which I outlined in my post. Instead of trying what I suggest and fix it, instead you are calling me troll. Well played.

But let me tell you one thing. If you are Joomla Guy for 16 years you should really know that positions are unique...

**Comment by greenlanegreb** [comment] 2020-08-09 16:46
Thanks for entering into some constructive dialogue. Perhaps we could forget about the points scoring now please? 

OK, so if you were testing some code, and you wanted to be able to see the error at that position, surely it would actually be useful to have repeated system error messages, nearest to where you were working for debugging purposes? 

YAML editors return that the YAML does not contain syntax errors. Each container has a different number on the end of the position for example (and uniqueness highlighted): 

/container-**k**/:
    -
      - sidebar**11** 5:
        - position-sidebar
      - main**11** 80:
        - position-breadcrumbs
        - system-messages
        - system-content
      - aside**11** 14:
        - position-aside

  /container-l/:
    -
      - main**12** 100:
        - position-breadcrumbs
        - system-messages
        - system-content

As I am sure you are aware, the position names can be changed once YAML is ported in and are arbitrary at the point of loading the YAML file but may result in unintended results when the Joomla enquiry (web view) is obtained. Of course, I do change the position names (per my snag.gy screenshot above). 

Why would having a repeated system error section, within a uniquely identified container, cause the issues i've reported please? 

Many thanks.

**Comment by thexmanxyz** [comment] 2020-08-09 16:53
Well I'm saying it one last time. Positions are unique and you have tons of duplicates in your file. A valid YAML file does not mean anything. Start fixing your file before debating about this and that. You're they only one acting childish and uncooperative. So fix your file first and then we can discuss about issues in the loading routine.

**Comment by greenlanegreb** [comment] 2020-08-09 17:00
I'm sorry you feel that way, I'm really trying to understand the issue to rule it out from being a bug which i'm convinced it is. I've attempted to be constructive here and i've even highlighted to try and emphasise where I am coming from, that I am making each container unique. There was a point when I added a unique identifier to every single system message to but I was told not to do that previously!  Are you saying precisely the opposite please? Please understand, that when you get mixed advice, how the goodness can you learn? 

There's absolutely no harm in giving what you are saying a crack - sure - and I will. Can I please first confirm that what you are saying is as follows: 

**Instead of** 

  /container-k/:
    -
      - sidebar11 5:
        - position-sidebar
      - main11 80:
        - position-breadcrumbs
        - system-messages
        - system-content
      - aside11 14:
        - position-aside

**You are saying**

  /container-k/:
    -
      - sidebar11 5:
        - position-sidebar -> I guess I can't have this more than once either. 
      - main11 80:
        - position-cheese
        - position tomatoes
      - aside11 14:
        - position-aside -> I guess I can't have this more than once either???

**Comment by thexmanxyz** [comment] 2020-08-09 17:08
Well you were already convinced in things in our 100s of messages on gitter and you were proven wrong every time. That I'm even pointing on the obvious things is ridiculous to me because I swore myself to never ever get in any discussion with you anymore. I'm at least saying that positions are unique. What positions in Gantry and Joomla are can be foundin many many sources. Start there and then if your file is fixed and you're still convinced in a bug feel free to adapt the issue. Without a valid file any further discussion is a waste of time. Sorry

**Comment by greenlanegreb** [comment] 2020-08-09 17:16
Firstly, the YAML file is within the pastebin link above. Secondly, the interpretation of it, by the layout manager is contained within the snag.gy link. 

I have effectively asked you, please, to explain the differences between aside and sidebar being reused (these are not unique) and system messages, for example, from what you say, having to be unique. If Gantry's own manual does not explain this in the YAML section, then how are people to know? I'm entirely confused. I've tried to give you an example above and i'd be grateful if you would explain why this is not explained in the official documentation? Why would one rely on secondary sources that could easily be an inaccurate interpretation of what is supposed to happen? Where I am now is as the result of what i've learnt in the chat channel over the years. Let's not forget, that this issue is sporadic. The fact that the interpretation changes ever time I reload the same YAML file points to a bug rather than an unintended consequence borne of error in any event. 

You've avoided confirming my interpretation example above?

**Comment by thexmanxyz** [comment] 2020-08-09 17:25
You refuse to fix your file so any discussion is useless. The pastebin link never changed it is still the same wrong file. `system-messages` is a Joomla element my dear friend and has per se nothing to do with Gantry. Gantry just wraps it in a particle. But it has to be unique per definition. That's how things work. Fix your duplicate positions e.g. `position-breadcrumbs` but there are dozens in your file. I won't fix your file this is your job if you want to prove "your" bug.

**Comment by greenlanegreb** [comment] 2020-08-09 17:30
Yeah, sure absolutely - I would never expect you to sit there and fix anything for me. I'm just trying to understand, before I start, what I can and can't do. One thing i'm quietly worried about is, does there not need to be some positions specified in order to add modules later? All as I look to do is to be able to fully control each section with SCSS - to do that, certainly in every single use case I have, i've needed multiple sections. I do appreciate your explanations, I am simply confused about how to properly interpret them. We've got this far, surely it would be good to just iron this out. 

What can be reused?
What can't be? 

I think that's the clearest way of putting it. 

From there - please could the parser be updated to be more verbose about this?
Please could the manual be updated to include a few more sections in the code example and go into what always has to be unique and what shouldn't. This would make a lot of sense, avoid confusion, repeat bug reports and answer what I am sure will be a repeating question on the chat room. 

Thanks.

**Comment by thexmanxyz** [comment] 2020-08-09 17:36
I'm not answering that many questions sorry. Use Google to find answers for your questions. Many can be answered by reading the documentation. Please create simple files to understand the concepts. You already got useful hints from me on how to fix issues with your file. Take them and start over. Verify carefully and then come back to outline the bug or create a feature request.

**Comment by greenlanegreb** [comment] 2020-08-09 17:43
> I'm not answering that many questions sorry

 -> You haven't answered any in a way that I can understand and you haven't successfully established that this is not a bug. Being evasive instead of explaining in a way that somebody can interpret suggests that you are not convinced in the purported knowledge that you are sharing. It makes no sense, particularly since it is not backed up in the manual. 

> Go on Google

Surely the developers would prefer one to rely on their manual than on a search engine. This also makes the presumption that Gantry would never have issues of its own. The proper arena for Gantry issues is in a Gantry forum i.e. here. 

> Outline a bug

I already have. You have been defensive of Gantry as opposed to disproving a bug, seemingly based on that rather large chip on your shoulder.

**Comment by thexmanxyz** [comment] 2020-08-09 17:51
No there is no bug when the input is garbage and you won't try to prove it with a correct file.

Start simple and then go complex. That's all I can provide at this point. As I am seeing you don't understand the concepts fully you should try to do that now.

Everything what you need can be googled in seconds. If I throw a car of a bridge and I'm surprised why it sinks down to the ground of the river might be good analogy. It is not a bug of the car but rather the usage and what you expect.

I know tag @mahagr and @newkind for close as I am seeing the same stubborn behavior I love you for.

Everything to help you was said.

**Comment by greenlanegreb** [comment] 2020-08-09 17:54
Except for what should and shouldn't be unique and why Gantry is interpreting the same YAML code in different ways every time I press the reload button???

**Comment by greenlanegreb** [comment] 2020-08-09 18:32
Although I was cynical for all of the reasons above, I followed the advice and **it didn't work**. 

Here is Main 11 randomly appearing in the header [https://snipboard.io/v5PYuO.jpg](url)

Here is my unique YAML (compliant with the vague advice above): [https://pastebin.com/eA1RshuF]

Now it will be:

a) "Oh your Joomla install is messed up"

b) "Oh your Gantry install is messed up" 

c) "Oh your hosting is messed up"

d) "Oh you have a conflicting module"

(I think i've covered every reason why it _couldn't possibly_ be a Gantry bug now.)

In the case of (a) and (b) - I have had this issue before and I have reinstalled - it didn't make any difference. In the case of (c), i've moved web host since the last time. In the case of (d) I've got the same issue on a clean install with no additional modules activated.  

Sighs.

**Comment by thexmanxyz** [comment] 2020-08-10 04:44
Thanks for correcting the file. As I don't see any issue with the file anymore we now have something valid to discuss about / test against. But I believe there is still some issue with the file but I might be wrong. That is all I asked for, to correct the obvious things and start over.

**Comment by thexmanxyz** [comment] 2020-08-10 05:50
One last thing that is 100% OT now and my last answer on this issue.

You are a toxic person who wants to start endless discussions every time you appear. You are not interested in solutions someone proposes if they don't fit your perspective. I saw that quite often and that was also the reason you got kicked out of the Gitter chat. I remember that. You think you are a super pro in CMS and frontend development but you are NOT.

Sorry @mahagr that I have to say that now but I'm really pissed of this stubborn toxic behavior. We see the same thing in other issues he opened on GitHub and what he wrote on Gitter in the past. I might be self-conscious but it the same stuff every time...

**Comment by mahagr** [comment] 2020-08-10 06:13
@greenlanegreb I am not able to see the YAML file, but the section and position names need to be unique (or if a general name is used, there should be only a single instance of it). This is because of Gantry uses those names as IDs and inserts the contents based on the ID. Having conflicting names will cause undefined behaviour, which may alter based on caching state and other random events.

The reason why there's no detection for this is mostly twofold: it makes the code slow and there are no checks on saving either because of historical reasons, mostly to keep backwards compatibility to the older themes. Also, these files are not meant to be changed without deeper knowledge of the internal workings -- yes, there is room for an improvement in the documentation on this part.

@thexmanxyz In public non-moderated discussions, there will always be flame wars and toxic behaviour. The best thing anyone can do is not to get stuck into those conversations which tend to trigger you. I generally just ignore people who are not polite to me as I don't have the time nor interest in arguing with people unless it is productive to do so.

**Comment by greenlanegreb** [comment] 2020-08-10 07:27
@mahagr Thanks for this. Each container and item within it is unique. One thing, upon reflection I have not done, is to clear the Gantry Cache - it is however in development mode and I was once told (not sure if this is right) that the development mode is largely to overcome caching issues. 

I would have thought that the layout manager, upon using the load functionality, should always return the same result, regardless of whether the YAML is correct or not. 

Many thanks.

**Comment by thexmanxyz** [comment] 2020-08-10 10:19
@mahagr the file is there it is just incorrectly linked. Take the URL and not the link.

**Comment by greenlanegreb** [comment] 2020-08-10 21:29
Just an update - I did clear all Cache's but the same issue still presents.

**Comment by dmleeman** [comment] 2020-08-11 17:51
Just an idea, but why not post a mock up of the layout that you are looking for.  In the original YAML file, it was difficult to see the intended end result. A mock up would give other members a chance to post a solution.

**Comment by greenlanegreb** [comment] 2020-08-19 11:03
> @mahagr the file is there it is just incorrectly linked. Take the URL and not the link.

From this, were you able to see any obvious issues? 

Thanks.

**Comment by dmleeman** [comment] 2020-08-19 11:47
Ok, by pastign the quoted url I can see your YAML structure now.

Am I right in thinking that you are looking to create a series of sections and at various points you have sections with left and right sidebars, then a 100% section,  then a sidebars section, etc.?

**Comment by thexmanxyz** [comment] 2020-08-19 12:51
@greenlanegreb Did you now try what I suggested you? Did you start over with a simple layout file and narrow down the issue so that you actually get a feeling on how layout files should look like! I'm asking that because I know you already tinkering around with that layout file for months now. The last time you asked with a quite similar file back in 2019. In my opinion it doesn't make sense given the complexity of your file.

This would also help in determining the reason of the bug you're reporting here. Even though I suspect that there is a bug at all but rather the file. If you did not start with a fresh file or a working pre-defined layout file modifying it step by step I would really and for gods sake suggest to do that right now.

**Comment by dmleeman** [comment] 2020-08-19 14:15
Given his level of experience, if thexmanxyz has taken time to respond, I personally would follow his advice.
I'm not 'ganging up' against you personally (there is clearly some 'history' here).
It's simply a case of probabilities.
Gantry5/YAML bug far less probable than an error in the proposed structure. 
Giving it a quick look over, it's too complicated for me to be of any help, certainly if mahagr and thexmanxyz have already advised upon it.
I just thought that. given the practice of sketching out a layout (wireframe/mockup whichever) before committing to code, then seeing the design in its preliminary form may result in a solution for you.

**Comment by thexmanxyz** [comment] 2020-08-19 14:25
@dmleeman It's everything fine, nothing wrong with your advices ;). What I already suggested the other day is a basic concept when dealing with new stuff. Starting small, try out how it works and then go complex. This is the way how learning and understanding how things work is far easier.

You can also create a complex file without fully understanding the concepts. There is nothing invalid with that approach but you will probably waste hours or days...TBH I won't go with that approach.

**Comment by greenlanegreb** [comment] 2020-08-26 07:43
Thank you for your comments. I'd point you to my previous posts. There seems to be a lot of reading other's comments and not a lot of reading my own. The fact that you have a bug is blindingly obvious. I will quote myself from above: 

"...Gantry is interpreting the same YAML code in different ways every time I press the reload button??? Unpredictable results point like a blinding beacon to bugs...." "...It would be entirely different if the web "page" didn't look the way it was intended to but customised YAML is allowed to break the layout manager despite a parser being in situ - that sometimes works and more often doesn't..."

The Xmanxyz has said: "Thanks for correcting the file. As I don't see any issue with the file anymore we now have something valid to discuss about / test against...."  

Other than repointing to:

a) The same YAML template working with other websites; 

b) The parser having a clear purpose but sometimes reporting on issues and other times going as far as breaking the layout manager is a clear issue - i'm not so sure that nested containers are actually necessary to achieve a particular task or even in any way beneficial given that SCSS/CSS classes can be called on existing section and module positions in any event. 

c) As raised in the past, the need to create a custom layout  in order to have a variation in when the sidebar and aside exists and doesn't is inflexible. 

d) Most obviously ignored in this chain is the fact that every time the load button is pressed, the same loaded YAML layout is interpreted differently. 

I would have thought, by now, this would have been looked at from a Developer point of view. 

Thanks.

**Comment by thexmanxyz** [comment] 2020-08-26 10:30
> a) The same YAML template working with other websites;

You repointing? That original file was not correct so it actually also did not work on other sites. You also did not state anywhere that it works on other websites! Where did you state that? If it works on other sites it proves just one thing, that your Gantry installation on that specific site or something else influences the behavior and breaks the functionality. If it works on a clean install it is with a high change no Gantry bug. **Try that and report back!**

> b) The parser having a clear purpose but sometimes reporting on issues and other times going as far as breaking the layout manager is a clear issue - i'm not so sure that nested containers are actually necessary to achieve a particular task or even in any way beneficial given that SCSS/CSS classes can be called on existing section and module positions in any event.

You are mixing up tons of different things here. Error handling might need improvement but yeah that is unrelated to your issue. Feel free to create issue the especially targeting this problem.

> c) As raised in the past, the need to create a custom layout in order to have a variation in when the sidebar and aside exists and doesn't is inflexible.

Well why not simply doing that? You have all the flexibility you just have to create the layout in a way you need it. I don't get the point!

> d) Most obviously ignored in this chain is the fact that every time the load button is pressed, the same loaded YAML layout is interpreted differently.

That proves nothing and I say that as a software developer. It indicates some issue but it does not prove anything related to your issue.

**What did you since my last question? Did you try anything I suggested you? Yes / No? You don't want to do that, am I right?**

**Comment by thexmanxyz** [comment] 2020-08-26 11:25
@greenlanegreb 

I read your posts but your you information is contradictory.

> The fact that you have a bug is blindingly obvious....Unpredictable results point like a blinding beacon to bugs.

Well is it? I doubt it is! I would be careful not to make such a general statement at all. Without the knowledge of codeflow it doesn't tell you at all if there is a bug or not. It just tells us that the error handling might not be 100% correct.

> a) The same YAML template working with other websites;

You repointing? That original file was not correct so I guess it did not work on other sites as well. You also did not state anywhere that it works on other websites! Where did you state that? If it works on other sites it proves just one thing, that your website has an issue (custom modification, hoster, Gantry, Joomla,...). If it works on a clean install it is with a high change no Gantry bug. **Try that and report back!**

> c) As raised in the past, the need to create a custom layout in order to have a variation in when the sidebar and aside exists and doesn't is inflexible.

Well and how you expect this to work? This is an architecture breaker. You can only achieve this with a custom layout and I see no issue at all doing it like that.

> d) Most obviously ignored in this chain is the fact that every time the load button is pressed, the same loaded YAML layout is interpreted differently.

That proves nothing and I say that as a software developer. It indicates some issue but it does not prove anything related to your issue.

**What did you do since my last answer? Did you try anything I suggested you? Yes / No?**

Did you start over with a fresh template included layout file and started modifying it step by step to see what breaks the layout manager to rule out issues with your file? This would actually help @mahagr to find the issue of your problem. So why not doing this? 

If you want to contribute something useful, for fucks sake start enclosing the issue you are facing. What is your intention? No one will logon to your site and fix issues with your installation for you. That will not happen. You are still not providing consistent comprehensible information of the actual issue.

After all the text you dumped here I personally still don't know if you checked the validity of the file at all (step-by-step). I don't know if this is an issue that happens on just one site or not. You are not clearly telling us. You're assuming there MUST be a bug because you can't explain it to yourself and you don' try to enclose the issue. Please do that. Stop debating and tell us the necessary facts.

**Comment by thexmanxyz** [comment] 2020-08-26 11:49
@greenlanegreb BTW 1min reading the documentation I found the first issue in your file.

[Layout Documentation Gantry](http://docs.gantry.org/gantry5/advanced/creating-layout-presets)

```
version: 2

preset:
  image: gantry-media://images/admin/layouts/3-col-right.png

layout:
  /header/:
    -
      - menu

  /container-main/:
    -
      - main 60:
        - position-breadcrumbs
        - system-messages
        - system-content

      - sidebar1 20:
        - social
        - position-sidebar
        - position-right

      - sidebar2 20:
        - social
        - position-sidebar
        - position-right

  /footer/:
    -
      - position-footer
    -
      - copyright 40
      - spacer 30
      - branding 30

  offcanvas:
    -
      - mobile-menu

structure:
  sidebar1:
    subtype: aside
    block:
      fixed: 1
  sidebar2:
    subtype: aside
    block:
      fixed: 1
```

Can you already see the issue with your file when compare it with the above snippet? Your `structure` part in the layout file incorrect or in the best case just does nothing as you ar referencing on aside and sidebar that aren't in the file...

**Comment by thexmanxyz** [comment] 2020-08-26 11:55
@greenlanegreb Another 2mins evaluating your file. Next issue:

![image](https://user-images.githubusercontent.com/17965908/91300416-85e0a900-e7a3-11ea-88b6-13e826276d92.png)

BTW this is from documentation, did you read it? Why did you not do it like it is described there? I will highlight the important parts:

**EACH HORIZONTAL ROW NEEDS TO EQUAL 100% WIDTH .... DIVISIBLE BY 2**

**Comment by thexmanxyz** [comment] 2020-08-26 12:26
Take now the documentation, read it carefully. Then start with a fresh working file and extend it incrementally with your changes. Step-by-step and verify after each step. This will help YOU not us in understanding how your layout files should look like so that they are working. This sounds to me like a good approach can we confirm that now please?

When you did this and found an issue you can't explain in one of the baby-steps. Come to this issue, state the issue and you will receive help. If you're not doing this you're lost...full stop.

**Comment by dmleeman** [comment] 2020-08-27 19:16
@thexmanxyz 

I've been following this and found your answers very useful. With a good read of the docs and the detail in this thread I have successfully created a batch of yaml based layouts. I've been working mainly on Helium variants and usually managed to use a 'built in' section on all of my gantry5 based sites.

So, if it has not helped anyone else,  I can say for sure that the advice here has helped me to progress.

**Comment by mahagr** [comment] 2020-09-01 15:16
The issue is here:

```yaml
      - sidebar1 20:
        - social
        - position-sidebar
        - position-right

      - sidebar2 20:
        - social
        - position-sidebar
        - position-right
```

Both sidebars have identical particles and positions. I cannot remember the exact logic, but with positions, it will likely just render the content two times and with particles, it'll assign random id every time.

Saving the layout in admin freezes the layout, so I recommend doing that, too. Defining layouts like this are only supported in presets as layouts will add a lot extra information during the save.

**Comment by thexmanxyz** [comment] 2020-09-02 04:11
@mahagr but that snippet is from the documentation 🙂 it's not taken from the file of @greenlanegreb 

But thanks for the additional input on the use of layout files

**Comment by N8Solutions** [comment] 2020-09-02 09:19
> 
> 
> @mahagr but that snippet is from the documentation 🙂 it's not taken from @greenlanegreb file.
> 
> But thanks for the additional input on the use of layout files. Might it be useful to update the documentation then to prevent confusion? Because currently the snippet is kind of misleading as it contains duplicate positions.
 
Since that is from the documentation under [How to Create a Sidebar Section](http://docs.gantry.org/gantry5/advanced/creating-layout-presets#how-to-create-a-sidebar-section), maybe @RyanMPierson can take a look at it so it can be updated.

**Comment by mahagr** [comment] 2020-09-02 09:32
Yes, looks like there's some kind of copy/paste mistake in that section of the documentation.

**Comment by simmonsr** [comment] 2020-09-02 15:02
i fixed the doc issue here.

**Closed by simmonsr** 2020-09-02 15:02 UTC
Labels: docs
