### ISSUE TITLE
SCSS compiler not supporting 'map' functionalities?

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1117] opened 2016-01-19 21:12 UTC
Live site: http://a.nyaii.com/
Gantry version: 5.2.7

Related files:
http://a.nyaii.com/templates/rt_antares/custom/scss/components/_variables.scss

    $primary-color: color("materialize-red", "lighten-2");
    $primary-color-light: lighten($primary-color, 15%) !default;

http://a.nyaii.com/templates/rt_antares/custom/scss/components/_color.scss

    
        $materialize-red: (
      "lighten-5":  #fdeaeb,
      "lighten-4":  #f8c1c3,
      "lighten-3":  #f3989b,
      "lighten-2":  #ee6e73,
      "lighten-1":  #ea454b
    );
    $colors: (
      "materialize-red": $materialize-red
    );
    @function color($color, $type) {
      @if map-has-key($colors, $color) {
        $curr_color: map-get($colors, $color);
        @if map-has-key($curr_color, $type) {
          @return map-get($curr_color, $type);
        }
      }
      @warn "Unknown `#{name}` in $colors.";
      @return null;
    }

The error message says expecting color, which means function `color` doesn't execute properly. I tried compiling these two files with sass 3.4, there was no error. The answer(Update: unfortunately the answer has been deleted) of this SO post http://stackoverflow.com/questions/31575029/scss-compiling-error-expecting-color mentioned that `map` functionality was not fully supported but suggested that it would be mplemented. Is it now?

**Comment by mahagr** [comment] 2016-01-20 07:55
We are using https://github.com/leafo/scssphp as our SASS compiler, more exactly version 0.3.0 of it. Later versions have fully working hash support, but unfortunately we are stuck on this older version because of some of the templates were using SASS 3.2, which is incompatible to SASS 3.4. Namely the issue is in variable scoping, which didn't exist in older version of SASS.

Basically this means that updating Gantry without upgrading theme will result on broken site.

I would so much be able to solve this issue, but we need a really good plan how not to break existing sites.

**Comment by mahagr** [comment] 2016-01-20 10:28
Reference to the issue:

https://github.com/leafo/scssphp/issues/338

**Comment by mahagr** [comment] 2016-01-20 16:19
Looks like there was a bug in earlier scssphp versions that caused the below issue. I created a branch https://github.com/gantry/gantry5/tree/feature/scss34 which uses the latest compiler and I've not seen any issues this far.

Some more testing is required, though.

**Comment by adi8i** [comment] 2016-01-20 17:55
So this is affected by the bug?
`@media all and (max-width: $breakpoints-desktop-container) and (min-width: $large-mobile-container)`

**Comment by mahagr** [comment] 2016-01-20 18:19
No, there's no bug anymore. We just need to test it out as there has been so many SASS 3.4 changes that are incompatible to 3.2.

**Comment by adi8i** [comment] 2016-01-20 21:44
I tried to use that with latest CI, that's why i asked :)

**Comment by mahagr** [comment] 2016-01-21 05:46
Latest CI doesn't contain the update; right now its in its own branch until it gets tested a bit more.

**Comment by newjie** [comment] 2016-01-21 15:42
@mahagr I am not very familiar with Git. I want to apply the scss34 branch to my test site, how do I do it?   When I click the link, I think what I see is a development version including source files, how do I know which files to be updated to my test project?

**Comment by mahagr** [comment] 2016-01-22 07:05
The best and shortest documentation on how to use git can be found in here -- github help pages https://help.github.com/. I recommend using some git client, though, as it makes your life much easier.

You will also need https://github.com/rockettheme/hebe to properly symlink Gantry to your site (it has good docs how to set it up), though it doesn't work in Windows.

Copying files isn't really recommended as by using git you can easily keep your branches/code up to date.

**Comment by w00fz** [comment] 2016-02-20 00:12
Just an update.
The branch has moved forward, I updated Bourbon and SCSS to the latest versions. 3.4 is supported and seems to work properly.
There is one issue remaining which is related to sourcemaps. Paths in the comments are gone.

I think once that is solved we should merge into `develop` and start building CI Builds for people to test as it's a big change that we need to ensure is ok to release.

**Comment by IamHenryValdez** [comment] 2016-02-24 03:19
Hi just wanna know. Is the issues is solved ?
If not, wich Sass Compiler did you use to compile the scss ?

**Comment by w00fz** [comment] 2016-02-24 03:26
We still haven't merged the branch in (https://github.com/gantry/gantry5/tree/feature/scss34) and we use [leafo/scssphp](https://github.com/leafo/scssphp).

Our `scss34` branch features the latest version of leafo's scssphp as well as latest [bourbon](http://bourbon.io/). As soon as we finish testing and fixing a few minor issues, we will merge it in and do a release.

**Comment by mahagr** [comment] 2016-03-17 10:41
Update: I just fixed the last bugs in our SCSS feature branch. The issue is that we cannot really release it yet because of it needs some fixes from development version of scssphp, which haven't yet been released.

I'm also thinking that maybe we should wait for Gantry 5.3 release anyway as having a major update in both SCSS compiler and bourbon may require some CSS updates in themes that people have created (mostly if they happened to be using deprecated features).

**Comment by w00fz** [comment] 2016-06-04 05:03
This is now fixed in develop as we merged the features.

**Closed by w00fz** 2016-06-04 05:03 UTC
Labels: bug, important
