### ISSUE TITLE
Multi-lingual Language Switching - Frontend Exception

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#304] opened 2015-05-18 09:33 UTC
Hi, RC2 fixed the backend issue where multi-lingual menus would not be properly recognised, but now switching to a different language on the frontend results in an exception.

I am quoting the exception here:

    Whoops \ Exception \ ErrorException (E_NOTICE)
    HELP
    Undefined property: stdClass::$id
    Open: /Volumes/site/utpr2.dev/public/libraries/gantry5/classes/Gantry/Framework/Configurations.php
                $template = \JFactory::getApplication()->getTemplate(true);
            }
     
            $gantry = $this->container;
            $locator = $gantry['locator'];
     
            $preset = $template->params->get('preset', 'default');
            $configuration = $template->params->get('configuration', $template->id);
     
            return is_dir($locator("gantry-config://{$configuration}")) ? $configuration : $preset;
    Server/Request Data
    REDIRECT_HTTP_AUTHORIZATION 
    REDIRECT_STATUS 200
    HTTP_AUTHORIZATION  
    HTTP_HOST utpr2.dev
    HTTP_DNT  1
    HTTP_ACCEPT_ENCODING  gzip, deflate
    HTTP_COOKIE 4884262b71f249da5ac5f34d0f2886e0=alohkbs4k62b7gdpbld14kbk92; cccbef3cfbc7949923db9ae7c03c97d3=5kd192e6010lut8ru1sat633q2; fc36c8c84206911ebc819df74619ddcc=es-ES
    HTTP_CONNECTION keep-alive
    HTTP_ACCEPT text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    HTTP_USER_AGENT Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/8.0.6 Safari/600.6.3
    HTTP_ACCEPT_LANGUAGE  en-gb
    HTTP_REFERER  http://utpr2.dev/en/
    HTTP_CACHE_CONTROL  max-age=0
    PATH  /usr/bin:/bin:/usr/sbin:/sbin
    SERVER_SIGNATURE  
    SERVER_SOFTWARE Apache/2.4.10 (Unix) PHP/5.5.24
    SERVER_NAME utpr2.dev
    SERVER_ADDR 127.0.0.1
    SERVER_PORT 80
    REMOTE_ADDR 127.0.0.1
    DOCUMENT_ROOT /Volumes/site/utpr2.dev/public
    REQUEST_SCHEME  http
    CONTEXT_PREFIX  
    CONTEXT_DOCUMENT_ROOT /Volumes/site/utpr2.dev/public
    SERVER_ADMIN  ali.samii@ergonomiq.net
    SCRIPT_FILENAME /Volumes/site/utpr2.dev/public/index.php
    REMOTE_PORT 55992
    REDIRECT_URL  /es/
    GATEWAY_INTERFACE CGI/1.1
    SERVER_PROTOCOL HTTP/1.1
    REQUEST_METHOD  GET
    QUERY_STRING  
    REQUEST_URI /es/
    SCRIPT_NAME /index.php
    PHP_SELF  /index.php
    REQUEST_TIME_FLOAT  1431939142.205
    REQUEST_TIME  1431939142
    GET Data
    empty
    POST Data
    empty
    Files
    empty
    Cookies
    4884262b71f249da5ac5f34d0f2886e0  alohkbs4k62b7gdpbld14kbk92
    cccbef3cfbc7949923db9ae7c03c97d3  5kd192e6010lut8ru1sat633q2
    fc36c8c84206911ebc819df74619ddcc  es-ES
    Session
    __default Array ( [session.counter] => 5 [session.timer.start] => 1431938615 [session.timer.last] => 1431939136 [session.timer.now] => 1431939142 [session.client.browser] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/8.0.6 Safari/600.6.3 [registry] => Joomla\Registry\Registry Object ( [data:protected] => stdClass Object ( ) [separator] => . ) [user] => JUser Object ( [isRoot:protected] => [id] => 0 [name] => [username] => [email] => [password] => [password_clear] => [block] => [sendEmail] => 0 [registerDate] => [lastvisitDate] => [activation] => [params] => [groups] => Array ( [0] => 9 ) [guest] => 1 [lastResetTime] => [resetCount] => [requireReset] => [_params:protected] => Joomla\Registry\Registry Object ( [data:protected] => stdClass Object ( ) [separator] => . ) [_authGroups:protected] => Array ( [0] => 1 [1] => 9 ) [_authLevels:protected] => Array ( [0] => 1 [1] => 1 [2] => 5 ) [_authActions:protected] => [_errorMsg:protected] => [userHelper:protected] => JUserWrapperHelper Object ( ) [_errors:protected] => Array ( ) [aid] => 0 ) [com_mailto.links] => Array ( [122bf3f15bd80c105419b34486bb08271e310d2e] => stdClass Object ( [link] => http://utpr2.dev/es/busqueda [expiry] => 1431939142 ) ) [session.token] => 61c640c647593fb19944c023d38756d0 )
    Environment Variables
    empty
    Registered Handlers
    0. Whoops\Handler\PrettyPageHandler
    1. Whoops\Handler\PlainTextHandler
    2. Whoops\Handler\JsonResponseHandler

**Comment by mahagr** [comment] 2015-05-18 09:40
Wow, this is weird one.. Template style should always have id, otherwise there is no way to know which settings it should be using.

How do you get this?

**Comment by alisamii** [comment] 2015-05-18 09:42
I saved some changes in the mainmenu-es from within Gantry 5, then switched to the front-end. I was on the home page in English. I reloaded the page, then clicked to switch from English to Spanish...and got this error.

**Comment by mahagr** [comment] 2015-05-18 09:45
I'm not having any issues like that; switching between Finnish and English here.

**Comment by alisamii** [comment] 2015-05-18 10:16
Please see the Secure message I placed on the RocketTheme forums:

http://www.rockettheme.com/forum/gantry-framework/241806-multilingual-menus?start=0#1202855

**Comment by mahagr** [comment] 2015-05-18 10:50
Replied in there. I didn't have any issues on changing languages, it all worked just great.

**Comment by mahagr** [comment] 2015-05-18 16:43
Issue was caused by advanced template manager, I was able to replicate issue locally. Almost fixed in 9824d06, but we still need a fix from noNumber as well.

**Closed by mahagr** 2015-05-18 16:43 UTC
Labels: bug
