### ISSUE TITLE
Menu particle not pointing to a new ID menu

### ISSUE THREAD

**Issue by beamaria** [gantry/gantry5#122] opened 2015-04-25 09:44 UTC
after updating the framework, in Gantry menu editor the particle is  pointing to the wrong ID (the previous one was 103, now it should be 111), but the field is greyed and I can't change anything... also in Gantry menu editor it is not possible to trash this menu particle... in other words it isn't possible to update the particle so as it can reflects the new ID menu. If it is possible, it could be a good idea to add an "update" button to the menu particles, otherwise every time you update gantry framework this problem crops up
![menu editor](https://cloud.githubusercontent.com/assets/11693902/7332457/5bcf2bce-eb40-11e4-852f-3c427f81bbfa.jpg)

**Comment by adi8i** [comment] 2015-04-25 16:46
The problem is `g5_hydrogen/custom/config` folder. *I have no idea how this folder will be override at update, because i did a clean install*

Here: `g5_hydrogen/custom/config/menu` you will see `mainmenu.yaml` file. Here are menu config stored.
*(i have no idea what will happen if you delete that folder, will be the settings in template manager the same or will go to default or empty? @w00fz )*

Edit that file and you will see a line like this, where you can change the menu item id:
```
items:
  home:
    id: '101'
```

**Comment by beamaria** [comment] 2015-04-25 18:30
Thanks adi8i !! I've taken your advice and now the"info" menu works correctly. Anyway your supposition is correct: all the mess happened after importing the backup "custom" folder I of my previous installation. I imported it globally, as recommended in gantry blog (because some files may be hidden) the only thing I deleted was the "scss-compiled", but not the "config/menu" folder. I think that in gantry blog instructions for the updating this should be stated, at least until gantry team finds a new and brilliant (as they usually do!!!) solution for updating

**Comment by mahagr** [comment] 2015-04-27 07:37
Actually I'm going to reopen this as it reminds me from a task that needs to be done.

**Comment by beamaria** [comment] 2015-04-27 08:39
Ok! Happy to be a useful contributor to Gantry :-)

**Comment by mahagr** [comment] 2015-04-27 11:54
Half of the issue is fixed in here: https://github.com/joomla/joomla-cms/pull/6854

Will look into second half of it soon...

**Closed** 2015-05-07 12:08 UTC
Labels: bug
