### ISSUE TITLE
Chrome 65.0.3325.181 - Image and Font picker popups do not open

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#2262] opened 2018-03-22 09:43 UTC
First brought up by Damir.

Using **WordPress** with current Gantry 5.4.23 and Fluent theme, the image and font picker popups in the Styles tab do not open in Chrome Version 65.0.3325.181 (Official Build) (64-bit).

There is no issue with Joomla or Grav.

**Comment by marktaylor46** [comment] 2018-03-22 09:52
I can confirm this issue too.

**Comment by kuse-de** [comment] 2018-04-23 09:29
I can confirm it too, and with Chrome Version 68.0.3404.0 (Official Build) canary (64-Bit) the font picker and left side image pickers are working but on the right side they are still broken.

Would be great to see this fixed soon!

**Comment by drnasin** [comment] 2018-05-16 14:15
Confirming this on Grav + Chrome 66.0.3359.181 (Official Build) (64-bit). Works in FF Developer Edition ...

**Comment by newkind** [comment] 2018-05-19 08:16
This is not a bug in Gantry. Our code is proper and works fine in all browsers but latest Chrome. It's a bug in Chrome and should be fixed in chrome. We can't do anything about it. I've tested latest Chrome Canary and it's mostly fixed there besides small visual artefacts with the toggles on the assignments page. You guys will have to wait for Chrome update or use Chrome Canary or any other good browser in the meantime ie. Firefox.

**Closed by newkind** 2018-05-19 08:16 UTC
Labels: wontfix
