### ISSUE TITLE
Asset Timestamp Confusion

### ISSUE THREAD

**Issue by thexmanxyz** [gantry/gantry5#2263] opened 2018-03-22 21:54 UTC
Hey there,

it might be not a big thing, however it took me right now about 2 hours to find out how the actual Asset Timestamp works, because initially I though it is broken or I broke it somehow. On the deleted post below you can see how much confusion the Asset Timestamp in its current state can cause. So the original question now changes into some sort of feature request or at least some suggestion how to change the current behaviour to prevent misconceptions for other users in the future. 

But where does the whole confusion originate. I initially thought that the Asset Timestamp is not generated because none of my custom assets had some attached. On another install however the opposite was the case and all assets had one but after I exchanged one image on this install the Asset Timestamp was gone again for exactly that image I modified.

So the actual situation is the following. For new images and the default setting in the Gantry 5 - System plugin assets never seem to get the timestamp attached initially. They will after the "Timestamp Period", which also can be set in the system plugin, has passed or the value is set to 0. 

Now to my suggestion. I would strongly recommend to always attach an Asset Timestamp to assets and not starting to attach it after the period has passed the first time. This is somehow very inconsistent and causes a lot of confusion. I don't know why this is resolved this way. This is not a big deal TBH however if you never messed around with the Asset Timestamp it would take someone literally hours or days to find out why the timestamp would not be generated for an asset. Finally, it has to be said that also a cache clean would reset the Asset Timestamp and prevents it from beeing attached until the period is reached again, which was the problem in my case and why they disappeared everywhere. That is really confusing and the current situation might be very quickly fixed in the code base.

Sorry for the long text but it was necessary to lay down what happened to me and why the current state isn't perfect and should be changed to my suggestion if possible.

<del>This is probably no bug, however IDK how to find out how I can fix this issue. Maybe I caused it myself with some sort of modification. However there was at least one Joomla and Gantry update between so the core files shouldn't be affected and aren't modified. The actual issue is that "Asset Timestamps" simply do not work anymore. I'm on the latest G5 and J3. Template is Hydrogen. </del>

<del>I have another fresh install with Helium and there it works without problems. It doesn't matter whether I enable or disable the setting in the Gantry 5 System Plugin. Moreover it doesn't change anything when switching do Developer Mode. </del>

<del>I also tried disabling all custom plugins except Gantry 5 which doesn't resolved the issue. Furthermore I also renamed the custom folder in my template. Didn't worked either. Did someone of you already had this issue? </del>

<del>There is another strange thing. For some of the external CSS and JS files it does actually work but for none of my gantry imported images and also not for my particle CSS and JS files. </del>

<del>Below are the files were Asset Timestamps are generated. But nowhere else. Would really appreciate some help. </del>

```
<link href="/joomla/templates/g5_hydrogen/custom/css-compiled/hydrogen_10.css?5ab4234a" rel="stylesheet" />
<link href="/joomla/templates/g5_hydrogen/custom/css-compiled/hydrogen-joomla_10.css?5ab4234a" rel="stylesheet" />
<link href="/joomla/templates/g5_hydrogen/custom/css-compiled/custom_10.css?5ab4234c" rel="stylesheet" />
```

**Comment by mahagr** [comment] 2018-04-16 15:28
Actually, the asset timestamp goes away after 7 days by default, so it is only there for files which have just been changed. Having asset timestamps for longer will lower pagespeed score a lot, which is why it works in that way. Having 0 is a special case as it keeps the timestamps forever.

Timestamps are enabled if you're in development mode as you likely want to have the latest version of css/js always loaded.

**Comment by thexmanxyz** [comment] 2018-04-17 10:39
@mahagr I think there is a misconception. Please read my initial post again, the asset timestamp does not go away after 7 days it appears after 7 days. If you setup you site with gantry and clean the cache there won't be a asset timestamp on resources. However if the asset timestamp time span has passed the asset timestamp will appear. That's how it currently works. I checked that. 

The actual problem I meant is that the asset timestamp should be generated immediately and not after 7 days because that's very confusing and also seems for me not the way to go. Please carefully reread what I've written above (I know it's a long text and that sucks) because it clearly states how it currently works and I'm pretty sure this behaviour should be changed. Also your answer seems like you didn't get my point, no offense at all, just read again what I've written so we can discuss on the actual problem.

**Comment by thexmanxyz** [comment] 2018-04-17 10:54
@mahagr 

Just to break it down to the actual behaviour:

**Current**
- img-01.jpg
- img-01.jpg?56667 (after 7 days)
- img-01.jpg?89832 (after 14 days)
- img-01.jpg?47322 (after 21 days)

**Expected**

- img-01.jpg?32324
- img-01.jpg?56667 (after 7 days)
- img-01.jpg?89832 (after 14 days)
- img-01.jpg?47322 (after 21 days)

**Comment by mahagr** [comment] 2018-07-04 09:45
@thexmanxyz I'm not able to reproduce the issue, the feature works opposite to what you're describing it to work. For me touching a file adds the timestamp and making the file modification time older than 7 days makes the timestamp to disappear. Timestamps work even for the future times.

Basically, the 3 CSS files having timestamps are the ones that change on every admin save, so even that looks correct to me. Note that Gantry only adds timestamps to the files which were added from Gantry theme (inside particle or main theme), it doesn't do anything to the component or module assets.

To test it out:
> cd media/gantry5/engines/common/nucleus/css-compiled
> touch nucleus.css

You should now see timestamp in the above file.

> touch nucleus.css -t 201806271200

Now it shouldn't have any timestamp anymore.

Closing the issue as it works as designed.

**Comment by thexmanxyz** [comment] 2018-07-04 10:50
@mahagr I understand that it takes time to work issues through. However I have the feeling that they aren't read very carefully. That said. I won't reiterate what I have already said two times because the latency is weeks and I don't want to state the same thing over and over.

I can't confirm the behaviour and it looks like you didn't test correctly. Because if nothing has changed since I created the issue the problem is still there. Finally I will later test again and give a feedback (one last time). It's a bit annoying to me that there is still a discussion going on. I won't write a issue that long if there is no problem at all....

reopen until I reply

**Comment by mahagr** [comment] 2018-07-04 11:01
@thexmanxyz Yeah, sorry, I've been really busy on another project with deadlines and I've not really had time to look into this before.

I've never seen the issue you describe and I am not able to reproduce the issue in any of my sites. Also by looking at the code, it does the right thing. Timestamps are only added to the new files and they get removed after 7 days have been passed (or if you manually change the modified date of the file). 

By default Gantry only adds timestamps to the 3 files from your first post and they go away after 7 days, which you can configure. After Gantry update other files may get timestamps too, as they changed. In Gantry particles you may also have timestamps if you are using `url()` function in them. 

I need a better example, something I can reproduce step by step in order to understand your issue better.

**Comment by mahagr** [comment] 2018-09-07 09:50
@thexmanxyz I tested this again with my sites as none of them are showing the timestamps unless I save the styles.

**Closed** 2020-04-24 08:49 UTC
Labels: cannot reproduce
