### ISSUE TITLE
Error Outline works differently in 5.3.9 (Joomla)

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1732] opened 2016-12-08 14:40 UTC
Hey Matias,

As the title says, the "Error" outline works differently in 5.3.9
Until now, if the user has the same Layout Preset in the "Error" outline as the one in the Base/Default outline they will see just the error message on the Error Page.
But in 5.3.9 they will see everything that is published on the Homepage.

Have a look at [this video](https://youtu.be/p0XzsBHqsBE), it shows everything.

So, is this a bug or the new behavior is here for good?
The only related thing in the 5.3.9 changelog is:

> Automatically load jQuery and Mootools frameworks in error page if particles or atoms request them

**Comment by mahagr** [comment] 2016-12-09 11:26
I'm not able to reproduce the issue locally... See my PM.

**Comment by mahagr** [comment] 2016-12-09 11:41
OK, I think I can see the issue now, though you need to trigger the 404 page in home page in order to see modules from that outline.

**Comment by mahagr** [comment] 2016-12-09 11:49
After a quick look I know what causes this issue.

In the past 404 page under home page was throwing an exception in router, thus there was no menu item set. It was a bad practise, so I changed the code to throw 404 inside the component instead.

So basically error page will now always load modules assigned to the current menu item -- previously it did that only with other components than Gantry 5.

I don't think the new behavior is correct, error page should show only those modules which haven't been assigned to any menu item and are available in all pages.

**Comment by JoomFX** [comment] 2016-12-09 12:26
Thanks Matias!

> error page should show only those modules which haven't been assigned to any menu item and are available in all pages.

Yes, this is exactly how I think it should work. Only modules that are assigned to "All Pages" should be rendered on the Error Page.

**Comment by mahagr** [comment] 2016-12-09 12:37
Was a nasty one to fix, but yeah, its fixed now. :)

**Closed by mahagr** 2016-12-09 12:37 UTC
Labels: bug, joomla

**Comment by JoomFX** [comment] 2016-12-09 12:46
Just tested the latest CI build and everything works just fine!
Thanks Matias ;)
