### ISSUE TITLE
Font Picker styles popover has wrong position calculated

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#363] opened 2015-05-27 09:49 UTC
When you hover the available styles in the font picker the popover has wrong position. Please see attached pic.
![gantry 5 options gantry5 wordpress wordpress 2015-05-27 11-47-50](https://cloud.githubusercontent.com/assets/1641534/7833348/5fae68d8-0466-11e5-905e-cf83da313dba.jpg)

**Comment by newkind** [comment] 2015-05-27 09:52
Also other popovers have wrong location
![gantry 5 options gantry5 wordpress wordpress 2015-05-27 11-51-20](https://cloud.githubusercontent.com/assets/1641534/7833393/be1a819a-0466-11e5-8a9f-99229592ef86.jpg)

**Comment by w00fz** [comment] 2015-05-27 18:52
Duplicate of #362

**Closed by w00fz** 2015-05-27 18:52 UTC
Labels: bug, wordpress
