### ISSUE TITLE
Inheritance issue

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1336] opened 2016-06-05 19:29 UTC
Hey guys,

I just installed the CI build to test the Inheritance, but there's something wrong.
As soon as I try to set any Inheritance I get an error message.

The second issue with the CI build is just a cosmetic one - when you go to "Outlines", a dark background shows for a second.

Have a look at [this video](https://youtu.be/ie7vR0qkR84), it shows both issues.

**Comment by w00fz** [comment] 2016-06-05 21:09
Weird I'm not seeing any of the issues as you, I tried replicating the black Outlines issue in Chrome, Safari and Firefox on OSX.

**Comment by mahagr** [comment] 2016-06-06 07:21
Ok, so the video says that the issue is in Layout/Layout.php line 777. I'm going to take a look what's going on in there.

**Comment by JoomFX** [comment] 2016-06-06 07:39
Alright guys, here are some more details:

1. I'm able to reproduce the issue with all my G5 template and with all RT templates. So far I tested it with Ethereal, Galatea and Topaz and the issue is reproducible there as well.

2. I'm not able to reproduce the issue with Hydrogen.

3. The cosmetic (dark background) issue is not reproducible in most of my G5 templates and in none of the RT template. It is reproducible only in my Milano template (see the next point, most probably these are related).

4. In all RT templates and in all my templates except "Milano", the "Particle Defaults" tab is removed in all Outlines except "Base". I'll try to troubleshoot this further. There seems to be something wrong in my "Milano" template but not sure what, as everything is standard, the same as in all other templates.

**Comment by JoomFX** [comment] 2016-06-06 07:44
Actually I'm able to reproduce the cosmetic (dark background) issue in all my templates and in Ethereal, Galatea and Topaz as well. It is just a sporadic issue.

**Comment by JoomFX** [comment] 2016-06-06 08:06
The thing with the "Particle Defaults" tab is really strange.
It does not get removed in my Oxygen and Milano templates, while it gets removed from the rest of my templates.

All my templates (the code, options, fields, etc) are pretty much the same. No G5 templates overrides, etc. 
How does the "Particle Defaults" tab get removed? What's the logic/code behind it? Do you have any idea why it works for most templates and it doesn't for Oxygen and Milano ? :smile:

**Comment by mahagr** [comment] 2016-06-06 08:55
Particle defaults will stay there as long as you have overridden anything in the outline. If you haven't done that, you can still make it visible by going into base outline, selecting defaults and changing outline. Once you save changed settings, it will enable the tab until you remove all the overrides in it.

**Comment by mahagr** [comment] 2016-06-06 09:28
Should be fixed now.

**Closed by mahagr** 2016-06-06 09:28 UTC
Labels: bug

**Comment by JoomFX** [comment] 2016-06-06 10:14
Hey Matias,

Yes, the error is now fixed and the Inheritance works. Thanks :wink: 

Regarding the "Particle Defaults" tab - well, I do not have any overrides in the "Default" outline but the tab is still visible. Have a look at [this video](https://youtu.be/2xg5IH9w83I). Any idea why?

Regarding the sporadic issue with the dark background in "Outlines" - I hope somebody else (preferably from the RT Team) will be able to reproduce it as well and will open a new issue for it.

**Comment by mahagr** [comment] 2016-06-06 11:22
Try saving the outline; the logic just checks if the particles folder exists and it wasn't removed in the previous versions.

**Comment by JoomFX** [comment] 2016-06-06 11:38
Awesome! That was it :smile: 

Re-saving the Outline didn't make any difference.
Then I checked the `custom` folder and I actually had a `particles` folder for that Outline.

I was just curious why that was happening. Of course, customers will not experience this issue as there is no `custom` folder in the package by default.

Thanks Matias!

P.S. Regarding the "dark background" issue in "Outlines" - it is reproducible in Firefox only (mine is 46.0.1). It works just fine in Chrome and IE11.
Do you want me to open a new issue for that?

**Comment by mahagr** [comment] 2016-06-06 11:40
I'm using FF, too (same version as you're in), and I've never had that issue. :) I'm on Linux, though.

**Comment by JoomFX** [comment] 2016-06-06 11:54
I'm on Windows 8.1 :)

I see it almost every time I go to "Outlines", no matter what template I use (mine or RT) :)

Anyway, it is not really important so let's leave it for now.

Thanks Matias :wink:
