### ISSUE TITLE
Gantry menu not saving any changes made to menu

### ISSUE THREAD

**Issue by Nabisvv** [gantry/gantry5#3061] opened 2022-07-14 14:01 UTC
Hi.

I have a Inspire Theme Template installed (Joomla 3.10.10). In Gantry/menu I am unable to save any changes I make to the menu. I can move the menu items left and right to reorder them or I can open the settings for a specific menu item and change it but, when I save the changes, I get thin modal popup window with nothing inside and no changes are saved.

So basically I am unable to build a desired menu structure. If I add a new menu item, it becomes the last menu item and that is where it stays.

Please, any assistance will be greatly appreciated. We are growing the site with more and more menu links and I need to be able to restructure or move menu items where i need them.

I have attached a short video so you can see what happens...

https://user-images.githubusercontent.com/109085570/179000969-f259fe63-a9c3-4a02-99d8-3ca01f159f87.mp4

Kind regards

**Comment by mahagr** [comment] 2022-08-22 09:28
There was likely some temporary issue with cache..? Nonetheless, it's good that the issue is gone. I'll close the issue.

**Closed by mahagr** 2022-08-22 09:28 UTC
Labels: question
