### ISSUE TITLE
Menu start & Max levels don't work Part II

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#836] opened 2015-09-15 06:52 UTC
Using Gantry 5 v5.1.2 and the Hydrogen template g5_hydrogen 5.1.2 when I setup Menu Levels I get a "in_array() expects parameter 2 to be array, string given" error on the frontpage.
PC setup -> Local MAMP for WINDOWS - PHP 5.6.8 - Joomla 3.4.4

Here are the steps:
1. Setup a 4 level deep menu
![1-admin-menu-setup](https://cloud.githubusercontent.com/assets/3792467/9869684/0a0b801a-5b54-11e5-8128-8f05acd56bd2.jpg)

Front end display
![1-frontend-menu-setup](https://cloud.githubusercontent.com/assets/3792467/9869687/0a0c1b42-5b54-11e5-9d1f-d976a50654cb.jpg)

2. in the Home Outline -> Layout Manager -> edit the menu particle
![2-admin-menu-setup](https://cloud.githubusercontent.com/assets/3792467/9869686/0a0bfb76-5b54-11e5-9617-fd85de7fbd3f.jpg)

3. Particle setup
![3-admin-menu-particle-setup](https://cloud.githubusercontent.com/assets/3792467/9869685/0a0be7a8-5b54-11e5-84cb-61151f04e4da.jpg)

4. Front end result the error message
![4-frontend-menu-display](https://cloud.githubusercontent.com/assets/3792467/9869688/0a0c3136-5b54-11e5-9cb8-483f53672a9f.jpg)

**Comment by DanGthatRokGallery** [comment] 2015-09-18 04:10
With dev-a8c370d38-joomla-pkg_gantry5_develop installed on the site, the error message is gone but only the Site Administrator item is visible.

**Comment by mahagr** [comment] 2015-09-18 09:42
I believe I've fixed this one in #666; I'm not able to reproduce this one anymore.

**Comment by DanGthatRokGallery** [comment] 2015-09-19 04:59
On my remote test site -> PHP 5.4.39  - Joomla 3.4.4 -  Gantry  5.1.4 - Hydrogen 5.1.4

Menu levels of Start=2 and Stop=4 on a 5 level menu still ends up showing only the last parent item.

**Comment by mahagr** [comment] 2015-09-28 10:50
I'm not able to reproduce this one, it just seems to work fine to me. Can you go to menu manager and hit `Rebuild` button in the top?

**Comment by mahagr** [comment] 2015-09-29 06:48
It looks like the feature works as described, the only issue is external url in the end which isn't properly detected as being out of scope.

**Comment by mahagr** [comment] 2015-09-29 07:11
Alright, the menu item is working just fine. Parent of that item was home, so showing second level of home displayed the menu item correctly.

**Closed by mahagr** 2015-09-29 07:11 UTC
Labels: bug, joomla
