### ISSUE TITLE
rokbox is always being loaded?

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#165] opened 2015-05-01 01:39 UTC
i cleared out all particles and atoms from my layout and loaded the frontpage.
nothing is visible as expected on frontend, but when viewing the source code, rokbox (amongst some others) is being loaded, not sure if that is intentional?

![g5_rokbox](https://cloud.githubusercontent.com/assets/5719486/7425590/08e024da-ef79-11e4-93ae-f68815198d31.jpg)

**Comment by w00fz** [comment] 2015-05-01 03:04
I believe because that's still a component you are loading and the system plugins are still enabled. 
I think it is expected behavior, @mahagr?

// Djamil Legato // From iPhone //

**Comment by kat05** [comment] 2015-05-01 03:12
system plugins are indeed enabled, but i am not loading any component. the example is the home menu item, and everything in the layout is cleared out, even page content. i also unpublished all modules, just to be sure.

**Comment by kat05** [comment] 2015-05-01 03:12
checked other pages and i have rokbox loading on all of them, no idea where it's coming from. do you have any idea what it could be?

**Comment by w00fz** [comment] 2015-05-01 03:16
I think it's because you are still loading a menu item and that triggers the system plugins to load even if the page is empty. The same reason you still get the meta tags, class names, page title etc.

// Djamil Legato // From iPhone //

**Comment by kat05** [comment] 2015-05-01 03:21
ok, tried with acacia, disabled everything, all modules, features, frontpage components, all menu items except home etc etc, so getting a white page to load and rokbox also shows up in the source. guess it's not a gantry 5 thing at all, feel free to close this. :)

**Comment by mahagr** [comment] 2015-05-01 07:59
I can confirm that it always loads the assets. Closing the issue as its not related to Gantry5.

**Closed by mahagr** 2015-05-01 07:59 UTC
Labels: invalid
