### ISSUE TITLE
Problème between the compnant DPCalendar and Gantry5/Helium template

### ISSUE THREAD

**Issue by Johann009** [gantry/gantry5#2706] opened 2020-09-23 07:45 UTC
Hello,

I use joomla 3.9.21 with Gantry5.
I use DPCalendar Component to present my events.
My problem is that I can't access to the event location description anymore, the link redirects to the home page .

I reinstalled the dpcalendar 7.4.6 pluggin - the problem is still there.
I reinstalled Gantry5 and the Helium5.4.35 template. The problem is still there.
I notice that In DP calendar:
router setting: Modern  it doesn't work
router setting: Legacy   it works !
I prefer de Modern setting, so why it doesn't work? ...

**
I contacted the developper of the component. I gave him full access to the website and see below his feedback :
"It works with protostar template. Also when I add some debug code in the location view default.php file with a die; statement, then the location code is printed, even with the gantry template. Not sure why but the template is not printing the component output for some reasons. I suggest you contact the template developer and ask them, what can be the cause. For me it looks like a bug on their end."
**

I give you a link to an event page to see by yourself:
https://jazcompreparevotresite.com/all-calendars/timeless-loving-level1
the link is on the title of the location in the right size (in this exemple it’s Shalom Hill Farm.

Tell me when your are ready and I pass Set error reporting to maximum and turn on debugging in my Joomla configuration, just let me know ?

Thank you for you feedback

**Comment by mahagr** [comment] 2020-09-28 08:12
Gantry has no redirects, but if the URL doesn't change but you see the layout from the home page, you have likely assigned home layout as the default layout. This is a common mistake as people think that template layouts work like a menu.

In admin go to Extensions > Templates > Styles and check which style is set to default. Usually it should be `Helium - Default`.

**Comment by Johann009** [comment] 2020-09-28 09:31
Hello,

thank you for your feedback,

to be clear this is not a problem of assignment on the home page layout.

When the DPCalendar module integration is in "Legacy" mode, the event page is contained in the following URL:
https://jazcompreparevotresite.com/all-calendars/95
From this page the URL to the description of the location is:
https://jazcompreparevotresite.com/all-calendars?view=location&id=37
In this case the display works correctly and we access the location description page.

When the DPCalendar module integration is in "Modern" mode, the event page is contained in the following URL:
https://jazcompreparevotresite.com/all-calendars/timeless-loving-level1
From this page the URL to the description of the location is:
https://jazcompreparevotresite.com/component/dpcalendar/location/37
In this case the display does not work. We are redirected to the home page.

Where can this bug come from? The developer of the DPCalendar pluggin thinks that it comes from the template because with the Protostar template it works in both modes... This bug only concerns the location description page, everything else works correctly.

Thanks for your help.

**Comment by mahagr** [comment] 2020-09-29 08:17
OK, I can see that the issue isn't the home page layout. But it is still not redirecting the page, it is just using wrong Joomla template layout. If you go to Gantry Admin and switch to your Home outline, switch to Layout and drag `Page Content` into the layout and save. After that, you will likely see that the content uses wong layout.

Maybe the issue is in your menu -- check that your default menu item isn't using DPCalendar page, but empty Gantry page.

Gantry does not do any redirects or layout assignments, Joomla does that and the template is just called like in Protostar. The only difference is that Gantry homepage does not display any content where Protostar does. If you assign modules into Protostar home style, you would be seeing the wrong modules, just like in Gantry.

I say this again: Gantry works like any other template and there's no custom logic in Gantry frontend to decide which layout to display. Only the rendering differs from regular Joomla templates.

**Comment by Johann009** [comment] 2020-09-29 10:16
Just to be clear, the problem is not about the layout, the content is simply not displayed in Modern mode. The home page is displayed instead. In Legacy mode the content is displayed correctly in the right page of the template.
So my question is why it works well in Legacy mode when it doesn't work in Modern mode??

Thank you for you comment.

**Comment by mahagr** [comment] 2020-09-30 06:23
I'm saying the same. This issue has been reported many, many times and has always been a bug in either the component or configuration issue. It can be replicated with protostar with similar style configuration.

Gantry does not change which template style is being loaded -- it's fully handled by Joomla (or by the component).

I have a debugging tool, which allows you to see what is happening there. Contact me by email matias at rockettheme dot com or ping me on Gantry 5 gitter channel.

**Comment by mahagr** [comment] 2020-11-10 09:08
Followup: This issue with the modern mode can be fixed by creating a hidden menu link for DPCalendar. DPCalendar will use the menu item, which sets the correct layout for the page.

**Closed** 2020-11-10 09:08 UTC
Labels: joomla, question
