### ISSUE TITLE
Block variations are not shown in Grav

### ISSUE THREAD

**Issue by ghost** [gantry/gantry5#1103] opened 2016-01-10 10:56 UTC
Olli

**Comment by mahagr** [comment] 2016-01-11 08:57
If you meant ´Settings > Menu > Base Item` I have fixed it. If not, you need to describe yourself a bit better. :)

**Comment by Tyrion2737** [comment] 2016-01-11 09:06
Sorry Matias, sometimes I am not good in describing myself. I meant Menu-Particle > Block > Variations do not show up when clicked.

**Comment by mahagr** [comment] 2016-01-12 07:20
Alright, I can fix that too. :)

**Comment by mahagr** [comment] 2016-01-12 09:07
I cannot reproduce the issue: Variations list shows up for me just fine. Which browser you're using?

**Comment by Tyrion2737** [comment] 2016-01-12 12:52
I use Safari 9.0.3 but in latest Firefox and Chrome the list does not show up either.

**Comment by mahagr** [comment] 2016-01-12 13:11
@w00fz Do you have any idea what might be broken?

**Comment by Tyrion2737** [comment] 2016-01-20 09:29
Thank you very much for your work!

Did you already have an idea @w00fz?

**Comment by mahagr** [comment] 2016-03-08 11:08
Variations should not show up inside this context. This should be fixed now -- there's no block variations in menu.

**Comment by tyrion273** [comment] 2016-03-08 13:09
I am sorry again Matias, I mean the variations-field below 😉

![ohne titel](https://cloud.githubusercontent.com/assets/14146656/13602386/ae325530-e536-11e5-8511-b0abdca93156.jpg)

**Comment by mahagr** [comment] 2016-03-08 14:07
OK, that one doesn't seem to work.

**Closed** 2016-06-17 12:57 UTC
Labels: bug, grav
