### ISSUE TITLE
Add support for Fontawesome 5

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2196] opened 2017-12-13 11:10 UTC
Since Fontawesome 5 is now available and uses SVG's it would be nice to provide support for this within Gantry5. Fortunately Fontawesome do provide a mechanism to retain backwards compatibility with fontawesome 4 codes through the use of their "shim" - please see...

https://fontawesome.com/how-to-use/upgrading-from-4

**Comment by pplopx** [comment] 2018-01-29 21:21
+1

Thanks!

**Comment by 810** [comment] 2018-04-01 15:13
any progress?

**Comment by wbarnes** [comment] 2018-04-02 12:40
+1 Thanks,
 I am also interested in updates?

**Comment by XaRz** [comment] 2018-04-06 11:03
+1 Thanks!
we want new fa5! 👍

**Comment by adoewa** [comment] 2018-04-10 12:19
+1 tnx

**Comment by webhelpus** [comment] 2018-04-17 19:01
I'd like to be able to 1) easily use the new Font Awesome 5 icons (which are amazing) and 2) be able to use the Pro version too. (they just released their beta CDN)

**Comment by pplopx** [comment] 2018-04-17 19:39
Indeed, the CDN Pro of FA5 is now online (beta)! 

A suggestion: to implment the free version it is enough to include the files (and the corresponding code) in the distribution of Gantry, as usual. I understand that the solution for FA5 Pro users should be to be able to use this new CDN. I have not yet studied the method well, but it seems that each user would have to include a token that FA provides us with. 

Since I suppose that the distribution of Gantry can not include the exclusive icons of the FA5 Pro subscription by license terms, I suggest that the Gantry implementation offer as an alternative a setting that if it is filled with the code of the token, ignore the files of the version free included with Gantry and work directly with the CDN Pro. 

I think it should be possible to do so and it could be a smart solution. I can provide Gantry developers with access to the test token if they do not get it directly from the FA guys.

**Comment by webhelpus** [comment] 2018-04-24 17:47
For Now, pro users can add the CDN to their Head in Page Settings.  You'll have to enter the codes and won't have a GUI in Gantry.

**Comment by paolavness** [comment] 2018-04-25 16:45
Is there an ETA on this? Specifically, it would be good to be able to access the Icons in `simplecontent` and `infolist` particles in Grav. 

Could you give guidance on where to edit these particles in the backend to access the new icons?

**Comment by thexmanxyz** [comment] 2018-04-28 11:47
@webhelpus better way would be to override `page_head.html.twig`, `base.html.twig` and `layout.html.twig` this way it would be general available however IDK if there are any incompatibilities. Didn't do a test.

**Comment by thexmanxyz** [comment] 2018-04-28 11:53
@paolavness I listed the files above which should be overriden if you want to use an other `css` file like for FA5, but didn't test. However these are the files include the default gantry FA version.

**Comment by webhelpus** [comment] 2018-04-28 18:08
@thexmanxyz Adding the CDN worked for me.  I just had to manually put in the codes and search for the codes on the Font Awesome website, but they have improved it so much that it's easy to do.  I've got it to work on the site I'm building right now using my method.

**Comment by paolavness** [comment] 2018-04-28 18:36
thank you @thexmanxyz. I'm getting more of a handle on it all. I've installed the FA5 fonts and files and for now, from the gantry admin UI, am simply referencing the FA5 styles in the in the `Icon` (`input.icon`) field rather than searching via dropdown F4 list. Its working a charm :)

**Comment by thexmanxyz** [comment] 2018-04-28 18:40
@webhelpus I know it works the way you did it, however there are reason i suggest to adapt it with overrides. You are loading the whole css two times for absolutely no reason, you have CSS rule overrides for everything that concerns FA. I would at least suggest overriding `pag_head.html.twig` instead of messing around with loading two version of FA.

**Comment by N8Solutions** [comment] 2018-04-28 18:48
@thexmanxyz just wanted to point out a typo. You mean the `page_head.html.twig`  😉

**Comment by webhelpus** [comment] 2018-04-28 19:06
@thexmanxyz Good point.  I'll make my adjustments accordingly.

**Comment by webhelpus** [comment] 2018-04-28 19:34
@thexmanxyz Where is the page_head.html.twig and other twig files.  I'm not finding them.

**Comment by thexmanxyz** [comment] 2018-04-28 19:37
@webhelpus 

- `media\gantry5\engines\nucleus\templates`
- `administrator\components\com_gantry5\templates\partials`

**Comment by pplopx** [comment] 2018-04-28 21:24
@thexmanxyz et al 

Is it safe to do it with overrides? When I tried this same approach, Gantry's dashboard broke. The dashboard makes intensive use of FA icons also in backend. Many times a call with code is not enough. Could they publish the modifications exactly and how would it work? I understand that it is a patch until the Gantry development team implements it, are there dates for this?

Thanks!

**Comment by thexmanxyz** [comment] 2018-04-28 21:42
@pplopx I can't 100% tell if it safe with overrides :P. Especially with changes on the admin site. So no guarantees at all from my side. However just changing the `page_head.html.twig` for front end matter should work without any issue. However, you won't have any support from backend icon selectors and stuff. You have to rely on text inputs. Be aware that you don't override the original files. And also the link @marktaylor46 has provided above (shim for v4).

**Comment by pplopx** [comment] 2018-04-29 09:39
Thanks, okay. I am testing it on my dev site and I will comment on the news.

**Comment by Legolasindar** [comment] 2018-05-31 15:34
+1 Yes please.

**Comment by N8Solutions** [comment] 2018-08-21 13:13
Any official update for this?
I have a project I'm working on now where I need to implement FA5.

**Comment by newkind** [comment] 2018-08-21 13:16
Not yet, this is not a trivial task how it can sound. If we will be implementing this we have to maintain backwards compatiblity with FontAwesome 4, toggles for changing FontAwesome switching, updates to Icon Picker for both versions, support for FA5 Premium owners, support for all variants like svg's etc. This issue is much, much bigger than you might think. If you need it right now, use the FA5 font files and implement them in your theme like any other font.

**Comment by marktaylor46** [comment] 2018-08-21 13:47
I will add that if all  you want is to use FA5 in your own content using the FREE version then it's fairly straightforward to do that. You just need to load FA5 in the base outline > page settings via their CDN. Using the code here:

```<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">```

![2018-08-21_14-41-21](https://user-images.githubusercontent.com/11683218/44405313-d7208700-a550-11e8-9092-567ebc94b1ba.jpg)


Then you can use it in a custom html particle/module (or anywhere else that you can add html) like this
```<i class="fas fa-apple-alt fa-fw fa-2x"></i>```

Obviously though any existing particles that use the Gantry 5 font picker won't see the FA5 icons at all.

I hope that helps.

**Comment by Legolasindar** [comment] 2018-08-21 15:30
This work great for me @marktaylor46 thanks

**Comment by N8Solutions** [comment] 2018-08-22 10:42
@marktaylor46 Thank you for your suggestion! I'd like to add that this works even for Pro accounts.
For Pro accounts, the CSS code provided in our accounts includes our specific Key so that code should be added to the Head section under Page Settings instead of the code you provided.
You add the domains to your account where you will be using FA5 and once the CDN has been updated with your domains FA5 works brilliantly throughout the site. You just have to update all the FA codes to their FA5 counterparts.

**Comment by marktaylor46** [comment] 2018-08-22 10:46
@N8Solutions Good, glad to help. :)

**Comment by AndiLeni** [comment] 2018-10-04 22:00
Is there a way to add a costum icon-font to the icon picker?

**Comment by marktaylor46** [comment] 2018-10-04 22:06
No you cannot add a custom font to the font picker as explained above - it's not a trivial undertaking.

Regards, Mark.

**Comment by AndiLeni** [comment] 2018-10-04 22:33
Thank you very much for you answer! 

Regards
Andi

**Comment by Shorece** [comment] 2018-11-17 21:56
@marktaylor46 
very good!!!

**Comment by muffindcc** [comment] 2019-08-21 09:36
Can't we add a new YAML field, such as input.fa5, so you can use either/or from that level. Rather than worrying about backward compatibility, it introduces a new type that people can use at their leisure. FA5 has been out for 2 years, which effectively means input.icon is going to be decreasingly useful. You don't have to include all the new features, but just so that you can do the most basic of selections from the picker.

**Comment by pplopx** [comment] 2019-08-21 11:39
**+1** 

This is a good approximation for those who still use FA4. Having two options would provide full compatibility. Some configuration option would suffice to set one or the other version by default.

**Comment by thexmanxyz** [comment] 2019-08-21 11:57
@muffindcc But be aware that every particle has to be updated concerning the `input.icon` field that is something that might confuse many people.

**Comment by marktaylor46** [comment] 2019-08-21 12:36
Yep, so, that's currently well over 160 Rockettheme particles that would have to change to accommodate this extra field setting... in other words, if and when FA5 get's fully implemented it won't be like that. Also, don't forget all the third-party developers who would need to change their particles too.

I think my workaround above is the least pain option for now.

**Comment by muffindcc** [comment] 2019-08-21 12:49
> @muffindcc @pplopx But be aware that every particle using `input.icon` has to be updated for FA5. That is something that might confuse many people (having both fa4 and fa5 icon pickers).

Why would it? It would be a brand new YAML type, that would only be included going forward, or people could add themselves. It would be the quickest way of getting a FA5 picker without any backward compatibility problems. Simply, no templates would need updating at all.

This isn't about deploying FA5 on the frontend, which your workaround is sufficient for, but purely about the backend. Obviously we can use FA5, but the idea of the Gantry interface is to make it easier for admins.

**Comment by muffindcc** [comment] 2019-08-21 12:51
Obviously a fully updated input.icon solution that would allow you to switch between versions would be perfect. But from a practical point of view, we've had FA5 for nearly 2 years, and there hasn't been any traction on this, so sometimes its better to implement something small but functional, then never update it at all, as there aren't any resources to do it "properly".

**Comment by marktaylor46** [comment] 2019-08-21 12:53
Feel free to do a pull request if you think you have a solution. I very much doubt that the developers are going to get any time to implement this for the reasons they have already given.

**Comment by thexmanxyz** [comment] 2019-08-21 14:31
@muffindcc It doesn't make sense to add another field type as long as there is no official support from the template / framework. However the FA5 implementation in the end will look like. @marktaylor46 also said the obvious thing, when FA5 will be implemented everything from that point on will be FA5 and there will be no need for an additional field (or as you recommended it might contain the option to use either FA4 or FA5 within the picker). I see no reason to implement an explicit field type for the meantime like you suggested.

But to make things from now on easier I will create a project that at least allows to automatically add FA5 compatibility + the option to switch between FA4 and FA5. This will not cover the input field problem. But at least it allows to quickly upgrade the site to FA5 or switch back to FA4. I will keep you updated here.

**Comment by mahagr** [comment] 2019-10-01 12:33
Merged the pull request. So at least there's an option to disable FA. :)

**Comment by thexmanxyz** [comment] 2019-10-02 12:41
@mahagr Really appreciate, that we have that option now 👍

**Comment by newjie** [comment] 2020-03-27 20:33
Do we have this implementation already? I still can't choose new icons in a icon picker.

**Comment by newjie** [comment] 2020-03-28 23:32
> I will add that if all you want is to use FA5 in your own content using the FREE version then it's fairly straightforward to do that. You just need to load FA5 in the base outline > page settings via their CDN. Using the code here:
> 
> `<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">`
> 
> ![2018-08-21_14-41-21](https://user-images.githubusercontent.com/11683218/44405313-d7208700-a550-11e8-9092-567ebc94b1ba.jpg)
> 
> Then you can use it in a custom html particle/module (or anywhere else that you can add html) like this
> `<i class="fas fa-apple-alt fa-fw fa-2x"></i>`
> 
> Obviously though any existing particles that use the Gantry 5 font picker won't see the FA5 icons at all.
> 
> I hope that helps.

I tried this but many fa4 icons are broken in icon picker.
What I did is downloading the whole fa5 library and self-host it instead of using your CDN, could this be the reason?

I can manually input the fa5 code to override icon picker's default though. For example, replace `fa fa-facebook ` with `fab fa-facebook` works, as shown in the picture.
![iconpicker](https://user-images.githubusercontent.com/12814040/77836243-d9829400-712a-11ea-9d45-31c2b9ec30ef.png)

**Comment by mahagr** [comment] 2020-09-28 13:21
Merged FA5 improvements from @thexmanxyz also.

Admin always uses FA5 web fonts with FA4 shims installed.

There are still some issues, like icon selection does not change in the administration when you select FA4 vs FA5.

We may also need to force disable FA4 when using a theme that uses FA5.

**Comment by marktaylor46** [comment] 2020-09-28 13:31
Couldn't we have Fontawesome version selectable on "page settings" base outline (not overrideable by outline and have it default to FA4? To my mind you want to use one or the other and unlikely to want to use both?

Icon picker then just uses whichever version is active?

We need to make it backwards compatible so existing sites carry on working as they are.

Wouldn't that also make it easier to add FA6 (or whatever comes next) with an update in the future too?

Obviously any particles that has already selected icons would need to be updated and saved again if you changed FA version but that shouldn't be a surprise.

**Comment by thexmanxyz** [comment] 2020-09-28 17:10
@marktaylor46 It is actually already default to FA4. It would not be the common case to have FA4 on one outline and FA5 on another but this should not harm at all it just gives freedom as we support both but only one is actually loaded. It is already selectable on `page settings`.  Version selection is also already there.

All sites will keep working as we did not touch the FA4 as it is. But nonetheless we need to skip that pseudo-elements as they are unsupported. A switch to a higher version can be easily done already as we have a FA dashboard. So I assume you simply did not check #2550. 

> Obviously any particles that has already selected icons would need to be updated and saved again if you changed FA version but that shouldn't be a surprise.

That is completely wrong. Therefore we have the FA4 shims. When there is a old class name stored it will be still working as that is the purpose of the shiming.

**Comment by marktaylor46** [comment] 2020-09-28 17:58
I haven’t checked anything I was just asking questions and expressing views in response to @mahagr comments. I personally wouldn’t want to see the two versions in play at the same time. I haven’t looked how it works but what about inheriting particles that use fa4 on one outline and use fa5 on another outline. Anyway I was just expressing views so you can just ignore everything I said.

**Comment by mahagr** [comment] 2020-09-29 08:02
To be honest, we do need one place to set either FA4 or FA5 or we cannot show the right icon picker in the admin. Also, there needs to be a way in the theme to prevent using the wrong version of FA.

Remember that many of the SCSS files contain icons, but do that in character codes, which get broken when FA5 version changes.

**Comment by thexmanxyz** [comment] 2020-09-30 07:09
@marktaylor46 Alright, didn't know that you not checked the PR. That's just fine I think my PR should answer all your questions concerning the current state. You are right actually we should really do that globally and NOT allow outline based changes because that might confuse users and lead to error states if you don't consider your version when creating outlines (but this only happens when you use FA5 icons, FA4 icons are not affected because of the shim). 

Don't want to ignore, sorry for the maybe harsh reply. 

@mahagr You are right with both things. Actually FA5 should always be loaded within Admin there should be only FA4 shim in backend for the icon picker. The correct solution might be to change the picker in dependence of the theme selected FA version if possible. The FA version should not be overridable per outline. 

TBH we should completely drop those pseudo-elements in CSS that is something that also template developers should consider and move towards because it isn't really supported with FA5 and it won't be in future releases. That is at least my information state.

**Comment by mahagr** [comment] 2020-10-06 08:45
I agree on dropping those pseudo-elements in CSS.

Additionally, it looks like there are some issues in Grav after this update.

**Comment by marktaylor46** [comment] 2020-10-06 11:32
I've now had an opportunity to look at this and it does seem to work quite well. But I still think that we really should not allow overrides by outline for the page settings > fontawesome settings. The reason for this is that a particle may be inherited from one outline to another and therefore it's possible that selecting "fab" icons for a particle would work on one page and not on another if the overrides were used. I really think it should be a global setting (only set in the base outline).

Regards, Mark.

**Comment by mahagr** [comment] 2020-10-07 07:06
Yes, we already talked about this and I agree. We shouldn't allow the setting to be overridden.

**Comment by fabio42170** [comment] 2021-03-14 10:08
Hello everyone !
Very recently, there was an update on Gantry (Helium) - version 5.4.37. After updating, I noticed something went wrong with the meny item icons. Some icons have been replaced by blinking excalamtive and question marks icons on some pages and not others.  This is a link to the problem encountered : [https://www.4u2learn.fr/joomla/forumkunena] 
Could it be linked to Gantry and the fact that they don't support the new Awesome Font 5 ?
Thanks for your answer !

**Comment by mahagr** [comment] 2021-03-15 08:52
It is likely caused by a clash between two versions of Font Awesome. Your site attempts to load both order and the new version at the same time.

**Comment by fabio42170** [comment] 2021-03-15 10:42
Hello !
Thanks for answering so quicly. Do you know if there are any parameters I should fiddle to get this resolved ?
Thanks in advance !

**Comment by fabio42170** [comment] 2021-03-16 13:57
Problem solved !
The "cultprit" was an item in the configuration of the Kunena Forum component in the template. Kunena's template crypsis loads external Awesomefont library and yes, that must be confilcting with the older library. So, just a tweak to get back to normal. 
[url=https://ibb.co/CBx2jvz][img]https://i.ibb.co/NxwS0ps/loadexternal.png[/img][/url]
Yet, it is a pity that Gantry does not support the new Awesomefont library ! When will that happen ?
Thanks again !

**Comment by N8Solutions** [comment] 2021-03-18 08:28
Not to throw a wrench in the works, but the Alpha release of FA6 is already available.
https://fontawesome.com/6

I think it would be a good idea to start thinking about integrating FA6 in to a future release of Gantry 5.

**Comment by fabio42170** [comment] 2021-03-18 14:27
I cannot bur agree with this. High time Gantry moved on away from deprecated libraries !

**Comment by mahagr** [comment] 2021-05-13 12:35
FA5 will be supported in Gantry 5.5

**Closed** 2021-05-14 08:57 UTC
Labels: enhancement, fixed

**Comment by lipatovroman** [comment] 2021-05-22 06:48
> FA5 will be supported in Gantry 5.5

Hello!
Is it possible to include in Gantry 5.5 full version of Font Awesome Free set?
A mean all 1,609 Icons.
And when Gantry 5.5 will be ready?
Thanks.

**Comment by mahagr** [comment] 2021-05-24 07:32
Looks like we currently have 1598 icons. Looks like a few were added since we did the update.

**Comment by lipatovroman** [comment] 2021-05-24 07:36
> since we did the update

You already released Gantry 5.5?
If yes, I don't see it in Joomla update section.

**Comment by mahagr** [comment] 2021-05-24 07:39
It has not been released yet. We're testing it and fixing the bugs that are being found.

**Comment by fseesink** [comment] 2021-06-12 19:24
Any update on this by any chance, as in any estimate when **Gantry 5.5** will be released?

I ran into the fact something as simple as the [Discord icon](https://fontawesome.com/v5.15/icons/discord?style=brands), using `fa fa-discord fa-fw`--similar to how the GitHub, Twitter, and LinkedIn icons are set--does NOT show on the site itself.  What is strange is that it DOES show when you set it up in the Social particle of the Base Outline.  So guessing that's somehow referencing things differently.

(Mind you, I have not tried doing any of the things mentioned in this thread like what @marktaylor46 suggested.  I've tried to use Grav with Gantry "as is" purely via the Web UI/Admin tool, mostly as I'd like to see how far someone could go without having to dig under the hood.)

Looks like all of this seems to fall back on that Gantry 5 has yet to support FontAwesome v5, which originally came out in early 2018 if I understand things correctly.  (And FA v6 is already in Beta to look at their site.)

**Comment by mahagr** [comment] 2021-06-14 08:35
@fseesink Please test the Gantry 5.5 build yourself (in a test site) and report back how it went. We are currently ironing out bugs and the more testing we can get, the faster the release will be out.

**Comment by fire2** [comment] 2022-02-23 08:53
I guess it's time to create a new issue to add support for Fontawesome 6, now that it's released?

**Comment by mahagr** [comment] 2022-02-28 07:33
Geez, let's hope it doesn't change the icons again.

**Comment by N8Solutions** [comment] 2022-02-28 08:24
> I guess it's time to create a new issue to add support for Fontawesome 6, now that it's released?

Glad you posted this. I had received their email a few days before you posted your comment and got busy and forgot to comment here.

**Comment by mahagr** [comment] 2022-02-28 08:27
Please just open a new issue. I would also appreciate if someone else had time to look into this.

**Comment by fire2** [comment] 2022-03-09 09:31
> Please just open a new issue. I would also appreciate if someone else had time to look into this.

Created #3016
