### ISSUE TITLE
Modal in the background

### ISSUE THREAD

**Issue by 810** [gantry/gantry5#35] opened 2015-03-31 20:59 UTC
the modal is not in the front:
![untitled](https://cloud.githubusercontent.com/assets/876623/6929244/94cae01c-d7f9-11e4-812c-777a670c261d.jpg)

**Comment by w00fz** [comment] 2015-03-31 21:01
Can you open the inspector and give us some hints on what element `zIndex` should be tweaked? Are both the overlay and the modal from bootstrap styles?

**Comment by 810** [comment] 2015-03-31 22:04
yes, it tried no luck:

````
<div class="modal fade in" id="statusTextModal" aria-hidden="false" style="display: block;" abp="124">
	<div class="modal-header" abp="125">
		<button class="close" role="presentation" type="button" abp="126" data-dismiss="modal">x</button>
		<h3 abp="127">Set Status Message</h3>
	</div>
	<div class="modal-body" abp="128">
		<p abp="129">Type your message below</p>
		<div class="control-group" abp="130">
			<div class="controls" abp="131">
				<textarea name="status_text" class="input-block-level" style="text-align: left; resize: none;" maxlength="255" rows="3" abp="132">test</textarea>
			</div>
		</div>
	</div>
	<div class="modal-footer" abp="133">
		<button class="btn" type="button" abp="134" data-dismiss="modal">
			Cancel		</button>
		<button class="btn btn-primary" onclick="Joomla.submitbutton('statusText-form ');" type="submit" abp="135">
			Submit		</button>
	</div>
</div>
````

and

````
<div class="modal-backdrop fade in"></div>
````

**Comment by w00fz** [comment] 2015-03-31 22:11
If you inspect the styles what are the zIndex values for the 2?
I checked and we aren't changing any zIndex at all for `.modal` or `.modal-backdrop`, they should come straight from bootstrap. `.modal` should be 1040 and `.modal-backdrop` should be 1050.

**Comment by 810** [comment] 2015-04-01 07:49
.modal-backdrop = 1040
.layout#kunena .modal = 2000
div.modal = 1050

**Comment by w00fz** [comment] 2015-04-02 17:32
I am not sure here, I don't think any of this is caused by Gantry nucleus/hydrogen. Do you have any idea what's causing that?

**Comment by w00fz** [comment] 2015-04-17 22:36
Is this still an issue? Did you sort it out? 

I'm going to close the issue but feel free to reopen if needed.

**Closed by w00fz** 2015-04-17 22:36 UTC
Labels: question
