### ISSUE TITLE
Loading slow and white screen issues

### ISSUE THREAD

**Issue by Calexander39** [gantry/gantry5#1353] opened 2016-06-10 05:03 UTC
My website is loading very slow, getting white screens from time to time when navigating to other pages and error messages. I have had Gantry since 2014 now and despite what I try nothing is working.

Please Help!

**Comment by mahagr** [comment] 2016-06-10 06:09
I'm assuming you are using Joomla. Usually if Gantry is slow and the rest of the site is fast, the issue is in the settings. First take a look into `System - Gantry 5` plugin and check that all the selections are set to `yes` (or green) except for `Asset Timestamps`.

PS: Ping me in Gitter chat (https://gitter.im/gantry/gantry5) and I'll take a look into your site.

**Comment by Calexander39** [comment] 2016-06-11 04:23
Thank you for responding. First I would like to mention that I am very new to joomla and still in the learning stages. I would be very grateful if you were to take a deeper look into this issue.

**Comment by mahagr** [comment] 2016-06-13 08:39
Like I said, I can take a quick look if you contact me on gitter chat.

**Comment by mahagr** [comment] 2016-06-14 09:15
The site is in Gantry4, closing this issue as the tracker is for Gantry5. I'll continue discussion in gitter chat.

**Closed by mahagr** 2016-06-14 09:15 UTC
Labels: question
