### ISSUE TITLE
Fontawesome Pro: How to add new field type or update `input.icon`

### ISSUE THREAD

**Issue by paolavness** [gantry/gantry5#2284] opened 2018-04-25 21:37 UTC
Hi there,

When editing particles (via the Grav Gantry admin interface) that include a `type: input.icon`, I would like the icon options to include the Fontawesome 5 options for `fas`, `far` and `fal` - the solid, regular and light versions.

Where/how I can I update the field type `input.icon` or add a new particle field types  to enable access to the complete FontAwesome 5 set?

Thank you.

== Edit ==
Realized particles are a Gantry thing, rather than a Grav thing - edited the question & title to reflect this.

**Comment by mahagr** [comment] 2019-10-02 11:39
Duplicate of #2196

**Closed by mahagr** 2019-10-02 11:39 UTC
Labels: question

**Comment by thexmanxyz** [comment] 2019-10-02 12:50
@mahagr @paolavness At least a pointer or hint on how to create own field types would also be highly appreciated by me. As I'm aware of anything like that can be found in the docs. A simple link to an issue describing briefly on how to this would be great as the thread starter also asked on how to do this!

**Comment by mahagr** [comment] 2019-10-03 07:19
Just take a look int Grav documentation (it should mostly apply) and look into `/platforms/common/templates/forms/fields`.

**Comment by thexmanxyz** [comment] 2019-10-04 17:07
@mahagr Thanks for pointing on the Grav docs and the respective Gantry repository path 👍
