### ISSUE TITLE
Clicking on "+" or gear icon for Section in layout view on iOS device fails

### ISSUE THREAD

**Issue by charleshowell** [gantry/gantry5#1028] opened 2015-11-24 22:07 UTC
I'm on an iPad Air 2 running iOS 9.1. My version of Gantry is 5.2.3 and I am on Joomla 3.4.5.

In either Safari or Chrome, if I go to the layout manager and press on the "+" or Gear icon for a Section, the callout appears but nothing else happens - even with repeated presses - effectively making it impossible to add a new row in a section, or to view/edit the setting for the section.

**Comment by w00fz** [comment] 2015-11-25 05:49
Hi Charles,
I don't have an iPad but I tried with the OS X Simulator, iPad Air 2 with iOS 9.1 and I actually couldn't reproduce the issue, I could add the new row. I am not sure if this is a Simulator vs real device issue, it is mostly always accurate.

I am wondering, is your Section already displaying an empty row? That is the only case I can think of  where a new row wouldn't be added (case 1 vs case 2 in the screenshot below). Empty rows are never stored so unless you fill an empty row first, you cannot add a new one right away.

![ios 9 1 13b137 2015-11-24 21-44-08](https://cloud.githubusercontent.com/assets/11734/11389406/37a34502-92f5-11e5-9cc3-ecb09b7a9fe4.png)

**Comment by charleshowell** [comment] 2015-11-25 17:25
I've tried it on my iPhone 6 Plus and a 4th Generation iPad, all running iOS 9.1 and the behavior is the same. 

There isn't already a row. I do know what you mean about that. I couldn't create a new row if my mom's life depended on it with an iOS device right now. 

I just click (well, press) on the "+" sign, the fallout box appears above and to the left of the icon, but no new row appears. If I press on it repeatedly, or long press on it, nothing happens.

**Comment by charleshowell** [comment] 2015-11-25 17:27
Callout box, not fallout box, that is...

**Comment by w00fz** [comment] 2015-11-25 19:49
I tried with my iPhone 6 and I could add a row.

Things I can think of are some other JS in the page conflicting with Gantry. Have you tried with a fresh and clean Joomla instance with only Gantry + Hydrogen, to see if you can still replicate this?

Please note that I am not doubting you see the issue, I am just unsure what would be causing it only on your end, perhaps you can ping me in Gitter with site and user details so I can take a closer look and see if I can replicate it there?

**Comment by w00fz** [comment] 2015-12-14 00:08
Any updates on this? I am still not able to reproduce the issue and if this is still a problem for you I would like to be able to test this on your site, to see if I can find a fix for it or, at least, the cause.

**Comment by charleshowell** [comment] 2015-12-14 18:39
Hey, w00fz. Thanks for the follow up. The issue still remains. I have updated my iOS devices (iPad 4th gen, iPad Air 2 and iPhone 6+) to iOS 9.2 since we last spoke. But, in Chrome and Safari the behavior is the same. I can't click on the plus or gear icon in a section. That is to say, I can click (well, press) on each of them and get a small black callout. But, repeated presses do not result in adding a row or opening the settings window. I would be more than happy to activate the login that I created for support folks. It's a SU account, or course. How can I get the login detail to you in a secure way? p.s. Thanks for your willingness to take a look at it!

**Comment by mahagr** [comment] 2015-12-15 11:17
You can join our Gitter chat https://gitter.im/gantry/gantry5 and send private message to @w00fz . I do not own any iOS devices, so I cannot help much here.

**Comment by mahagr** [comment] 2016-04-13 17:08
This may have been fixed in the upcoming version (5.2.14) as we had similar issue on all touch devices. If it is still an issue after the release, please comment on this issue.

**Closed by mahagr** 2016-04-13 17:08 UTC
Labels: question

**Comment by mahagr** [comment] 2016-04-13 17:10
Duplicate of #1218?
