### ISSUE TITLE
Particles in module positions

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#75] opened 2015-04-08 15:12 UTC
Page content particle can be placed everywhere but is not too useful this way, there's no reason to limit    its positioning too. 

It is possible to add some filters ? 

Example:  I place page content particle on main section and chose to display only articles from category 1. Then i will place a second page content on Subfeature section and chose to display articles from category 2. And so on, there will be many things you can do, will be a powerful tool.

Or select to display only featured articles, you know.... things like this :stuck_out_tongue_winking_eye:

**Comment by w00fz** [comment] 2015-04-09 06:33
That would be very cool to have. Probably VERY platform specific and definitely not easy!

@mahagr this is yours :)

**Comment by mahagr** [comment] 2015-04-09 07:01
Not much I can tell more at this point. I had this discussion also in Gitter chat yesterday and basically I said there that right now we aren't trying to replace Joomla.

Instead I'm going to take a look if we can implement particles as a module, where you can select your particle as well as configure it. That will give you the power of modules in a platform specific way.

**Comment by JoomFX** [comment] 2015-04-09 08:23
*Instead I'm going to take a look if we can implement particles as a module, where you can select your particle as well as configure it. That will give you the power of modules in a platform specific way.*

That would be really, really, really awesome @mahagr :)

**Comment by adi8i** [comment] 2015-04-09 09:06
Will not replace Joomla, because will still use joomla com_content, layouts to display items etc.

But if i think better, this can be done with joomla article_category module, latest, most read ... just need an overlay or some css

**Comment by mahagr** [comment] 2015-04-10 07:23
I'm going to reopen this to keep me reminded that I really should look into this.

**Comment by adi8i** [comment] 2015-04-22 17:07
I don't think the tile is too relevant, my suggestion was about filtering page content (joomla articles)

**Comment by adi8i** [comment] 2015-04-22 18:36
If i think better, what i've said first time is pretty hard to achieve and pretty confusing also, because page content, will take page settings, so if page Home is set to load category 1 and don't display featured articles, page content will do just that, so it will look more like Joomla's "Articles - Category" Module, but with more functionality and aesthetics. :)

**Comment by mahagr** [comment] 2015-05-23 08:54
Module part is duplicate of #163.

What comes to Joomla content, we have currently no plans on replacing component and module output with our own. I'm closing the issue.

**Closed by mahagr** 2015-05-23 08:54 UTC
Labels: question
