### ISSUE TITLE
Gantry5 problem in Chrome

### ISSUE THREAD

**Issue by webstersen** [gantry/gantry5#2231] opened 2018-01-31 10:43 UTC
Hello
I have an administrator issue on all my gantry5 pages when I use Chrome:

Failed to load resource: the server responded - media / gantry5 / assets / fonts / fontawesome-webfont.woff2? V = 4.7.0 with a status of 403 () ...

I use Akeeba admintools for my web pages.
In Opera, the problem does not occur.
I've been using Gantry for some years, but have not met this problem before.

**Comment by mahagr** [comment] 2018-02-01 12:26
I'm not able to reproduce this locally, does it happen on just one site/server or multiple ones?

**Comment by webstersen** [comment] 2018-02-02 08:39
It happens on 3 different servers and 8 websites with gantry and only when I use Chrome.
I use Akeeba admintools who also respond to the error.

null:null@taarupfors…at=json&navbar=true Failed to load resource: the server responded with a status of 401 ()
null:null@taarupfors…89ba0=1&format=json Failed to load resource: the server responded with a status of 401 ()
Roboto-Bold-webfont.woff2 Failed to load resource: the server responded with a status of 401 ()
Roboto-Bold-webfont.woff Failed to load resource: the server responded with a status of 401 ()
Roboto-Bold-webfont.ttf Failed to load resource: the server responded with a status of 401 ()
null:null@taarupfors…at=json&navbar=true Failed to load resource: the server responded with a status of 401 ()
null:null@taarupfors…89ba0=1&format=json Failed to load resource: the server responded with a status of 401 ()

**Comment by mahagr** [comment] 2018-02-16 08:17
@webstersen Have you password protected some of the directories in Apache as  `401 Unauthorized` means that you haven't logged in?

**Comment by webstersen** [comment] 2018-02-20 16:19
Have seen that others have the same problem.
Sending link, which describes better than I can do.

https://www.akeebabackup.com/support/admin-tools/Ticket/29100-401-unauthorized-password-protect-administrator.html

**Comment by twdjo** [comment] 2018-02-20 18:00
I am experiencing the same issue in Chrome (64.0.3282.167). I have password protected the /administrator folder on my site using Directory Privacy in cPanel. This has been in effect for more than a year (with Gantry 5) without issue.

When I log in to the site's admin panel I enter the credentials and I can navigate/edit the rest of the site with no issue until I try to edit the Gantry 5 template. 

I can get to Components > Gantry 5 Themes > Default Theme and the Styles tab displays.

When I try to navigate to any other tab or link, I start getting the 401 Unauthorized overlay screen.

In addition, here are the console errors displayed in Chrome:
GET https://null:null@mydomainname.com/administrator/index.php?option=com_gantry5&view=configurations/default/layout&theme=it_headlines&f423182d9b9277e2f4ffc2766b7a7c0e=1&format=json&navbar=true 401 ()

GET https://null:null@mydomainname.com/administrator/index.php?option=com_gantry5&view=configurations/default/styles&theme=it_headlines&f423182d9b9277e2f4ffc2766b7a7c0e=1&format=json 401 ()

I have tested this in Firefox (58.0.2) and the issue is not present.

**Comment by mahagr** [comment] 2018-02-24 23:47
it's trying to log in as null using password null. That is clearly wrong. Gantry only uses relative urls in Joomla, which means that something else must be causing the issue in my opinion.

**Comment by webstersen** [comment] 2018-02-26 07:03
https://www.akeebabackup.com/support/admin-tools/Ticket/29100-401-unauthorized-password-protect-administrator.html

**Comment by WebAtelier47** [comment] 2018-02-28 10:22
Hello, i have the exactly same problem.

**Comment by WebAtelier47** [comment] 2018-03-02 12:14
I have this error https://i.imgur.com/LrP2rtL.jpg and in console https://i.imgur.com/JKZ5Qgc.jpg

**Comment by marktaylor46** [comment] 2018-03-02 12:53
https://bugs.chromium.org/p/chromium/issues/detail?id=808018

It's a Chrome Bug.


Regards, Mark.

**Comment by WebAtelier47** [comment] 2018-03-02 12:56
Hum OK thanks.

**Comment by webstersen** [comment] 2018-03-02 13:37
I also have exactly the same problem in Opera

**Comment by WebAtelier47** [comment] 2018-03-02 13:40
Perhaps opera use chromium like chrome...

**Comment by marktaylor46** [comment] 2018-03-02 13:46
Yes it does.... Opera uses Chromium

**Comment by twdjo** [comment] 2018-03-05 14:21
I can confirm this issue is resolved in Version 65.0.3325.106 (Official Build) beta (64-bit).

**Closed** 2018-04-16 15:16 UTC
Labels: more infos needed
