### ISSUE TITLE
Kraken refuses to show the update for 5.2.14

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#1241] opened 2016-04-16 22:57 UTC
Running J351 and Kraken 1.1.1 with Gantry 5.2.13 I see the purple update notice in an Outline. I click update and go to the Joomla Update screen. No matter how many times I clear cache and then Find update 5.2.14 is never found.

Had to install manually. Funny as I didn't have an issue with other templates.

**Comment by JoomFX** [comment] 2016-04-17 13:47
I'm not sure if it is the same issue, but I have a very similar problem...

The issue I have is not G5 related, it is somehow a Joomla/browser issue. Here are the symptoms:

1. When you login to the Joomla back-end (with Firefox), everything is reported as up-to-date.
2. Then if you go under Extensions -> Manage -> Update Sites you see a very wrong and unexpected view - [here it is](http://i.imgur.com/anf8mkI.png). 
3. If you do the above steps in Chrome for example, everything's fine - the update is being reported in Joomla back-end and Update Sites shows the correct view (with all update URLs of the installed extensions).

I've seen the above issue before with different parts of the Joomla Admin - it behaves differently in the different browsers. I've tried clearing browser cache and cookies but it didn't fixed it. Then after some time, everything starts working normally (in Firefox as well).

It is a really weird issue that I couldn't narrow down.
@DanGthatRokGallery I'm interested if the issue you experience is actually the same (not G5 related). Can you check how your "Update Sites" looks and also try with another browser.

**Comment by JoomFX** [comment] 2016-04-17 13:55
UPDATE: There is actually more to it. Have a look at the screenshot a put above (from "Update Sites). If you click on the "Clear" button, then all extensions are shown again, as they should.
Then if you go under "Update", no updates will be reported - see [this screenshot](http://i.imgur.com/JINSFfF.png). But then if you click on the "Clear" button there, the Gantry5 update will be shown - see [this screenshot](http://i.imgur.com/5zqUX0i.png).

It's a really weird and annoying issue :wink:

**Comment by DanGthatRokGallery** [comment] 2016-04-17 23:13
Just a note for the Devs another user in the Forums is having this issue.

**Comment by w00fz** [comment] 2016-04-17 23:18
Are we sure this is Gantry's issue and not joomla or the RL database of kraken? Seems weird since we just hook into the joomla update system and provide a link to look at.

**Comment by mahagr** [comment] 2016-04-18 05:42
Yeah, Gantry isn't handling Joomla updates -- we just read their database and show the notification in our end. Everything that happens outside of Gantry is Joomla's fault.

BTW, I did have similar issue when testing the update, but in my case clearing cache made the updates visible, then going to another screen and back -- it was empty again.

**Comment by nicutor** [comment] 2016-04-18 07:33
Hi guys,

I have the same issue with updating some of my templates.

I was able to see the new gantry framework update, but not the my templates updates. The joomla updates cannot find my gantry templates updates at all. I didn't tried with other joomla extensions because I have none or/and none of others don't have any update yet.

It may be because of last joomla update. I have no clue, but I want just to report this issue too.

**Comment by w00fz** [comment] 2016-04-21 02:59
Please let us know if you see this behavior happening for other extensions too, so that we can at least understand if could potentially be Gantry related or just Joomla.

**Comment by nicutor** [comment] 2016-04-29 17:07
@w00fz I've did this to another website. Upgrading to joomla 3.5.1 and to gantry 5.2.15 and all other modules, languages has detected for the new updates, but not the gantry template one. Don't know what to say. You should install a gantry template and generate couple of updates to test it..

**Comment by nicutor** [comment] 2016-05-17 13:38
Hi guys,

The last gantry update was detected again but my templates update not. 
After a short research I've figure it out where the problem is.

My Extension update XML had this:

<targetplatform name="joomla" version="3.4"/>

and after update of joomla to 3.5 none of my template updates was detected.

The fix it to put 

<targetplatform name="joomla" version="3.5"/>

or according to https://docs.joomla.org/Deploying_an_Update_Server you can add an all Joomla versions update with:

<targetplatform name="joomla" version=".*"/>

Now everything is fine. I think you can close this issue.

**Comment by mahagr** [comment] 2016-05-17 13:50
Looks like we already have updates

    <targetplatform name="joomla" version="3.[45]"/>

**Closed by mahagr** 2016-05-17 13:50 UTC
Labels: invalid, joomla
