### ISSUE TITLE
Side menu dropdowns not opening after update to G5.2.16

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1293] opened 2016-05-18 11:15 UTC
This appears to be an issue with G5.2.16 update and Kraken template. After updating to G5.2.16 the side menu dropdown no longer open. Reinstalling G5.2.15 fixes the issue.

I have confirmed this on a local Kraken rocketlauncher installation too.

**Comment by kat05** [comment] 2016-05-18 11:24
I can confirm that the menu behavior has changed with Gantry 5.2.16.

Previously, just hovering on the parent item, would open the menu flyout, hovering away would close it again. Now, you need to click on the parent to open the flyout and hovering away does leaves the flyout just open.

**Comment by marktaylor46** [comment] 2016-05-18 12:27
It would appear that the "sidemenu" particle does not have the new field "expand on hover" that was added to the standard "menu" particle in G5.2.16 - this seems the likely cause of the issue.

**Comment by w00fz** [comment] 2016-05-18 15:22
Hover should be the default behavior, if this is not working something else is going on with the default behavior in gantry or with the side menu particle.

**Comment by kevinmorrison** [comment] 2016-05-18 16:22
Does something need to be changed then in the particle to work with G5.2.16?

**Comment by mahagr** [comment] 2016-05-18 16:31
@hexplor @newkind Can you take a look on this if its something that's wrong in the particle.

**Comment by marktaylor46** [comment] 2016-05-19 13:01
Another member reports the same here http://www.rockettheme.com/forum/joomla-template-kraken/258985-flyout-menus-stopped-working?start=0#1293267

**Closed** 2016-05-19 17:53 UTC
Labels: bug

**Comment by w00fz** [comment] 2016-05-19 17:57
I fixed the default behavior for menus who don't implement the new click/hover system. So now it will be automatically default to hover as it always been.

However, this doesn't quite solve Kraken issue, meaning that you will only ever be able to use hover and never clicks, because the side menu itself just doesn't implement the new system and it will require changes in the particle. Although this is going to be a template matter at this point and not Gantry related anymore.

/cc @hexplor
