### ISSUE TITLE
GRAV - The menu selected is empty!

### ISSUE THREAD

**Issue by marcodeluca** [gantry/gantry5#2572] opened 2019-12-02 21:19 UTC
I see a bunch of similar issues from a few years ago, none of them helped though. Latest update to Grav v1.7.0-rc.1 - Admin v1.10.0-rc.1 shows an empty mainmenu when the menu is not, in fact, empty:)
<img width="1282" alt="Screen Shot 2019-12-02 at 4 17 37 PM" src="https://user-images.githubusercontent.com/968926/69996175-83586800-151f-11ea-811b-00c03e942e70.png">

**Comment by thexmanxyz** [comment] 2019-12-05 07:14
@marcodeluca Please open an issue in the Grav repository. This is the Gantry repo!

**Comment by mahagr** [comment] 2019-12-06 14:32
Duplicate of #2557 

Already fixed in `https://github.com/gantry/gantry5/commit/6b67d56febb71479a599a6667ec3a62c12e4aa28`

**Closed by mahagr** 2019-12-06 14:32 UTC
Labels: duplicate, grav
