### ISSUE TITLE
Possibility to choose a menu item or article instead of chasing down link (URL picker)

### ISSUE THREAD

**Issue by NeonTigerWeb** [gantry/gantry5#1073] opened 2015-12-18 09:03 UTC
where ever you choose an URL in a particle, can we have the option to choose a menu item or article rather than having to chase down the URL to enter in to the box? 

so operationally it would be similar to the way JCE does it

This would be extremely useful as occasionally URLs change, but the index.php/.... link which JCE stores _shouldn't_ change even if the text on the menu item does change

**Comment by w00fz** [comment] 2015-12-18 18:28
This is duplicate of #356

**Closed** 2015-12-18 18:28 UTC
Labels: duplicate, feature, joomla
