### ISSUE TITLE
Gantry Grav helium skeletons 5.4.3 doesn't work at all

### ISSUE THREAD

**Issue by cogito-eje** [gantry/gantry5#1796] opened 2017-01-14 15:07 UTC
Gantry Grav helium skeletons 5.4.3 doesn't work at all :

E_COMPILE_ERROR - Cannot use Grav\Common\Page\Page as Page because the name is already in use

**Comment by Quy** [comment] 2017-01-14 16:35
Duplicate of #1792.

**Closed** 2017-01-14 17:27 UTC
Labels: duplicate, grav
