### ISSUE TITLE
Unable to edit layout in Gantry and PHP 8.0 and 8.1

### ISSUE THREAD

**Issue by perronalain** [gantry/gantry5#3027] opened 2022-04-13 14:03 UTC
In rocketTheme after a question, i receive an answer saying that Gantry 5.5.12 is compatible with php 8.0 and php 8.1
On my host (Rochen) I install gantry last version and Rt_Zenith . I cannot edit any layout , an horizontal dialog appears without any information and without any error message. I do not understand why. 
I test this behavior on the save host with browsers (Safari, Firefox, Google Chrome) on my Imac and Macbook Air . Also with google chrome on PC with 8.1 system. All these browsers gave me the same display, an horizontal dialog without any other information. 
I also tested with other templates from rocketTheme. I use joomla 4.1.2 and PHP 8.10.7 the version available on Rochen. 
When I return to php 7.4 all works fine. 
The screen image joined was with another template but the same behavior appears with all templates based on Gantry last version. 
Can you help me where I can search for this problem ? Options in php 8 or other information for that. 

Thank you in advance for your precious help.
![PHP 8](https://user-images.githubusercontent.com/50833917/163197993-3d97751a-adc6-4e71-bd84-e644ef7dd9fd.jpg)

**Comment by marktaylor46** [comment] 2022-04-13 14:46
There's no ned to post here at all - I was trying to help you in the RT forum https://rockettheme.com/forum/gantry5-for-joomla/288197-gantry-5-5-12-and-php-8-0-or-8-1-1

This will be a configuration matter and not a bug in Gantry 5.

Regards, Mark.

**Comment by mahagr** [comment] 2022-04-13 14:54
Agreed that it's not a bug as I don't use PHP 7 anymore. However, there's a bug in PHP 8.0.17 and 8.1.4, which breaks JSON responses in Gantry if you're running Joomla gzip compression turned on.

**Comment by mahagr** [comment] 2022-04-25 05:48
I think the issue has been fixed in PHP 8.0.18 and 8.1.5 as I cannot reproduce the issue with zip on.

**Closed** 2022-04-25 06:10 UTC
