### ISSUE TITLE
Wordpress "widget" particle does not work

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2407] opened 2018-11-01 14:40 UTC
My understanding is that the "widget" particle in Wordpress Gantry 5 is supposed to be the equivalent of the "module instance" particle in Joomla Gantry 5. If I am correct then the "widget" particle does not work at all.

The "widget" particle allows you to choose a particle type but that's as far as it goes. You cannot make any settings for the chosen particle and nor do you get any opportunity to select an existing widget.

Furthermore, in some RT templates there is a "popupwidget" particle - again this does not work at all since it exhibits exactly the same behaviour as the "widget" particle.

So I believe both of these particle are fundamentally broken.

**Comment by kuse-de** [comment] 2018-11-04 02:34
The Widget Particle creates a Widget Area u can find it in Design -> Widgets.

**Comment by newkind** [comment] 2018-11-04 09:45
@kuse-de the Widget Position particle creates a position in Appearance -> Widgets

@marktaylor46 yah, that Widget particle is what Module Instance is in Joomla. It works fine for me. Here's a video for how it works for me : https://monosnap.com/file/WjWDST99BNXSz4XaSvlMlpotcJiqKP

All works fine for me.

*HOWEVER* there is an issue with new widget types like "Image" or "Video" widgets where the options for those widgets don't appear in G5. This is a known issue as those widgets. They are the new type of widgets and Gantry hasn't been modified to hijack their options yet. There's a separate issue about this #2023

**Comment by marktaylor46** [comment] 2018-11-04 09:55
Well I guess we have a different definition of "works" :) For me if something as basic as a "customHtml" widget does not even show the field to allow you to key in some html then I don't see how that can be counted as "works". 

Let's take you example of the calendar that "works" - no it doesn't because there is absolutely no where that you can enter "events" like you would if the "calendar" widget were placed directly on the layout. So the whole purpose of the widget in the first place is fundamentally undermined.

![2018-11-04_09-46-01](https://user-images.githubusercontent.com/11683218/47962581-cd1e0880-e016-11e8-9815-45345fe0637a.png)

![2018-11-04_09-46-41](https://user-images.githubusercontent.com/11683218/47962582-d27b5300-e016-11e8-89b4-8a5f6e28b561.png)

So, sorry but I don't see how can be called "works" by any definition - it does not. Any particles added via a widget particle are completely unconfigurable and therefore useless.

Yes, I see the reference to the other ticket, but it's not "new" widgets - it is every single widget added via a widget particle.

Personally I think this is a big deal and should be fixed ASAP (as your comment in that ticket in March 2018 acknowledges).

Regards, Mark.

**Comment by newkind** [comment] 2018-11-04 10:51
I don't think you exactly understand how it works. "Widget" particle allows you to place **WordPress Core** widgets using the Gantry 5 Layout Manager instead of using Widget Postions.

Calendar **CORE WordPress widget** doesn't have any extra options like "Events" : https://monosnap.com/direct/qhXO0ucUbeNOml7AqKCylzFLB3LKYL

Gantry 5 will only display the options that core widget will have (besides the new widget approach which needs to be fixed in the issue #2023). The Custom HTML is a new type of widget with rich-text-editor that is part of the issue #2023.

The functionallity itself works like it should, the missing fields fron new type of widget need to be fixed to appear in the G5 admin.

**Closed** 2018-11-04 11:14 UTC

**Comment by marktaylor46** [comment] 2018-11-04 13:35
Oh I see what you mean. You're saying that the "widget" particle is ONLY for adding CORE Wordpress Widgets and none of the Gantry 5 particles at all. So in other words the "widget" particle IS NOT the equivalent of Joomla "Module Instance" particle at all - it's something completely different - so this is where my misunderstanding originates.

Even still, yes, that other github ticket REALLY needs fixing.

Thanks for the explanations.

Regards, Mark.

**Comment by eduardogcorrea** [comment] 2019-04-07 22:47
> 
> 
> Oh I see what you mean. You're saying that the "widget" particle is ONLY for adding CORE Wordpress Widgets and none of the Gantry 5 particles at all. So in other words the "widget" particle IS NOT the equivalent of Joomla "Module Instance" particle at all - it's something completely different - so this is where my misunderstanding originates.
> 
> Even still, yes, that other github ticket REALLY needs fixing.
> 
> Thanks for the explanations.
> 
> Regards, Mark.

I agree with that... 
And I can´t edit the options for a "core widget". Example.. I can´t change de word "search" in searaching widget. So. This feature needs review.

**Comment by mahagr** [comment] 2019-04-08 10:09
@eduardogcorrea Please create a new issue describing the issue and an example of how to reproduce it (just in case).
