### ISSUE TITLE
Mobile Menu on Android/Firefox not working consistently

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#557] opened 2015-07-10 10:56 UTC
Further to #553 and conversations with @kat05 @mahagr 

It would appear that mobile menu on Adroid 4.1.2 in firefox 39 and Android 4.2.x does not work reliably. sometimes requiring multiples taps.

Collectively we feel that we should have another look at this to see if anything can be done.

This is forum link http://www.rockettheme.com/forum/joomla-template-callisto/244530-firefox-android-does-not-open-second-level-items-in-mobile-menu?start=0#1217081

**Comment by w00fz** [comment] 2015-07-11 00:18
I've been able to launch an emulator with Android 4.1.1 and Firefox 39 but the issue wasn't reproducible.
If anyone is able to reproduce the issue and perhaps contribute with a fix, it will be much appreciated, otherwise we just have no way of fixing it.

This is a video of the emulator running android 4.1.1 and Firefox 39.0, as you can see there is no issue with it: https://cloudup.com/cQ-rR4dO6N5

**Comment by mahagr** [comment] 2016-03-16 12:52
I've just tried this in my old android phone with FF 45.0 and it looks like that everything that is not a link always required double click where real links always needed one. So this must be a feature in Firefox itself because of it doesn't happen in my new phone (nor tablets) with exactly the same FF version.

Maybe Firefox has some detection on old devices (or different settings for old Android) which makes it to behave in a different way depending on which device you're using.

To me this looks like intentional behaviour and not a bug. Maybe FF is following some Android 4 rules or compensates on low res / insensivite touch trying to prevent users from mis-clicking.

Closing the issue.

**Closed by mahagr** 2016-03-16 12:52 UTC
Labels: help wanted
