### ISSUE TITLE
The same script loads multiple times when loaded from both "page_head.html.twig" and a particle

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#876] opened 2015-09-26 19:55 UTC
@w00fz @mahagr Hey guys,

I don't know if this is the expected behavior or not so I want to discuss it with you.

As you know, when you use `JHtml::_('jquery.framework');` or in Gantry5 the newly added `{{ joomla.html('jquery.framework') }}` it loads the jQuery assets only once, no matter how many times you have used this code.

Also, as far as I know, if you load the same script (from exactly the same location, with exactly the same syntax) from different places it should load the asset just once.

So, here's my scenario... I load a script and a stylesheet globally from the `page_head.html.twig` file. These assets bring some additional features so I will use them in all my templates. Here's the code I use in the `page_head.html.twig` file:

```
<link rel="stylesheet" href="{{ url('gantry-theme://css/mycss.min.css') }}" type="text/css"/>
<script src="{{ url('gantry-theme://js/myscript.min.js') }}" type="text/javascript"></script>
```

Now, I've built some nice particles that use the features from the above assets. And I want to release these particles for free. It means that these particles must work in all G5 Templates. In order to achieve this I need to load the above assets from the particle itself. Here's the code I use in the particle:

```
	{% assets in 'head' with { priority: 0 } %}
		<link rel="stylesheet" href="{{ url('gantry-theme://css/mycss.min.css') }}" type="text/css"/>
		<script type="text/javascript" src="{{ url('gantry-theme://js/myscript.min.js') }}"></script>
	{% endassets -%}
```

And here comes the strange thing. The stylesheet (`mycss.min.css`) is loaded just once, as expected, but the script (`myscript.min.js`) is loaded twice.

Is this the expected behavior? And can it be enhanced so if G5 detects that absolutely the same script is loaded more than once, it actually loads the asset only once?

A workaround is to maintain two versions of each particle - one that will come with my templates (nothing will be loaded from the particle) and another one that will be released for free (the assets will be loaded from the particle). But this is really not nice :smile: 

P.S. It is really strange that the stylesheet is loaded just once and the script is loaded twice.

**Comment by mahagr** [comment] 2015-09-28 08:35
Try to add multiple particles; js should only be added once by it (not x times). If this happens, you have likely the script in wrong place in your `page_head` or using wrong priority in your particle (try 10).

I believe that the issue is the later one as I'm not checking if the asset already exists on another priority. If that's true, this is a bug, though I'm not sure how it should be fixed and which priority should be used (highest?).

**Comment by JoomFX** [comment] 2015-09-28 09:32
@mahagr Thanks Matias.

I added another particle that loads the script and then I checked what is loaded in the `<head>` - there are two assets loaded (not three). Here's some more details:

#### Loading the script from `page_head.html.twig` and one particle
The script is loaded twice. This is the output in the `<head>`

```
<script type="text/javascript" src="/my_template/templates/g5_hydrogen/js/myscript.min.js">
<script type="text/javascript" src="/my_template/templates/g5_hydrogen/js/myscript.min.js">
```

#### Loading the script from `page_head.html.twig` and two particles
The script is still loaded twice (not three times). This is the output in the `<head>`

```
<script type="text/javascript" src="/my_template/templates/g5_hydrogen/js/myscript.min.js">
<script type="text/javascript" src="/my_template/templates/g5_hydrogen/js/myscript.min.js">
```

I also tried setting the priority in the Twig to both `10` and `-10` but it did not make any difference.

Regarding my `page_head.html.twig` file - I'm loading the script just before the closing `</head>` tag.

**Comment by mahagr** [comment] 2015-09-28 09:37
you cannot load the script outside of `head_platform` or `head_overrides`, so make sure you're either of those blocks. It shouldn't make any difference which one you use, so head_platform is safer. Both seem to use priority=10.

**Comment by JoomFX** [comment] 2015-09-28 10:04
Wonderful :smile: 

Putting the script inside `head_overrides` fixed the "issue".

But there is something strange that you might want to look at - putting the script inside `head_platform` does not load the script at all. I really prefer to have my scripts in `head_platform` rather than `head_overrides` but the following does not load the script at all:

```
    {% block head_platform %}
        <script src="{{ url('gantry-theme://js/myscript.min.js') }}" type="text/javascript"></script>
    {% endblock %}
```

Also, one additional question - if I want to load jQuery globally in the template, should I also put `{{ joomla.html('jquery.framework') }}` inside `head_overrides`? If I put it inside `head_overrides` it works, if I put it inside `page_platform` it doesn't.

**Comment by mahagr** [comment] 2015-09-28 11:17
Hmm, `head_platform` should work just fine -- otherwise your page would be unstyled. If neither of them works for you, I'm almost thinking you got the wrong file.

**Comment by JoomFX** [comment] 2015-09-28 11:22
No no Matias, can you please test it?
Can you try to load a script inside `head_platform`? By default, this block is empty in `page_head.html.twig`:

```
{% block head_platform %}{% endblock %}
```

You will see that the script will not be loaded.

Then move the script inside `head_overrides` and you will see that the script is loaded. Here is the default `head_overrides` block in `page_head.html.twig`:

```
    {% block head_overrides -%}
        {% for css in gantry.theme.configuration.css.overrides %}
            {%- set url = url(gantry.theme.css(css)) %}{% if url %}
            <link rel="stylesheet" href="{{ url(gantry.theme.css(css)) }}" type="text/css"/>
        {% endif %}
        {%- endfor %}
    {% endblock -%}
```

**Comment by mahagr** [comment] 2015-09-28 11:28
You're in wrong file, check out https://github.com/gantry/gantry5/blob/develop/engines/joomla/nucleus/twig/partials/page_head.html.twig#L10

Do not modify the general file but platform specific one.

**Comment by JoomFX** [comment] 2015-09-28 11:37
I'm really confused. Please bear with me Matias to clear this out.

@w00fz has always told us to modify `root/media/gantry5/engines/templates/page_head.html.twig` file. Always.

Now is the first time I hear that we are supposed to modify the platform specific file.

Also, there is no point to modify the platform specific file if I will convert this template to other platforms as well (WP and Grav).

Also, have a look at [this part of the Documentation](http://docs.gantry.org/gantry5/advanced/file-overrides#gantry-5-nucleus-engine-file). It is about `page.html.twig` but it is the same for `page_head.html.twig`.

**Comment by mahagr** [comment] 2015-09-28 11:40
The issue here is that currently platform specific one doesn't call parent() in here, which is something we may want to fix in the future; now that you said it, I do consider it as a "bug".

**Comment by JoomFX** [comment] 2015-09-28 11:42
Thanks :smile: 
So, should I continue working with the general (not platform specific) `page_head.html.twig` file as the Documentation says?

I really do not feel right to work with the platform specific one.

**Comment by mahagr** [comment] 2015-09-28 11:44
If you want the template to work with older versions of Gantry (looking into this now), the answer is you need to override the file in `/twig` directory. Otherwise you may want to wait me to close this issue.

**Comment by JoomFX** [comment] 2015-09-28 11:46
Ok, thanks :)

But the main issue is resolved (script loading multiple times). Cheer!

I learned something new and very important today ;)

**Closed** 2015-09-28 11:54 UTC
Labels: bug

**Comment by JoomFX** [comment] 2015-09-28 12:11
You are awesome, as usual :smile: 
Just tested it and now `head_platform` works in the general/independent `page_head.html.twig` file.
Thanks Matias!
