### ISSUE TITLE
WordPress - Menu editor refresh will reset dropdown selection

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#835] opened 2015-09-14 19:46 UTC
In my test install I have
- Empty Menu
- Long Menu
- Testing Menu

When first going to the Menu editor, the empty menu shows in the dropdown. I then switch to the Long menu for example and it will load all the menu items for the Long menu which is fine.

When I then refresh the page, the dropdown selection will default back to Empty Menu, but all the menu items from the Long menu will still show.

This is different in Joomla, where the selection in the dropdown after refreshing the page is the same as before refreshing.

**Comment by mahagr** [comment] 2015-09-14 19:56
I'm not able to reproduce the issue.

**Comment by w00fz** [comment] 2015-09-18 22:33
Closing as this wasn't reproducible anymore.

**Closed by w00fz** 2015-09-18 22:33 UTC
Labels: question, wordpress
