### ISSUE TITLE
Atoms not being inserted into site

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#330] opened 2015-05-21 14:10 UTC
Tried to create a new atom to insert the TypeKit javascript in the site.

Here's the code I used:

**The YAML**
```
name: Adobe Typekit
description: Configure Adobe Typekit.
type: atom

form:
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      description: Globally enable Typekit particles.
      default: false

    kit.id:
      type: input.text
      description: Enter the Adobe Typekit ID.
      label: Adobe Typekit
```
**The Twig**
```
{% extends '@nucleus/partials/particle.html.twig' %}

{% block javascript %}
  {{ parent() }}
  {% if particle.kit.id  %}
    <script src="//use.typekit.net/{{ particle.kit.id }}.js"></script>
    <script>try{Typekit.load();}catch(e){}</script>
  {% endif %}
{% endblock %}
```
The code generates the backend element without a problem.
![screen 20shot 20on 202015-05-21 20at 2016 3a05 3a27](https://cloud.githubusercontent.com/assets/1498512/7750241/5b8c8538-ffd3-11e4-966f-791e239c1939.png)

However no code is injected in the site on the front-end.

Tried to enable the Google Analytics atom to test.

Same issue, does not get inserted into the generated front-end code.

Also, would like to know where Javascript Atoms are injected? Are they inserted in the `<head>` element or at the end of the `<body>` element?

If they are injected at the end of the `<body>` element, is there a way to add a toggle or select box to allow the end-user to choose between `<body>` element and `<head>` element?

**Comment by mahagr** [comment] 2015-05-21 18:00
Atoms work just great for me, you just need to add them to the layout where you want to display it.

**Comment by w00fz** [comment] 2015-05-21 20:13
This was explained in the Gitter chat. An Atom needs to be drag and dropped into the Page Layout in the Atoms Section in order to display.

**Comment by JoomFX** [comment] 2015-05-21 20:22
@w00fz yes, but it needs to be drag and dropped on the Base Outline and at least on more (either Home or Default) in order to be rendered.

@mahagr said something but just to confirm - you will change that, right? I mean if you drag and drop the Google Analytics Atom only on the Home (and not on Base) it will still render? GA Atom is just an example, I know that everybody would want it on all pages ;)

P.S.   Custom CSS/JS Atom works as expected tho.

**Comment by w00fz** [comment] 2015-05-21 20:29
This is the way it works now and we know it's not ideal and it will be changed in the future.
The issue reported here was that Atoms stopped working which is not the case, it just needs to be added into the Atoms Section of the page.

**Comment by JoomFX** [comment] 2015-05-21 20:32
yep, thanks @w00fz 
just wanted to clarify this for myself

**Comment by mahagr** [comment] 2015-05-21 21:03
Inheriting parts of the layout from the base is a bit tricky and we need a good plan to do that in a way it doesn't get into your way.

The issue is that unless we restrict inheritance into section level (all or nothing), there's really no way to know what user wants to do.

**Comment by nzimas** [comment] 2015-07-30 23:46
I've added the atoms to the Atoms section in Hydrogen but not is being injected.
Neither GA's tracking code nor a custom inline JS are anywhere to be found.

Relevant screenshot:
https://www.dropbox.com/s/erlpdq22acep5j6/Screenshot%202015-07-31%2000.43.55.png?dl=0

**Comment by mahagr** [comment] 2015-08-03 10:53
Did you add atoms to all your outlines? There's issue for allowing us to inherit stuff from base outline, but it's not done yet, so the only way is to add it to everywhere.

**Comment by omikron** [comment] 2015-08-05 03:52
I am having this same issue, I have added the Atoms to the base outline layout as well as every single other outlines, but neither Google analytics or custom JS is getting injected.

**Comment by mahagr** [comment] 2015-08-05 08:44
Have you enabled those atoms from settings page?

**Comment by mahagr** [comment] 2015-08-05 08:52
I don't think that this fixes all the issues, but at least takes one obstacle away. I've enabled atoms in main configuration by default (for new installations) as it was one of the reasons people were confused.

**Comment by omikron** [comment] 2015-08-05 15:42
Yes, I have them enabled on all outlines.

**Comment by mahagr** [comment] 2015-08-06 07:48
@omikron Can you please check the latest CI build just in case if it's fixed. You can also contact me in gitter https://gitter.im/gantry/gantry5 as I'd like to check out your site.

**Comment by mahagr** [comment] 2015-08-27 12:36
Small status update on this one:

* Ability to set atom only in base outline has been assigned to 5.2.0 milestone (#340)
* There's a new and better way to assign CSS / JSS into the page:

    {% assets in 'head' with { priority: 1 } %}
        <script type="text/javascript" src="{{ url('gantry-theme://js/my.js') }}"></script>
        <link rel="stylesheet" href="{{ url('gantry-assets://css/font-awesome.min.css') }}" type="text/css"/>
    {% endassets -%}

You can also use ```{% scripts %}``` and ```{% styles %}```, they will take the same optional parameters. Possible locations are *head* and *footer*, priority can be any integer, though -10 ... 10 is what Gantry itself uses defaulting to 0.

**Comment by w00fz** [comment] 2015-10-09 23:33
With Page Settings feature (https://github.com/gantry/gantry5/tree/feature/page-settings) and the Generics block, this is now more elegant and easier to do.

**Closed** 2015-10-22 06:01 UTC
Labels: enhancement
