### ISSUE TITLE
Unclickable settings block in admin

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#2285] opened 2018-04-26 14:29 UTC
Inputs can't be clicked because of `backface-visibility: hidden`. 
Browser Google Chrome Version 66.0.3359.117 (Official Build) (64-bit)
Platforms: WordPress and Joomla

```
#g5-container .card {
    display: inline-block;
    background: #fff;
    border-radius: 3px;
    border: 1px solid #ddd;
    padding: 10px;
    min-width: 250px;
    vertical-align: top;
    margin: 10px 0;
    -webkit-backface-visibility: hidden;
    backface-visibility: hidden;
}
```

![capture](https://user-images.githubusercontent.com/9744973/39312098-530d7250-4977-11e8-857b-1ab17ddb2898.PNG)

**Comment by thexmanxyz** [comment] 2018-04-27 00:07
Possible duplicate #2262

**Comment by JoomFX** [comment] 2018-05-15 06:52
I can also confirm the issue.
Some fields are not clickable and there are some other visual issues when you "Collapse All". Have a look at this screenshot:

https://i.imgur.com/wFcvwVL.png

The issue is reproducible in Google Chrome and not in Firefox.

**Comment by marktaylor46** [comment] 2018-05-18 09:16
I can also confirm this issue in WP and Chrome - the "assignments" tab scrollbar for the "page" menu does not function at all in Chrome - it works in Firefox though.

![2018-05-18_10-12-42](https://user-images.githubusercontent.com/11683218/40226790-8e659d5a-5a84-11e8-907b-9950b72a6771.jpg)

**Comment by newkind** [comment] 2018-05-19 08:37
This is not a bug in Gantry. Our code is proper and works fine in all browsers but latest Chrome. It's a bug in Chrome and should be fixed in chrome. We can't do anything about it. I've tested latest Chrome Canary and it's mostly fixed there besides small visual artefacts with the toggles on the assignments page. You guys will have to wait for Chrome update or use Chrome Canary or any other good browser in the meantime ie. Firefox.

**Closed by newkind** 2018-05-19 08:37 UTC
Labels: wontfix
