### ISSUE TITLE
Active menu issue in multilang env

### ISSUE THREAD

**Issue by drnasin** [gantry/gantry5#2315] opened 2018-06-16 07:59 UTC
As per suggestion by Damir from RT I'm reporting this issue as a Gantry bug (http://www.rockettheme.com/forum/grav-theme-photon/276733-active-menu-issue-in-multilang-env)

Problem: I have 2 langs on my site. Everything works great except that on the main langugage the current active menu (and parent) will be highlighted but not on the other langugage.

Example - https://drnasin.com/spletne-strani/optimizacija - ok
(same page in croatian) https://drnasin.com/hr/web-stranice/optimizacija - no menu item highlighted

**Comment by N8Solutions** [comment] 2018-06-29 06:53
Hello @drnasin,
I'm wondering if this is specifically a Gantry 5 for Grav issue. I have 2 sites running Joomla!, one with Hydrogen and the other with Helium and neither of them have the issue you describe (I see it on your site as well).

**Comment by DamirPecnik** [comment] 2018-06-29 21:59
Its only Related to Grav.

**Comment by mahagr** [comment] 2018-07-04 11:56
@drnasin I am not able to reproduce the issue on my local site, so it would be nice if you could send me a copy of your site to matias at rockettheme.com.

**Comment by drnasin** [comment] 2018-07-04 12:11
@mahagr added you to my private repo if that's ok....content of user dir...

**Comment by mahagr** [comment] 2018-07-04 12:57
@drnasin I don't think i have access it, I'm just seeing 4 repositories and none of them look like Grav site.

**Comment by vangogs** [comment] 2018-08-15 18:53
I am confirming this problem. 
I think problem occurs when slug used for translated page doesn't match original slug / folder.

When I create translation page with the same page slug, it shows menu item active in both languages.

**Comment by drnasin** [comment] 2018-08-16 09:00
@vangogs I did send a zip with my site to @mahagr for debugging but haven't heard anything about it since then...

**Comment by mahagr** [comment] 2018-08-20 09:39
@drnasin I've not forgotten your zip, I've just been busy on elsewhere and haven't yet had a chance to look into this.

@vangogs Your fix looks good, except that it becomes really slow when you have a larger site with a lot of menu items. I guess it would be good, though, if only we cached the active menu item.

I've been working on Page class replacement which would fix this issue for good, but it still needs plenty of work so it's not a short-term solution.

**Comment by mahagr** [comment] 2018-08-20 10:02
Unfortunately the proposal from @vangogs doesn't work with @drnasin 's site.

**Comment by mahagr** [comment] 2018-08-20 10:13
Should be fixed now in latest CI.

**Closed by mahagr** 2018-08-20 10:13 UTC
Labels: bug, grav
