### ISSUE TITLE
3 collumn layout - width of center column

### ISSUE THREAD

**Issue by japre** [gantry/gantry5#366] opened 2015-05-27 11:47 UTC
If I use the 3 column layout in Hydrogen template, the main body doesnt fit between columns... you can see the problem here http://joomla3.gymnachod.cz/index.php/cz/o-skole/kde-nas-najdete.

**Comment by nicutor** [comment] 2015-05-27 12:16
The resolution is here: #354

**Comment by JoomFX** [comment] 2015-05-27 12:18
@nicutor it is a workaround, not a solution.

**Comment by nicutor** [comment] 2015-05-27 12:21
@JoomFX , yes. agree.

**Comment by w00fz** [comment] 2015-05-27 18:54
Duplicate of #354

**Closed by w00fz** 2015-05-27 18:54 UTC
Labels: bug
