### ISSUE TITLE
Assignments Menu assignments not working

### ISSUE THREAD

**Issue by bcordis** [gantry/gantry5#1932] opened 2017-03-15 13:40 UTC
Helium will show it has made a menu item it's template assignment but will not reflect on the site side.

Have tested on multiple systems.

Database Version	5.7.10-log
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.15-0ubuntu0.16.04.4
Web Server	Apache
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by mahagr** [comment] 2017-03-20 08:32
Many Joomla extensions break the template assignment in Joomla: Look for badly behaving system plugins and components with badly written routers (disabling those extensions one by one should lead you to the problem).

The issue is usually in calling some functions too early before Joomla has been properly initialized itself. The issue also got a lot worse lately with some changes in Joomla router code.

**Comment by bcordis** [comment] 2017-03-20 15:15
I'm trying this on a fresh install of Joomla with limited menu creation and the error persists.

Only the core templates will assign on the menu.

**Comment by Bonitto** [comment] 2017-03-22 05:05
I also am having similar issues and I am not sure why but when I assign a layout to my homepage it is not correctly set, even though it's showing up as assigned.

**Comment by senaiboy** [comment] 2017-03-23 18:00
Encountered the same issue with Helium template on Gantry 5. Setting template style via the Menus: Edit Item or Assignments Menu Assignments does not change anything.

Every page still takes on the default template style. Seems to be a recent thing as we've not noticed it before?

**Comment by mbogart24** [comment] 2017-03-24 04:28
I have found the problems start going from Joomla 3.6.2 to a newer version.
with 3.6.4 or higher the assignments quit working.
I reinstall 3.6.2 and it works again.

**Comment by bcordis** [comment] 2017-03-24 12:25
Anyone know how to fix the error? I'm trying to see what library is making the error?

**Comment by mahagr** [comment] 2017-04-03 06:34
Like I said, the issue is neither in Joomla or Gantry. It is usually in a badly written component router, which does stuff too early and breaks Joomla. Another possibility is badly written system plugin. 

You can verify this by changing template assignment for a menu item to Protostar -- it will not work either. The error can only be fixed by either uninstalling the offending component or system plugin or updating it to the latest (fixed) version.

**Comment by bcordis** [comment] 2017-04-03 11:18
I have set a menu item to Protostar and it worked. But if I try any other menu item to this template it will not change.

This was a new install of Joomla. And on a existing install I have reproduced it.

**Comment by senaiboy** [comment] 2017-04-03 11:23
We solved our issue, it's due to a faulty joomla plugin as mahagr stated.

Try turning off all joomla plugins and see if the issue persists.

**Comment by bcordis** [comment] 2017-04-03 11:39
I'll try the some and see where it is. Wish there was better debug on plugins.

**Closed** 2017-04-26 09:07 UTC
Labels: joomla, question

**Comment by akcreation** [comment] 2018-09-28 10:27
Just thought I would add my solution to this. I purchased and installed 'Advanced Module Manager' by Regular Labs and it fixed all the issues I was having with assigning modules to my menu items :)
