### ISSUE TITLE
Menu editor enhancement

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#228] opened 2015-05-12 06:41 UTC
With reference to https://github.com/gantry/gantry5/issues/223#issuecomment-101077342
something like the following in "Menu" can be challenging for @mahagr?
1- Create a drop-down of n-columns
2- Let G5 assign 180px (default) width to each column (instead of 100/n% in full-width)
3- Let the column slider change the column width values in px

**Comment by mahagr** [comment] 2015-05-12 06:44
Not really my area, @kevlardev might be better one to answer on this. :)

**Comment by w00fz** [comment] 2015-05-14 22:44
I think this is a duplicate of #223 ?

**Closed** 2015-05-15 19:01 UTC
Labels: question
