### ISSUE TITLE
Can't manage default theme on Joomla 4

### ISSUE THREAD

**Issue by WolfgangDomroese** [gantry/gantry5#2934] opened 2021-11-05 13:59 UTC
I've decided to make a complete new site with Joomla 4 - on a subdomain - and copied what I still need, clearing all the rest. It works all fine with one exception. As on Joomla 3.10 I have one Layout as default, expecting every article, that is not assigned, will be shown with this Layout. This works fine with 3.10 - but not with 4! Here ist,what I did:

![image](https://user-images.githubusercontent.com/15429256/140520953-ad08f25f-a972-4e2f-bc95-fc3542686a33.png)

In Joomla Template Manager it shows perfect as well:
![image](https://user-images.githubusercontent.com/15429256/140521253-d7297f3c-189d-40a8-a355-08c4525e7431.png)

But when I select (in Joomla Administration) Components-<Gantry 5 Themes -> Default, it shows me "Base Outline" Layout. And every new article has this layout as well.

Besides that, each layout shows "Default" when editing:

![image](https://user-images.githubusercontent.com/15429256/140521960-04aa011a-4a09-4451-bb4a-04b948a766d9.png)

I don't know, if this is an issue or my fault. I even don't know where to look - Joomla 4 or G5?

I even have forgotten, where to select a certain layout as default :-(

Can you helP

Wolfgang

**Comment by mahagr** [comment] 2021-11-08 09:05
The "Default" you're seeing is really preset which was used in Home. Also, the base outline is shown by default as it affects the layout of every other layout. Think of it as default settings. The default layout in Joomla is different, to edit that one you should be editing "Helium - Privat". 

To answer your main question, Joomla doesn't use layouts to show the articles. It uses menu items, which have a layout assigned to them. To display your articles while using the layout you choose, you need to create a menu item with articles component and view.

**Comment by WolfgangDomroese** [comment] 2021-11-08 09:22
Thanks. But this is obviously different to the behaviour in J3. What I want: I use (private) URL, opening articels that are not assigned to a menu. How to create a layout for these articles? Definig a menu and hiding this is not the solution, as the URL in that case leads to error message.
Any idea to solve this in J4/G5.5?

**Comment by mahagr** [comment] 2021-11-08 09:28
It's not different behavior, it's identical to Joomla 3. Maybe you have a menu item in the old sites, which you missed in your new one.

The menu item is the only way in Joomla to set the layout (and modules). It can also be set by a plugin and there are some extensions that allow more customization than that, but they may also cause issues.

**Comment by WolfgangDomroese** [comment] 2021-11-08 09:37
Hm. There was definitely no menu. Just have a short look:
https://www.domroese.berlin/index.php?option=com_content&view=article&id=33:harzer-wandernadel&catid=2:uncategorised
There is no menu for this article. J4 uses "Home"-Layout. Why? Playing around with different settings, sometimes "Article"-Layout was used but never "Private", as I wanted to. When I can be sure, that always "Home" is used, than I can  change "Home" and create a new one for Home-Article...

**Comment by mahagr** [comment] 2021-11-08 10:41
Ok, so likely you didn't have home layout (but default) assigned to the home menu item. Or you had changed the layout to contain joomla content. 

To try to answer your question, that is how Joomla works. When Joomla tries to route articles, it looks for a menu item that matches. If it is found, that is where the articles will be routed to. If not, it falls back using the default menu item with the layout assigned to that one. In Gantry that is by default "Home", which prevents the content from being rendered, thus you will not see any articles.

Try unassigning "Home" layout / outline from the home menu item. If you do so, the same layout (in your case "Private" will be used in every page.

**Comment by mahagr** [comment] 2021-11-22 11:45
Duplicate of https://github.com/gantry/gantry5/issues/2938

This is actually a Joomla bug.

**Closed by mahagr** 2021-11-22 11:45 UTC
Labels: duplicate, joomla4

**Comment by marktaylor46** [comment] 2021-11-22 11:47
If it's a Joomla bug (and I'm not saying that it isn't) then it would be nice if someone reported it to Joomla. @mahagr as you seem to have the best information regarding this issue could you raise the bug on Joomla?

**Comment by mahagr** [comment] 2021-11-22 11:56
See the Joomla issue in your issue.

**Comment by marktaylor46** [comment] 2021-11-22 12:05
Aha! Thanks - for completeness https://github.com/joomla/joomla-cms/issues/35463
