### ISSUE TITLE
JSON call failing in G5.2.9 intermittently - specifically on filepicker

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1136] opened 2016-02-07 14:19 UTC
I have already mentioned this to both @w00fz and @mahagr 

This issue seems to have been introduced with Gantry 5.2.9.

Please see screenshot. 

When using the filepicker ytou intermittantly get  a single line popup because the JSON call is failing. There is no error message to explain why this is the case though.

links to two member posts in RT forum:
http://www.rockettheme.com/forum/joomla-template-callisto/254840-blank-line-when-saving-or-opening-template-settings
http://www.rockettheme.com/forum/configuration-and-security/254828-user-interaction-impeded-or-delayed

![2016-02-07_14-11-44](https://cloud.githubusercontent.com/assets/11683218/12872838/cf85f4f6-cda5-11e5-889e-dafdcdf15815.png)

**Comment by marktaylor46** [comment] 2016-02-07 14:25
Note both member sites appear to be using PHP5.5.28 and OPCACHE.

**Comment by mahagr** [comment] 2016-02-07 16:20
As the issue is random, though frequent, I suspect its PHP/opcache bug in 5.5.28. Any change to get users to temporary disable opcache in their sites to confirm if the issue gets fixed? If the issue is PHP bug, it will be really hard to track down and the easiest way to fix it would be to upgrade to PHP 5.6.

**Comment by marktaylor46** [comment] 2016-02-07 22:44
One member has now confirmed that disabling opcache does seem to resolve the issue. But shouldn't it work with opcache on? Is there anything else we can do?

**Comment by mahagr** [comment] 2016-02-08 08:47
Well, like all software PHP has bugs in it; there are literally hundreds of bugs fixed in PHP since 5.5. These compiler bugs are really hard to track down and even if we manage to fix them, they may come back later unless we fully understand which PHP bug causes the issues.

Easiest way to get rid of these kind of bugs is to upgrade PHP to the latest version; those usually get fixed sooner rather later.

I can take a look on this if I can easily reproduce it.

**Comment by mahagr** [comment] 2016-02-08 12:41
Whatever I try, I'm not able to reproduce the issue with PHP 5.5.28 and opcode extension.

**Comment by marktaylor46** [comment] 2016-02-08 17:45
Second member reports disabling opcache also fixed the issue for them too. Therefore, both member sites are now working. If we get any further reports of this I will let you know.

**Comment by mahagr** [comment] 2016-02-08 18:24
I would love to hear what happens if one of those users upgraded PHP and enabled opcode again.

**Comment by mahagr** [comment] 2016-04-01 11:37
I'm closing this issue as opcode bug which cannot be easily reproduced. If users have issues like this in the future, I'd like to have a look.

**Comment by 1webmaster4you** [comment] 2016-04-01 18:37
I mahagr,

I have a lots of difficulty to EDIT Gantry modules in ADMIN.
I have to CLEAR Gantry cache before I could edit and even then, I need to refresh many time the page in CHROME before I have access to the editing. 

_____Pre-Flight DEV : [http://moisson.designserv.net/](http://moisson.designserv.net/)

Here's my server config :
 _____
CentOS
Apache 2.4.18
DirectAdmin 1.50.0
MySQL 5.5.47
Php 5.6.20
_____

**[/usr/local/lib/php.conf.d]**
opcache.enable=1
opcache.revalidate_freq=0
opcache.validate_timestamps=0
opcache.max_accelerated_files=32531
opcache.memory_consumption=192
opcache.interned_strings_buffer=16
opcache.fast_shutdown=1
opcache.use_cwd=1
opcache.save_comments=1
opcache.enable_file_override=0
____

I need to resolve those Opcahe before I get 40,000 users at the same time…
There's no PHP errors in LOGS !

Alain

**Comment by mahagr** [comment] 2016-04-02 07:02
Reopening issue to allow further discussion. Can you turn `opcache.validate_timestamps=1` and see what happens.

**Comment by 1webmaster4you** [comment] 2016-04-02 16:34
THIS OPCACHE config resolved ALL aspect of GANTRY5 admin problems for now : 

opcache.enable=1
opcache.revalidate_freq=60
opcache.validate_timestamps=1
opcache.max_accelerated_files=65407
opcache.memory_consumption=400
opcache.interned_strings_buffer=16
opcache.fast_shutdown=0
opcache.use_cwd=1
opcache.save_comments=1
opcache.enable_file_override=1
opcache.max_wasted_percentage=10
opcache.revalidate_path=1

Alain

**Comment by 1webmaster4you** [comment] 2016-04-02 18:20
OPCAHE Final Config, as propose by maharg : 
(use **opcache.revalidate_freq=0** or updates in joomla fail).

opcache.enable=1
opcache.revalidate_freq=0
opcache.validate_timestamps=1
opcache.max_accelerated_files=65407
opcache.memory_consumption=400
opcache.interned_strings_buffer=16
opcache.fast_shutdown=0
opcache.use_cwd=1
opcache.save_comments=1
opcache.enable_file_override=1
opcache.max_wasted_percentage=10
opcache.revalidate_path=1

Note : This get a super fast server and pages of any websites (Joomla - Wordpres) are render at least 200% faster !!!  WOW !

Thank's

**Comment by mahagr** [comment] 2016-04-04 10:06
I'm going to have a look if I can fix opcode caching issues with our stored cache files. Because of that I will keep the issue open.

**Comment by mahagr** [comment] 2016-04-04 10:12
Opened a new issue: #1222

**Closed by mahagr** 2016-04-04 10:12 UTC
Labels: duplicate, joomla
