### ISSUE TITLE
Hydrogen nor  g5_helium can be uploaded to wordpress 

### ISSUE THREAD

**Issue by AlienDezine** [gantry/gantry5#2156] opened 2017-10-25 23:41 UTC
"Could not extract file from archive. g5_hydrogen/./
Could not extract file from archive. g5_helium/.

WordPress 4.8.2

Any solutions? 

Thanks

**Comment by whoey** [comment] 2017-10-26 01:20
unzip and rezip the themes /./ directory causes issues.

**Comment by newkind** [comment] 2017-10-26 06:17
Yes, we're aware of this. Closing as duplicate of #2154

**Closed by newkind** 2017-10-26 06:17 UTC
