### ISSUE TITLE
"g-system-messages" is loaded even if it should not

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#572] opened 2015-07-14 12:24 UTC
Hey guys,

I just updated the site I'm working on from G5 RC3 to G5.0.0 and I see that the `g-system-messages` element is loaded all the time, while it should not. And in RC3 the `g-system-messages` element was not loaded all the time, it was loaded only if there is a System Message that needs to be displayed. 

This is quite of an issue if, for example, you have applied some padding and background to the `g-wrapper` element.

The screenshot below shows what I mean. Thanks!

![alt](http://i.imgur.com/68H7EJO.png)

**Comment by mahagr** [comment] 2015-07-14 18:28
Yes, I know...

The issue is that Joomla really requires system messages to be around on all times and we had to think off a way which would affect the least. Even Gantry4 had the section that contained system messages to be around all the time. Same is true on all Joomla templates.

You just need to find a new location for system messages, maybe its own section or something. Or try to think a better way to do it -- assuming that it has to render regardless of whether there's content or not.

**Comment by JoomFX** [comment] 2015-07-14 19:27
I will create a new section specifically for the System Messages.

Thanks Matias :)

**Comment by kevlardev** [comment] 2015-07-14 23:07
Probably the best approach we can take for this is to not have the g-content div rendered for the system messages particle (which contains the margin/padding creating the spacing) and instead have the padding and margin applied on an internal element that is outputted by Joomla when an actual message is shown

**Comment by alisamii** [comment] 2015-08-01 13:56
@mahagr I see you closed this issue, but I like @kevlardev recommendation. However, it does not seem to have been implemented, at least not in the latest CI build.

Any idea when/if this will be implemented, or can you provide a solution that won't involve overriding something like `page.html.yaml`?

**Comment by mahagr** [comment] 2015-08-03 10:54
Did you override the file in your template as this has indeed been implemented.

**Comment by kat05** [comment] 2015-08-03 12:03
I can confirm that "g-system-messages" is being loaded at all times, tested in latest CI build (commit: 1d7e39cfe)

**Comment by mahagr** [comment] 2015-08-03 15:57
@kat05 It should be loaded but it should also be collapsing, meaning that it won't show up unless there is something in there.

So I still think it has been fixed.

**Comment by mahagr** [comment] 2015-08-19 20:25
Do you see a visible issue @kat05? If there is no visible glitch on having ```g-system-messages``` block there, I cannot see that there is an issue.

The block needs to be present at all times in order to Joomla messages to work.

**Comment by kat05** [comment] 2015-08-20 06:05
No visible issue for me @mahagr

**Closed** 2015-08-20 06:18 UTC
Labels: bug
