### ISSUE TITLE
Assignments: blank pane in backend 

### ISSUE THREAD

**Issue by Boumy** [gantry/gantry5#781] opened 2015-09-02 09:39 UTC
Hello. Now I am under Gantry 5.1.2 (Joomla 3.4.3) and I encounter a problem that I didn't face before:
There are some blank panes in the Gantry Assignments admin page. Especially the panes on the right! O.o The three menus panes on the right of the page are blank.

I disconnected and reconnected but it didn't help.

Any idea ?

Thank you.  

![prob-admin-assignments-gantry](https://cloud.githubusercontent.com/assets/13934889/9627745/66dbd134-5166-11e5-88a3-605b66e4355e.jpg)

**Comment by Boumy** [comment] 2015-09-02 10:22
Please note: this site is online. I can give an access to gantry's dev.

**Comment by Boumy** [comment] 2015-09-02 10:51
Actually, the issue appears under Chrome Version 45.0.2454.85 (64-bit)
 for OS X. Although I flushed the cache.
In Firefox, no problem.

**Comment by mahagr** [comment] 2015-09-02 16:13
What does the menu look like and are the items in some specific language?

**Comment by Boumy** [comment] 2015-09-02 16:32
Language is french and some words are in english but this is not a Joomla multilingual site. 
There are 8 menus. I made a test right now and if I resize the window's width, the menu items show up correctly.

**Comment by mahagr** [comment] 2015-09-02 16:41
Are the empty menus assigned to French language? Because of if they are, you may have run into the same bug as #748

**Comment by w00fz** [comment] 2015-09-02 16:56
I've seen this as well in Chrome beta and it is a rendering issue specific to Chrome. The elements are there but because of some glitch with the browser renderer, they aren't shown. I know I asked the other devs to check when I first spot this but nobody could reproduce it. I think the bug on the beta might have made its way through the stable, so we need to check that.

Did you recently update Chrome?

/cc @kevlardev @newkind

// Djamil Legato // From iPhone //

**Comment by Boumy** [comment] 2015-09-02 17:13
I updated Chrome +/- 24 hours ago. Thank you all for your support

**Comment by Boumy** [comment] 2015-09-02 17:17
BTW, what is supposed to be this "ignition" icon in front of some menu items in the Gantry Assignments?
--> ![image](https://cloud.githubusercontent.com/assets/13934889/9638401/da810f4c-51a6-11e5-9177-2714d355299a.png)

**Comment by mahagr** [comment] 2015-09-02 17:17
The icon means that it isn't a page in the site, so you cannot assign style for it.

**Comment by Boumy** [comment] 2015-09-02 17:22
Oh, yes. Like Item menu alias, external links, links pointing to admin pages, etc. Thank you.

**Closed** 2015-09-03 19:07 UTC
Labels: bug

**Comment by w00fz** [comment] 2015-09-03 19:09
So, I tried everything I could to fix the CSS rendering issue of Chrome without success. What I ended up doing is to workaround the issue via JavaScript, it's not ideal nor efficient but I was able to target just Chrome so the other browsers won't pay the price.

Hopefully this issue will get soon resolved in Chrome itself so we can then just remove my workaround, for the moment though, it is fixed.
