### ISSUE TITLE
Child theme outlines inherit base theme configurations.

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1758] opened 2016-12-19 13:27 UTC
Child theme outlines inherit assignments, page settings and so on from base theme outlines.
Up for discussions, but I think outlines should be isolated.

Not sure if it's related, this is how `assignments.yaml` for `default` outline looks like in a child theme.

```
---
post:
  page:
    1812: true
    1790: true
    1814: true
    1816: true
    1817: true
    1818: true
    1819: true
    1820: true
    1821: true
    1822: true
    1823: true
    1824: true
    1825: true
```

And so on, that's an excerpt ;)

**Comment by mahagr** [comment] 2016-12-20 15:29
Right now its inheriting outlines by design. But I do agree that with child themes it would be better if the outlines wouldn't affect each other.

Though -- in all platforms except in Joomla you're only allowed to use a single theme at any given time. So the issue isn't as big as you would think, including Joomla which uses different ids for every outline except the base.

**Comment by mahagr** [comment] 2017-08-15 17:14
This issue should be fixed in most parts on latest versions of Gantry themes.

If your theme still has issues, you should move default outlines from `/config` into `install/outlines` and set them up for the installer.

**Closed by mahagr** 2017-08-15 17:14 UTC
Labels: grav, wordpress
