### ISSUE TITLE
page settings meta items changing keys messes up all tags

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2539] opened 2019-09-11 10:39 UTC
I found this in Fluent template but it is true of any Gantry 5 template.

If you set up a number of meta tags on the base outline (doesn't matter what they are so I just used letters of the alphabet). Then change the key value and save, go to another tab and return you will see that the order of the items get change, repeat the process and then you will see the wrong entry gets changed and some deleted, etc etc it just gets worse and worse. Furthermore, if another outline inherits this and overrides this then the situation get's even worse and whole keys go missing or don't get changed at all.

see video example here: https://www.screencast.com/t/9K4ytDIO

If you check the resultant head.yaml file too that is all messed up...
![2019-09-11_11-43-04](https://user-images.githubusercontent.com/11683218/64690904-6fa1e600-d489-11e9-8904-cfb8cb0aef45.png)

**Comment by mahagr** [comment] 2020-04-27 09:04
I am able to reproduce this one.

**Comment by mahagr** [comment] 2020-04-27 10:09
The issue is in JS. The data coming in from the browser is broken, having both the old and new key, wrong ordering and dropped out variables. This happens only when you change the keys.

**Comment by newkind** [comment] 2020-04-27 11:47
This should be fixed - please give it some good testing and let me know if its fixed. To be precise the issue existed when you edited the existing key name on the keys that were between other fields - so not the 1st or the last key.

**Closed** 2020-04-27 14:23 UTC
Labels: bug
