### ISSUE TITLE
Copy layouts between templates on a site

### ISSUE THREAD

**Issue by photodude** [gantry/gantry5#1174] opened 2016-03-02 21:40 UTC
Goal
Copy the layout within a specific Gantry 5 template in order to use another template and not have to manually recreate the layout for each template.

Reason
Moving between Gantry 5 templates on a single site is essentially so time-consuming and complicated it has completely blocked any and all desire to for me use Gantry 5. Basically, in Gantry 5's current state changing templates results rebuilding an entire site. That for me completely defeats the purpose and reasons for using a CMS. If it's not dynamic and not easily changeable, it's not designed for CMS use.

Gantry 4 had similar issues with layouts between templates; but since most of the settings in the layouts reflected just "positions" it was easier to switch templates and modify a few modules to use any layout position names that may have changed / removed / added.

Possible concept for implementation
A button somewhere that would allow you to select a target template to copy to.
Behind the scenes the code would parse the particles/positions for each template and copy from A to B and display a list of particles/positions that could not be automatically copied. It would be beneficial to also include a in the "failed copy" dialog to select a new positions for items in positions that could not be matched automatically. (this concept could also work in reverse, just the from and to targets change when copying from B to A)

**Comment by w00fz** [comment] 2016-03-03 00:26
Did you know you can copy the `custom/` folder between templates and do very little adjustments in the files for a very easy porting?

**Comment by photodude** [comment] 2016-03-03 01:25
@w00fz I was unaware of the "copy the `custom/ folder` between templates" trick. Is that in the documentation? (I still would like to see an automated method)

**Comment by w00fz** [comment] 2016-03-03 01:31
It might not be explained clearly in the docs and I'll ask @FrugalGeek to take a look at it.
The `custom/` folder is the basic concept of Gantry 5 where everything that gets stored after a user interaction, custom settings, custom layouts, custom css, it all goes in that folder so that it can be easily backed up, never lost after updates and because we use a flat-file approach for storing the data, it can easily get ported over to other instances, both between templates as well as between platforms.

Yes, Import and Export is in our list of things to do [Gantry 5 Agenda, Exploration and Time Travel](https://github.com/gantry/gantry5/wiki/Gantry-5-Agenda,-Exploration-and-Time-Travel).

It isn't our highest priority right now but we will get there. The good thing is that it's very easy to customize and copy bits over since it's all there in files in the custom folder :)

**Comment by adi8i** [comment] 2016-03-03 06:30
In `custom` folder open `layout.yaml` and copy the code, then create a new file `my-new-layout.yaml` paste the code, and place this file in `layouts` folder, now just use load to load your new layout preset. This way you can do adjustments to your layout, it works just like `import / export` but you have to do it manually.

**Comment by w00fz** [comment] 2016-06-04 01:06
Marking this as duplicate of #218 which covers import/export.

**Closed by w00fz** 2016-06-04 01:06 UTC
Labels: duplicate, feature

**Comment by amrshah** [comment] 2016-12-11 06:28
I recently started exploring Gantry 5 and faced the same issue, I was thinking on the similar lines as commented by photodude. We could have some sort of import/export functionality built in the admin interface. I have started thinking about the complexity of adding this feature to my local Gantry 5 installation...or is there anywhere else I should consult about it?

**Comment by joomlabeat** [comment] 2017-03-08 12:13
any chance someone could spread some light on this issue? I can't move my local dev work on another site.
What are the too little adjustments in the files that have copied over? 

In backend, I can see all my configurations (outlines, particles, page settings etc) - but in the front-end I am not getting the expected layout.

**Comment by mahagr** [comment] 2017-03-09 08:05
In Joomla it is not possible to just copy layouts over. You need to create a new template style and rename outline folder to match the id.

**Comment by photodude** [comment] 2017-03-09 16:39
@mahagr the intent of my request was for a one-click or other simple UI interface to copy layouts between templates. 

It's nice to know that you can manually copy and rename but it's still a slow and error prone process.
