### ISSUE TITLE
Box/Title styles not applied in Module Positions

### ISSUE THREAD

**Issue by BrentCritch** [gantry/gantry5#857] opened 2015-09-18 19:52 UTC
Modules assigned to positions do not display individual box or title styles assigned via Module Class Suffix in the Module Manager. Classes can be assigned to full positions through the Gantry Layout Manager, but this does not allow variations for individual modules.

**Comment by w00fz** [comment] 2015-09-18 19:56
Are you referring to the `variations` classes not being applied to the module, when set from the module class suffix?

**Comment by BrentCritch** [comment] 2015-09-18 19:57
Yes. See this thread for a fuller explanation: http://www.rockettheme.com/forum/joomla-template-callisto/242756-box-styles-for-module-positions

**Comment by rgblogs** [comment] 2015-09-19 10:53
I use module instance in Gantry Layout and then apply variations for each module.

**Comment by w00fz** [comment] 2015-09-21 18:39
The issue you mention, @BrentCritch, is an intended behavior. There are a few reasons why this is not possible. The main is logistical. Because a module in Joomla is always a child of a Position Particle and Block of Gantry 5 Layout, and because you can add variations from the Block level in the Layout Manager, to make the module class suffixes supporting block variations also, each template will have to provide support for all the possible combinations between the Block and the Module.

To explain this better, imagine you create a module position `A` and in the Block tab you select the `box-2` variation. Then in Joomla's module manager you create a module and assign it to the position `A` you just created, as well as adding to the class suffix a `box-1` variation.

In the rendering of the page the particle will now have the block with `.box-2` and the child module with `.box-1`, probably resulting in a conflict of styles or just inheriting the last most applied variation `box-1`.

Now like I said this could be avoided by having the template providing all the combinations, but this would be enormous. If we only take 1 type of variation like `box-X` and we say a template has 10, it will require the template to provide 100 combinations to satisfy the mix and to avoid styles conflicts.

The second reason is also related to styling. Because a Position Particle (and its Block) are merely a container for Joomla's modules, and because in Joomla you can assign infinite number of Modules to the same Position, this will become problematic if at the module level you could also assign the variation from the class suffix.
Any Joomla's module assigned to the same position, renders stacking up, vertically. Because the position and horizontal space occupied are always the same, no matter how many modules are present in said position, this can potentially result in a style nightmare unless, like above, the template in question doesn't take all this in consideration.

As you can see, there are different problems related to the issue that don't make this as easy to resolve as we would like. The moment we unchained the layout in Gantry 5, making it extremely dynamic and flexible comparably to Gantry 4, we encounter a few of these issues that are just more complicated than others to resolve and that have never been in issue before because the whole layout was "hardcoded" from the very beginning.
Since YOU can build your own layout now, we had to follow some rules in order to build the logic to make all of the rendering working and dynamically building.

So I just wanted to let you know that we have been discussing this matter, a lot, and we have been looking at finding the best possible approach to accomodate your request while keeping everything still simple and fast. It just happen to be a very complicated issue, even though it doesn't look like it, and it might require some time to get this fully sorted out and implemented.

Thank you for your feedback!

> Note: If interested, in https://github.com/gantry/gantry5/issues/789#issuecomment-137559756 I also explained how the levels, modules, positions and blocks work in Gantry 5.

**Comment by BrentCritch** [comment] 2015-09-22 17:01
Thanks for the explanation on this. I understand where you guys are coming from, but from a user perspective this "breaks" much of the functionality of the CMS. Being able to assign repeatable elements to pages at will is part of what makes the system work. The new Gantry 5 layout builder is great, but I don't want to be forced to build a new layout every time I need to change which modules are on the page.  

It also introduces issues with keeping modules (particles) updated. If I have three layouts, (let's call them default, A, and B) I might have a particle/module that I want to display on A and B, but not default. If I then update the information in that particle, I have to do it in both layouts. This is only one step ahead of the old days of hand-coding HTML pages. 

A possible solution which I'm sure you've probably considered would be to remove box styles from module positions only. This would eliminate the scenario you outlined with styles stacking on top of each other. If I want to use particles in a particular layout I would still be able to do so, but this would allow me to continue to use Joomla as it's designed. I could then mix and match module positions and particles within my layouts to create some really nice designs.

**Comment by mahagr** [comment] 2016-02-25 11:31
Looks like this has been fixed.

**Closed by mahagr** 2016-02-25 11:31 UTC
Labels: enhancement
