### ISSUE TITLE
Loading jQuery library (the one that comes from Joomla) from a Particle

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#856] opened 2015-09-18 16:40 UTC
@w00fz @mahagr Hey guys, how can I load the jQuery library from a Particle/Twig? The jQuery that comes with Joomla by default.

I'm looking for exactly the same thing as this:

```
JHtml::_('jquery.framework');
```

The above code loads the following assets in the `<head>`

```
<script type="text/javascript" src="/media/jui/js/jquery.min.js">
<script type="text/javascript" src="/media/jui/js/jquery-noconflict.js">
<script type="text/javascript" src="/media/jui/js/jquery-migrate.min.js">
```

So, I'm looking for something like the following that I will put in my Particles:

```
{% assets in 'head' %}
    {jquery.framework}
{% endassets -%}
```

Where the `{jquery.framework}` is the same thing as `JHtml::_('jquery.framework');`

I do believe that we need such thing so the jQuery library is loaded just once.

**Comment by w00fz** [comment] 2015-09-18 16:43
Duplicate of #546

**Comment by adi8i** [comment] 2015-09-18 16:45
Try this `{% do gantry.theme.joomla(true) %}`

**Comment by JoomFX** [comment] 2015-09-18 16:47
@w00fz Djamil, why do you think it is a duplicate? :)

It is a feature request.

I'm not complaining that Bootstrap or jQuery are not loaded by G5, I'm happy about that.

Don't you thing that adding a Twig equivalent of `JHtml::_('jquery.framework');` is really, really needed?

If I use `{% do gantry.theme.joomla(true) %}` Bootstrap will be loaded as well, and I do not need it. I only need jQuery.

**Comment by w00fz** [comment] 2015-09-18 16:51
Duplicate is not a negative label at all.
I marked as so because if you read further down in https://github.com/gantry/gantry5/issues/546#issuecomment-119656219 I already proposed an analog implementation, something like `gantry.loadBootstrap()` and `gantry.loadJquery()`, hence the duplicate label :smile:

**Comment by JoomFX** [comment] 2015-09-18 16:57
Alright, I see now. I should read more carefully :D
Thanks guys!

When do you think it can be implemented? I know you are overloaded as hell, but still.... :)

P.S.  I'm not saying "Duplicate" is negative :) I just wanted to make sure that this specific issue is being looked at (I didn't noticed the `gantry.loadJquery()` thing the first time) ;)

And by the way, how would `gantry.loadJquery()` be loaded in Twig once it is implemented? I mean what will be the syntax? Something like this:

```
{% assets in 'head' %}
    {gantry.loadJquery()}
{% endassets -%}
```

Or...?

**Comment by mahagr** [comment] 2015-09-18 17:21
Closing this one in hopes of moving the discussion into #546.

**Closed by mahagr** 2015-09-18 17:21 UTC
Labels: duplicate
