### ISSUE TITLE
Blog url forced onto post inside pre tag.

### ISSUE THREAD

**Issue by kaptinavenger** [gantry/gantry5#1328] opened 2016-06-03 03:14 UTC
I have the following code I am displyaing on my blog inside a pre tag just like, exactly like, this:

<pre class="lang:xhtml decode:true ">&lt;% var next_page = TemplateTags.getNextPage(); %&gt;
&lt;a href="right here err&lt;%= TemplateTags.getPageLink( next_page.id ) %&gt;"&gt;Next Page&lt;/a&gt;</pre>

And on the published posts it forced the url of the blog into the code like so:

<pre class="lang:xhtml decode:true ">&lt;% var next_page = TemplateTags.getNextPage(); %&gt;
&lt;a href="http://myblog.address.com/right here err&lt;%= TemplateTags.getPageLink( next_page.id ) %&gt;"&gt;Next Page&lt;/a&gt;</pre>

I uninstalled a half dozen plugins when I found the bug, before I tried changing themes. After I changed themes to twenty fourteen the forced url went away, and I then started turning plugins back on, it turned out to be only the Gantry theme.

Hydrogen Gantry 5.2.18 / Wordpress 4.5.2

**Comment by w00fz** [comment] 2016-06-03 06:22
Thanks for figuring this out and opening an issue about it @kaptinavenger.

So the issue is in our `Document::urlFilter` method, right now we are running a regex that is very fast and effective but unfortunately doesn't take into account if the links are inside a `<pre>` or a `<code>`.

I have a working proposal that I just implemented and tested, which works fine, but might definitely add a little bit of overhead.

I haven't pushed this yet but goes like this:

``` php
public static function urlFilter($html, $domain = false, $timestamp_age = null)
{
    $dom = new \DOMDocument();
    libxml_use_internal_errors(true);
    $dom->loadHTML($html);
    $dom->removeChild($dom->doctype);

    $xpath = new \DOMXPath($dom);
    $filtered = $xpath->query('//*[not(ancestor::pre)][not(ancestor::code)][@src|@href|@url]');

    foreach ($filtered as $element) {
        $value = '';
        $type = '';
        foreach (['src', 'href', 'url'] as $attribute) {
            if (!$value) {
                $type = $attribute;
                $value = $element->getAttribute($attribute);
            }
        }

        $element->setAttribute($type, static::url(trim($value), $domain, $timestamp_age));
    }

    return preg_replace('~<(?:!DOCTYPE|/?(?:html|head|body))[^>]*>\s*~i', '', $dom->saveHTML());
}
```

This would also make the two methods `Document::linkHandler` and `Document::urlHandler` redundant.

Honestly I don't like much DOMDocument, it isn't very forgiving of broken HTML, however I know that handling this via regex is quite complicated.

An alternative solution I thought about is to tokenize any `<pre>*</pre>` and `<code>*</code>, perform pass all links to the handlers and then replace back the tokens in the processed HTML. This might require some extra regex but might be still a tad faster than DOM.

What are you thoughts @mahagr ?

**Comment by mahagr** [comment] 2016-06-03 06:54
We are already using DOMDocument in parsing head JS/CSS and its not only unforgiving, but it cannot always parse even valid HTML. For example it has issues with <code> and <script> tags and in some servers it just fails to parse a simple HTML because of some libxml bug.

**Comment by w00fz** [comment] 2016-06-04 00:04
Alright this is now fixed and I opted to go with the tokens idea I had (https://github.com/gantry/gantry5/commit/90654f1c06de69b6d242893390bbdc2994148218#diff-42fd73adcbd6c8718e26d88681a39d35). Feels like a much safer and reliable way to go, I just don't like DOMDocument even though it's always suggested to use that when manipulating HTML.

**Closed** 2016-06-04 00:17 UTC
Labels: bug

**Comment by kaptinavenger** [comment] 2016-06-04 02:56
Fixed fixed? Like turn gantry back on, update and bam it'll work?

**Comment by w00fz** [comment] 2016-06-04 03:01
Yup, however it's not released yet, just fixed in develop  branch. I would also suggest against testing CI Builds right now, we have develop set to 5.3 release which is a major release. But you can look at my commit and apply the same code to Document.php, it will work fine.
