### ISSUE TITLE
Updating  WP plugins with G5 activated causes endless Maintenance mode

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1271] opened 2016-05-05 06:41 UTC
"Briefly unavailable for scheduled maintenance. Check back in a minute."

We need to locate it and fix it - happens everytime when updating things.

**Comment by mahagr** [comment] 2016-05-13 12:17
I cannot reproduce the issue with WP 3.5.0, didn't try the latest version, though.

**Comment by newkind** [comment] 2016-05-17 10:14
Can't reproduce anymore. Closing.

**Comment by Matt-Yorkley** [comment] 2016-06-16 17:36
I'm getting this as well as a recurring issue. The Wordpress debug bar shows this message when updating a plugin hangs in maintenance mode (only shows up under javascript errors, as the update call is done through ajax):

"Error: Syntax error, unrecognized expression: {"error":{"type":"Whoops\\Exception\\ErrorException","message":"Undefined index: type","file":"\/var\/www\/html\/roots\/wp-content\/plugins\/gantry5\/admin\/init.php","line":119}}"

It looks like the gantry5_upgrader_post_install() function in line 116 of /plugins/gantry5/admin/init.php is getting called when other plugins are updated, but the $options array it takes as an argument is empty in this case.

**Comment by Matt-Yorkley** [comment] 2016-06-16 19:10
After a bit more digging, the $options array that gets checked in line 199 doesn't contain the ['type'] key at all (when other plugins are being updated), only ['plugin'], which contains a string like: "path/to/plugin-file.php".

A quick check at the top of that function (at line 117) fixes the issue:

if( isset($options['plugin']) && $options['plugin'] != "gantry5/gantry5.php" ) { return; }

**Comment by newkind** [comment] 2016-06-17 10:04
Reopen as this is still the issue.

**Comment by nikola3244** [comment] 2016-06-24 14:31
Same issue on dev-20916e3ba, WP 4.5.3

**Comment by Matt-Yorkley** [comment] 2016-06-24 16:28
Have a look at my description of the issue in commit #1365

**Comment by mahagr** [comment] 2016-06-30 12:29
Should be fixed now, please test it out.

**Comment by mahagr** [comment] 2016-06-30 12:30
Looks like the issue only happens when `display_errors = On`

**Closed** 2016-06-30 12:30 UTC
Labels: bug, important, wordpress
