### ISSUE TITLE
Issues with single select field with multiple values

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1402] opened 2016-06-30 06:11 UTC
+ WordPress
+ Latest CI

You get the error when you open all **collection** items in particle.
![capture](https://cloud.githubusercontent.com/assets/9744973/16478647/93d5a428-3ea3-11e6-967b-2348cd39fe26.PNG)

`Oops, An exception has been thrown during the rendering of a template ("trim() expects parameter 1 to be string, array given") in "forms/fields/select/select.html.twig" at line 25..`

**Comment by mahagr** [comment] 2016-06-30 06:42
The issue is really a single `select.select` field having a "bad" value. I will need to think how to best work around it.

**Comment by adi8i** [comment] 2016-07-01 12:10
Hi Matias, was it merged in CI? The issue is still there.

**Comment by w00fz** [comment] 2016-07-01 18:21
I think the issue is that multiselect is really not working at all.
Are you able to even save a multiple selection? For me it only saves 1 value.

**Comment by w00fz** [comment] 2016-07-01 22:01
Alright, the multiselect field issue I described above is now fixed, however this was always an issue apparently.
What you are describing and that I can reproduce, is something related to the collections field and has nothing to do with select or specific inner fields.
I think the issue has been introduced with befaa6ef16ca00bd5.

At this stage, no multiple editing for collections work, no matter the field. What I see happening is that for each collection item field, the whole value of the collection is passed in, rather than just the single item value as expected.

**Comment by adi8i** [comment] 2016-07-02 10:34
This might be related. I seen it first time when i opened this issue, it's array everywhere, the particle is empty, no saved value. And it's social particle.

![capture](https://cloud.githubusercontent.com/assets/9744973/16539899/72e97570-4059-11e6-8865-26351507d315.PNG)

**Comment by mahagr** [comment] 2016-07-04 07:50
Yes, this was the reason why I opened #1405 in the first place. I was fixing this one when I ran into the other issue. Will take a look on the remaining issue in a bit.

**Comment by mahagr** [comment] 2016-07-04 19:00
Good catch, fixed!

**Comment by adi8i** [comment] 2016-07-07 07:10
@mahagr the array thing is still there.

**Comment by mahagr** [comment] 2016-07-07 07:14
See comment on #1346. This change broke default values.

**Closed** 2016-07-07 10:49 UTC
Labels: bug, important

**Comment by w00fz** [comment] 2016-07-07 17:14
@adi8i Can you double check this is working right now?

**Comment by adi8i** [comment] 2016-07-08 20:55
Eh, I missed this one, yes it's working fine :+1:

**Comment by adi8i** [comment] 2016-07-08 22:15
This is still an issue + #1402 

In this example the field is checked by default, if i save it empty it should inherit from base. But nothing happens. After refresh, the field is checked again.
http://www.awesomescreenshot.com/image/1383069/13baa651829e689abfafcc9d4ca5b125

I think you understood it wrong. The default behavior is fine, empty field -> inherit from base.

What i mean about config, is that it should be used to install demo data only, to create outlines on install. Like you do with home outline in hydrogen, wordpress. Or i don't understand how config works :P. Please let's me know if i do something wrong.

There are two states. Field unchecked -> inherit from base. Field checked -> override base. Config likely introduce a third state and that's not possible.

**Comment by adi8i** [comment] 2016-07-08 22:27
And i think i posted it wrong :D
