### ISSUE TITLE
User is wrongly called in G5 somewhere

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#787] opened 2015-09-03 09:12 UTC
When bbPress or BuddyPress are active, there's this notice :

```
NOTICE [1024] bbp_setup_current_user was called incorrectly. The current user is being initialized without using $wp->init(). Please see Debugging in WordPress for more information. (This message was added in version 2.3.) 
```

Somewhere in G5 the user is wrongly initialized as this error is gone on non Gantry powered themes.

**Comment by mahagr** [comment] 2015-09-03 10:51
We are calling user from Theme class and also from the new offline feature. Must be one of those two.

**Comment by newkind** [comment] 2015-09-05 18:42
Checked both locations and that's not it. Might be a conflict with overbuffer.

**Comment by mahagr** [comment] 2015-09-08 08:53
I'm not able to reproduce this issue with Hydrogen (linked BuddyPress Profile to menu)...

**Comment by mahagr** [comment] 2015-09-08 09:44
I tracked the issue down to Page Builder plugin by SiteOrigin.

**Comment by newkind** [comment] 2015-09-08 10:03
Nope, that's not it.

**Comment by mahagr** [comment] 2015-09-08 10:18
The issue might be in the menu as I'm not able to get the issue in my new test site with all active, but in my another test site I get the error without Gantry installed.

**Comment by mahagr** [comment] 2017-12-01 11:37
Closing due to no further reports on this.

**Closed by mahagr** 2017-12-01 11:37 UTC
Labels: wordpress
