### ISSUE TITLE
Collection is not working if the field selector is nested: main.items

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1867] opened 2017-02-11 13:21 UTC
You can create items, but you can't edit the item, error 404

```
main.items:
  type: collection.list 
  label: Items 
  array: true 
  ajax: true 
  value: name 
  fields:
    .title:
      type: input.text 
      label: Title
```

**Comment by mahagr** [comment] 2017-02-13 08:41
I've reproduced the issue.

The issue seems to be restricted only to nested keys, if you change `main.items` into `items`, the call seems to work just fine.

**Comment by mahagr** [comment] 2017-02-13 11:05
Should be fixed in latest CI build.

**Closed by mahagr** 2017-02-13 11:05 UTC
Labels: bug
