### ISSUE TITLE
Add option to copy particle inside Layout manager

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1992] opened 2017-05-12 09:55 UTC
The ability to go to the Layout manager and just hit some sort of 'Copy particle' button on each already existing and configured particle would be super helpful. :)

**Comment by mahagr** [comment] 2017-05-16 06:46
It already exists, kind of... You can copy particles which have been saved by using the cloning/inheritance feature.

**Comment by mahagr** [comment] 2017-06-01 09:11
The feature doesn't work for base outline, though.

**Comment by mahagr** [comment] 2017-06-02 05:45
Duplicate of #1703 (as copying is already possible in other outlines),

**Closed by mahagr** 2017-06-02 05:45 UTC
Labels: duplicate
