### ISSUE TITLE
Problem with menu items order

### ISSUE THREAD

**Issue by cvrak** [gantry/gantry5#2772] opened 2021-03-09 14:56 UTC
Hi,
I have a multilingual site (English & Greek), English is the default lang. I used Falang for translating the content, and the menu items as well.
I face this problem: When I switch to greek section, menu items are not in the right order.
You can see what I mean at www.inspire-tv.com
After a lot of searching I found out that if I delete the yaml file from siteroot/templates/g5_hydrogen/custom/config/menu the menu is ok. The file is mainmenugb.yaml . Obvliously this is the file for the menu.
But if I make any change at the menu in the Gantry UI, the file is created again and the problem returns.
Is it possible to have some conflict? How this can be corrected?

Thanks in advance
Chris

**Comment by mahagr** [comment] 2021-03-15 08:40
This is a known bug and I'm trying to find a fix for it for Gantry 5.5 (a similar issue has already been fixed in WP).

**Comment by joomlabeat** [comment] 2021-03-15 18:50
Not sure if this is related, but I arrived here today because I am facing a big issue when trying to work with the menus.
Gantry 5.4.7 - WP and multilingual.

The problem I have is that I am trying to create columns in the sublevel.
I create the columns and then try to move and place the menu items across the columns - I click save - going to the front-end and the menu items are taking their own positions in the columns disregarding where I placed in the admin.
I refresh the menu page of the admin and nothing of my previous actions has been saved.
I have tried so many times with so many twists (less/more columns, different menu items, changing the order of the menu items in WP menus, nesting menu items etc). 
Actually, changes in the WP menu items, do not reflect right away in gantry admin. 

I am also got a fatal error - I created 5 columns and placed menu items in there ... 

Invalid argument supplied for foreach()
 /Users/john/Sites/webrivermedia/wp-content/plugins/gantry5/src/classes/Gantry/Admin/Controller/Html/Menu.php
/classes/Gantry/Admin/Controller/Html/Menu.php489

Overall, the whole menu thing seems broken.

**Comment by joomlabeat** [comment] 2021-03-15 19:00
https://user-images.githubusercontent.com/6756053/111206763-773bd100-85d1-11eb-9bfa-406eaf066119.mov

**Comment by joomlabeat** [comment] 2021-03-15 19:52
Working directly inside the yaml file of the menu is my workaround for now.

**Comment by N8Solutions** [comment] 2021-03-15 19:59
Maybe this is something that @w00fz needs to look at? I know the Menu was his design.

**Comment by mahagr** [comment] 2021-04-07 09:59
I've been working on fixing this issue in Joomla/WP, and the menu works now (well, it does need some more testing).

**Comment by cvrak** [comment] 2021-04-07 10:05
> I've been working on fixing this issue in Joomla/WP, and the menu works now (well, it does need some more testing).

Good news! so, what we have to do? update gantry, or something else?

**Comment by joomlabeat** [comment] 2021-04-08 06:33
Although busy these days - let me know if there is something to test, I could do some testing in the weekend (I guess).

**Comment by N8Solutions** [comment] 2021-04-11 19:47
I'm happy to do some testing as well @mahagr. Just let us know what you need.

**Comment by mahagr** [comment] 2021-04-13 11:42
@cvrak @joomlabeat @N8Solutions I have experimental builds in here: http://www.avusto.fi/

Please test it **ONLY** in a test site with a backup as the release needs far more testing and may have bugs that cause issues with the menu. There may also be issues elsewhere as this is a big rewrite to modernize the codebase.

**Comment by ganakee** [comment] 2021-04-19 13:38
I too have been seeing this across all sites using Gantry 5 on Wordpress (WP).  Menu ordering simply occurs randomly no matter if properly ordered in WP Menu or Gantry5 Menus. Cannot reliably set order on Top Level or Sublevel Menus. (I can confirm that this is something that occurred fairly recently. Older sites with no menu changes for a while ~year) are OK. It is when you changea menu or add a menu item that the menus become erratic.

**Comment by mahagr** [comment] 2021-05-13 12:54
Fixed in upcoming Gantry 5.5.

**Closed by mahagr** 2021-05-13 12:54 UTC
Labels: bug, joomla
