### ISSUE TITLE
Saving Styles causes 405 Method Unalowed

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#669] opened 2015-07-30 16:58 UTC
I can't save changes in the Styles tab. I'm not sure what's causing that as I had this behavior before, then it started to work, right now it's again broken. 

![screen shot 2015-07-30 at 18 52 52](https://cloud.githubusercontent.com/assets/1641534/8989413/5295ae5a-36ec-11e5-8577-f0e5696b02b5.png)

**Comment by mahagr** [comment] 2015-08-04 18:39
Looks like this bug exists only when you have not clicked on styles tab. URL is different when you first access the page.

**Comment by newkind** [comment] 2015-08-04 18:40
Yah, confirmed.

**Comment by mahagr** [comment] 2015-08-04 18:50
@w00fz 

It looks like javascript doesn't obey <form action="..."> in styles tab causing it to send data to wrong url the first time you enter to the page in WP.

**Comment by w00fz** [comment] 2015-08-05 21:47
We never used the form action for saving, it always follows the URL. In this case the issue is that when you access it from the `Hydrogen Theme` button on the sidebar, the view `&view=configurations/default/styles` is missing and the save fails.

I hacked the JS to force adding the default view in the URL whenever it's missing but really this should be addressed by fixing the `href` on that button, to point to the full valid url `/wp-admin/admin.php?page=layout-manager&view=configurations/default/styles`.

This is the same issue that was with the `_wpnonce`, when you access the admin via button on the sidebar, no `_wpnonce` gets added and I had to hack-force it. 

Would be nice if you could fix the route for this, I tried looking where this is happening and couldn't find it.

**Comment by w00fz** [comment] 2015-08-05 21:51
I'll close this since it is technically fixed but I really think it should be addressed differently than via JS.

**Closed by w00fz** 2015-08-05 21:51 UTC
Labels: bug, important, wordpress

**Comment by mahagr** [comment] 2015-08-06 07:43
The issue in WP is that there's no way to add those details to the page in WP; I can only set &page=layout_manager and that's it. WP doesn't allow me to add any other parameters as far as I know.

I agree that there must be better way to fix this, but we can take a look into it later.

In the mean time, thanks!

**Comment by newkind** [comment] 2015-08-06 07:51
Maybe this : http://wordpress.stackexchange.com/questions/114810/how-to-create-sub-menu-with-a-url-parameter ?

**Comment by mahagr** [comment] 2015-08-06 09:02
@newkind Can you create new low priority issue on this?

**Comment by newkind** [comment] 2015-08-06 09:02
sure
