### ISSUE TITLE
Can't choose SVG graphic as logo image

### ISSUE THREAD

**Issue by artemlebsak** [gantry/gantry5#448] opened 2015-06-09 21:38 UTC
Particle Settings -> Logo -> Image
Graphic in SVG format can be upload but after that can't be chosen.

**Comment by w00fz** [comment] 2015-06-10 18:09
This is a known issue related to https://github.com/gantry/gantry5/issues/379#issuecomment-106008543 . We still need to do some work on the Filepicker.

Right now, when you upload an image, including svg, you have to click on another folder and come back, in order to refresh it in the proper way so that it is selectable.

**Comment by w00fz** [comment] 2015-06-19 00:26
Marking this as resolved since it's caused by #379.

**Closed by w00fz** 2015-06-19 00:26 UTC
Labels: bug
