### ISSUE TITLE
"405 Method not allowed" when editing outline name on styles tab

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1427] opened 2016-07-11 09:44 UTC
G5.3.0 (and tested on CI build too).

Clicking on the pencil icon next to the outline name (when on styles tab) results in a tiny field which you can't click in and doesn't prefill the existing outline name. clicking on the pencil icon again you can key into the field but once you press enter you get a "405 Method not allowed".

![2016-07-11_10-39-52](https://cloud.githubusercontent.com/assets/11683218/16726480/51d3cc8a-4754-11e6-9b4e-e78ab067fe54.png)
![2016-07-11_10-40-31](https://cloud.githubusercontent.com/assets/11683218/16726482/56c77796-4754-11e6-8a69-d5020f69074f.png)

**Comment by mahagr** [comment] 2016-07-11 10:49
For me edit doesn't work at all (clicking icon renders selectize unusable); same issue is in both Chrome and FF.

**Comment by w00fz** [comment] 2016-07-11 16:53
Duplicate of #1422

**Closed by w00fz** 2016-07-11 16:53 UTC
Labels: duplicate
