### ISSUE TITLE
[urgent] - v5.4.20 breaks template backend

### ISSUE THREAD

**Issue by thexmanxyz** [gantry/gantry5#2194] opened 2017-12-11 20:30 UTC
Hey there,

this is an urgent issue because the latest version of gantry at least for Joomla breaks the template backend and throws a stacktrace on accessing any gantry template for Hydrogen and for Helium. The error appears in the [Outlines.php](https://github.com/gantry/gantry5/blob/develop/src/platforms/joomla/classes/Gantry/Framework/Outlines.php#L77) at L77. The `$theme` object will always be null but the following attached exception is thrown at L77 because previous error checks circumevent that the error appears earlier. I suspect that the source of the error originates in the `Outlines.php` because I did not find any changes in this file since .19. I tried to find the origin of the problem but I do not have the time and knowledge of the Gantry code base to find a quick fix for the issue.

But to bring it down the issue has something to do with `OutlineCollection` and the `container` member because there is no identifier in the `container `object for `theme.name` so I assume that the problem can be found in this member object. I will prepare the stacktrace and attach it to the issue as soon as I'm done with it.

Thanks @yellowwebmonkey for pointing on this issue.

Stacktrace:
16 Pimple\Exception\UnknownIdentifierException in C:\xampp5\htdocs\projectXYZ\libraries\gantry5\vendor\pimple\pimple\src\Pimple\Container.php:101
**15 Pimple\Container:offsetGet in C:\xampp5\htdocs\projectXYZ\libraries\gantry5\classes\Gantry\Framework\Outlines.php:77**
14 Gantry\Framework\Outlines:load in C:\xampp5\htdocs\projectXYZ\libraries\gantry5\classes\Gantry\Framework\Base\Gantry.php:244
13 Gantry\Framework\Gantry:Gantry\Framework\Base\{closure} in C:\xampp5\htdocs\projectXYZ\libraries\gantry5\vendor\pimple\pimple\src\Pimple\Container.php:114
12 Pimple\Container:offsetGet in C:\xampp5\htdocs\projectXYZ\libraries\gantry5\classes\Gantry\Admin\Controller\Html\Configurations.php:207
11 Gantry\Admin\Controller\Html\Configurations:forward in C:\xampp5\htdocs\projectXYZ\libraries\gantry5\classes\Gantry\Component\Controller\BaseController.php:91
10 call_user_func_array in C:\xampp5\htdocs\projectXYZ\libraries\gantry5\classes\Gantry\Component\Controller\BaseController.php:91
9 Gantry\Component\Controller\BaseController:execute in C:\xampp5\htdocs\projectXYZ\libraries\gantry5\classes\Gantry\Component\Controller\HtmlController.php:32
8 Gantry\Component\Controller\HtmlController:execute in C:\xampp5\htdocs\projectXYZ\libraries\gantry5\classes\Gantry\Component\Router\Router.php:92
7 Gantry\Component\Router\Router:execute in C:\xampp5\htdocs\projectXYZ\libraries\gantry5\classes\Gantry\Component\Router\Router.php:53
6 Gantry\Component\Router\Router:dispatch in C:\xampp5\htdocs\projectXYZ\administrator\components\com_gantry5\gantry5.php:57
5 require_once in C:\xampp5\htdocs\projectXYZ\libraries\src\Component\ComponentHelper.php:381
4 Joomla\CMS\Component\ComponentHelper:executeComponent in C:\xampp5\htdocs\projectXYZ\libraries\src\Component\ComponentHelper.php:356
3 Joomla\CMS\Component\ComponentHelper:renderComponent in C:\xampp5\htdocs\projectXYZ\libraries\src\Application\AdministratorApplication.php:101
2 Joomla\CMS\Application\AdministratorApplication:dispatch in C:\xampp5\htdocs\projectXYZ\libraries\src\Application\AdministratorApplication.php:159
1 Joomla\CMS\Application\AdministratorApplication:doExecute in C:\xampp5\htdocs\projectXYZ\libraries\src\Application\CMSApplication.php:267
0 Joomla\CMS\Application\CMSApplication:execute in C:\xampp5\htdocs\projectXYZ\administrator\index.php:51

**Comment by terryburg** [comment] 2017-12-11 20:44
Same issue here as thexmanzyz but if I navigate to template via Components -> Gantry 5 Themes -> Available -> mytemplate then I can work on the template without issue.

**Comment by thexmanxyz** [comment] 2017-12-11 20:48
@terryburg you are right only accessing the templates over "extensions/templates" causes the described issue!

**Comment by Eggeriley** [comment] 2017-12-11 21:17
I am having the same issue. After the update it breaks the backend view

Twig_Error_Runtime thrown with message "An exception has been thrown during the rendering of a template ("Identifier "theme.name" is not defined.")."

Stacktrace:
#39 Twig_Error_Runtime in /home/accessip/public_html/administrator/components/com_gantry5/templates/partials/outlines-list.html.twig:9
#38 Pimple\Exception\UnknownIdentifierException in /home/accessip/public_html/libraries/gantry5/vendor/pimple/pimple/src/Pimple/Container.php:101
#37 Pimple\Container:offsetGet in /home/accessip/public_html/libraries/gantry5/classes/Gantry/Framework/Outlines.php:77
#36 Gantry\Framework\Outlines:load in /home/accessip/public_html/libraries/gantry5/classes/Gantry/Framework/Base/Gantry.php:244
#35 Gantry\Framework\Base\Gantry:Gantry\Framework\Base\{closure} in /home/accessip/public_html/libraries/gantry5/vendor/pimple/pimple/src/Pimple/Container.php:114
#34 Pimple\Container:offsetGet in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php:522
#33 Twig_Template:getAttribute in /home/accessip/public_html/cache/gantry5/admin/twig/ae/ae6f7a3b9e7f3ac46517e0e0199b1e1ff5cf0c7d82dbab8ef7a1422fc4f916f2.php:41
#32 __TwigTemplate_7f0b804926adf165da630ad30eb4a8e8cffc613607655015ce17dc441561b876:doDisplay in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php:432
#31 Twig_Template:displayWithErrorHandling in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php:403
#30 Twig_Template:display in /home/accessip/public_html/cache/gantry5/admin/twig/c4/c4ec628d4c8959bd5bfb6d2027840799c85c2eaec4683e4f432cced62dfbf30f.php:35
#29 __TwigTemplate_01c62f4c6e3c78bfbf195598cc8364bffb709c97f2cc40f9882d92237f0e0be3:doDisplay in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php:432
#28 Twig_Template:displayWithErrorHandling in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php:403
#27 Twig_Template:display in /home/accessip/public_html/cache/gantry5/admin/twig/00/00257f4731d690262d473d0ecc0e68e86e300bae511ff0ec4f96f5208180b822.php:32
#26 __TwigTemplate_28e671f205cb8ee173638bfca68ab7b0fd5c0a93c02cc74f82413eab462f75a0:doDisplay in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php:432
#25 Twig_Template:displayWithErrorHandling in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php:403
#24 Twig_Template:display in /home/accessip/public_html/cache/gantry5/admin/twig/df/df4ed5a52f94eff58f3191724d6292b71a9da64065f084df059bddd254f05333.php:104
#23 __TwigTemplate_384776485d81bf84180533e7f14878746281d17b65f085ea5e310c0f338cba08:block_gantry_content_wrapper in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php:215
#22 Twig_Template:displayBlock in /home/accessip/public_html/cache/gantry5/admin/twig/df/df4ed5a52f94eff58f3191724d6292b71a9da64065f084df059bddd254f05333.php:91
#21 __TwigTemplate_384776485d81bf84180533e7f14878746281d17b65f085ea5e310c0f338cba08:block_content in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php:215
#20 Twig_Template:displayBlock in /home/accessip/public_html/cache/gantry5/admin/twig/a1/a100508a030524c5bdf5d68967a040bcd35ae81c47d5adf197dc8a6235864110.php:48
#19 __TwigTemplate_5f6c280cd698df7929efedbbe121634512ea854ec18a320780702f7d5acecbe3:doDisplay in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php:432
#18 Twig_Template:displayWithErrorHandling in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php:403
#17 Twig_Template:display in /home/accessip/public_html/cache/gantry5/admin/twig/df/df4ed5a52f94eff58f3191724d6292b71a9da64065f084df059bddd254f05333.php:29
#16 __TwigTemplate_384776485d81bf84180533e7f14878746281d17b65f085ea5e310c0f338cba08:doDisplay in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php:432
#15 Twig_Template:displayWithErrorHandling in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php:403
#14 Twig_Template:display in /home/accessip/public_html/cache/gantry5/admin/twig/cc/cc872e9a41abed15b14b103f4575c3e9c84102adb92be345f40ecc637d9ed055.php:23
#13 __TwigTemplate_4668309e01223c11b88b3d70a3cbcc72fdf4b581120807e568b1792344cce512:doDisplay in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php:432
#12 Twig_Template:displayWithErrorHandling in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php:403
#11 Twig_Template:display in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php:411
#10 Twig_Template:render in /home/accessip/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Environment.php:363
#9 Twig_Environment:render in /home/accessip/public_html/libraries/gantry5/classes/Gantry/Component/Theme/AbstractTheme.php:162
#8 Gantry\Component\Theme\AbstractTheme:render in /home/accessip/public_html/libraries/gantry5/classes/Gantry/Component/Router/Router.php:163
#7 Gantry\Component\Router\Router:getErrorResponse in /home/accessip/public_html/libraries/gantry5/classes/Gantry/Component/Router/Router.php:63
#6 Gantry\Component\Router\Router:dispatch in /home/accessip/public_html/administrator/components/com_gantry5/gantry5.php:57
#5 require_once in /home/accessip/public_html/libraries/src/Component/ComponentHelper.php:381
#4 Joomla\CMS\Component\ComponentHelper:executeComponent in /home/accessip/public_html/libraries/src/Component/ComponentHelper.php:356
#3 Joomla\CMS\Component\ComponentHelper:renderComponent in /home/accessip/public_html/libraries/src/Application/AdministratorApplication.php:101
#2 Joomla\CMS\Application\AdministratorApplication:dispatch in /home/accessip/public_html/libraries/src/Application/AdministratorApplication.php:159
#1 Joomla\CMS\Application\AdministratorApplication:doExecute in /home/accessip/public_html/libraries/src/Application/CMSApplication.php:267
#0 Joomla\CMS\Application\CMSApplication:execute in /home/accessip/public_html/administrator/index.php:51

**Comment by thexmanxyz** [comment] 2017-12-11 21:27
@Eggeriley Please remove the hashtags because the reference to other issues which they should not they polute the issue history thanks!

**Comment by w00fz** [comment] 2017-12-11 22:04
This seems to be caused by your recent deprecation cleanup @mahagr  (https://github.com/gantry/gantry5/commit/f7d9c9ddd043abd92b828fd5f237fb2f02b630ac#diff-298a2b5178e139bfff6d69c8328946c9)

Also, edited @Eggeriley comment to put that content in a block code.

**Comment by mahagr** [comment] 2017-12-11 22:18
If you are having issues, please install the previous version of Gantry (Code / Releases here in GitHub) to the site and the issue should be gone. I'll take a look at this tomorrow.

**Comment by mahagr** [comment] 2017-12-11 22:32
Fixed in latest CI.

**Closed** 2017-12-11 22:34 UTC
Labels: joomla, regression

**Comment by w00fz** [comment] 2017-12-11 22:52
@LukeDouglas2 which version of the CI are you running? it should be `e3b020f`

**Comment by LukeDouglas2** [comment] 2017-12-11 22:54
@w00fz Hmmm..not sure what your referring to.  What does Cl represent?

**Comment by w00fz** [comment] 2017-12-11 22:57
CI means Continuous Integration, see here: http://gantry.org/downloads#ci-builds

The fix Matias has put in is available in the latest CI Build, so you have to grab it and install it.
If you downloaded it before the system actually completed creating the package, you might have just downloaded a broken version again.

See in the admin which version of Gantry you are running, the ones with the fix is the latest on the site which is `e3b020f`

**Comment by LukeDouglas2** [comment] 2017-12-11 23:05
@w00fz Duh!!  Someone told me that a couple of years ago and I just completely forgot. Age is having it's effect on me, I guess. LOL

I downloaded the joomla-pkg_gantry5_develop.zip file and that fixed it.  I'll update this when the updated release candidate is ready for download.

**Comment by mahagr** [comment] 2017-12-12 07:42
Gantry 5.4.21 released.

**Comment by jamgit** [comment] 2017-12-12 23:21
Okay, so now this update breaks things in Wordpress. 

1. Cannot save layout in backend on any outlines.
2. Adds error message on front of site: 
"Caught exception: Layout reference conflict on #simplecontent-7644"

![screen shot 2017-12-12 at 3 12 24 pm](https://user-images.githubusercontent.com/7244493/33913743-f8d47af4-df4f-11e7-9f75-46afd8f92b21.png)
![screen shot 2017-12-12 at 3 12 53 pm](https://user-images.githubusercontent.com/7244493/33913754-0155d9ac-df50-11e7-9f6c-59e685bfe6b4.png)

**Comment by mahagr** [comment] 2017-12-13 07:08
@jamgit It has already been fixed and the new release can be found on our download page. Automatic WP update should be online soon.
