### ISSUE TITLE
Problem with the touch behaviour on smartphones in sub-menu items

### ISSUE THREAD

**Issue by NosyWeb** [gantry/gantry5#1620] opened 2016-10-17 13:37 UTC
In the toggle mobile menu, when I put my finger to scroll down (swap move), it works, but once I take it off, it opens the sub-items of the item where I previouly put my finger to scroll down.
Consequently, I can't navigate in items which are at the bottom of my mobile menu.

In other words : once your finger take it off the screen (when you swap move to scroll down), it opens the menu item as if we click (touch) on it.

The forum post : 
http://www.rockettheme.com/forum/joomla-template-topaz/262813-mobile-menu-navigation-problem

The issue occurs only on the Topaz RT template.

Many thanks.

**Comment by NosyWeb** [comment] 2016-12-22 19:51
Hello,

Do you plan to fix the issue in the next Gantry release ?
I tried with Gantry 5.4.2 but the problem is always here :-(

Regards.

**Comment by newkind** [comment] 2016-12-23 12:23
What mobile browser are you using?

**Comment by NosyWeb** [comment] 2016-12-23 12:57
Hello,

I use Chrome and Firefox on Android 5, but the problem seems to be here on all devices (iOS / Android / Windows...).

**Comment by DamirPecnik** [comment] 2016-12-28 01:30
Working fine we can close this one, user code was hiding the arrow links ...

**Comment by NosyWeb** [comment] 2017-01-02 08:43
Hello,

Thanks for your help.
Sorry fo the late reply, I was in holidays.

I had just hidden the arrow links, nothing else. Now I added the arrow links but the problem is the same :-(
I don't know where can I look for this issue...

Regards.

**Comment by DamirPecnik** [comment] 2017-01-02 18:17
The arrows are the links to the next menu and not the word, i removed the code now arrows show try now ...

**Comment by DamirPecnik** [comment] 2017-01-16 23:20
The problem is with the menu items if you have them longer then the screen size you need to tap and scroll but it opens the link ...

**Comment by NosyWeb** [comment] 2017-02-06 08:37
Hello,

Did you find something on this issue which affect all Gantry 5 templates since the beginning ?

Thanks.

Regards.

**Comment by alansegar** [comment] 2017-06-18 11:20
This is affecting the base Gantry 5 Helium template for me making it impossible to open some of the menus on mobiles. I'm able to reproduce this on the demo site at http://demo.gantry.org/ by using an android mobile in portrait orientation with Chrome which has a low enough screen resolution / size to cause at least the last menu item (Styles) to be hidden from view due to insufficient screen height to show the whole menu. 
Scrolling down (touch - drag up - release finger) to bring the Styles menu item into view opens the sub-menu of whichever item was touched when starting the scroll, rather than scrolling the top-level menu without opening any sub-menus.
On sites with more top-level menu items which all have sub-menus, the problem affects high resolution mobiles as well and is much easier to reproduce even in landscape orientation (I'm trying to use it with 11 top-level menu items which all have sub-menus).
Is there any workaround / fix that you know of for this? Thanks.

**Comment by w00fz** [comment] 2017-06-28 16:57
![helium particles demonstration gantry 5 - en toutes lettres 2017-06-28 09-54-13](https://user-images.githubusercontent.com/11734/27649812-bf76e0d0-5be7-11e7-9f33-3e6f6a930028.png)

There are two types of arrows, the one with background/box and the one without.

With background/box it means that the parent item is both a parent of sub items as well as a link itself. This combination triggers the menu item to split the arrow into its own clickable/touchable element, hence the box. When you click the item itself it will open the link of the parent item, when you click on the boxed arrow, it will expand the sub menu.

Without background/box it means the menu item is either a non-linked parent or a link without children. This means that clicking the item itself either expand the submenu or takes you to its link.

I'm trying to understand what is the issue exactly, I'm testing with the inspector of the browser as I don't have an easy way to check on an android. However this seems to be working as expected.

Can you perhaps take a screencast of the issue?

Thank you.

**Comment by NosyWeb** [comment] 2017-06-28 17:07
Thanks for this clarification.

On my side, you can try here with a smartphone : 
http://sainte-maxime.zoomsurmaville.com/

You can try to navigate in the Shopping & Artisans sub-items to understand the issue. 
You will see we can't navigate in the sub-sub-items of the Shopping & Artisans sub-items which are at the end of list because a touch to scroll down will open the item that we touch (we are forced to touch a sub-item to scroll down the list of sub-items).

Regards.

**Comment by N8Solutions** [comment] 2017-06-28 17:57
I visited his site and see the behaviour he is describing. Performing a "Tap & Drag" to scroll through the menu will open the menu item that was used for the "Tap & Drag" upon removing your finger from the screen.

This is also visible on the http://demo.gantry.org website. Even though the menu isn't long enough to necessitate a "Tap & Drag", nevertheless if you try to perform a "Tap & Drag" then release, whichever menu item your finger was on during that process will open.

I just tried this on another site using the Requiem theme and it has the same behaviour. All of the top level menu items on that site are non-links, merely place holders. They have sub menus and performing a tap-drag-release causes the sub menu to open.

I can see where this would be a problem if there menus with a lot of items. Scrolling through on a touch screen would make this troublesome.

**Comment by alansegar** [comment] 2017-06-28 19:19
[gantryMobileMenuBug.zip](https://github.com/gantry/gantry5/files/1109955/gantryMobileMenuBug.zip)
See attached wmv video clip (inside gantryMobileMenuBug.zip) showing this on an Android phone.

**Comment by w00fz** [comment] 2017-06-28 22:04
Thank you all for the details, I'll look into this.

**Comment by w00fz** [comment] 2017-06-29 18:36
Thanks for all the details and help in getting me to reproduce the issue. I was able to and it is now sorted.

Cheers.

**Closed** 2017-06-29 18:36 UTC
Labels: bug

**Comment by N8Solutions** [comment] 2017-06-29 18:38
@w00fz Great Job Djamil! Thank you for taking care of this so quickly!

**Comment by alansegar** [comment] 2017-07-01 09:48
@w00fz Thanks for fixing this. I've installed the latest CI build and can confirm it at least partially fixes the issue for me. There are still some minor issues, but it's now possible to access all the menu items. 
One issue is that after scrolling the top-level menu to access an item that was off the bottom of the screen, when the sub-menu opens it is scrolled down by the same amount as the top-level menu was. This means that some (or all) of the sub-menu items are scrolled off the top of the screen and there's no indication to the user that they need to scroll up to see the items. Is it possible to open the sub-menu in the fully scrolled-up state instead?
The other issue is that the problem partially comes back after a period of time. I'm still trying to find the exact set of steps to recreate this but it only happens after the user has either stayed on a page for a while and / or interacted with the menu several times (navigating in and out of sub-menus without clicking any items that cause a page reload. It only affects some of the top-level items rather than all of them (even though all the top-menu items are the same type of item to open a sub-menu). The menu items that are affected changes each time. Re-loading the page / navigating to a different page makes it work normally again for a while. If I can find an exact set of steps to recreate this I'll add them here.

**Comment by mahagr** [comment] 2017-07-03 09:42
@alansegar If you find out more about the above issues, please create a new issue from them.
