### ISSUE TITLE
Gantry / Helium not compatible with Bedrock

### ISSUE THREAD

**Issue by inorbita** [gantry/gantry5#1429] opened 2016-07-11 13:20 UTC
I'm using [Bedrock](https://roots.io/bedrock/) which sets up a slightly different WP folder structure (/wp-content > /app). Upon activation of the Helium theme I receive the following errors on the frontend > http://pastebin.com/cQfngRP1 and a white screen in the wp backend. Seems Gantry uses and depends on certain absolute paths?

**Comment by mahagr** [comment] 2016-07-11 15:59
No, its the opposite. Your WP installation has some absolute paths making Gantry unable to figure out what would be the relative path for the URLs.

**Comment by inorbita** [comment] 2016-07-11 17:41
Ah I see, thanks for getting back to me. I will take it to the roots.io support forum.

**Comment by inorbita** [comment] 2016-07-12 08:33
According to a dev at roots.io: "Bedrock uses proper WP supplied methods of changing paths". So apparently it's not an issue within either Gantry or Bedrock, might it be the Timber plugin then?

**Comment by mahagr** [comment] 2016-07-12 09:06
The issue you see in Timber has been fixed and will be in their next update.

It's likely issue in the way that those paths are set; the issue is kind of in our end as we do not support paths outside of root of the WP installation for directories where we have assets (css/js/images). 

The failing line is this:

```twig
<link rel="stylesheet" href="{{ url('gantry-assets://css/font-awesome.min.css') }}" type="text/css"/>
```

It looks the files from theme and Gantry plugin. Where are those located in?

**Comment by inorbita** [comment] 2016-07-12 09:27
This is the [folder structure](https://roots.io/bedrock/docs/folder-structure/) of Bedrock. The theme is installed in /app/themes and plugins in /app/plugins. The WP core files are located in /wp. So themes and plugins are indeed installed outside of the WP root. Is there a workaround for the time being, or should I just wait for the official TImber and Gantry/Helium updates?

**Comment by mahagr** [comment] 2016-07-12 09:58
Thanks, we need to take a look into this. For now I don't think there are workarounds that I can think of, this is something we didn't take into consideration. We are probably using wrong path to define doc root; I think it points to `wp` folder instead of the main level.

**Comment by inorbita** [comment] 2016-07-12 11:56
I don't know really, the dev over there didn't seem very willing to help me out. Unlisting my topic > https://discourse.roots.io/t/gantry-5-and-bedrock-absolute-path-issues/7168

**Comment by swalkinshaw** [comment] 2016-07-12 13:27
👋 all we're doing is setting some WP constants:

* https://github.com/roots/bedrock/blob/24da66fdc430859c3bc5d590db9ddcdd15f73baf/config/application.php#L44-L46
* https://github.com/roots/bedrock/blob/24da66fdc430859c3bc5d590db9ddcdd15f73baf/config/application.php#L82

We don't define any constants for the web root itself since it shouldn't be needed. You could build it from `ABSPATH` if you needed to (it's just the parent dir).

This shouldn't be Bedrock specific either. It's common to have WP in its own [subdirectory](https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory) which is the pattern we follow.

**Comment by nikola3244** [comment] 2016-07-12 13:32
Related? #1394

**Comment by inorbita** [comment] 2016-07-12 17:52
@nikola3244 I don't think so. In the case of Bedrock it's not only Wordpress in a subdirectory, it's the entire /wp-content folder (renamed /app) outside of the wp core folder.

**Comment by QWp6t** [comment] 2016-10-23 14:15
Also worth noting [this line should probably be using `plugin_dir_path()`](https://github.com/gantry/gantry5/blob/develop/platforms/wordpress/gantry5/gantry5.php#L31).

> WordPress makes use of the following constants when determining the path to the content and plugin directories. **These should not be used directly by plugins or themes**, but are listed here for completeness.

See: https://codex.wordpress.org/Determining_Plugin_and_Content_Directories#Constants

**Comment by TipTopCoder** [comment] 2017-01-30 16:56
May I know whether you guys can fix this Uri Locator issue?

**Comment by mahagr** [comment] 2017-02-03 08:29
Just notes to myself:

Setting up bedrock with Gantry:

```
composer create-project roots/bedrock
composer require "wpackagist-plugin/gantry5"
```

And follow instructions in https://roots.io/bedrock/docs/installing-bedrock/

**Comment by TipTopCoder** [comment] 2017-02-03 08:34
```
[InvalidArgumentException]                                                   
  Could not find package wpackagist-plugin/gantry5 at any version for your mi  
  nimum-stability (stable). Check the package spelling or your minimum-stabil  
  ity
```

I got this error when trying your suggestion, look like there is a problem with wp packagist gantry5

**Comment by mahagr** [comment] 2017-02-03 08:36
For me it works just fine. Above installed both wp and the latest version of Gantry 5.4.6. I am investigating the issue and hoping to find a solution for it.

**Comment by mahagr** [comment] 2017-02-03 11:26
@swalkinshaw 

I was able to make Gantry work with Bedrock, but `WPINC` seems to point to a wrong folder (`web/wp-includes` instead of `web/wp/wp-includes`). I cannot see if anything breaks because of that, but it might be something you would like to take a look.

It would also be great if there was a way to detect Bedrock by `define()` and if there was another define pointing to `$webroot_dir`, something like:

```php
define('WP_BEDROCK', $version);
define('WP_BEDROCK_WEBROOT', $webroot_dir);
```

**Closed** 2017-02-03 11:43 UTC
Labels: enhancement, wordpress

**Comment by mahagr** [comment] 2017-02-03 11:56
@QWp6t Unfortunately plugin_dir_path() isn't symlink safe and messes up the path.

**Comment by swalkinshaw** [comment] 2017-02-03 23:22
@mahagr why does Gantry need to know the web root path?

Bedrock doesn't have a constant to identify it because there should be no reason to specifically detect it. We don't want plugins hardcoding anything just for Bedrock. It may be non-standard, but everything is done in an official WP way.

**Comment by QWp6t** [comment] 2017-02-04 00:19
@mahagr what exactly is the symlink issue?

`plugin_dir_path()` is essentially a wrapper for `dirname()`, which only does string parsing.

If you want it to return the symlink path, then use `plugin_dir_path()`.

If you want it to return the real path, then still use `plugin_dir_path()`, but also wrap in [`realpath()`](http://php.net/manual/en/function.realpath.php).

Either way, it seems like you can use `plugin_dir_path()`. Or am I missing something here?

**Comment by mahagr** [comment] 2017-02-06 08:23
@swalkinshaw 

Gantry doesn't need to know webroot as such, but it does need to know common ancestor folder for the CMS installation because of it uses relative folders for example in CSS files, which are generated dynamically. As in Bedrock some of the files are under `/app` and some under `/wp`, the common root for all the files is the folder below both of them.

@QWp6t 

The issue is that I don't want to return `realpath()`, so I cannot use `__FILE__` either. I want to return virtual path, which is under the webroot. We are using symlinks in our development environments pointing to GIT repositories which are outside of webroot. At the same time, we need js/css/image file locations for the website and the files can be anywhere depending on used CMS, theme overrides etc.
