### ISSUE TITLE
Skeleton download link broken on getgrav.com

### ISSUE THREAD

**Issue by salgua** [gantry/gantry5#1804] opened 2017-01-16 11:24 UTC
On https://getgrav.org/downloads/skeletons, if I click on the "download" link of the helium skeleton, it try to open the page "https://github.com/gantry/gantry5/releases/download/@version@/grav-skeleton-helium-site-@version@.zip" returning a 404 error.

**Comment by mahagr** [comment] 2017-01-17 12:46
I can reproduce the issue, link seems to be wrong.

**Comment by w00fz** [comment] 2017-01-17 19:51
Thanks this is fixed now.

**Closed by w00fz** 2017-01-17 19:51 UTC
Labels: bug, grav
