### ISSUE TITLE
"cache path not defined for compiled files"

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#478] opened 2015-06-17 08:58 UTC
A number of members on RT forum are reporting that they are getting the above fatal error on the front-end of their sites. Usually clearing cache makes the error go away only for it to return again later.

I have discussed this at length with @mahagr and he has all the details of member sites to investigate further. As yet neither of us can reproduce this issue on our local systems.

![fatal](https://cloud.githubusercontent.com/assets/11683218/8203159/b935e8aa-14d7-11e5-811c-d148a9c1bb8f.png)

**Comment by mahagr** [comment] 2015-06-17 09:36
I'm able to reproduce this in users sites (by clearing cache or just by waiting long enough), but not in my local environment.

Not sure what is causing this, but it has already happened for at least 3 people.

**Comment by gospelpowered** [comment] 2015-06-20 00:08
Its happening to only one of my sites too, but not to the other 4 i have on g5. Really strange, not sure what the difference between them is :(

**Comment by hiddenmagic** [comment] 2015-06-21 12:27
We have the same issue as well with one of our client sites. Let me know if you would like me to make it available to you. We can spin up a server with a copy of the site, and give you full access if need be. We're entirely baffled by this bug.

**Comment by mahagr** [comment] 2015-06-22 09:16
Can you guys try something for me before I'm going to make more radical change to fix this?

https://github.com/gantry/gantry5/blob/develop/src/classes/Gantry/Component/File/CompiledYamlFile.php#L23

Can you move this line 2 lines up to be the first thing in the class? Not sure if it fixes the issue, but for some reason that variable cannot be found and it may be because of the wrong ordering...

**Comment by gospelpowered** [comment] 2015-06-22 09:35
I'm trying that now and will report back with results soon

**Comment by hiddenmagic** [comment] 2015-06-22 09:37
Just tried it, no luck here. Thanks for the effort.

**Comment by hiddenmagic** [comment] 2015-06-22 09:41
Also, a strange addition to this, which is something I noticed much by accident when it started. At least in my case, when the error appears. If I refresh the page the error appears again. However, if I hold the F5 button for about 3-4 seconds and refresh rapidly. The page will appear without error.

I'm not joking, and I have no idea what to make of that. @gospelpowered try it on your end, I'm curious if that's specific to my issue.

Thanks!

**Comment by gospelpowered** [comment] 2015-06-22 09:43
Hey @hiddenmagic that is strange. For me it works just fine when i refresh it again, the error page only appears when i first go to the site and then on refresh the site loads fine for a while. I don't need to hold F5 or refresh multiple times.

**Comment by mahagr** [comment] 2015-06-22 09:44
@hiddenmagic We are just talking on this in Gitter chat (private one). If you want to join, we can continue in https://gitter.im/gantry/gantry5

**Comment by hiddenmagic** [comment] 2015-06-22 09:46
Curious. Well, it's a mystery to us, but we're in good hands for sure.

**Comment by mahagr** [comment] 2015-06-22 11:13
Looks like the issue has been fixed. @hiddenmagic has also another issue, which I'm looking now.

Closing the issue, be free to reopen if the above issue gets back.

**Comment by gospelpowered** [comment] 2015-06-22 11:22
Awesome thanks @mahagr

**Comment by gospelpowered** [comment] 2015-06-22 11:40
Its back again however slightly different now, as discussed with @mahagr

**Comment by mahagr** [comment] 2015-06-22 12:32
@hiddenmagic Your second issue seems to be related to cart clearing up all directories in ```/cache``` every page load. Because of that the directory gets created before component gets rendered, but is being removed before Gantry 5 tries to use it.

**Comment by Christianlocal** [comment] 2015-06-23 01:25
"Looks like the issue has been fixed. @hiddenmagic has also another issue, which I'm looking now.
Closing the issue, be free to reopen if the above issue gets back."

I have the issue that was raised by #478 can someone explain how to fix this? Thanks!

**Comment by w00fz** [comment] 2015-06-23 01:36
Try installing the CI Builds, you can find more details about what they are and how to use them here: http://gantry.org/blog/gantry5-ci-builds

You can find the packages in the Downloads section under CI Builds (http://gantry.org/downloads#ci-builds)

**Comment by Christianlocal** [comment] 2015-06-23 02:52
i downloaded the latest and installed. I received a different error this time. 

An exception has been thrown during the rendering of a template ("Who just removed Gantry 5 cache folder? Try reloading the page if it fixes the issue") in "@nucleus/content/spacer.html.twig" at line 1.

**Comment by mahagr** [comment] 2015-06-23 06:00
@Christianlocal 

Yup, you have the same error as @hiddenmagic, some extension keeps removing every extra folder in your Joomla cache directory. Check if you have K2 Store component. This was the offending line for him: /components/com_k2store/controllers/mycart.php Line 46: K2StoreUtilities::cleanCache();

Gantry 5 relies on compiling most files into PHP, so component or plugin doing this would make the site to load slow even if I worked around the issue.

**Comment by gospelpowered** [comment] 2015-06-23 06:21
This is another error i got. 
![crikey there was an error3](https://cloud.githubusercontent.com/assets/12219933/8300043/14f2b026-19b3-11e5-91d3-c034d6680e82.jpeg)

**Comment by mahagr** [comment] 2015-06-23 12:21
There is still some bug causing first load to fail for some people.

**Comment by mahagr** [comment] 2015-06-27 06:55
User is now reporting following issue instead:

http://www.rockettheme.com/forum/joomla-template-ethereal/243963-gantry-5-issues-still-exist-undefined-error-traps

**Comment by mahagr** [comment] 2015-07-09 11:13
Looks like this one was wrong alarm: user reported that he fixed the issue by reinstall.

**Closed by mahagr** 2015-07-09 11:13 UTC
Labels: bug
