### ISSUE TITLE
Whoops reporting "loaded already" modules

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1821] opened 2017-01-24 10:11 UTC
Discussed with @mahagr 

There have been several instances where whoops is reporting that PHP modules have been loaded already. This seems to have changed recently. Although this is highly likely to be a php configuration issue it is unfortunate that Gantry 5 (specifically whoops) is spotting these and therefore Gantry 5 breaks (forever spinner, or whoops message). 

It would be good if we can just log these errors and carry on and have Gantry 5 not break under these situations.

**Comment by mahagr** [comment] 2017-01-25 10:16
I did not mean to close this issue. Not sure if the above fix works as I'm unable to reproduce the issue.

**Closed** 2017-01-27 10:29 UTC
Labels: bug
