### ISSUE TITLE
circle animations on buttons - WordPress

### ISSUE THREAD

**Issue by Wicko-Design** [gantry/gantry5#2819] opened 2021-06-03 15:04 UTC
WordPress 5.7.2
Gantry 5.4.37
Helium 5.4.34
PHP 7.4.16

I have noticed that I am getting animated circle buttons on all buttons in the Gantry Theme area. 
I get these every time I press save and they increase in number as I type new content into any field. 
![Screenshot 2021-06-03 at 15 50 05](https://user-images.githubusercontent.com/11837048/120667385-59219680-c485-11eb-8c0f-343398907436.png)

**Comment by mahagr** [comment] 2021-06-07 08:45
I have never seen anything like this. Maybe you should start by checking if FA is being loaded two times or if there's something else weird going on with CSS/JS?

**Comment by marktaylor46** [comment] 2021-06-07 08:47
This has been fixed - it was caused by a third-party "ns fontawesome" widget that broke all the icons in g5 admin.

**Comment by Wicko-Design** [comment] 2021-06-07 08:49
Hi @mahagr
I mentioned this on the Rockettheme forum and we discovered the issues is a conflict with the Fontawesome plugin. 
We have fixed the issue on our site. Wouldn't normally use the Fontawesome plugin but was suggested by them to try and fix an issue with multiple versions of fontawesome being loaded and effecting the page speed. 
regards
David

**Comment by mahagr** [comment] 2021-06-07 08:51
Feel free to close the issue if it has been resolved. Thanks for the update.

**Closed** 2021-06-07 09:25 UTC
Labels: question, wordpress
