### ISSUE TITLE
Use of iframe breaks Offcanvas button function on Android Firefox

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#662] opened 2015-07-28 16:48 UTC
http://www.rockettheme.com/forum/joomla-template-callisto/244247-mobile-navigation-not-working-on-firefox-for-android?start=10

The issue with the offcanvas menu not opening (clicking the hamburger icon won't show the menu) on android firefox has been narrowed down to the use of iframe.

It seems that even embedding a youtube video on the site breaks the functionality.

The code in question sits in a custom_html module with the following code:

```
<div><iframe src="//www.youtube.com/embed/EKHvlojQJFU" width="550" height="309" frameborder="0" allowfullscreen="allowfullscreen"></iframe></div>
```

**Comment by w00fz** [comment] 2015-07-31 22:22
This looks like a duplicate of #557

**Comment by RustyR** [comment] 2015-08-04 10:38
This is no duplicate of #557. In that issue Android/FF was tested with a clean Rocketlauncher install without a youtube iFrame placed in a custom_html module.

Offcanvas menu is working on all pages without iframes and not working on the pages with. After de-publicating the modules with iFrames the offcanvas menu is working everywhere!

Tested and able to reproduce the issue over and over again on Genymotion virtual device Google Nexus 4 running Android 4.4.4 and 5.0.0

**Comment by w00fz** [comment] 2015-08-10 20:53
I considered it a duplicate because it involves Android Firefox there too. I believe the issue is purely related to the browser itself and there isn't much we can do about it.

**Comment by nikola3244** [comment] 2016-04-28 21:15
This bug is not there anymore on currently latest Firefox 46, Android 5.1.1.
Can be closed.

![screenshot_2016-04-28-23-12-38](https://cloud.githubusercontent.com/assets/15911110/14901688/0cef09a0-0d97-11e6-9bc7-5b0ac674d6ae.jpg)

**Comment by w00fz** [comment] 2016-04-28 21:22
Thanks for checking. I also added a few extra checks for the iframe as can be seen in https://github.com/gantry/gantry5/issues/1224#issuecomment-209773162

**Closed by w00fz** 2016-04-28 21:22 UTC
Labels: bug
