### ISSUE TITLE
Second level menu items not opening on ANDROID mobile in firefox

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#553] opened 2015-07-09 16:11 UTC
I've see this raised by two members now and had it confirmed that this happens (I don't have Android device myself) - so I though I'd raise a ticket and see if there are any suggestions.

Two RT forum posts are:

http://www.rockettheme.com/forum/joomla-template-callisto/244530-firefox-android-does-not-open-second-level-items-in-mobile-menu?start=0#1216805

http://www.rockettheme.com/forum/joomla-template-callisto/244247-mobile-navigation-not-working-on-firefox-for-android?start=10#1216237

David and I tried to recreate and couldn't

**Comment by kat05** [comment] 2015-07-09 18:34
i am unable to replicate the first issue and have left comments on the forum topic.

the 2nd issue, is caused by a custom html module containing an iframe. once that module is disabled, the menu works fine for me. left another response to that member as well.

**Comment by w00fz** [comment] 2015-07-09 18:53
Closing since they aren't really G5 issues.

**Closed by w00fz** 2015-07-09 18:53 UTC
Labels: question
