### ISSUE TITLE
Refreshing page in layout manager switches outline dropdown to previous item

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#972] opened 2015-11-04 12:38 UTC
Steps to reproduce :

1. Go to theme admin
2. Switch to any outline in the top left dropdown
3. Confirm that the url changes and outline switches too
4. Go to the Layout tab
5. Refresh the page - dropdown will show the previous item even though the url is untouched

**Comment by w00fz** [comment] 2015-11-04 17:48
Works fine for me?

**Comment by sural98** [comment] 2015-11-05 09:16
G5 won't remember the last instance.
Probably the same issue with https://github.com/gantry/gantry5/issues/968
5.2.x update caused the issue.

**Comment by newkind** [comment] 2015-11-05 09:46
This seems to be Firefox issue only. @w00fz was investigating it yesterday.

**Comment by mahagr** [comment] 2015-11-06 11:07
I'm not able to reproduce the issue at all, FF/Chrome in Linux. Did you force reloading the page to update js?

**Comment by w00fz** [comment] 2015-11-07 04:10
I think it's just Firefox being weird the way it caches form fields such as select. I tried to workaround it but nothing much i can do, hard refresh always fix the issue and it seems to be only Firefox.

I'm closing it for now as it's just one odd browser issue that only recently appeared so it might just be a bug of Firefox.

**Closed by w00fz** 2015-11-07 04:10 UTC
Labels: bug, important
