### ISSUE TITLE
Font picker: sourcesanspro font adding wrong font string

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1384] opened 2016-06-21 12:36 UTC
I checked this in several templates and they all behave the same... If you change a font in an outline (on the styles tab) using the font picker to any of the "source sans pro" fonts then you get a string of

"family=Source+Sans+Pro" which obviously then get's used in the CSS and in invalid and that font is not rendered.

E.g. Topaz
![2016-06-21_11-58-14](https://cloud.githubusercontent.com/assets/11683218/16229516/21cf464e-37b5-11e6-9f2d-87a4efad76d3.png)
![2016-06-21_11-57-36](https://cloud.githubusercontent.com/assets/11683218/16229520/246c9262-37b5-11e6-96f8-68b14d4cc107.png)

Forum issue: http://www.rockettheme.com/forum/joomla-template-topaz/260057-font-family-changing-bug?start=0#1299810

**Comment by adi8i** [comment] 2016-06-21 13:01
Hello,

I tested on a client website and it works fine, it's a custom wordpress template, using the latest CI Build. I use both Dosis and Source Sans Pro.

![capture](https://cloud.githubusercontent.com/assets/9744973/16230272/46df2c7e-37c9-11e6-964f-0f4c36df31a2.PNG)
![2](https://cloud.githubusercontent.com/assets/9744973/16230275/477e7202-37c9-11e6-83be-f8e940cfadb9.PNG)

**Comment by marktaylor46** [comment] 2016-06-21 13:05
I am testing in Firefox. Try it there. Also I am testing Topaz and the "promo" font field.

**Comment by marktaylor46** [comment] 2016-06-21 13:08
![2016-06-21_14-07-06](https://cloud.githubusercontent.com/assets/11683218/16230513/ac0eb318-37b9-11e6-83a4-27b53559aba4.png)

**Comment by adi8i** [comment] 2016-06-21 13:13
Hey, I trust you, you are a trusty member ;). I was just saying i couldn't reproduce it, probably a variable typo in template.

**Comment by marktaylor46** [comment] 2016-06-21 13:14
heh thanks. I couldn't find the root cause but it's definitely wrong.

**Comment by JoomFX** [comment] 2016-06-21 13:20
@marktaylor46 Mark, I'm also not able to reproduce it with the latest CI build.
I think that the problem is in the template (I see that you've checked several templates).
But here's the thing:

1. The issue cannot be reproduced if the correct syntax is being used:

```
font-family: get-font-family($fonts-menu-font);
```

2. The exact issue CAN be reproduced if there is a wrong syntax, for example:

```
font-family: $fonts-menu-font;
```

**Comment by marktaylor46** [comment] 2016-06-21 13:30
I guess it must be somewhere in /components/com_gantry5/js/google-fonts.json but I can't see where the issue is....

**Comment by JoomFX** [comment] 2016-06-21 13:43
Hey Mark,

The problem is in Topaz.
Go to `rt_topaz/scss/topaz/sections/_header.scss` and find the following code on line 313:

```
font-family: $font-family-promo;
```

Replace the above code with:

```
font-family: get-font-family($font-family-promo);
```

That should do it :wink:

**Comment by marktaylor46** [comment] 2016-06-21 13:46
Ah yes. Unfortunately I fear this sort of thing is wrong in many templates so I will raise internal tickets for the templates.

**Comment by marktaylor46** [comment] 2016-06-21 14:09
I think Gantry 5 itself needs checking too since I found reference to font-family: $xxxxxxx in many places in core.

**Comment by w00fz** [comment] 2016-06-21 14:54
Where exactly?

**Comment by marktaylor46** [comment] 2016-06-21 14:57
too numerous to mention buthere's a screenshot of my scan.

![2016-06-21_15-56-23](https://cloud.githubusercontent.com/assets/11683218/16234237/d01277f4-37c8-11e6-8aeb-ef4ebc3d86c0.png)

**Comment by adi8i** [comment] 2016-06-21 14:59
Gantry looks fine to me, this is the search result.

```
Searching for $font-family in/wp-content/plugins/gantry5/engines/nucleus/scss (Found 8 matches in 4 files)

/wp-content/plugins/gantry5/engines/nucleus/scss/configuration/nucleus/_typography.scss:
	17: $font-family-mono:              "Menlo", "Monaco", monospace !default;

/wp-content/plugins/gantry5/engines/nucleus/scss/nucleus/theme/_typography.scss:
	51: 	font-family: $font-family-mono;

/wp-content/plugins/gantry5/engines/nucleus/scss/vendor/bourbon/css3/_font-face.scss:
	2:   $font-family,
	12:     font-family: $font-family;
	17:       $font-family,

/wp-content/plugins/gantry5/engines/nucleus/scss/vendor/bourbon/helpers/_font-source-declaration.scss:
	13:   $font-family,
	26:     svg:   "#{$file-path}.svg##{$font-family}" format("svg")

Found 8 matches in 4 files 
```

**Comment by w00fz** [comment] 2016-06-21 22:27
@marktaylor46 The list in your screenshot are just regular default fonts passed via the variables `$font-family-default` and `$font-family-mono` like you would regularly do.

The ones in Styles are using our sass mixin which supports built-in, local and google fonts.
The variables from Styles are of the type `$font-family-title` or `$font-family-promo`, etc, which need to be handled via the template `scss` using the `get-font-family()` mixin as explained above. 

If you don't use the mixin, you end up passing to the `font-family` css rule just the plain value of whatever the user has put into the font picker field. In this case, if a user picks a google font it will render as `font-family: "family=Ubuntu"`, which is correct.

As Ivo and Adrian have pointed out, I think the issue is just in our template for that promo font only, everything else in Gantry looks good to me.

Please open this in our internal issue tracker and assign to @hexplor / @newkind. We might as well have a deep look in case there are others like the promo that are affected.

Cheers! 👯

**Closed by w00fz** 2016-06-21 22:27 UTC
Labels: question

**Comment by marktaylor46** [comment] 2016-06-22 07:09
Thanks @w00fz - Already done - thanks for double-checking. @hexplor is going to check the others I found.
