### ISSUE TITLE
Gantry 5.5-dev- Cannot add a Joomla Article Particle via Module - J4 beta 7

### ISSUE THREAD

**Issue by dmleeman** [gantry/gantry5#2800] opened 2021-05-10 10:53 UTC
Here is one for J4 beta 7, G5.5-dev + Helium 5.5-dev PHP 8.0.3
I cannot add a Joomla Article within a Module

https://imgur.com/a/JtVym6B

**Comment by mahagr** [comment] 2021-05-10 17:22
Is this for Joomla 4 only?

**Comment by dmleeman** [comment] 2021-05-11 13:30
Add a Gantry 5 Joomla Article within a Module
Tested in 3.9.26, PHP 8.0.3, G5.5-dev

Result: OK

Seems to be J4 only

**Comment by mahagr** [comment] 2021-05-17 08:36
I'm not able to reproduce this issue in my local using today's build. The particle picker works just fine and I'm able to save the particle. Can you test again?

**Comment by dmleeman** [comment] 2021-05-17 09:21
Ok, after installing updated version g5.5-dev 17/05/21 I still get the error

500 Internal Server Error
Oops, An exception has been thrown during the rendering of a template ("Unknown fetch type '8'")..

500 suggests maybe a local issue but it's a decent host and server. And there is no problem on J3 install (on PHP8.0.3)

:0

**Comment by mahagr** [comment] 2021-05-17 09:31
Can you enable debug from Joomla and see if we can figure out what is going on from the trace back?

**Comment by dmleeman** [comment] 2021-05-17 09:33
Will do

**Comment by mahagr** [comment] 2021-05-20 05:54
If you enable debug, it will show a lot more information on `500 Internal Server Error`, or specifically where in the code the error happened. Basically, I need the file and line where the exception was thrown and where it was called from.

**Comment by dmleeman** [comment] 2021-05-20 07:23
Hmm, ok after another attempt the error now seems to be [object Object]

Ok, I've got debug turned on and in the console there are the above tabs. The event triggers nothing in the log files, I can see my login but nothing else.
There are entries under Session but they look like log in too
The attempt to call in Joomla Articles Particle just gives me this

`37 statements were executed8.66ms124.88KB
SELECT @@SESSION.sql_mode;75μs1.59KB/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php:293Copy
SHOW FULL COLUMNS FROM `q08pj_users`427μs4.64KB/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php:584Copy
SELECT *
FROM `q08pj_users`
WHERE `id` = :userid113μs3.32KBParams/libraries/src/Table/User.php:105Copy
SELECT `g`.`id`,`g`.`title`
FROM `q08pj_usergroups` AS `g`
INNER JOIN `q08pj_user_usergroup_map` AS `m` ON `m`.`group_id` = `g`.`id`
WHERE `m`.`user_id` = :muserid55μs1.71KBParams/libraries/src/Table/User.php:135Copy
SELECT `session_id`
FROM `q08pj_session`
WHERE `session_id` = :session_id LIMIT 1115μs2.27KBParams/libraries/src/Session/MetadataManager.php:191Copy
UPDATE `q08pj_session`
SET `guest` = :guest
	, `time` = :time
	, `userid` = :user_id
	, `username` = :username
	, `client_id` = :client_id
WHERE `session_id` = :session_id112μs992BParams/libraries/src/Session/MetadataManager.php:329Copy
SELECT `extension_id` AS `id`,`element` AS `option`,`params`,`enabled`
FROM `q08pj_extensions`
WHERE `type` = 'component' AND `state` = 0 AND `enabled` = 1315μs4.06KB/libraries/src/Component/ComponentHelper.php:429Copy
SELECT `id`,`rules`
FROM `q08pj_viewlevels`82μs1.11KB/libraries/src/Access/Access.php:1020Copy
SELECT `b`.`id`
FROM `q08pj_user_usergroup_map` AS `map`
LEFT JOIN `q08pj_usergroups` AS `a` ON `a`.`id` = `map`.`group_id`
LEFT JOIN `q08pj_usergroups` AS `b` ON `b`.`lft` <= `a`.`lft` AND `b`.`rgt` >= `a`.`rgt`
WHERE `map`.`user_id` = :userId60μs2.92KBParams/libraries/src/Access/Access.php:929Copy
SELECT `folder` AS `type`,`element` AS `name`,`params` AS `params`,`extension_id` AS `id`
FROM `q08pj_extensions`
WHERE `enabled` = 1 AND `type` = 'plugin' AND `state` IN (0,1) AND `access` IN (:preparedArray1,:preparedArray2,:preparedArray3,:preparedArray4,:preparedArray5)
ORDER BY `ordering`868μs11.88KBParams/libraries/src/Plugin/PluginHelper.php:301Copy
SELECT `id`,`name`,`rules`,`parent_id`
FROM `q08pj_assets`
WHERE `name` IN (:preparedArray1,:preparedArray2,:preparedArray3,:preparedArray4,:preparedArray5,:preparedArray6,:preparedArray7,:preparedArray8,:preparedArray9,:preparedArray10,:preparedArray11,:preparedArray12,:preparedArray13,:preparedArray14,:preparedArray15,:preparedArray16,:preparedArray17,:preparedArray18,:preparedArray19,:preparedArray20,:preparedArray21,:preparedArray22,:preparedArray23,:preparedArray24,:preparedArray25,:preparedArray26,:preparedArray27,:preparedArray28,:preparedArray29,:preparedArray30,:preparedArray31,:preparedArray32,:preparedArray33,:preparedArray34,:preparedArray35,:preparedArray36,:preparedArray37,:preparedArray38)162μs10.25KBParams/libraries/src/Access/Access.php:369Copy
SELECT `extension_id` AS `id`,`element` AS `option`,`params`,`enabled`
FROM `q08pj_extensions`
WHERE `type` = 'library' AND `element` = :element194μs1.85KBParams/libraries/src/Helper/LibraryHelper.php:162Copy
UPDATE `q08pj_extensions`
SET `params` = :params
WHERE `type` = 'library' AND `element` = :element167μs880BParams/libraries/src/Helper/LibraryHelper.php:126Copy
SELECT `s`.`template`,`s`.`params`,`s`.`inheritable`,`s`.`parent`
FROM `q08pj_template_styles` AS `s`
LEFT JOIN `q08pj_extensions` AS `e` ON `e`.`type` = 'template' AND `e`.`element` = `s`.`template` AND `e`.`client_id` = `s`.`client_id`
WHERE `s`.`client_id` = 1 AND `s`.`home` = '1'
ORDER BY `s`.`home`79μs1.02KB/libraries/src/Application/AdministratorApplication.php:265Copy
SELECT `element`,`name`,`client_id`,`extension_id`
FROM `q08pj_extensions`
WHERE `type` = 'language' AND `state` = 0 AND `enabled` = 1222μs1.22KB/libraries/src/Language/LanguageHelper.php:229Copy
SHOW FULL COLUMNS FROM `q08pj_modules`523μs5.2KB/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php:584Copy
SELECT `element`,`client_id`
FROM `q08pj_extensions`
WHERE `extension_id` = :extensionid AND `type` = 'module'149μs4.21KBParams/administrator/components/com_modules/src/Model/ModuleModel.php:712Copy
SELECT `menuid`
FROM `q08pj_modules_menu`
WHERE `moduleid` = :moduleid160μs1.61KBParams/administrator/components/com_modules/src/Model/ModuleModel.php:755Copy
SELECT `enabled`
FROM `q08pj_extensions`
WHERE `type` = 'plugin' AND `folder` = 'system' AND `element` = 'languagefilter'226μs872B/libraries/src/Language/Multilanguage.php:82Copy
SELECT DISTINCT a.id, a.title, a.name, a.checked_out, a.checked_out_time, a.note, a.state, a.access, a.created_time, a.created_user_id, a.ordering, a.language, a.fieldparams, a.params, a.type, a.default_value, a.context, a.group_id, a.label, a.description, a.required,l.title AS language_title, l.image AS language_image,uc.name AS editor,ag.title AS access_level,ua.name AS author_name,g.title AS group_title, g.access as group_access, g.state AS group_state, g.note as group_note
FROM q08pj_fields AS a
LEFT JOIN `q08pj_languages` AS l ON l.lang_code = a.language
LEFT JOIN q08pj_users AS uc ON uc.id=a.checked_out
LEFT JOIN q08pj_viewlevels AS ag ON ag.id = a.access
LEFT JOIN q08pj_users AS ua ON ua.id = a.created_user_id
LEFT JOIN q08pj_fields_groups AS g ON g.id = a.group_id
WHERE 
(`a`.`context` = :context AND `a`.`state` = :state) AND 
(`a`.`group_id` = 0 OR `g`.`state` = :gstate)
ORDER BY a.ordering ASC170μs5.17KBParams/libraries/src/MVC/Model/BaseDatabaseModel.php:144Copy
SHOW FULL COLUMNS FROM `q08pj_template_styles`527μs3.27KB/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php:584Copy
SELECT *
FROM q08pj_template_styles
WHERE `home` = '1' AND `client_id` = '0'70μs1.34KB/libraries/src/Table/Table.php:800Copy
SELECT `element`,`name`,`enabled`
FROM `q08pj_extensions`
WHERE `client_id` = :clientid AND `type` = 'template' AND `enabled` = :state304μs1.88KBParams/administrator/components/com_modules/src/Helper/ModulesHelper.php:153Copy
SELECT DISTINCT `position`
FROM `q08pj_modules`
WHERE `client_id` = :clientid
ORDER BY `position`59μs2.05KBParams/administrator/components/com_modules/src/Helper/ModulesHelper.php:82Copy
SELECT `a`.`id` AS `value`,`a`.`title` AS `text`
FROM `q08pj_viewlevels` AS `a`
GROUP BY `a`.`id`,`a`.`title`,`a`.`ordering`
ORDER BY `a`.`ordering` ASC39μs1.11KB/libraries/src/HTML/Helpers/Access.php:274Copy
SELECT DISTINCT `a`.`id` AS `value`,`a`.`title` AS `text`,`a`.`alias`,`a`.`level`,`a`.`menutype`,`a`.`client_id`,`a`.`type`,`a`.`published`,`a`.`template_style_id`,`a`.`checked_out`,`a`.`language`,`a`.`lft`,`e`.`name` AS `componentname`,`e`.`element`
FROM `q08pj_menu` AS `a`
LEFT JOIN `q08pj_extensions` AS `e` ON `e`.`extension_id` = `a`.`component_id`
WHERE `a`.`client_id` = :clientId AND `a`.`published` != -2
ORDER BY `a`.`lft` ASC762μs4.59KBParams/administrator/components/com_menus/src/Helper/MenusHelper.php:223Copy
SELECT *
FROM `q08pj_menu_types`
WHERE `menutype` <> '' AND `client_id` = :clientId
ORDER BY `title`,`menutype`54μs2.01KBParams/administrator/components/com_menus/src/Helper/MenusHelper.php:255Copy
SELECT `element`,`name`
FROM `q08pj_extensions`
WHERE `client_id` = :clientId AND `type` = 'template' AND `enabled` = 1213μs1.76KBParams/libraries/src/Form/Field/ChromestyleField.php:257Copy
SELECT `id`
FROM `q08pj_assets`
WHERE `name` = :component154μs1.64KBParams/libraries/src/Form/Field/RulesField.php:200Copy
SELECT `parent_id`
FROM `q08pj_assets`
WHERE `id` = :assetId145μs1.64KBParams/libraries/src/Form/Field/RulesField.php:224Copy
SELECT COUNT(`id`)
FROM `q08pj_usergroups`39μs872B/libraries/src/Helper/UserGroupsHelper.php:210Copy
SELECT *
FROM `q08pj_usergroups`
ORDER BY `lft` ASC41μs1.95KB/libraries/src/Helper/UserGroupsHelper.php:270Copy
SELECT `m`.`id`,`m`.`title`,`m`.`module`,`m`.`position`,`m`.`content`,`m`.`showtitle`,`m`.`params`,`mm`.`menuid`
FROM `q08pj_modules` AS `m`
LEFT JOIN `q08pj_modules_menu` AS `mm` ON `mm`.`moduleid` = `m`.`id`
LEFT JOIN `q08pj_extensions` AS `e` ON `e`.`element` = `m`.`module` AND `e`.`client_id` = `m`.`client_id`
WHERE 
(
(
(`m`.`published` = 1 AND `e`.`enabled` = 1 AND `m`.`client_id` = :clientId AND `m`.`access` IN (:preparedArray1,:preparedArray2,:preparedArray3,:preparedArray4,:preparedArray5)) AND 
(`m`.`publish_up` IS NULL OR `m`.`publish_up` <= :publishUp)) AND 
(`m`.`publish_down` IS NULL OR `m`.`publish_down` >= :publishDown)) AND 
(`mm`.`menuid` = :itemId OR `mm`.`menuid` <= 0)
ORDER BY `m`.`position`,`m`.`ordering`1.1ms18.31KBParams/libraries/src/Cache/Controller/CallbackController.php:124Copy
SELECT *
FROM `q08pj_extensions`
WHERE `element` = :element AND `type` = :type LIMIT 1327μs4.91KBParams/libraries/src/Extension/ExtensionHelper.php:469Copy
SELECT `postinstall_message_id`,`extension_id`,`title_key`,`description_key`,`action_key`,`language_extension`,`language_client_id`,`type`,`action_file`,`action`,`condition_file`,`condition_method`,`version_introduced`,`enabled`
FROM `q08pj_postinstall_messages`
WHERE `extension_id` = :eid AND `enabled` = :published66μs4.34KBParams/libraries/src/Cache/Controller/CallbackController.php:124Copy
SELECT *
FROM `q08pj_extensions`
WHERE `type` = 'plugin' AND `enabled` = 1 AND `folder` = 'twofactorauth'401μs3.77KB/plugins/twofactorauth/totp/postinstall/actions.php:35Copy
SELECT `a`.*,`u`.`name` AS `user_from`
FROM `q08pj_messages` AS `a`
INNER JOIN `q08pj_users` AS `u` ON `u`.`id` = `a`.`user_id_from`
WHERE `a`.`user_id_to` = :id AND `a`.`state` = :state
ORDER BY a.date_time DESC90μs2.77KBParams/libraries/src/MVC/Model/BaseDatabaseModel.php:144`

**Comment by mahagr** [comment] 2021-05-24 07:41
I'm prioritizing Joomla 3.9 fixes over 4.0, so I haven't looked into this one yet.

**Comment by dmleeman** [comment] 2021-05-24 07:42
no problem, I have other projects on too so completely understand

**Comment by mahagr** [comment] 2021-06-23 08:02
I'm still not able to reproduce the issue. Did you try this with Helium and the default theme set to use it?

**Comment by dmleeman** [comment] 2021-06-23 09:02
I will take another look this weekend with the latest builds, using the Helium default. I had added a UIKIT3 Atom as part of the Joomlead particle package but that was the only significant difference.

**Comment by mahagr** [comment] 2021-09-10 11:47
I think this one has been fixed in the latest build.

**Comment by dmleeman** [comment] 2021-09-10 16:22
Thanks Matias, I shall try the latest builds this week.

**Closed** 2021-09-17 15:52 UTC
Labels: bug, joomla4, fixed
