### ISSUE TITLE
For "Custom HTML" module, the Title renders twice

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#129] opened 2015-04-27 17:32 UTC
For the "Custom HTML" modules the elements render twice (both the `moduletable` and the `h3` ). 
Have a look at this [this screenshot](http://i.imgur.com/cqyoaZb.png)

**Comment by kevlardev** [comment] 2015-04-27 19:48
I can't seem to find a way to replicate this. Each custom html module i create in Joomla appears properly for me in all positions. Could you walk me through the steps you took setting up this particular module so I can try to reproduce it exactly?

**Comment by JoomFX** [comment] 2015-04-27 20:20
@kevlardev When I read your reply I thought that the issue comes from my Installation (Joomla 3.4 Quickstart Package of a Template built on Gantry4).

So I just tested on a clean installation (Joomla 3.4, G5_Beta4 and Hydrogen Beta 4) and I was able to reproduce the issue again.

Have a look at [this video](https://youtu.be/wAZH2wzVH1k) . It shows everything.
Let me know if you need anything else.

**Comment by w00fz** [comment] 2015-04-27 23:32
This was actually an issue, @kevlardev fixed it in 961728 and  3d09a3.
I want to still keep this open because I saw some oddities on a non-dev environment where the title wasn't rendering. We need to run a quick test once we have B5 ready for release.

**Comment by sural98** [comment] 2015-04-28 15:15
Where is the corresponding file located in the installation package for "themes/hydrogen/joomla/html/modules.php" of https://github.com/gantry/gantry5/commit/3d09a3ca6fbd913aefdce3046d46afa34a43c52f?

**Comment by adi8i** [comment] 2015-04-28 16:21
As i understand it should be in `templates/g5_hydrogen` , but is not any html there, maybe you want to create one :)

**Comment by w00fz** [comment] 2015-04-28 17:35
Correct this is not in B4 yet but will be in B5. You can see it on the `develop` branch under [themes/hydrogen/joomla/html](https://github.com/gantry/gantry5/tree/develop/themes/hydrogen/joomla/html)

**Comment by kat05** [comment] 2015-04-29 04:11
this is still an issue i believe. it appears randomly for me, between editing the layout in the yaml file and editing the layout directly in the template's layout manager. i can't pinpoint yet how it can be replicated every time, but will keep playing with it.

**Comment by kat05** [comment] 2015-04-29 04:14
this is extremely weird, it can be broken on a certain page, then when browsing to another page and going back to the first page again, it can then be suddenly work fine. i'll have more infos soon.

**Comment by adi8i** [comment] 2015-04-29 04:42
I don't have this kind of issue :)

**Comment by kat05** [comment] 2015-04-29 18:37
with the latest packages from this morning, everything seems to be fine for me so far. :)

**Comment by w00fz** [comment] 2015-04-29 23:22
Sweet, I'm going to close this one for now. Feel free to reopen if this is still an issue in the next beta.

**Closed by w00fz** 2015-04-29 23:22 UTC
Labels: question
