### ISSUE TITLE
Widget particle in Layout manager should load custom widget css/js

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#677] opened 2015-08-04 13:56 UTC
Widget particle in Layout manager should load custom widget css/js that might be needed to support widget settings form.

**Comment by GiannisZ** [comment] 2016-08-04 07:08
The problem is with js files because css files are loaded correctly!

**Comment by newkind** [comment] 2016-08-04 07:13
@mahagr we need this for next big release ;)

**Comment by mahagr** [comment] 2021-09-10 17:51
WordPress 5.8+ is moving towards a new system, which makes this feature less interesting and duplicate.

**Comment by mahagr** [comment] 2021-09-10 18:04
Deprecated Widgets in Layout Manager.

**Closed by mahagr** 2021-09-10 18:04 UTC
Labels: wontfix, wordpress, feature
