### ISSUE TITLE
Responsive Menu issues

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#30] opened 2015-03-31 08:08 UTC
There are two issues I noticed with the responsive menu. The first one was reproduced by other users as well.

First issue - the responsive menu does not load at all. It loads perfectly fine on the Homepage (first screenshot), but when you go to another page it does not load. The Menu button (hamburger) is there and when you click it the offcanvas appears but it is empty (second screenshot):

![alt](http://i.imgur.com/lNMt1SI.png)

![alt](http://i.imgur.com/Eb66qwG.png)

Second issue - the submenus in the responsive menu cannot be expanded:

![alt](http://i.imgur.com/tOoHAjt.png)

**Comment by mahagr** [comment] 2015-03-31 08:28
@w00fz Can you take a look on this one?

**Comment by w00fz** [comment] 2015-03-31 21:04
I cannot reproduce issue 1 but regarding issue 2 we are aware, it didn't make it into beta1.
We are about to rework the menu JS on frontend so a lot is going to change and probably will solve both of these issues.

**Comment by w00fz** [comment] 2015-04-01 00:19
Issue 1 has been  fixed in ef3583c, Im going to leave this open until we get issue 2 sorted out.

Thanks!

**Comment by w00fz** [comment] 2015-04-05 05:56
We are going to rework the menu pretty much entirely based on the limitations we came across, the great feedbacks provided by you guys and the issues we have found and that have been reported. We have a good plan of attack and to keep things easier to track and maintain I created an unified ticket (see #58) where all the issues regarding the menu are now grouped together.

I'm going to close this issue, if there's anything else to add please feel free to comment in issue #58.

Thank you!

**Closed by w00fz** 2015-04-05 05:56 UTC
Labels: bug
