### ISSUE TITLE
Times New Roman shows on Mac if you use the font selector

### ISSUE THREAD

**Issue by uglyeoin** [gantry/gantry5#1884] opened 2017-02-22 12:37 UTC
https://files.gitter.im/gantry/gantry5/d3Yy/blob
https://files.gitter.im/gantry/gantry5/C9jo/blob

If I select "Lato" and use a weight like 700, it will arrive as Lato:700.  using the font selector it adds family=Lato:700.  

When viewed on Mac it shows Times New Roman.  I believe this is because it does not add "sans-serif" at the end.  If I use a local file it does show sans-serif at the end and does not use "Family=".  

If I add Sans-serif on the end, it does not work.  If I do it manually in the custom.scss then it works fine, which is why I think this is the problem.  When I view on PC it shows Arial, which is also incorrect.

I'm using Hydrogen, latest version of Gantry.  

Here's link to a live site: http://greenenergyelectrical.squareballoon.co.uk/index.php you can see from any of the headings that they have "lato" crossed out in the inspect element.  Thus they are not loading correctly or something odd is going on.

**Comment by w00fz** [comment] 2017-06-28 01:14
This is working fine for me.
`family=` means you are using Google Fonts. You can't append `sans-serif` there because the font is getting loaded via the Google Fonts API.

Check your inspector and see if you are getting any 404 while trying to load that font. By the sounds of it, it looks like the font is not loading at all and just defaulting to the Times New Roman default font.
This is not an issue though, the issue is the Google font failing to load. It could be caused by some browser extension you are running perhaps.

I understand this is an issue from February, can you set up a page where I can look at the issue again? The link you provided doesn't seem to be using Lato anymore.

**Comment by uglyeoin** [comment] 2017-06-28 09:37
@w00fz Are you using a Mac?  Are you using the font selector to choose the font with a weight?  Perhaps if the default font is sans-serif it will work, maybe it needs to be a serif font by default to show Times New Roman. If you would like a test site I can facilitate it and give you access.  Anything to help.

**Comment by w00fz** [comment] 2017-06-28 16:00
Yes I'm on mac. If you could set up a page for me to look at that would be very useful.

Thanks

**Comment by uglyeoin** [comment] 2017-07-01 10:53
How can I get you the details?

**Comment by uglyeoin** [comment] 2017-07-01 10:54
I'll gitter them to you

**Comment by w00fz** [comment] 2017-07-01 13:15
hey @uglyeoin,
I looked at the site you left me in DM but the Lato font is working fine.

Try looking if perhaps you have the font installed locally with Font Book, if you do perhaps try deleting it and see if that helps.

**Comment by uglyeoin** [comment] 2017-07-01 14:25
@w00fz Just have another quick check if you have time, I have removed an SCSS referring to Lato which I had used to overcome the issue.  I think the issue is because originally the font is set to serif but when choosing the new font via the font picker it sets it as Lato but does not add sans-serif.  I'll try to find out what system the client has i.e. his version of mac/OS/browser.

**Comment by w00fz** [comment] 2017-07-01 14:57
It is still working for me. You should check the inspector (I left you a note on Gitter btw).

If you inspect the page and highlight any header (h1, h2), then select the Elements tab and Computed, it will tell you which font is using and how.

When I highlight an h2 this is what I get:

![home 2017-07-01 07-55-48](https://user-images.githubusercontent.com/11734/27763148-efef78ce-5e32-11e7-8882-303f2a175793.png)

**Comment by uglyeoin** [comment] 2017-07-01 15:14
@w00fz sorry just saw it, thanks, good tip.  Yes, I can inspect the element but it shows for me, so I'll teach the client.  I'll come back with any findings and provide screenshots if possible.

**Comment by mahagr** [comment] 2017-11-23 15:30
Closing as it cannot be reproduced. Please comment if it's still an issue.

**Closed by mahagr** 2017-11-23 15:30 UTC
Labels: cannot reproduce
