### ISSUE TITLE
Helium: No space between Joomla modules

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1674] opened 2016-11-12 20:47 UTC
is it possible to put a gap in between Joomla modules that are in the same module position from within the gantry admin.

**No Gap**
![module stack](https://cloud.githubusercontent.com/assets/319997/20240787/f84cbbaa-a918-11e6-8057-0a3245ffeec9.png)

**With Gap**
![modules with gap](https://cloud.githubusercontent.com/assets/319997/20244485/8255a682-a97c-11e6-875a-fcf3149af53f.png)

I can manage it with custom CSS but I am sure I have managed to do this without custom CSS by using a Gantry admin settings. I have tried all of the options that i can find but I am stuck or wrong.

If it is not possible from within Gantry admin, can this be added as a feature, a variation or a core setting  could be used to set this. A per module option for variations, not just the whole position.

The reason is I would like to have each module styled as separate blocks so they look nicer

Thanks

**Comment by newkind** [comment] 2016-11-14 08:22
You're talking about horizontal or vertical space ?

**Comment by shoulders** [comment] 2016-11-14 08:44
my website is https://quantumwarp.com/

Just to clarify. in the image 2 example (i used photoshop) you can see 2 joomla modules, these modules are in the smae module positions but they have a gap inbetween them and also the variations are applied to them individually (ie title and box border)

**Comment by newkind** [comment] 2016-11-14 08:56
Thanks for the link. So the issue is in a way you placed your modules. For some reason all of them have `platform-content` class and there is only 1 module per such class, where the behavior is that first found module should not have margins and paddings.

Can you please show me a picture of Layout Manager with these modules placed in the layout ? Did you add any extra classes like `platform-content` in the block tab (or anywhere else) ?

**Comment by shoulders** [comment] 2016-11-14 09:13
@newkind 

The second image was an example (either done by photoshop or using 2 module positions) to show you how I would like the modules to look. This is better for joomla.

The following is from my live site.

**Layout page**
![layout-manger](https://cloud.githubusercontent.com/assets/319997/20258880/b78ab7de-aa49-11e6-9e08-914c4c2310d7.png)

content-right section = no classes or other changes.

**content-right module position classes**
![module position classes](https://cloud.githubusercontent.com/assets/319997/20258885/beb613e6-aa49-11e6-9bd3-8c65ebe45cc0.png)

> Did you add any extra classes like platform-content in the block tab (or anywhere else) ?

I have had a look and can not find anywhere I have used these

If you want i can make some temporary login/ftp details for you

**Comment by mahagr** [comment] 2016-11-14 09:24
@newkind I just checked the code and `platform-content` class gets added individually for main page content and for each module which isn't a particle. Basically in Joomla it's purpose is to initialize/fix Bootstrap styling, which conflicts with the rules used in Nucleus CSS.

To fix this, I would add some margin into Joomla module class.

**Comment by JoomFX** [comment] 2016-11-14 10:33
Hey Matias,

Shouldn't this be handled by the template?
I'm a bit worried that if you add some margin to the Joomla modules it will affect the current templates.
It will be fine if you add it to Helium/Hydgrogen but it might not be fine if you add the margin to Gantry core.

**Comment by shoulders** [comment] 2016-11-14 10:36
could this not be done by a variation on the module position?

**Comment by mahagr** [comment] 2016-11-14 12:18
@JoomFX This issue is for Helium (which is in Gantry repository).

**Comment by alexparcs** [comment] 2017-02-23 10:02
Hi, I have the same issue. Is there any way to fix this problem?

**Comment by hexplor** [comment] 2017-03-15 15:52
This is not an issue. All modules positions has a correct margins and padding. Altering it in any way will cause lots of issues. Problem is that @shoulders applied variations directly into module position: 
![module](https://monosnap.com/file/eeW6u5UqUr7iqqWx5qeGcUuO763PFS.png)

Instead applying it into module.
![](https://monosnap.com/file/fKq2xW6E9h7u7bzGCsBuXAAFurVoYM.png)

This is how it works if you want to inject modules using modules positions. Remember that you can still use variations like you did. Just use gantry particle "Module Instance" instead. It's easier, more comfortable and way more powerful.

![](https://monosnap.com/file/Qyu5txYjczOYoNKek5A10Lhicx8RNb.png)

**Comment by shoulders** [comment] 2017-03-15 20:51
I will give it a go and see what happens but this make variations pointless when using joomla modules and because joomla uses modules quite a lot I do see this as an issue.

**Comment by mahagr** [comment] 2017-03-20 08:40
Or you can create your own module chrome (read more from Joomla docs) which uses custom HTML to get the look you want.

**Comment by hexplor** [comment] 2017-06-01 11:38
I'm closing this.

**Closed by hexplor** 2017-06-01 11:38 UTC
Labels: bug, joomla
