### ISSUE TITLE
mod_menu overrides in Joomla not working with Gantry Menu

### ISSUE THREAD

**Issue by N8Solutions** [gantry/gantry5#2273] opened 2018-04-10 13:00 UTC
I have discovered an issue with Firefox that is quite annoying and I have figured out a way around it using a Joomla! override.  However the override does not work for Gantry templates. I have applied the override to several different installations and the outcome is the same every time. It works on the standard Beez or Protostar template but when a Gantry template is applied it fails.
Here is a link to the discussion thread with the solution over on the Joomla! forum.
https://forum.joomla.org/viewtopic.php?f=706&t=960992

Any ideas on how I can get the override to work with the Gantry templates?
I believe it has something to do with the fact that the Gantry menu has it's own setting for the "Link Target" and the override is not passed through to it properly.

@w00fz I know the menu is your area of expertise though if you @mahagr or @newkind have any input for me I would welcome it very much!

**Comment by N8Solutions** [comment] 2018-04-10 14:40
Quick update, I found the file **Menu.php** with the following code from lines 310 to 323

```php
                // Get default target from Joomla.
                switch ($menuItem->browserNav)
                {
                    default:
                    case 0:
                        // Target window: Parent.
                        $target = '_self';
                        break;
                    case 1:
                    case 2:
                        // Target window: New with navigation.
                        $target = '_blank';
                        break;
                }
```

As a test I modified the **_blank** to **_self** but unfortunately the Gantry menu does not explicitly define and add **_self** to the link since it is the default. However, due to the behavior of a pinned tab in Firefox, unless it is explicitly defined the browser will open open it in a new Tab/Window.

I know this shouldn't be necessary but in this circumstance it is due to the way that a pinned Tab in Firefox is functioning.

**Comment by thexmanxyz** [comment] 2018-04-11 11:03
@N8Solutions How about overriding `menu.html.twig` shouldn't that be enough to create a custom fix?!

**Comment by N8Solutions** [comment] 2018-04-12 06:16
@thexmanxyz I'm not really sure if it would be or not. Like I said, I replaced **_blank** with **_self** in the `menu.php` file however because **_self** is the default it is not explicitly written. So even though I changed it I need to have a way for it to be defined explicitly otherwise it won't solve anything.

I had a look at the `menu.html.twig` file located in `\engines\common\nucleus\particles` and it imported `_self` as `SELF`. If there is a way to tell it to explicitly add `_self` to menu items that are listed as URL I do not know how to do it.

In the file there is this section

```twig
{% macro displayItem(item, menu, context, dropdown_type) %}
    {% import _self as SELF %}
    {% if item.type == 'particle' and not item.options.particle.enabled %} 
        {% set enabled = 0 %}
    {% endif %}
    {% if item.visible and item.enabled and enabled|default(1) %}
        {% set title = item.icon_only or item.link_title ? ' title="' ~ item.link_title|default(item.title)|e ~ '"' %}
        {% set label = item.icon_only and (item.image or item.icon) ? ' aria-label="' ~ item.title|e ~'"' %}
        {% set active = menu.isActive(item) ? ' active' %}
        {% set dropdown = item.level == 1 ? ' g-' ~ item.getDropdown() %}
        {% set parent = item.children ? ' g-parent' %}
        {% set target = item.target != '_self' ? ' target="' ~ item.target|e ~ '"' %}
        {% set rel = item.rel ? ' rel="' ~ item.rel|e ~ '"' %}

        <li class="g-menu-item g-menu-item-type-{{ item.type }} g-menu-item-{{ item.id }}{% if not item.dropdown_hide %}{{ parent }}{% endif %}{{ active }}{{ dropdown }} {% if item.url and item.children %}{% if not item.dropdown_hide %}g-menu-item-link-parent{% endif %}{% endif %} {{ item.class|default('') }}"
                {{- SELF.getCustomWidth(item, menu, 'item', dropdown) }}
                {%- if context.particle.renderTitles|default(0) %} title="{{ item.title }}"{% endif %}>
            {% if item.url %}<a class="g-menu-item-container{{ item.anchor_class ? ' ' ~ item.anchor_class }}" href="{{ item.url }}{{ item.hash }}"{{ (title ~ label ~ target ~ rel)|raw }}>
            {% else %}<div class="g-menu-item-container{{ item.anchor_class ? ' ' ~ item.anchor_class }}" data-g-menuparent=""{{ label|raw }}>{% endif %}
                {% if item.image %}
                    <img src="{{ url(item.image) }}" alt="{{ item.title }}" />
                {% elseif item.icon %}
                    <i class="{{ item.icon }}" aria-hidden="true"></i>
                {% endif %}
                {% if item.url %}
                    <span class="g-menu-item-content">
                        {{ SELF.displayTitle(item) }}
                    </span>
                    {% if (item.children) and not item.dropdown_hide -%}
                        <span class="g-menu-parent-indicator" data-g-menuparent=""></span>
                    {%- endif %}
                {% else %}
                    {% if item.type == 'particle' %}
                        {{ SELF.displayParticle(item, context) }}
                    {% elseif item.type == 'heading' %}
                        <span class="g-nav-header g-menu-item-content"{{ title|raw }}>{{ SELF.displayTitle(item) }}</span>
                    {% else %}
                        <span class="g-separator g-menu-item-content"{{ title|raw }}>{{ SELF.displayTitle(item) }}</span>
                    {% endif %}
                        {% if (item.children) and not item.dropdown_hide -%}
                            <span class="g-menu-parent-indicator"></span>
                        {%- endif %}
                {% endif %}
            {% if item.url %}</a>
            {% else %}</div>{% endif %}
            {% if (item.children) -%}
                {{ SELF.displaySubmenu(item, menu, context, dropdown_type) }}
            {%- endif %}
        </li>
    {% endif %}
{% endmacro %}
```

Any help in modifying either the `menu.html.twig` file or the `menu.php` file to accomplish this would be greatly appreciated.

**Comment by thexmanxyz** [comment] 2018-04-12 10:33
@N8Solutions As an additional information that `{% import _self as SELF %}` has nothing to do with a link target. This is just the TWIG syntax for accessing e.g. macros inside a macro.

**Comment by N8Solutions** [comment] 2018-04-12 11:00
@thexmanxyz Your suggestion worked! Thank you very much! I was looking to have the `target` attribution explicitly written out for URL links only in the  menu but your suggestion does it for all the menu items so it still accomplishes what I need.

The only reason I need this is because I have a subdomain associated with a main site and want to make the navigation between the 2 sites appear seamless through the navigation. The issue is that with Firefox, a link in a pinned tab will always open in a new tab/window. This is unique to Firefox and does not happen in Chrome or IE. In the off chance someone will pin the tab of this site it will help maintain the seamless navigation between the 2 sites.

Thank you for the clarification regarding the TWIG syntax.

Even though your suggestion works for me I'm still going to leave this ticket open so the Gantry team can take a look at it. The initial issue still remains where the override in Joomla is not applied to the menu. Maybe they can even implement your suggestion to the menu as a new option for future revisions.

Thanks again!

**Comment by thexmanxyz** [comment] 2018-04-12 11:08
I modify this post a bit later however as a start you can also do this so you only write out `target="_self"`for links which start with http otherwise the old routine is used. Probably this is the exact behaviour you need :).

```
{% if item.url matches '/^http.*/' %}
  {% set target = ' target="' ~ item.target|e ~ '"' %}
{% else %}
  {% set target = item.target != '_self' ? ' target="' ~ item.target|e ~ '"' %}
{% endif %}
```

**Comment by N8Solutions** [comment] 2018-04-12 11:26
@thexmanxyz Thank you once again! Where would I add that code in the `menu.html.twig` file?

**Comment by thexmanxyz** [comment] 2018-04-12 11:34
@N8Solutions simply replace that previous line with that five as before :). np

**Comment by N8Solutions** [comment] 2018-04-12 11:50
That worked great! Thank you!

**Comment by thexmanxyz** [comment] 2018-04-12 12:26
@N8Solutions Glad to hear that it worked :), np. 

Ok, I understand, so it's as I thought, I did fly over the post you linked, yesterday, but didn't try to fully understand the actual issue. However it has to be said that this is an issue which has to be addressed by Mozilla directly. This is just a fix to force the intended behaviour for pinned tabs but it shouldn't be your / our task to do this, actually.

So basically it has to be said that the `menu.php` has nothing to do with the Gantry menu and it also works as intended so there might be no reason that changes to that php file reflect in the main gantry menu.

I'm pretty sure this isn't a bug and works as expected. If you include the menu not based on the menu particle the `menu.php` change will be effective and reflected by the site. You can see the Gantry menu as a separate render item. If I had to guess I would also say the Gantry team won't include this fix into the branch because it's a Firefox bug and we should not try to fix issues of other apps by including exceptions.

You should leave it open but I would say if someone of the Gantry members has noticed and read through /close it.

**Comment by N8Solutions** [comment] 2018-04-12 12:40
It would still be nice if this was an option to choose from and moreover that if an override is implemented in Joomla that it is passed through to the Gantry menu. After going through this with you I'm not sure that is possible due to the way the Gantry menu has been developed.

Also, I do not believe Mozilla will fix this "issue" because they do not seem to see it as an issue. I found [this thread](https://support.mozilla.org/questions/1190923) in which the accepted suggestion was to change the behavior of Firefox. While that solution is fine for end users it would appear it is working as intended on their part and they expect coders and developers to explicitly define the `_self` if a link is not to be opened in a new Tab/Window.

I also realize that this scenario of mine is rare and that most people will not be using 2 sites intertwined like this. Nevertheless I want to try for the best user experience possible.

Regardless of the outcome on either side I will keep the solution you gave me and use it in the future. I also imagine that I will need to update this override when future versions of Gantry make changes to the `menu.html.twig.` file.

Thank you again @thexmanxyz for your help and for providing a solution to this.

**Comment by thexmanxyz** [comment] 2018-04-12 12:57
@N8Solutions No the override of `menu.php` should not be passed over it's a completely different thing. These two things are completely different and shouldn't be mixed and probably can't even be. 

There is just one thing that would make sense and what I would suggest that can be implemented within Gantry. However I have to some investigations where this has to be done and how, but I will report back in the next message. With the actual fix.

Mhm the link to the Mozilla forums does not threat the actual pinned tab issue it's just about the general `target` handling and this is the basic and standard behaviour of FF which does also work as intended and how we expect it to work. Yes you are right, however the `_self` vs `nothing` works in standard tabs as intended it ONLY does not work for pinned tabs. I do not know if there is a bug report somewhere on the Mozilla reporting system and not whether it has been dismissed for some Reason. However it should be reported to Mozilla if not already be done because I'm sure this is not the way it should work. Because also Chrome, IE and Edge does handle it right (differently). 

No matter what's the case we can do something to simply give users a way to threat this behaviour if necessary and I will check for a solution subsequently. I understand your intention and if you need it and want it I understand this. I just talked in the sense of the Gantry developing team because you shouldn't follow unregular behaviour of one browser with exception. That's not good practise for the main branch and should be prevented if possible. 

No you don't need to keep track on overrides if gantry or the template is update. Please check the (documentation)[http://docs.gantry.org/gantry5/advanced/file-overrides] here you can see how you create an override for the menu which will be maintained beyond updates of either plugin and template.

**Comment by thexmanxyz** [comment] 2018-04-12 13:33
@N8Solutions So I have checked what I wanted to check and have a solution. We need something like the following:

**menuitem.yaml**

```
.target:
  type: select.selectize
  label: Link Target
  placeholder: 'Select...'
  options:
    none: None - No Target Attribution
    _self: Self - Current Window or Tab
    _blank: Blank - New Window or Tab
```

**menu.html.twig**

`{% set target = item.target != 'none' ? ' target="' ~ item.target|e ~ '"' %}`

This would be a solution which fixes the problem without adding an exception. So the user can choose either no target or `_self` as target manually if necessary and the issue is gone.

**Comment by N8Solutions** [comment] 2018-04-12 14:33
Thanks again for all the work you have put in to this!

I am very familiar with creating an override. I've been working with Gantry for many years now. I started with Gantry 4 😉 

When I mentioned about watching for updates and updating the override as needed the comment was directed at the fact that if the `menu.html.twig` file gets an update, and I'm still using the older version of the file which contains the override, then its possible that the menu will malfunction if enough of it was changed. I know this because it happened a couple of years ago with another core Gantry file. I had created an override then the Gantry team completely redid one of the files and since my override was using the old version it completely gummed up the works. It also took us a while to figure that out.

**Comment by thexmanxyz** [comment] 2018-04-12 15:35
@N8Solutions created a PR see also #2276

**Comment by N8Solutions** [comment] 2018-04-12 16:13
@thexmanxyz I tried those changes you suggested but it didn't make any difference. When I go in to the Menu via Gantry the Dropdown options do not change.

**Comment by thexmanxyz** [comment] 2018-04-12 16:24
@N8Solutions I did the changes on the core files and they do work I did a test right now. I assume there is something wrong with the override.

**Comment by thexmanxyz** [comment] 2018-04-12 16:25
@N8Solutions 
`menu.yaml` isn't the correct file `menuitem.yaml` is the correct one

**Comment by N8Solutions** [comment] 2018-04-12 16:25
I updated my comment to reflect that. 
Placing the `menu.html.twig` file in the `/TEMPLATE/custom/particles` folder works but just not for the `menu.yaml` file.

**Comment by N8Solutions** [comment] 2018-04-12 16:27
sorry, brainfart, I was using `menuitem.yaml` but typed out the wrong thing. LOL!
I need more coffee! ☕️ 
I'll update my comments now.

**Comment by N8Solutions** [comment] 2018-04-12 16:37
changing the option to the choice of `None` does not seem to change anything on the front end of the website. Can you confirm by inspecting the site that it changes on your end?

![code](https://user-images.githubusercontent.com/12389693/38691232-f12b0ff0-3e88-11e8-9c07-481cf40da1d6.png)

**Comment by thexmanxyz** [comment] 2018-04-12 17:00
@N8Solutions This is must be a bug in Gantry I also noticed this right now, it doesn't even work with the default files and both of the default options. Sometimes it changes and sometimes not. IDK what's going on can you confirm that?!

**Comment by N8Solutions** [comment] 2018-04-12 17:06
@thexmanxyz I have reverted to the default but I have not seen that problem yet. If I choose **New Window or Tab** it does save.

**Comment by thexmanxyz** [comment] 2018-04-12 17:15
@N8Solutions For me it doesn't save if to clean cache and then it's saved but it doesn't hold 'none' that's correctly. I will put some investigations on this.

**Comment by thexmanxyz** [comment] 2018-04-12 17:56
@N8Solutions You were right it doesn't work this way and I also know why - the default menu and the Gantry menu settings are connected with each other for the target attribute. However I now checked an untouched second install, the target settings do never reflect after refresh or reopen of the menu item settings. I always need to clean cache otherwise the previous setting keeps showing. I will modify the pull request and post here when I'm done with a working solution. 

For the placement of the overrides please take a closer look to the [documentation](http://docs.gantry.org/gantry5/advanced/file-overrides). Both files should be placed to another folder:

- `menu.html.twig` goes to `TEMPLATE_DIR/custom/engine/particles`
- `menuitem.yaml` goes to `TEMPLATE_DIR/custom/admin/blueprints/menu`

Take always care were to place the files and also watch exactly what subfolders have to be respected, they are not optional. I tested both directories they work! Just to let you know they are correct :P.

**Comment by N8Solutions** [comment] 2018-04-12 19:11
I've placed the files in those new directories but I am still receiving the same issue as before. It is not holding the new `None` attribute. No matter how many times I clear the cache it's just not saving correctly.

**Comment by thexmanxyz** [comment] 2018-04-12 19:13
@N8Solutions As I said I had to change the PR because it didn't work for me either. Check now the last commit on PR #2276 these changes now work you can take them directly from there. I tested it together with the override it's now works as it should.

**Comment by thexmanxyz** [comment] 2018-04-12 19:45
@N8Solutions Thanks I really appreciate, finally we got it working and found another bug 👍

**Closed** 2018-09-06 07:17 UTC
Labels: enhancement
