### ISSUE TITLE
Internal Server Error on saving menu if you have icon only menu entry.

### ISSUE THREAD

**Issue by trainspotting** [gantry/gantry5#574] opened 2015-07-14 19:09 UTC
When using the Gantry v5 menu editor, if you edit a menu entry so that it only has an icon and no actual text (so for example I added a HOME icon and removed all text from the heading)... then the settings won't save and throw an Internal Server Error.

(In RC3 it was accepted ok, and so anyone who has upgraded from RC3 to v5 with just an icon will encounter this problem... as will anyone who tries to create a new menu item with just the icon)

Presumably having just an icon with no text on the menu should be ok, in which case this looks like a bug?

**Comment by sam-sk** [comment] 2015-07-15 01:10
I'm having same problem and posted in the forum.

**Comment by w00fz** [comment] 2015-07-15 22:34
This issue should be fixed in the latest [CI Build](http://gantry.org/downloads#ci-builds). I can reproduce the problem in the latest 5.0.0 but not in the CI Build. 
If you guys could confirm it by trying out the CI Build it would be great. You can always revert back to stable by updating from the Joomla Updates.

I'm closing it now, feel free to reopen if the issue persists.

Thank you!

**Comment by sam-sk** [comment] 2015-07-16 02:32
I'm using dev-7c004a5ef CI Build and still having Internal Server Error

**Comment by mahagr** [comment] 2015-07-16 07:20
That is the latest build with all changes up to this moment. I'm reopening the issue so we can continue investigating it.

@sam-sk Just to verify that we are trying to do exactly the same, could you provide steps to reproduce the issue?

**Comment by sam-sk** [comment] 2015-07-16 08:12
It is may be not allowed by Joomla. But it was possible in RC. 

Open any menu in Hydrogen menu editor and set FontAwesome icon. Then edit the title and remove all text. Save without title just to get the fa icon only shown.

500 Internal server error. 
Cannot save menu without title.

**Comment by mahagr** [comment] 2015-07-16 08:32
Having title in menu item is a requirement from Joomla.

Improved error message so that you're able to fix the existing issues, but in the future we really need to detect this from Javascript.

**Comment by kat05** [comment] 2015-07-16 11:27
i am now getting a proper notification:

400 Bad Request
Oops, Failed to save /ambrosia: Menu Item must have a title..

**Comment by csbalazs** [comment] 2015-07-16 14:28
@sam-sk I agree with you. This "feature" worked in RC3, but after I upgraded, I get the following error message "500 Internal Server Error - Oops, Menu Item must have a title.." when I want to change this menu item.

![image](https://cloud.githubusercontent.com/assets/1657924/8725990/ad79e6bc-2bd7-11e5-942e-bb98402d1152.png)

**Comment by adi8i** [comment] 2015-07-16 14:35
Haven't we talked this on gitter? You can fix this in `custom/config/menu`

**Comment by w00fz** [comment] 2015-07-16 16:50
I think we should allow empty titles even if Joomla prevents it. It's a nice feature to have and quite common, especially for Home, to just have the home icon.
Also other platforms might not be as restrictive as Joomla so a JS check would force this behavior on all of the platforms and I don't think it's good to have.

**Comment by w00fz** [comment] 2015-07-16 16:52
At the very least we should have a toggle that let you show/hide the title via Menu Editor

**Comment by w00fz** [comment] 2015-07-16 19:55
This has now been changed a bit. Empty titles are not allowed anymore, like it was in the RCs, this is due to platforms requirements.
Although, we do now offer a way to hide the title, or rather, display only its Icon / Image.

![icon only](https://cloud.githubusercontent.com/assets/11734/8733684/ef2a8f80-2bb9-11e5-85a5-c889ddafa4ea.jpg)

**Closed** 2015-07-16 19:54 UTC
Labels: bug, enhancement
