### ISSUE TITLE
Widgets with tabs do not allow tab to be selected

### ISSUE THREAD

**Issue by dudewithamood** [gantry/gantry5#1021] opened 2015-11-21 07:39 UTC
In Wordpress, for any widget that uses tabs for its settings, when editing the widget in the widget particle under an outline the tabs do not work i.e. one cannot click them to access the addition settings.

**Comment by mahagr** [comment] 2015-11-22 08:48
@newkind Are you able to reproduce this issue?

**Comment by newkind** [comment] 2015-11-22 10:21
Well this is the case that we discussed when we were introducing widget particle - what about widgets that have their own custom admins with custom scripts (and that is the case as normal widgets don't have support for tabs) and how we should load the scripts and styles selectively on the layout manager page.

**Comment by dudewithamood** [comment] 2015-11-23 05:02
I see the difficulty. My work around is fairly straight forward in that I then use a widget position instead and add the widget using Appearance > Widgets. I still get the kind of control I want, just with an extra step. No biggie.

For reference though, the plugin I encounter this with is Flexible Posts Widget.

**Comment by mahagr** [comment] 2016-03-16 13:22
I'm closing this as a duplicate of #677

**Closed by mahagr** 2016-03-16 13:22 UTC
Labels: wordpress
