### ISSUE TITLE
Adding particle into menu and clicking "Apply & Save"

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#302] opened 2015-05-18 09:23 UTC
When you add the 'logo' particle in the menu (multi-lingual setup) and click `Apply & Save` you get a `404 not found` error.

If you click `Apply` in the particle modal and then click `Save Menu` the particle addition is saved properly.

**Comment by mahagr** [comment] 2015-05-18 09:25
I think we fixed something similar already, but lets wait reply from @w00fz if this is still an issue.

**Comment by w00fz** [comment] 2015-05-18 18:46
Duplicate of #300 (related to #283)

**Closed** 2015-05-18 18:52 UTC
Labels: bug
