### ISSUE TITLE
The file upload dialog only accepts lowercase file extensions

### ISSUE THREAD

**Issue by User123698745** [gantry/gantry5#1852] opened 2017-02-05 22:24 UTC
**Description:**
The file upload dialog only accepts lowercase file extensions.

**Environment:**
grav-skeleton-helium-site-5.4.6.zip

**Steps to reproduce:**
![screen](https://cloud.githubusercontent.com/assets/1911682/22630369/418b31d4-ebf9-11e6-85ba-f9f92e3d42ee.gif)

**Expected result:**
The file upload dialog should be case insensitive, when it comes to file extensions. The uploaded files may still be saved on the server with lower case file extensions.

**Comment by mahagr** [comment] 2017-02-07 08:57
We need to make filter case insensitive.

**Comment by w00fz** [comment] 2017-02-07 17:13
The filter for this is all via yaml/php, perhaps @newkind or @hexplor can take a look?

**Comment by newkind** [comment] 2017-02-08 08:45
Select is working fine, this is an issue with uploading only.

**Comment by mahagr** [comment] 2017-02-10 09:43
There is no file upload request going to the server. Controller converts file extension to lowercase before checking against valid file types. File extensions are case insensitive in the browser and server, which means that maybe the issue is in JS..?

**Comment by w00fz** [comment] 2017-06-28 02:00
This works fine for me now. Must have been fixed already.

Feel free to reopen if needed.

**Comment by w00fz** [comment] 2017-06-28 18:10
My bad @User123698745 this was actually an issue and I misread! Sorry about it.
It's fixed now.

**Closed** 2017-06-28 18:10 UTC
Labels: bug

**Comment by User123698745** [comment] 2017-07-02 01:19
I tested it today with vdev-3fc90f6a6. It works, thanks 😄
