### ISSUE TITLE
Suggestion:Template Manager -  Under Styles Tab 

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#305] opened 2015-05-18 09:42 UTC
Would be nice if you could add collapsible fields in `Template Manager` under `Styles`. Like in the picture. So we will have `Core Styles` all collapsible, then `section` etc....

This will help if you have many styles in  there.

![capture](https://cloud.githubusercontent.com/assets/9744973/7678222/22f997a8-fd5b-11e4-96e5-559e95d5004d.PNG)

**Comment by JoomFX** [comment] 2015-05-18 10:07
And while we are on collapsing, I would really appreciate if you can add a nesting option for the fields in the Admin.

Have a look at this screenshot:

![alt](http://i.imgur.com/G9AZv0L.png)

What I mean is:

1. By default only the "Background Image" field will be visible
2. Once you select an image (once the field is not empty) the child fields will appear - "Background Attachment", "Background Repeat" and "Background Size".

We have this in G4 :)
This will really keep the Admin clean.

**Comment by adi8i** [comment] 2015-05-20 09:09
@w00fz  @mahagr  Thing goes really messy here, at leat a search box at top,  would be useful . Or if there is any way to group fields using `selectize` or anything else.

**Comment by JoomFX** [comment] 2015-05-25 20:22
@w00fz @mahagr what do you think about this?
Of course there are more important things to be done, but what do you think about the above and also about https://github.com/gantry/gantry5/issues/349 ?

**Comment by w00fz** [comment] 2015-05-25 20:32
Honestly I am not too sure about this one. We had it in Gantry 4 and it's something I was very glad to drop for Gantry 5, reason being that managing multiple different fields is not something as easy at it might seem. There are different issues that will bring complexity to the system and that I would rather avoid.

It's something I am considering though, we just need to find a good way to implement it.

Note that here I am referring to yours request, not adi8i's, since adi8i's is duplicate of #349.

**Comment by JoomFX** [comment] 2015-05-25 20:43
@w00fz I can live without this "feature" if it is too complicated and/or if it bring more harm than good to G5. But once again, I would really like to have the collapsible sections/particles (in my opinion collapsed by default with a well visible Global Toggle Button) ;)

**Comment by mahagr** [comment] 2015-05-28 02:59
Well, we already have grouping with options implemented, but its still using multiple rows. The type is container.set and it should be easy to improve it or create another variation of it that does what you want. 

I would really love if someone had time to look into it and contribute it to core. :)

**Comment by w00fz** [comment] 2015-05-28 03:09
The collapsible particles and also the presets is now implemented. I'm going to close this for now.

**Closed by w00fz** 2015-05-28 03:09 UTC
Labels: feature, question
