### ISSUE TITLE
Callisto RokSprocket Tabs module - Infolist is borked by G5 5.1.1

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#764] opened 2015-08-30 05:51 UTC
Updated Callisto to 5.1.1 and the panel content for the RokSprocket Tabs module has disappeared.
![borked-sprocket-tabs-panel](https://cloud.githubusercontent.com/assets/3792467/9565902/9ba1b3c0-4eb9-11e5-8fb4-021aaa45c57b.jpg)

**Comment by DanGthatRokGallery** [comment] 2015-08-30 06:55
Uninstalled G5 5.1.1 and re-installed 5.1.0
then reinstalled 5.1.1 and then it worked
I don't know???

**Comment by mahagr** [comment] 2015-08-31 06:50
I'm going to keep this open..

**Comment by kat05** [comment] 2015-08-31 08:08
i am not seeing any issue with callisto sprocket tabs using 5.1.1 and also not using latest Version: dev-290dcf45c.

i think it's invalid?

**Comment by adi8i** [comment] 2015-08-31 09:52
The issue should be fixed in the latest CI Build, please read: #773

**Comment by mahagr** [comment] 2015-08-31 18:19
We are not able to reproduce this anymore. Closing unless proved wrong.

**Closed by mahagr** 2015-08-31 18:19 UTC
Labels: bug, regression
