### ISSUE TITLE
Joomla serious breakpoints issues and mismatch

### ISSUE THREAD

**Issue by morphinestyle** [gantry/gantry5#2626] opened 2020-04-19 17:12 UTC
I love Gantry, i use it on every Joomla website.
The breakpoints are never correct, and template "goes crazy" near breakpoint area.

I prefer use px intead rem, because sometimes i use BODY font-size based on device width, so i need to use fixed px value on Gantry breakpoints.

Issues descripion:
- **the breakpoints are never exact**, i'm using various tools with programmable breakpoints, and also i program heavy CSS mediaquery coding that match every breakpoints of any tools, but never with Gantry.
- **"near" breakpoints dimensions Gantry templates assume completely wrong measures for little range of pixels** getting big or becoming small than expected, i have every website with this issues, and sometimes i need to put heavy CSS override to correct Gantry elements for very very little range of dimensions around any breakpoints zones.

Please solve it! I love Gantry!

**Comment by blizam** [comment] 2020-04-20 04:00
REM can be as exact as a PX can... divide you pixel value by 16 to get the REM value for the Breakpoints area.

Your 2nd bullet is related to this: https://github.com/gantry/gantry5/issues/2492

There is a 1px issue at every breakpoint edge with the way the ranges are calculated; and it drives me crazy too... and unfortunately it's an SCSS file and so the file itself cannot be overwritten with Gantry's override system for template files.

**Comment by morphinestyle** [comment] 2020-04-20 07:53
I'm already using px instead rem, because sometimes i change BODY px font-size based on viewport width, so i need set a fixed value in px as breakpoint.

Whatever i set in breakpoint (in px) it doesn't match with final frontend result.
Never it works correctly, in every website made with Gantry.

**Comment by blizam** [comment] 2020-04-20 16:36
TBH I've never used px in the Breakpoints settings... based on the way they're calculated in the _breakpoints.scss file I would imagine that using pixels creates an issue visible at 2, maybe 3px... whereas using the larger REM unit the issue is definitely only present at 1px on each breakpoint edge... which still isn't great.

I think you'll find it work better if you use REM units... you can still set font-sizes in px of course... take your pixel value and divide by 16 to get the exact REM value.

Gantry still needs to fix the overlap issue, but I could see where it'd be more exaggerated using PX as unit versus REM

**Comment by morphinestyle** [comment] 2020-04-20 18:41
I can't set it in rem, because this website use dynamic font size based on monitor viewport.
If detect a 4k monitor it set BODY font-size at least @ 18px.

This not change the situation: Gantry make wrong px breakpoint calculation, please take a look to Joomla Helium theme: it's completely inconsistent! Has several bugs with breakpoints calculation, in px and with Helium Joomla template.

The generation of breakpoints are completely wrong and contains GAPs between the media-queries, take a look to the picture i attach.


![github-example](https://user-images.githubusercontent.com/35969533/79787373-2aab2f80-8347-11ea-9571-2e9c0fb1b4aa.jpg)



Take a look, this is what i need to overwrite in CSS code to make it working correctly with Bootstrap 3.x breakpoints:

`#g-page-surround > DIV.g-container, .g-fixed-container .g-container, SECTION:not(.g-flushed) .g-container:not(.g-flushed)
{
	max-width: 100%;
}
@media (max-width: 767.98px)
{
	BODY [class*="size-"]
	{
		flex-grow: 0;
		flex-basis: 100%;
		max-width: 100%;
	}
}
@media (min-width: 576px)
{
	#g-page-surround > DIV.g-container, .g-fixed-container .g-container, SECTION:not(.g-flushed) .g-container:not(.g-flushed)
	{
		max-width: 576px;
	}
}
@media (min-width: 768px)
{
	#g-page-surround > DIV.g-container, .g-fixed-container .g-container, SECTION:not(.g-flushed) .g-container:not(.g-flushed)
	{
		max-width: 768px;
	}
}
@media (min-width: 992px)
{
	#g-page-surround > DIV.g-container, .g-fixed-container .g-container, SECTION:not(.g-flushed) .g-container:not(.g-flushed)
	{
		max-width: 992px;
	}
}
@media (min-width: 1200px)
{
	#g-page-surround > DIV.g-container, .g-fixed-container .g-container, SECTION:not(.g-flushed) .g-container:not(.g-flushed)
	{
		max-width: 1200px;
	}
}
.visible-large, .visible-desktop, .visible-tablet, .visible-phone, .g-block.visible-large, .g-block.visible-desktop, .g-block.visible-tablet, .g-block.visible-phone
{
	display: none !important;
}
@media only all and (max-width: 767.98px)
{
	.visible-phone
	{
		display: block !important;
	}
	.g-block.visible-phone
	{
		display: block !important;
	}
}
@media only all and (min-width: 768px) and (max-width: 991.98px)
{
	.visible-tablet
	{
		display: block !important;
	}
	.g-block.visible-tablet
	{
		display: block !important;
	}
}
@media only all and (min-width: 992px) and (max-width: 1199.98px)
{
	.visible-desktop
	{
		display: block !important;
	}
	.g-block.visible-desktop
	{
		display: block !important;
	}
}
@media only all and (min-width: 1200px)
{
	.visible-large
	{
		display: block !important;
	}
	.g-block.visible-large
	{
		display: block !important;
	}
	.visible-desktop
	{
		display: block !important;
	}
	.g-block.visible-desktop
	{
		display: block !important;
	}
}
@media only all and (max-width: 767.98px)
{
	.hidden-phone
	{
		display: none !important;
	}
}
@media only all and (min-width: 768px) and (max-width: 991.98px)
{
	.hidden-tablet
	{
		display: none !important;
	}
}
@media only all and (min-width: 992px) and (max-width: 1199.98px)
{
	.hidden-desktop
	{
		display: none !important;
	}
}
@media only all and (min-width: 1200px)
{
	.hidden-large
	{
		display: none !important;
	}
	.hidden-desktop
	{
		display: none !important;
	}
}
@media only all and (max-width: 767.98px)
{
	.align-right
	{
		text-align: inherit !important;
	}
	.align-left
	{
		text-align: inherit !important;
	}
}
`

**Comment by mahagr** [comment] 2020-04-21 06:56
They can be fixed, just find the SCSS rules and fix them. Then create a pull request from the fix. I would be using REM though, as it tends to be working better.

**Comment by morphinestyle** [comment] 2020-04-21 07:29
Thank you Mahagr, i need to do something now on github about the issue or it's already in the future Gantry "to-fix-list"?
(Please note that the CSS code i've posted here is now constantly updating and increasing because i'm discovering new elements (like logo) affected by wrong breakpoints calculation.)

**Comment by marktaylor46** [comment] 2020-04-21 13:30
I'd be extremely careful here. The impact of any pull request could be profound and affect everyones site using Gantry 5. If you look at _breakpoints.scss you will see that this adjustment has been done very deliberately. I honestly can't remember the exact reason but it was done in the very early versions of Gantry 5 because of mismatches the other way around.

![2020-04-21_14-26-18](https://user-images.githubusercontent.com/11683218/79871608-7fe55080-83dc-11ea-92d9-fac004baffae.png)


Extreme caution is advised and thorough testing would be required before approving any pull request.

**Comment by morphinestyle** [comment] 2020-04-21 14:33
I've been realized it. And probably you're right. But now the px based breakpoints are inconsistent (never used REM breakpoint so i don't know how it works).

We have entire websites that changes design blocks not uniformly by resolution change, because other CSS drived blocks and other components move with accuracy based on well working breakpoints. Just yesterday i've found and corrected also the wrong logo visualization between devices resolutions.

I need to add a fix CSS code to every website to get Gantry works fine, and i can "fix" by myself in this way for every website, but the calculation however is not working properly.

Keep in mind that websites with dynamic BODY font-size (based on device viewport) are growing fast, and use the "REM based breakpoint calculation" makes hard to manage correct view related to viewport because REM is based to the declared font size in BODY tag, so: **when i set 18px BODY font-size only for 4k monitor you will have different (real) breakpoints pixel measurement between the FULL-HD and 4K website version**.

I could suggest a PX or REM detection to minimize any affects only to who's using PX values as breakpoints.

**Comment by marktaylor46** [comment] 2020-04-21 14:46
I would suggest that you use rem unints throughout because they are the most consistent. Use them for the breakpoints and your font sizes too. Also note that there is a "responsive font size" scss variable in Gantry 5 too that uses vw units that can be quite useful too. 

Anyway, if you have found a solution that works for you that is great. I was just concerned that a pul request was going to be raised to change Gantry 5 core for this - this would need a great deal of testing as the results could be profound.

Regards, Mark.

**Comment by morphinestyle** [comment] 2020-04-21 17:47
We are a design agency and we often need to use dynamic font-size for BODY to keep control over graphic design in respect to monitor size, we also use very special CSS rule for font-size adaptation, mixing calculation (rem + vw) to obtain best user experience crossing monitor sizes to 4k.

We look basically the design.

I repeat myself: **take care because when you use dynamic font-size, the REM Gantry breakpoints immediatly stop working consistently**.

What sense keeping a not well working tool? Most people use px as breakpoint.
What sense use a customizable framework leaving as default the settings parameters?
Responsiveness is a primary question today, it makes an pointless reason to look a well working frameworks: why allow it when Gantry has an incredible usability and power?

Personally i think that Gantry is missing only two fundamental goals:
- not well working breakpoints
- missing subpage/pseudo-page layout assignable to article, category, etc. joomla views.
About the rest: Gantry is the best framework, the most versatile and powerful, fast to set and modify, we use it with satisfaction on every our Joomla and Wordpress project.

In any case, maybe we've quite fixed the issue: we wish only the best Gantry ever.

Best regards.

**Comment by blizam** [comment] 2020-04-21 18:44
A pull request does need to be raised because it's currently broken no matter unit parameter you use... out of the box it's broken using REM units as I point out here: https://github.com/gantry/gantry5/issues/2492

https://github.com/gantry/gantry5/blob/develop/engines/common/nucleus/scss/nucleus/mixins/_breakpoints.scss

A full pixel (0.992px) is essentially being subtracted from the range

I searched around quite a bit on best practices for media query ranges... there's lots of arguments out there for using a cascade approach and only defining min-width breakpoints (like Bootstrap 3) instead of capped ranges with both min-width and max-width statements... I don't think it'd be possible to covert Gantry to essentially remove all the maxwidth statements from _breakpoints.scss but I'm curious if @mahagr thinks it might be possible...

For media query ranges best practices I found this to be helpful: https://tzi.fr/css/prevent-double-breakpoint/#a-separation-of-1px

It's discussed that if the media query is uses pixels it's fine but when it's using em or rem there can be issues with text zoom or browsers rounding incorrectly and they ultimately settle on 0.01em which is a value I've seen referenced elsewhere for ranges after searching around

I note in https://github.com/gantry/gantry5/issues/2492 when I changes the 0.062rem calculation values to 0.00125rem it resolves the issue... perhaps that is too aggressive though as the article mentions and 0.01rem is the safer value to use.

If that all sounds well and good I'm happy to create the pull request

**Comment by mahagr** [comment] 2020-04-22 12:57
Just a note.. instead of using plain numbers in breakpoints SCSS, what if you use either `1px` or `0.0625rem` as the value? SCSS should be able to convert numbers between the types.

**Comment by mahagr** [comment] 2020-04-22 13:02
Oh, and no, I don't think it is easy to convert Gantry to use just min-width breakpoints without breaking existing templates.

**Comment by blizam** [comment] 2020-04-22 19:21
_breakpoints.scss presently uses 0.062rem for it's calculations; not regular numbers.

I changed all the 0.062rem values to 0.01rem and confirmed that it resolves the issue completely for em and rem units. For px units I could still barely glitch it out in a desktop browser where there's about a half a pixel where no media query is applied at the edges... but it was literally a case where the browser pixel width that chrome inspector or mozilla dev tools was showing didn't change... it'd read 1199px and be fine and I'd barely move it to where it'd still say 1199px but no media query would be applied.

What I noticed in this that i didn't understand before was what @morphinestyle was alluding too with pixels... the gap issue isn't any more pronounced using pixels it's that it's offset 5.6 pixel or so... so if you set a breakpoint in backend of 1200px it's really being set at 1194.4px with the current calculations. Changing them 0.01rem means you 1200px breakpoint will indeed be at 1199px

All around I think it's a good, safe, move to change _breakpoint.scss to use 0.01rem in it's edge calculations which is inline with SASS' own official (3rd party) media query mixin

I'm going to create a pull request just in case

**Comment by mahagr** [comment] 2020-04-23 07:13
Please remember to create pull request as well. I'm aiming for PHP 7.4 fix release in couple of days (please test CI builds).

**Comment by morphinestyle** [comment] 2020-04-23 12:59
Hi Mahagr, i'm not a developer and i cannot create a pull request (i don't know how).

**Comment by blizam** [comment] 2020-04-23 15:12
I’m not the savviest at GitHub… but I think I did it correctly? It shows linked here from referencing it in the pull request details

**Comment by simmonsr** [comment] 2020-04-23 15:20
I'm just not seeing this "gap" that you guys are talking about specifically when using rem:

http://demo.gantry.org/

**Comment by simmonsr** [comment] 2020-04-23 20:18
So I can replicate the issue when using pixels. The math should could out as 0.062rem = 1px. But for some reason the compiler is interpreting 0.062rem = 6px, thus the problem with gaps. So that's the issue we are struggling with right now.

**Comment by morphinestyle** [comment] 2020-04-23 22:01
Simmonsr it's not exact: 1 rem stands for Root EM, and it's not an absolute element, because is related to :root declaration.

So it's not always: 1 rem = 16 px.
But 1 rem = (px declaration):root

So i can set:
**HTML, BODY: font-size 16px**   ---so--->   **1 REM = 16 px**   ---and--->   **0.062rem = 1px**

or i can set:
**HTML, BODY: font-size 22px**   ---so--->   **1 REM = 22 px**   ---and--->   **0.045rem = 1px**

Please not consider REMs as absolute values.

**Comment by simmonsr** [comment] 2020-04-23 22:02
I don't consider it an absolute value. But the SCSS compiler is currently defining 1rem = 96px.

**Comment by simmonsr** [comment] 2020-04-24 02:37
I pushed a fix where basically if px is being used then it will subtract (or add) by 1px. Other units will just rem for now. So no more gap for all who use PX breakpoints.

**Closed by simmonsr** 2020-04-24 02:37 UTC
Labels: bug

**Comment by blizam** [comment] 2020-04-24 03:42
> 
> 
> I'm just not seeing this "gap" that you guys are talking about specifically when using rem:
> 
> http://demo.gantry.org/

Windows 10, Firefox 75, 959px: https://imgur.com/a/32bQc7a
No media query is applied, the non-flush g-containers revert to their base width

.... but ya know what... I used to be able to do the exact same thing in Chrome... certainly back in May on #2492 I could do it in Chrome... but I can't anymore, 959px works fine

The compiler seems to be ok with 0.01rem, it's a tighter gap which I don't think anyone would argue is a bad thing and it's inline with other projects and recommendations out there; and it definitely resolves the issue in FF... so I would still push for that if possible.

**Comment by simmonsr** [comment] 2020-04-24 03:44
Can you try my CI build?

**Comment by mahagr** [comment] 2020-04-24 06:34
Let's continue in #2492
