### ISSUE TITLE
Equalized blocks improperly render their sizes on frontend

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#881] opened 2015-09-28 16:36 UTC
I have seen this in two templates now so I believe it is a Gantry 5 issue rather than the template per-se.

This example if Requiem "mainbar-a, mainbar-b, and mainbar-c" each of which are set to 33.3% width - yet when they are rendered in the page they are being set to size-33, size-34, and size-33 which obviously leads to height and width variations when they should be the same. They should be rendered as size-33-3 each.

You can see this on the porfolio page of requiem (note you may have to save layout first).

![2015-09-28_17-31-44](https://cloud.githubusercontent.com/assets/11683218/10141947/4f12a946-6607-11e5-844d-c190a5a79dca.png)

![2015-09-28_17-31-06](https://cloud.githubusercontent.com/assets/11683218/10141948/543877e8-6607-11e5-9999-bc607e3cb0d5.png)

**Comment by w00fz** [comment] 2015-09-28 23:18
I can replicate the issue. It looks like the values are properly stored and loaded in the admin but on the frontend it renders by rounding up.

**Comment by w00fz** [comment] 2015-09-29 01:08
Ok this should be fixed now.

**Closed** 2015-09-29 01:07 UTC
Labels: bug

**Comment by kat05** [comment] 2015-09-29 06:20
I can confirm that dev-f9d727378 fixes the issue.
