### ISSUE TITLE
Gantry5 and Joomla SEF links issue HELP!

### ISSUE THREAD

**Issue by Shmell77** [gantry/gantry5#1562] opened 2016-09-07 14:01 UTC
Hi guys,
i'm using Gantry5 with Helium template, after turn SEF links on all article links, that not associated with menu items opening home page instead of article, but still shows article's url without index.php.
I've checked .htaccess file, looks good, another Joomla website in different folder but on regular template works fine with SEF links on.

Please Help!

**Comment by joomlabeat** [comment] 2016-09-08 06:51
@Shmell77 Another website is another website. Probably not because you have an issue with your website, you should see the same issue in other websites. I guess this is an issue due to how your website has been configured and is not a bug or issue with Gantry or your template. 

Probably in your homepage you don't have component output to display Joomla Content. Same time, you probably don't have a menu item that will be responsible to display those articles, therefore they are forced to be displayed under the homepage menu item, which likely doesn't have component output, as said above. You need to have a menu item to "hold" those content items - e.g. a category blog menu item for those categories. 

You can get more Joomla help at Joomla.org forums or Joomla StackExchange: http://joomla.stackexchange.com

**Comment by mahagr** [comment] 2016-09-08 06:56
If you are trying to use `index.php?Itemid=xxx` in particles and it didn't work, I've already fixed that issue in CI builds.

If you're talking about something else, please explain what did you mean. :)

**Comment by w00fz** [comment] 2016-09-09 22:09
I think that's what @Shmell77 is referring to, so closing the issue.

Feel free to reopen and comment otherwise.

**Closed by w00fz** 2016-09-09 22:09 UTC
Labels: question
