### ISSUE TITLE
JS in Custom Content causes unknown error

### ISSUE THREAD

**Issue by igor-gp** [gantry/gantry5#970] opened 2015-11-04 03:42 UTC
I have tried putting in some JS code in the Page Settings 'custom content' box however it gives an error. I can't even see an error but it doesn't want to save. This is using the latest Gantry version 5.2.1. See attachment.

![2015-11-04_114150](https://cloud.githubusercontent.com/assets/12219933/10929010/169bddea-82e9-11e5-9cb8-2fecea1ac6b5.jpg)

**Comment by w00fz** [comment] 2015-11-04 04:11
Don't use the <script>, it gets wrapped for you

**Comment by w00fz** [comment] 2015-11-04 04:35
Also if you enable debug mode you should be getting a more meaningful error either in the modal or in the network panel of the inspector 

// Djamil Legato // From iPhone //

**Comment by mahagr** [comment] 2015-11-04 06:58
Sounds like a bug to me. Can you give us instructions on how we can easily reproduce your error?

**Comment by igor-gp** [comment] 2015-11-04 07:19
I have tried it with the script tag as per the Gantry docs

```<script>
(function(w,d,s,p,u,e,b){w['PlotObject']=p;w[p]=w[p]||function(){(w[p].q=w[p].q||[]).push(arguments)},w[p].d=1*new Date();
e=d.createElement(s),b=d.getElementsByTagName(s)[0];e.src=u;e.async=1;b.parentNode.insertBefore(e,b)})(window,document,'script','_plot','//cdn.plot.io/plot.js');
_plot('init', '67a6d98bdc7a4352a1b774512645a899');
</script>```

I have tried with adding `type` to it too. Both instances cause the error. 

I have then tried without the script tags and that allowed me to save it, but it was not correct in the front end.

I imagine you should have to use script tags, otherwise how does it know whats js, css etc.

**Comment by w00fz** [comment] 2015-11-04 08:12
Well in your code try are closing it but never open, unless it's just a bad paste?

// Djamil Legato // From iPhone //

**Comment by adi8i** [comment] 2015-11-04 08:17
@w00fz i think the issue is this one, read my first comment  #943 , i am not sure if is something wrong in Gantry or if it's a C9 bug.

Also you need to add `<script>` tag in `custom content` box. I tried the code now, and it works. That pop up appear often when you try to save. 

`XMLHttpRequest cannot load https://c9.io/_user_content/authorize?redirect=http%3A%2F%2Fworkspace-adi8i…%26theme%3Dgp_bless%260759d0ddc03cad483116aceddb80e491%3D1%26format%3Djson. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://workspace-adi8i.c9.io' is therefore not allowed access.`

**Comment by w00fz** [comment] 2015-11-04 21:00
Ah yeah sorry, I was on phone and from the picture i thought you were adding custom JS into the Assets. in Custom Content of `<head>` you definitely need the `<script>` or any tag the same way you would write it in an text editor.

Regarding the issue, it looks like it's again still related to that cross origin issue from cloud9. You should let them know about it.

**Closed by w00fz** 2015-11-04 21:00 UTC
Labels: bug
