### ISSUE TITLE
Menu Start | End levels not working with Gantry 5 5.1.3

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#803] opened 2015-09-07 05:19 UTC
Using latest Hydrogen, Callisto and Requiem RocketLauncher's running G5 - 5.1.2 the Menu particle menu levels aren't working for me.
When viewed in the Frontend the Menu is gone replaced with this error message:
in_array() expects parameter 2 to be array, string given

I used the same setup for all three templates and this is how I set the levels in hydrogen:
![hydrogen_start_level-setup-admin](https://cloud.githubusercontent.com/assets/3792467/9709686/1f8fa2ec-54fe-11e5-8bfa-41cc767a43d5.jpg)

This is how the Main Menu is setup
![hydrogen-mainmenu-setup](https://cloud.githubusercontent.com/assets/3792467/9709685/1f8ee758-54fe-11e5-871c-231bcfa4588d.jpg)

Another user has the same issue on Callisto -> http://www.rockettheme.com/forum/joomla-template-callisto/247278-menu-start-level-1-error

**Comment by mahagr** [comment] 2015-09-07 10:15
Enabling Joomla debug mode will reveal what goes wrong.

**Comment by mahagr** [comment] 2015-09-07 10:40
I couldn't reproduce issue, but I believe it is now fixed.

**Comment by DanGthatRokGallery** [comment] 2015-09-07 19:03
From my local Callisto -Debug ON:

![expects-parameter-2](https://cloud.githubusercontent.com/assets/3792467/9721904/994c2060-5571-11e5-85f4-52a7899c8fb8.jpg)

**Closed** 2015-09-08 15:31 UTC
Labels: bug
