### ISSUE TITLE
Menu does not save changes after editing

### ISSUE THREAD

**Issue by sooryakalai** [gantry/gantry5#2065] opened 2017-07-31 05:17 UTC
Details first
Wordpress Version : 4.8  Release Date : 08-06-2017
Gantry 5 framework : Version 5.4.14
Helium theme : v5.3.2
Issue : In Menu editor, after editing the items in the menu, like so
![image](https://user-images.githubusercontent.com/20853406/28763579-cb262ae4-75dc-11e7-8d48-f6db40e56209.png)
![image](https://user-images.githubusercontent.com/20853406/28763619-ff7006a8-75dc-11e7-8e2c-0003614dd3ee.png)

After clicking on "Save Menu", I get a strange window like shown below , and the edition is not saved. 
![image](https://user-images.githubusercontent.com/20853406/28763637-342265f8-75dd-11e7-867f-348d57178a7d.png)
![image](https://user-images.githubusercontent.com/20853406/28827546-8b1b38f8-76eb-11e7-9bff-72c237163df2.png)

Please do let me know and guide me if you need any further details / diagnostics.

Thanks !!!

**Comment by mahagr** [comment] 2017-08-14 16:30
@sooryakalai Sorry for my late response.

Try changing the menu in both WP menu and Gantry menu. Synching the ordering is currently disabled because of a bug which needs more investigation.

**Comment by mahagr** [comment] 2017-08-14 16:31
Duplicate of https://github.com/gantry/gantry5/issues/726

**Closed by mahagr** 2017-08-14 16:31 UTC
Labels: duplicate

**Comment by sooryakalai** [comment] 2017-08-16 12:31
@mahagr I tried doing that aswell. The problem still seem to persist.

**Comment by mahagr** [comment] 2017-08-17 04:20
I know. It is still an open issue. I just closed this issue as being the same issue as above.
