### ISSUE TITLE
Gantry Logo particle redirects to current url not site url

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#676] opened 2015-08-03 17:26 UTC
As mentioned on hipchat today, in Joomla when clicking the Logo from a subpage, the current page just gets reloaded. You won't get back to the Homepage.

This issue only happens with SEF disabled. When SEF is on, everything works as it should

**Comment by Hertak** [comment] 2015-08-06 00:07
I think this is not a bug. You need add a "/"  on Base Path in logo particle or basic settings

**Comment by mahagr** [comment] 2015-08-06 09:09
In that case logo shouldn't have link at all if the setting is empty :) So still a bug.

**Comment by w00fz** [comment] 2015-08-10 20:17
I don't see this issue @kat05. I disabled SEF, went to a subpage (Typography of Callisto) and clicking the Logo took me back to the Home page.

**Comment by Hertak** [comment] 2015-08-10 20:25
@w00fz  The problem is with hydrogen theme. 
On Logo configuration don´t have / for default if you add the slash there is no problem. 
I think the solution is on hydrogen theme put on logo particle the slash.

**Comment by w00fz** [comment] 2015-08-10 20:28
It doesn't need a `/` by default because in the particle it already defaults to `siteUrl()`

```
<a href="{{ url(particle.url)|default(gantry.siteUrl()) }}" 
```

So it is on purpose that if left blank it will take you to the homepage. Although I tried with both SEF and non-SEF and I get the same expected behavior on both.

**Comment by Hertak** [comment] 2015-08-10 20:31
Ok. When i use without slash the hydrogen theme the logo url don´t work.

**Comment by w00fz** [comment] 2015-08-10 20:38
What do you mean it doesn't work? Are you getting a link added?
When I'm in Hydrogen and leave empty the URL field, on frontend i get `<a href="/" ...`

**Comment by w00fz** [comment] 2015-08-10 23:14
Nevermind, I couldn't reproduce the issue because it was already fixed with #479 @ 61b94a2.
It is already fixed in the latest CI Build.

**Closed by w00fz** 2015-08-10 23:14 UTC
Labels: bug, duplicate, joomla

**Comment by w00fz** [comment] 2015-08-11 00:29
Be nice if you guys could try the CI Build, just to make sure! :smile:

**Comment by JoomFX** [comment] 2015-08-11 10:05
@w00fz I have very similar issue with the site I'm currently building.
It is actually reproducible only on the Error Page. I mean, when I'm on the Error Page and click on the Logo it just reloads the page and stays on the Error Page instead of going to Home (index.php/siteUrl).

I then tested it with the latest CI build and the issue was no longer reproducible :)

**Comment by marktaylor46** [comment] 2016-03-23 13:56
@w00fz I have today had another example of this issue in the RT forums. I had to add "/" in the url for the logo particle (in base outline) to fix this. So I think this ticket should be reopended as the issue does seem to exist still. This is the forum topic (admin details therein):

http://www.rockettheme.com/forum/gantry5-for-joomla/256727-link-homepage-on-logo?start=0#1281701

Member is using G5.2.13 and Joomla 3.5.0

**Comment by mahagr** [comment] 2016-03-24 08:52
I don't think its the same issue; the new issue seems to relate to Joomla 3.5. I could reproduce it, too.

Can you open a new issue as the one you linked seems to be issue only in J! 3.5?

**Comment by marktaylor46** [comment] 2016-03-24 09:03
Done #1210 :)
